### ISSUE TITLE
[Wapiti] Loading model -> error: invalid format <No such file or directory>

### ISSUE THREAD

**Issue by kclaes** [kermitt2/grobid#100]
Hi,

I'm trying to run grobid-service in Linux (AWS, more specifically).

The build went fine without -DSkiptests, and I've adjusted the filter.properties to replicate the correct file location (I've specified /opt/grobid-home in that file and unzipped the grobid-home artifact in said directory).

Jetty starts and loads Grobid fine. 
However, when uploading a document, I get the following error in the Jetty logs before is completely quits:

```
[Wapiti] Loading model: "/opt/grobid-home/models/header/model.wapiti"
error: invalid format
        <No such file or directory>
```

Obviously, I double checked that the file exists and is accessible for all users.

Scenarios tried:
- Native AWS: error
- Docker container in AWS/OSX/Windows: error
- OSX: works

So, it seems to work out of the box with OSX, but on Linux it doesn't (Docker is Linux for all practical purposes).

Would you have any pointers or things I can try?

For completeness, the Docker file I used (pretty straightforward)
```
FROM jetty:9.3-jre8

ADD ./grobid-home/target/grobid-home-0.4.1-SNAPSHOT.zip /opt
RUN unzip /opt/grobid-home-0.4.1-SNAPSHOT.zip -d /opt && rm /opt/grobid-home-0.4.1-SNAPSHOT.zip

COPY ./grobid-service/target/grobid-service-0.4.1-SNAPSHOT.war /var/lib/jetty/webapps/ROOT.war

```

**Comment by liar666** [comment]
> ADD ./grobid-home/target/grobid-home-0.4.1-SNAPSHOT.zip /opt
> RUN unzip /opt/grobid-home-0.4.1-SNAPSHOT.zip -d /opt && rm /opt/grobid-home-0.4.1-SNAPSHOT.zip
> 
> COPY ./grobid-service/target/grobid-service-0.4.1-SNAPSHOT.war /var/lib/jetty/webapps/ROOT.war


I'm not a GROBID expert, but have you tried:
- to put grobid-core / grobid-home .jars in the PATH?
- to use the grobid-core ".one-jar" file?
- to add GROBID's deps in the CLASSPATH?


-- 
Guillaume MULLER, PhD
Presans c/o REMIX COWORKING - L'APPART
57 rue de Turbigo
75003 Paris
France
http://www.presans.com
http://feeds.feedburner.com/OYI/fr

**Comment by kclaes** [comment]
Figured it out. The default image from AWS didn't have libxml2 installed, which was needed for pdf2xml.
After I installed the library, the REST-service started working...

How an wrong error message can totally set you on the wrong track..

**Comment by lfoppiano** [comment]
@kclaes which error message did you get that was wrong? if it's something we can fix, would be nice to do so.

**Comment by kermitt2** [comment]
Indeed, let's reopen it !

Normally you have received the error because the path to GROBID_HOME was not set or not set correctly in your docker configuration, as explained in the [Grobid Service documentation](https://github.com/kermitt2/grobid/blob/master/grobid-service/src/main/doc/grobid-service-manual.pdf) (section 3.2). Are you sure you have not corrected this setting in-between?

Because if pdf2xml were failing, you would have received another error from a completely different place and different stage of processing (raised in the class Document.java). In addition, I think normally you don't need to install libxml2 for pdf2xml because at least for Linux64 the executable packaged with grobid is a standalone executable with all static libraries. I can double check, but I have normally GROBID running on linux machines without libxml2 installed (Linode default Ubuntu image).

**Comment by kclaes** [comment]
Ok, I found out I ran into 2 problems.

- invalid format as in original bug: caused by making the maven build on a Windows (10) machine. Uploading that zip to the AWS instance cause the 'invalid format' error on the wapiti-model. I fixed/circumvented this by checking the code out on a linux machine and building the 'grobit-home'-zip on there before transferring it to AWS on putting it in a docker container. After that: no more error.
I would assume this has something to do with the way maven filters the resources or perhaps something with line-endings that were messed up?

- pdf2xml failed with errno 127: through some hacking of the pdf2xml-script I found out the cause of this was libxml2 not being available on the machine (the original script sent the error to /dev/null :s ). I fixed this by installing said library and it worked immediately after that.

**Comment by lfoppiano** [comment]
@kclaes how did you manage to build GROBID's models on windows 10? Wapiti is not supported by default. Did you do something particular? 

AFAIK, Wapiti doesn't build by default on windows and is not included in the GROBID installation (we are still waiting for such contribution :D).

I'll check the docker problem in the meantime.

**Comment by kclaes** [comment]
@lfoppiano I just figured I could build the artifacts anywhere with Maven and then put that on a server running the application (our AWS doesn't have a complete Maven-build environment, nor do I want to).

I assumed, since Wapiti itself didn't need to be run or built, I could do it on whichever machine Maven runs on. If that's not the case, perhaps it should be included in the documentation?

**Comment by lfoppiano** [comment]
@kclaes indeed. I'll check it out as well.

**Comment by kermitt2** [comment]
So we have two different issues : 

- portability of the artefacts built for service deployment

- the libxml2 requirement for pdf2xml as packaged currently in GROBID for linux

I open another issue for the second one, and we can stick on the first one which corresponds to the initial reported error.

**Comment by lfoppiano** [comment]
👍

**Comment by lfoppiano** [comment]
Tested on ubuntu 32bit using virtualbox (not so easy to simulate) 
1. Here the error in case of missing libxml2 library: 
<img width="1011" alt="screen shot 2016-05-13 at 18 38 04" src="https://cloud.githubusercontent.com/assets/15426/15255007/f096e7ec-1939-11e6-8033-6fcfd046b0d8.png">
...and the logs: 
<img width="953" alt="screen shot 2016-05-13 at 18 37 31" src="https://cloud.githubusercontent.com/assets/15426/15255070/34601624-193a-11e6-8dde-3afe3c853c3e.png">

2. Error in case of pdf2xml is not found: 
<img width="1003" alt="screen shot 2016-05-13 at 18 22 16" src="https://cloud.githubusercontent.com/assets/15426/15255052/1d65202c-193a-11e6-9b0c-b0e662d51af4.png">

@kclaes if you would like to do an additional test on an AWS instance without libxml2, would be helpful. 
Using your imput I'll working on on a docker installer for GROBID that allows to build the image by just using a command name (without changing the properties files manually).

**Comment by kclaes** [comment]
I'm sorry it took me a while to respond.

When I removed the libxml2 line, no error was thrown anymore regarding the missing library.

The Dockerfile I used (from the root of the project) is
```
FROM jetty:9.3-jre8

ADD ./grobid-home/target/grobid-home-0.4.1-SNAPSHOT.zip /opt
RUN unzip /opt/grobid-home-0.4.1-SNAPSHOT.zip -d /opt && rm /opt/grobid-home-0.4.1-SNAPSHOT.zip

COPY ./grobid-service/target/grobid-service-0.4.1-SNAPSHOT.war /var/lib/jetty/webapps/ROOT.war
```
Now all that is left is the maven build on windows that seems to corrupt the wapiti models.

**Comment by lfoppiano** [comment]
@kclaes indeed, I've just pushed a correction for the messages. Since it is a rare case, for the time being it's better to keep the library in the system, and have a proper error message. We can provide statically the library on a second step. 

Checking on windows is more complicated (and, perhaps frustrating :)). Could you give me more information on the system you have used? OS, version of Maven, did you use cygwin or any similar bash emulator?

**Comment by kclaes** [comment]
Windows 10 (10586.318)
Maven 3.3.3
No emulators.

But I'm guessing it'd be with any Windows version or fairly recent Maven version.

**Comment by kclaes** [comment]
I went to compare the files, and indeed, the only difference are the line endings (CR/LF on windows, LF on linux), so at this point it's safe to assume this is the culprit.
I have my git configured with autocrlf=true.

So, I created file called .gitattributes in the root of the repo, with the following content
```
* text=auto

*.wapiti text eol=lf
```

With these changes, the model gets loaded correctly!

**Comment by lfoppiano** [comment]
Great! I know is very small change, could you make a pull request with this file? Otherwise I will just add it manually.

**Comment by kclaes** [comment]
Could you maybe do it manually?
It seems like a hassle for one new file with 2 lines of text.

I'm fine with the mention in the commit message ;) (thanks for those, btw)

**Comment by lfoppiano** [comment]
Indeed. 
Thanks again @kclaes. I think we can close this issue :-).
