### ISSUE TITLE
GROBID docker image

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#102]
Use the input from #100, add a docker installer for GROBID that allows to build the image by just using a command name (without changing the properties files manually).

**Comment by kclaes** [comment]
Hi, a possible solution could be the added docker.diff.

The change is simple: delete filter.properties, create both profile/default.properties and profile/docker.properties and adjust pom to use these property-files.

The attached Dockerfile can be added in a different module or in the root of the project, wherever you see fit (just make sure the artifacts are correctly referenced).
Attached Dockerfile works when both artifacts are in the same directory as said Dockerfile.

**Comment by chrismattmann** [comment]
++1

**Comment by lfoppiano** [comment]
@kclaes I've integrated your changes but taking the artifacts from the current structure (wars are generated into the target directory).

**Comment by kclaes** [comment]
Just tried the image at https://hub.docker.com/r/lfoppiano/grobid/ and can gladly report back that it worked first try!

In Grobid-docker.md is an typo though, 
The pull should read (at the time of writing):
```
docker pull lfoppiano/grobid:0.1
```
(instead of ```docker pull lfoppiano-grobid```)
