### ISSUE TITLE
jQuery < v3.5.0 contains Cross-site vulnerabilities - how to fix in Docker and non-docker deployments?

### ISSUE THREAD

**Issue by mfeblowitz** [kermitt2/grobid#1023]
- OS: Docker on ubuntu

- Java version: openjdk 17.0.2 2022-01-18, as installed in docker container

- Problem: multiple cross-site scripting vulnerabilities exist in both Docker and non-docker ground service deployments (https://www.tenable.com/plugins/nessus/136929). This should be fixed for all Grobid deployments. 

For non-docker installations, a simple replacement of the current references to older jQuery versions is possible:
```
sed -i 's/jquery-3.4.1.min.js/jquery-3.5.1.min.js/' ./grobid-service/src/main/resources/web/index.html
rm ./grobid-service/src/main/resources/web/resources/js//jquery-3.4.1.min.js
wget  https://code.jquery.com/jquery-3.5.1.min.js --no-check-certificate
mv jquery-3.5.1.min.js ./grobid-service/src/main/resources/web/resources/js/
```
How can this be done for the ground docker image?

**Comment by kermitt2** [comment]
Sorry for the damn auto-close!
