### ISSUE TITLE
Update to Dropwizard 4.0

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#1031]
I've started looking into upgrading from dropwizard 1.x to 4.x. It's quite some work but doable. I've got already a working version of grobid-quantities. 😄 

I've started working on the branch `features/update-dropwizard`. 

There are two-three main changes to be done: 
 - ~~[ ] update the GrobidServiceConfiguration to cover all the elements from the YAML (it seems more strict than dropwizard 1~~
 -  ~~[ ] (probably) get rid of the GrobidProperties~~ 
 - [x] Move the output bytecode from jdk 1.8 to jdk 1.11
 - [x] Fix HealthCheck
 - ~~[ ] Fix tests to run with Junit 5 (`org.junit.internal.runners.rules.ValidationError: The @ClassRule 'APP' must implement TestRule.`)~~

I will update this thread as I progress

**Comment by kermitt2** [comment]
I think the main problem for this upgrade is that the JDK 1.8 compatibility is lost. 
In my tests, I had some difficulties replacing `dropwizard-guicier` by the more modern `dropwizard-guicey` for the guice stuff support in the new Dropwizard, I did not manage to bind the classes to the module.

**Comment by lfoppiano** [comment]
#1032 should be working fine except for the tests that are running with the legacy engine

**Comment by kermitt2** [comment]
Nice! What about adding it to the 0.8.0 release and move to Java 11 as minimal requirement?
