### ISSUE TITLE
Can only run in service mode on Ubuntu desktop, not server

### ISSUE THREAD

**Issue by axfelix** [kermitt2/grobid#104]
Hi folks!

I suspect there's some weird dependencies at work here, but I've been able to duplicate this on 12.04 and 16.04, so there's probably something amiss.

When running Grobid in service mode following the documentation, it starts up normally on Ubuntu desktop installations. However, on Ubuntu server, it prints these additional warning lines:

`[11:36]
[INFO] >>> maven-jetty-plugin:6.1.10:run-war (default-cli) > package @ grobid-service >>>`
`[11:36] 
[WARNING] The POM for com.sun.jersey:jersey-core:jar:1.9 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details`
`[11:36] 
[WARNING] The POM for asm:asm:jar:3.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details`

and then nothing happens after

`[INFO] No Transaction manager found - if your webapp requires one, please configure one.`

The warnings _seem_ like maven is just complaining about being able to resolve sources... any idea why this would be happening so consistently?

This is with maven 3 and openjdk-8-jre. Thanks!

**Comment by lfoppiano** [comment]
@axfelix could you please provide the whole log when you run maven with the option -X ? 

Could you also give me the result of the command `mvn dependencies:tree`?

**Comment by axfelix** [comment]
Nevermind -- this seems to be an issue with non-root users trying to start the Grobid service, which throws errors about dependency resolution. I'm not familiar enough with maven to know why that's happening, but I don't think it's a Ubuntu server issue.

**Comment by lfoppiano** [comment]
@axfelix if you send me the log information I've asked you I can try to figure it out ;)

**Comment by axfelix** [comment]
ok, ok :)

trying to run grobid-service as www-data after building as root (vagrant in this case) and then chowning the grobid directory to www-data for good measure results in this:

    vagrant@xmlps:/opt/grobid/grobid-service$ sudo su www-data
    www-data@xmlps:/opt/grobid/grobid-service$ mvn -Dmaven.test.skip=true jetty:run-war -U
    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building grobid-service 0.4.0
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] >>> maven-jetty-plugin:6.1.10:run-war (default-cli) > package @ grobid-service >>>
    Downloading: https://repo.maven.apache.org/maven2/org/grobid/grobid-core/0.4.0/grobid-core-    0.4.0.pom
    [WARNING] The POM for org.grobid:grobid-core:jar:0.4.0 is missing, no dependency information     available
    Downloading: https://repo.maven.apache.org/maven2/org/grobid/grobid-core/0.4.0/grobid-core-    0.4.0.jar
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1.967 s
    [INFO] Finished at: 2016-06-07T21:47:36+00:00
    [INFO] Final Memory: 13M/136M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project grobid-service: Could not resolve dependencies for project org.grobid:grobid-service:war:0.4.0: Could not find artifact org.grobid:grobid-core:jar:0.4.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1]     http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by lfoppiano** [comment]
@axfelix could you please provide the whole log when you run maven with the option **-X** ?
Could you also give me the result of the command **mvn dependencies:tree**?

**Comment by axfelix** [comment]
Sure! here they are when run as the www-data user.
[mvn-X.txt](https://github.com/kermitt2/grobid/files/305314/mvn-X.txt)
[mvn-dependencies.txt](https://github.com/kermitt2/grobid/files/305315/mvn-dependencies.txt)

**Comment by lfoppiano** [comment]
@axfelix sorry, the second command should be mvn dependency:tree, not dependencies. My mistake.

**Comment by lfoppiano** [comment]
@axfelix Since I haven't got any news, feel free to reopen it, if you have more feedback and we can continue investigating this problem.
