### ISSUE TITLE
Zombie daemons linger on

### ISSUE THREAD

**Issue by keto33** [kermitt2/grobid#1052]
Following issue #1051, I noticed that some processes linger on for a long time (e.g., for hours) without timeout.

Strangely, I noticed the daemons linger on even after killing the server. More strangely (at least to me), the daemons were still busy even after restarting the whole machine.

This is the start of the server after a fresh boot of the computer:

```
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :grobid-service:run
11:58:01.946 [main] INFO org.grobid.service.main.GrobidServiceApplication - Found conf path: /web/localhost/lib/grobid-0.7.3/grobid-home/config/grobid.yaml
11:58:01.952 [main] WARN org.grobid.service.main.GrobidServiceApplication - Running with default arguments: "server" "/web/localhost/lib/grobid-0.7.3/grobid-home/config/grobid.yaml"
11:58:01.952 [main] INFO org.grobid.service.main.GrobidServiceApplication - Configuration file: /web/localhost/lib/grobid-0.7.3/grobid-home/config/grobid.yaml
<===========--> 91% EXECUTING [2m 52s]
> :grobid-service:run
```

After killing the processes and the server and starting the server, it is common to see:

`Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details
`

**Comment by kermitt2** [comment]
Hello @keto33  !

I think you're talking about gradle build/run daemons. In principle, there's some auto-killing of these daemons by gradle after a while (a few hours). You can stop them manually, see below. Normally there's nothing to worry about. 

See https://stackoverflow.com/a/49074621

**Comment by kermitt2** [comment]
@keto33 I am closing the issue, as it is a normal/expcted Gradle behavior.
