### ISSUE TITLE
Building with newer glibc version

### ISSUE THREAD

**Issue by ahmedsaadpk** [kermitt2/grobid#1054]
**Host OS: Windows 11 Home 64-Bit**
CPU(s): 16
Disk: 500 GiB
RAM: 16 GiB
Processor: 13th Gen Intel(R) Core(TM) i7-13700H
Processor Architecture: x86

**Guest OS (via multipass):** 
Ubuntu 22.04.3 LTS
CPU(s): 4
Disk: 10 GiB
RAM: 4 GiB

**JDK (Guest OS)**
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

**Build Output**
ubuntu@primary:~/Softwares/grobid-0.7.3$ ./gradlew run --warning-mode all

> Configure project :
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
        at build_6d5upycqsrdh6v3hve2uq4itt$_run_closure8$_closure64$_closure75.doCall(/home/ubuntu/Softwares/grobid-0.7.3/build.gradle:535)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The Report.enabled property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the required property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:enabled for more details.
        at build_6d5upycqsrdh6v3hve2uq4itt$_run_closure9$_closure77.doCall(/home/ubuntu/Softwares/grobid-0.7.3/build.gradle:627)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Task :grobid-service:run
14:54:51.437 [main] INFO org.grobid.service.main.GrobidServiceApplication - Found conf path: /home/ubuntu/Softwares/grobid-0.7.3/grobid-home/config/grobid.yaml
14:54:51.449 [main] WARN org.grobid.service.main.GrobidServiceApplication - Running with default arguments: "server" "/home/ubuntu/Softwares/grobid-0.7.3/grobid-home/config/grobid.yaml"
14:54:51.449 [main] INFO org.grobid.service.main.GrobidServiceApplication - Configuration file: /home/ubuntu/Softwares/grobid-0.7.3/grobid-home/config/grobid.yaml
/usr/lib/jvm/java-11-openjdk-amd64/bin/java: symbol lookup error: /home/ubuntu/Softwares/grobid-0.7.3/grobid-home/lib/lin-64/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE

> Task :grobid-service:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grobid-service:run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
9 actionable tasks: 1 executed, 8 up-to-date

**Comment by kermitt2** [comment]
Hi @ahmedsaadpk 

Thank for the issue. The gradle deprecations are just warning and not a problem. 

The problem is the version of GLIBC for running the native libraries, this is a duplicate of #1019 or #976 

It was fixed with  #1020

**Comment by ahmedsaadpk** [comment]
Thanks kermitt22, it worked.
