### ISSUE TITLE
endpoint to process fundings

### ISSUE THREAD

**Issue by Aazhar** [kermitt2/grobid#1058]
We have to process the document completely ( fulltext ) in order to extract fundings, which can be a bit cumbersome for instance when the uploaded user files are processed in real time.

An idea would be to have an endpoint that deals with the fundings in the same way we already have an endpoint that processes cited literature.

**Comment by kermitt2** [comment]
Implemented with bb4b3591e51a084063791b6454f26faddfaf575b

**Comment by kermitt2** [comment]
I observe a runtime divided by 2 as compared to the complete full text processing. 
However, processing header alone is 50% faster. 
So this is the following typical scale for average document: fulltext 3s, header+funding:1.5s, header: 1s.

Endpoint is `/api/processHeaderFundingDocument`
