### ISSUE TITLE
Grobid extracts blank xml file from this pdf

### ISSUE THREAD

**Issue by Singularity9971** [kermitt2/grobid#107]
Tested on dataset of 30 publications, the following returns an xml file with just a TEI tag and nothing else. This pdf is quite similar to the other 29 which were extracted correctly.
[Heatseqaninteractive.pdf](https://github.com/kermitt2/grobid/files/374415/Heatseqaninteractive.pdf)

**Comment by lfoppiano** [comment]
Hi, which information did you try to extract? Fulltext, Header?

**Comment by Singularity9971** [comment]
Fulltext, was wondering if this is an issue just on my machine or it just does not work on this pdf for some reason

**Comment by kermitt2** [comment]
Hi, thanks for reporting the issue !

There is an open demo here for testing -> http://cloud.science-miner.com/grobid
I just tried your PDF file on the demo and there is a complete XML TEI document as result with header, body and so on. So it might come from your environment. 

Do you have any error message in the log? Are you using the batch or the service? If it is the batch, how much memory did you allocate to the process?

**Comment by Singularity9971** [comment]
Hi, thanks for the immediate response.

Yeah, I tried it too and and got the correct result, but fails on my localhost.
I have attached a screenshot. This error only pops up on this specific pdf for some reason. Should I just delete all the 
<img width="1280" alt="screen shot 2016-07-20 at 11 57 15 am" src="https://cloud.githubusercontent.com/assets/14922145/16999145/6a725f26-4e71-11e6-82a1-4be9cf8043aa.png">
files in that folder?

**Comment by Singularity9971** [comment]
So the folder is actually empty and deleting it prevents grobid from working so I deleted and recreated the folder again but same result.

**Comment by lfoppiano** [comment]
So we find the problem and we are working to fixing it. 
In the meantime, I would recommend you to either download the [latest stable version](http://grobid.readthedocs.io/en/latest/Install-Grobid/#getting-grobid) of GROBID or to use the cloud service directly.

**Comment by Singularity9971** [comment]
I am using latest stable version but will switch to cloud service for now, thanks

**Comment by lfoppiano** [comment]
@Singularity9971 are you sure about that? The stable version is 0.4.0 and you have to download the zip file from the link I've posted above. 
I'm pretty sure it doesn't have this bug. For precaution I've tested and, indeed, it works fine.
