### ISSUE TITLE
general paragraph text wrongly recognized as "figDesc/div/p"

### ISSUE THREAD

**Issue by sawyerzheng** [kermitt2/grobid#1077]
- What is your OS and architecture? Windows is not supported and Mac OS arm64 is not yet supported. For non-supported OS, you can use Docker (https://grobid.readthedocs.io/en/latest/Grobid-docker/)

I am using a docker container of `docker pull lfoppiano/grobid:0.8.0`

v0.7.3 also tested

- What is your Java version (`java --version`)? 

just used official docker: `lfoppiano/grobid`

- In case of build or run errors, please submit the error while running gradlew with ``--stacktrace`` and ``--info`` for better log traces (e.g. `./gradlew run --stacktrace --info`) or attach the log file `logs/grobid-service.log`.

No this file, as using docker

----------------

## Problem

1. The general paragraph text which is not belong to a figure is wrongly recognized as a `figDesc`
2. Part of the wrongly recognized text as figDesc also in the general paraph text "body/div/p"
    - This mean its repeated in two part of tei xml:  "body/figure/figDesc/div/p" and "body/div/p"
   
### original pdf area

![image](https://github.com/kermitt2/grobid/assets/44355570/dab1d510-5eae-4120-898f-4486d036b61a)

### extracted xml

![image](https://github.com/kermitt2/grobid/assets/44355570/b8a5faef-8c72-4022-b205-b4607942153c)

### Used pdf

[176_liu2010.pdf](https://github.com/kermitt2/grobid/files/14045640/176_liu2010.pdf)

### Result tei xml
**note**: github not accept .xml file, I modified its suffix as .txt

[176_liu2010.pdf.tei.xml.txt](https://github.com/kermitt2/grobid/files/14045650/176_liu2010.pdf.tei.xml.txt)

**Comment by lfoppiano** [comment]
Thanks @sawyerzheng for reporting the issue. 

Indeed, there are two problems: 
1) the paragraph is wrongly labeled as a figure. This is a common problem that we are (slowly) working on in PR https://github.com/kermitt2/grobid/pull/963 
For the time being, we could add your example as training data, however, unfortunately, because this is Elsevier and the article is copyrighted, it's not possible to redistribute it as training data. 
Nevertheless, should you find the same problem in other papers with a Creative Commons licence, we could use it as a test case.

2) the paragraph from "In inert gas" is duplicated and out of order.  It should be related to the figures processing. Please give me a couple of weeks, I should be able to fix it.

**Comment by sawyerzheng** [comment]
Thank you very much for your time.

So far, I have only been able to find one example PDF. If I come across a not copyrighted PDF with the similar problem in the future, I will upload it there.

**Comment by sawyerzheng** [comment]
I found one pdf with open access. The pdf has similar problem.

This parse result from grobid  gpu docker version: `grobid/grobid:0.8.0`
---
![Snipaste_2024-04-01_16-32-30](https://github.com/kermitt2/grobid/assets/44355570/5f7a06d1-9792-44aa-b2be-bd5262b406a9)
---
![image](https://github.com/kermitt2/grobid/assets/44355570/90855df4-259f-4509-8c04-e285e8e0cbd7)

---
![image](https://github.com/kermitt2/grobid/assets/44355570/a0b5f6bc-a6b5-4160-9406-e92160ac2cbe)


pdf: https://www.nature.com/articles/s41597-024-03160-z
doi:

**Comment by lfoppiano** [comment]
Indeeed. Thanks for finding an example we will surely add it to the training data

**Comment by lfoppiano** [comment]
This article was added as training data for fulltext in #1301. @sawyerzheng you could try with the master version it should have solved the problems of the fulltext recognition and having misplaced and duplicated test. . 

```
<div
                xmlns="http://www.tei-c.org/ns/1.0">
                <head>Field work.</head>
                <p>We conducted 128 near-weekly ground and aerial beach surveys at Kahaloa Beach, Waikīkī, from April 2018 to July 2021 (Fig. 
                    <ref type="figure" target="#fig_4">3</ref>). These surveys were initially motivated to better understand beach response to both seasonal and tropical-storm-generated waves. A consumer-grade sUAS (DJI phantom4 Pro v1 &amp; v2) and the flight planning software package DroneDeploy was used to collect overlapping images at 120 m altitude, resulting in a ground sampling distance of 3-4 cm. All images were taken at nadir with 80% side-lap/end-lap. The sUAS imagery was georeferenced using ground control points (GCPs) described below; RTK or onboard sUAS GPS was not used (Fig. 
                    <ref type="figure" target="#fig_2">2</ref>).
                </p>
                <p>Camera settings varied depending on light conditions, but high shutter speeds (1/1000-1/600) were prioritized to reduce motion blur. Each survey was conducted in the morning around sunrise to capture the beach prior to crowds and objects (e.g., beach umbrellas, chairs, tents, etc.), irrespective of tide level and ocean conditions. Repeat surveys were planned weekly; however, given the weather dependent nature of sUAS flights, surveys were conducted around optimal weather (low winds, no rain) for each week resulting in revisit times between 5 and 15 days (Fig. 
                    <ref type="figure" target="#fig_4">3</ref>).
                </p>
                <p>Seven 1 × 1 m vinyl targets functioned as GCPs and were spaced equidistant about 100 m alongshore for each survey. The position of GCPs were surveyed using a rod-mounted prism and a Leica TS16 Robotic Total Station with millimeter-level accuracy. Additionally, points were collected every 5-15 m along the seaward edge of the foreshore, here marked by the position of the top of the beach toe, also approximately equal to the low water mark (LWM) 
                    <ref type="bibr" target="#b39">39,</ref>
                    <ref type="bibr" target="#b42">42</ref> . Existing benchmarks provided a spatial reference using the WGS 1984 UTM Zone 4 projection. Elevations were measured with respect to local mean sea level (LMSL; Datums -NOAA Tides and Currents, present epoch: 1983-2001).
                </p>
            </div>
            <div
                xmlns="http://www.tei-c.org/ns/1.0">
                <head>Data processing.</head>
                <p>Following standardized USGS protocols 
                    <ref type="bibr" target="#b43">43,</ref>
                    <ref type="bibr" target="#b44">44</ref> for photogrammetry processing, Agisoft Metashape (formerly Photoscan) was used to generate a dense point cloud and orthomosaic (Fig. 
                    <ref type="figure" target="#fig_2">2</ref>). An initial sparse point cloud was created with GCPs manually identified and subsequently verified for each image containing a GCP. After importing the surveyed GCP coordinates and re-aligning the sparse cloud, an iterative error reduction process was initiated, in which points above a certain threshold were removed and the sparse point cloud re-aligned. This iterative process was repeated until uncertainty values were below a specific threshold. Approximately 10% of the points were removed at each iteration, initially reducing the "Reconstruction Uncertainty" to 10, followed by reducing "Projection Accuracy" to 3, and lastly reducing "Reprojection Error" once, by eliminating the 10% of the point cloud with highest values. From here, a dense point cloud, DEM, and orthomosaic was generated from Agisoft Metashape.
                </p>
```

however the issue with the first article has not be fixed, as we could not use that as training data.
