### ISSUE TITLE
grobid v0.7.3 cannot run on centos 7.9 with segmentation fault

### ISSUE THREAD

**Issue by sawyerzheng** [kermitt2/grobid#1081]
- What is your OS and architecture? Windows is not supported and Mac OS arm64 is not yet supported. For non-supported OS, you can use Docker (https://grobid.readthedocs.io/en/latest/Grobid-docker/)

CentOS 7.9 and grobid v0.7.3

- What is your Java version (`java --version`)? 

java 8 and java 11 has same problem

- In case of build or run errors, please submit the error while running gradlew with ``--stacktrace`` and ``--info`` for better log traces (e.g. `./gradlew run --stacktrace --info`) or attach the log file `logs/grobid-service.log`.

libwapiti.so -> libm.so.6 -> libc.so.6 cannot be load correct. Just give a segementation fault

## my trail fixing solution:

using grobid v0.6.0 's  lib/lin-64  folder to replace the corresponding v0.7.3's can fix the problem.

**Comment by kermitt2** [comment]
Hello @sawyerzheng !

Thanks for the issue. 

Normally libwapiti.so requires glibc version 2.14 or higher (post 2011). I suppose CentOS 7.9 has a lower version of glibc. I must emphasize that CentOS 7 and its glibc versions are outdated as Linux distribution. 

How to fix the problem: update to a more recent linux distribution (CentOS 7 is reaching end of life and has security issues) or use the docker image to avoid system dependencies.

**Comment by lfoppiano** [comment]
@sawyerzheng I'm closing this one, since the mentioned grobid version is already passed. Feel free to reopen with more details.
