### ISSUE TITLE
publication date not correctly extracted

### ISSUE THREAD

**Issue by Aazhar** [kermitt2/grobid#109]
Grobid alter the publication date found from the publication, maybe it makes bad interpretations.
I've found the problem with this document https://hal.archives-ouvertes.fr/hal-00135377/document

which give me back 
`<publicationStmt>
<date type="published" when="20077-03-07">7 Mar 2007 7th March 2007</date
</publicationStmt>`

**Comment by lfoppiano** [comment]
The dates seems now correct: 

```
            <publicationStmt>
                <publisher/>
                <availability status="unknown">
                    <licence/>
                </availability>
                <date type="published" when="2007-03-07">7th March 2007</date>
            </publicationStmt>
```
```
<monogr>
                        <imprint>
                            <date type="published" when="2007-03-07">7th March 2007</date>
                        </imprint>
                    </monogr>
```
