### ISSUE TITLE
Delete lines from xml, which have been created by Grobid.

### ISSUE THREAD

**Issue by kellytsorb** [kermitt2/grobid#1092]
Hello,
I have a problem I want to describe. Ok so in the first step, I transform the academic papers into xml files and in the second step I load them into SQLite Articles database named articles with sections: id, source, published, publication, authors, affiliations, affiliation, title, tags,  reference, entry. But there is a problem in section reference where there are the links with doi number. More specific, contains right the half part of the link (https://doi.org/) but after that it takes the MD5 number (https://doi.org/17B74451F0BD1A38F55A16E6AE5F476A). This is happening because in the xml there is first the line idno type="MD5">01483CB97635C3FE547D43F3E34DC4BD idno and then idno type="DOI">10.2308/accr-50369 idno. The right link must be https://doi.org/10.2308/accr-50369. I tried to delete the line in xml manually to keep only the idno with doi value and then I save the file but it doesn't work. So I wonder is it grobid fault? is something wrong when I load the files into my database? but I am thinking maybe after using grobid to make the xml the file locks the content and I can't make changes? Is there a way to put first the idno with doi value and not MD5 or doesn't put the MD5 in xml at all? 

Thank you in advance!

**Comment by kellytsorb** [comment]
<img width="431" alt="Screenshot 2024-03-15 at 12 15 03 AM" src="https://github.com/kermitt2/grobid/assets/77836075/9393e297-e0c0-49a0-a17b-e4bcc5939d34">

**Comment by lfoppiano** [comment]
Hi @kellytsorb, 
     it seems an issue on your end, where you cannot select the correct line to postfix to the url `https://doi.org`, it's not really related to Grobid. Even if you read the file without an XML parser you could select the line by including `type="DOI"` in your filtering. 
     
However, perhaps you could use this library to parse the XML https://pypi.org/project/grobid-tei-xml/ 
[Here](https://github.com/lfoppiano/document-qa/blob/104b3a928118fb6c9098d275856d0af36577e597/document_qa/grobid_processors.py#L159C9-L165C10) is something similar to what you need: 

```python 
doc = grobid_tei_xml.parse_document_xml(text)
doi = doc.header.doi if doc_biblio.header.doi is not None else ""
```

**Comment by lfoppiano** [comment]
I'm closing this issue, feel free to reopen or reply if you need more information.
