### ISSUE TITLE
how to modify the tei.xml file

### ISSUE THREAD

**Issue by cherry-fan** [kermitt2/grobid#1101]
hello

I tested the PDF in the Python client and found that the content related to "keywords" in the original PDF was not found in the tei.xml file. Should I regenerate the model by modifying the tei.xml file and then extract it? How should I modify the tei.xmi file?

![image](https://github.com/kermitt2/grobid/assets/42026148/dbaf3a5b-b77d-4a59-ba63-51f63374161e)

**Comment by Schroedi** [comment]
You will have to re-train the models: https://grobid.readthedocs.io/en/stable/training/General-principles/
In this case it's the header and maybe segmentation models.
