### ISSUE TITLE
failed with error 408 , None issue

### ISSUE THREAD

**Issue by Khyati-Microcrispr** [kermitt2/grobid#1121]
Hi, I am using grobid through python and facing this issue everytime I run 
Processing of [./resources/test_pdf_2//PIIS1535610823000831.pdf](https://file+.vscode-resource.vscode-cdn.net/Khyati/NLP_NER/Python_Notebooks_NLP/NLP/EXperiment_NLP/PDF_File_Sample%20/grobid_client_python-master/resources/test_pdf_2//PIIS1535610823000831.pdf) failed with error 408 , None

**Comment by lfoppiano** [comment]
@Khyati-Microcrispr could you please update the PDF here? I cannot download it from the link you provided.

**Comment by lfoppiano** [comment]
I close the issue. If you still have the same problem, feel free to comment or reopen it.
