### ISSUE TITLE
java program memory keeps growing without reclaiming the problem

### ISSUE THREAD

**Issue by zwjjiaozhu** [kermitt2/grobid#1122]
- MacOs arm64
- Java 17

Hello
Whenever I process a pdf file, java's memory grows by a few MB. i thought there would be a memory reclaim, but in fact the memory is not reduced.
I am looking for your help, thanks!
<img width="878" alt="Snipaste_2024-06-09_10-24-12" src="https://github.com/kermitt2/grobid/assets/34623422/c03f0738-cc12-43f2-8675-a76e863c7ef1">

**Comment by lfoppiano** [comment]
The JDK maximum amount of memory is usually capped, so it cannot go above a certain level. The JVM is designed to reclaim memory only when needed, without a policy to force the garbage collector running unnecessary computation. 
Over time the memory will flatten out to the maximum allowed to the JVM.

**Comment by zwjjiaozhu** [comment]
> The JDK maximum amount of memory is usually capped, so it cannot go above a certain level. The JVM is designed to reclaim memory only when needed, without a policy to force the garbage collector running unnecessary computation. Over time the memory will flatten out to the maximum allowed to the JVM.

i know，thank you very much!
