### ISSUE TITLE
Repo is not avilable from Maven

### ISSUE THREAD

**Issue by mladenbabic** [kermitt2/grobid#1129]
I have used a Java client in my maven project. The problem is that URL where grobid-core is located doesn't exist any more on this link: https://grobid.s3.eu-west-1.amazonaws.com/repo

Please, upload or allow entry for the required client file. 

Thanks
MB

**Comment by lfoppiano** [comment]
Hi @mladenbabic, 
   I think you can use the java client as a static jar with maven. maybe you can use it via https://jitpack.io/ 

Please note that https://github.com/kermitt2/grobid-client-java haven't been updated in the last few years so you might have some limited functionality in there. We are open to external contribution, if you want to catch up with the python client.

**Comment by mladenbabic** [comment]
Hi @lfoppiano , thx for the quick replay. I'll do as you suggested. Put the jar file directly in the project. 

Kind regards,
MB
