### ISSUE TITLE
docker image just crashes when i try Restfull Services option

### ISSUE THREAD

**Issue by mohdaliiqbal** [kermitt2/grobid#113]
Following are simple log output of the commands.. Once the server started i used the Restfull services screen and submitted a PDF for "Process fulltext document" option

```
$ docker run -t --rm -p 8080:8080 lfoppiano/grobid:0.4.1-SNAPSHOT
Unable to find image 'lfoppiano/grobid:0.4.1-SNAPSHOT' locally
0.4.1-SNAPSHOT: Pulling from lfoppiano/grobid

51f5c6a04d83: Already exists 
a3ed95caeb02: Pull complete 
7004cfc6e122: Pull complete 
aee1f2b2873f: Pull complete 
3a68342c4011: Pull complete 
6cbd71d4d1f4: Pull complete 
a26b1ce3360b: Pull complete 
55bdb2de3391: Pull complete 
80a3287ca69b: Pull complete 
acf842c93ef4: Pull complete 
5f88d4767ac5: Pull complete 
c91a3a3c603f: Pull complete 
974103e367a4: Pull complete 
c417f1f68764: Pull complete 
e2d9117f7415: Pull complete 
5f07915f3ba9: Pull complete 
1ca96470e18e: Pull complete 
60518e7304fb: Pull complete 
47ee7707e914: Pull complete 
Digest: sha256:03eb5d1b9e9700445feaad3723c52825fb5503614d91b532700776425afc5485
Status: Downloaded newer image for lfoppiano/grobid:0.4.1-SNAPSHOT
2016-08-11 07:43:55.363:INFO::main: Logging initialized @1477ms
2016-08-11 07:43:55.960:INFO:oejs.SetUIDListener:main: Setting umask=02
2016-08-11 07:43:55.991:INFO:oejs.SetUIDListener:main: Opened ServerConnector@6108b2d7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-08-11 07:43:55.994:INFO:oejs.SetUIDListener:main: Setting GID=999
2016-08-11 07:43:55.995:INFO:oejs.SetUIDListener:main: Setting UID=999
2016-08-11 07:43:56.000:INFO:oejs.Server:main: jetty-9.3.9.v20160517
2016-08-11 07:43:56.035:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
Aug 11, 2016 7:50:04 AM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  org.grobid.service
Aug 11, 2016 7:50:04 AM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class org.grobid.service.GrobidRestService
Aug 11, 2016 7:50:04 AM com.sun.jersey.api.core.ScanningResourceConfig init
INFO: No provider classes found.
Aug 11, 2016 7:50:04 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.8 06/24/2011 12:17 PM'
2016-08-11 07:50:07.282:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@1e397ed7{/,file:///tmp/jetty/jetty-0.0.0.0-8080-ROOT.war-_-any-3441311393187711935.dir/webapp/,AVAILABLE}{/ROOT.war}
2016-08-11 07:50:07.310:INFO:oejs.AbstractConnector:main: Started ServerConnector@6108b2d7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-08-11 07:50:07.313:INFO:oejs.Server:main: Started @373427ms
[Wapiti] Loading model: "/opt/grobid-home/models/fulltext/model.wapiti"
Model path: /opt/grobid-home/models/fulltext/model.wapiti
[Wapiti] Loading model: "/opt/grobid-home/models/segmentation/model.wapiti"
Model path: /opt/grobid-home/models/segmentation/model.wapiti
[Wapiti] Loading model: "/opt/grobid-home/models/figure/model.wapiti"
Model path: /opt/grobid-home/models/figure/model.wapiti
[Wapiti] Loading model: "/opt/grobid-home/models/table/model.wapiti"
Model path: /opt/grobid-home/models/table/model.wapiti
[Wapiti] Loading model: "/opt/grobid-home/models/header/model.wapiti"
error: out of memory
```
----
i tried again 

```
XXXXXXX>$ docker run -t --rm -p 8080:8080 lfoppiano/grobid:0.4.1-SNAPSHOT
2016-08-11 08:03:00.751:INFO::main: Logging initialized @713ms
2016-08-11 08:03:01.137:INFO:oejs.SetUIDListener:main: Setting umask=02
2016-08-11 08:03:01.163:INFO:oejs.SetUIDListener:main: Opened ServerConnector@6108b2d7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-08-11 08:03:01.166:INFO:oejs.SetUIDListener:main: Setting GID=999
2016-08-11 08:03:01.166:INFO:oejs.SetUIDListener:main: Setting UID=999
2016-08-11 08:03:01.170:INFO:oejs.Server:main: jetty-9.3.9.v20160517
2016-08-11 08:03:01.194:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
Aug 11, 2016 8:03:05 AM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  org.grobid.service
Aug 11, 2016 8:03:06 AM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class org.grobid.service.GrobidRestService
Aug 11, 2016 8:03:06 AM com.sun.jersey.api.core.ScanningResourceConfig init
INFO: No provider classes found.
Aug 11, 2016 8:03:06 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.8 06/24/2011 12:17 PM'
2016-08-11 08:03:08.371:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@1e397ed7{/,file:///tmp/jetty/jetty-0.0.0.0-8080-ROOT.war-_-any-833371186764385181.dir/webapp/,AVAILABLE}{/ROOT.war}
2016-08-11 08:03:08.385:INFO:oejs.AbstractConnector:main: Started ServerConnector@6108b2d7{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2016-08-11 08:03:08.387:INFO:oejs.Server:main: Started @8349ms
[Wapiti] Loading model: "/opt/grobid-home/models/fulltext/model.wapiti"
Model path: /opt/grobid-home/models/fulltext/model.wapiti
[Wapiti] Loading model: "/opt/grobid-home/models/segmentation/model.wapiti"
Model path: /opt/grobid-home/models/segmentation/model.wapiti
[Wapiti] Loading model: "/opt/grobid-home/models/figure/model.wapiti"
Model path: /opt/grobid-home/models/figure/model.wapiti
[Wapiti] Loading model: "/opt/grobid-home/models/header/model.wapiti"
Model path: /opt/grobid-home/models/header/model.wapiti
```
---
At this point the docker container crashed again ... and on UI it said 

"Error encountered while requesting the server."

**Comment by mohdaliiqbal** [comment]
Is there a way to increase Jetty memory?

**Comment by lfoppiano** [comment]
Thanks for reporting this. 

I'm going to have a look at it, in the meantime I need a couple of informations: 
- details of your virtual machine? Using the command: 
> docker-machine inspect

- what's the dimension of the PDF? Could you process it using the [online service](http://grobid.science-miner.com)?

**Comment by mohdaliiqbal** [comment]
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.99.100",
        "MachineName": "default",
        "SSHUser": "docker",
        "SSHPort": 62667,
        "SSHKeyPath": "/Users/xxxx/.docker/machine/machines/default/id_rsa",
        "StorePath": "/Users/xxx/.docker/machine",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "VBoxManager": {},
        "HostInterfaces": {},
        "CPU": 1,
        "Memory": 1024,
        "DiskSize": 20000,
        "NatNicType": "82540EM",
        "Boot2DockerURL": "",
        "Boot2DockerImportVM": "",
        "HostDNSResolver": false,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HostOnlyNicType": "82540EM",
        "HostOnlyPromiscMode": "deny",
        "NoShare": false,
        "DNSProxy": true,
        "NoVTXCheck": false
    },
    "DriverName": "virtualbox",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [],
            "Ipv6": false,
            "InsecureRegistry": [],
            "Labels": [],
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": true,
            "RegistryMirror": [],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Image": "swarm:latest",
            "Strategy": "spread",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": [],
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "/Users/xxxx/.docker/machine/certs",
            "CaCertPath": "/Users/xxxx/.docker/machine/certs/ca.pem",
            "CaPrivateKeyPath": "/Users/xxxx/.docker/machine/certs/ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/Users/xxxx/.docker/machine/machines/default/server.pem",
            "ServerKeyPath": "/Users/xxxx/.docker/machine/machines/default/server-key.pem",
            "ClientKeyPath": "/Users/xxx/.docker/machine/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "/Users/xxxx/.docker/machine/certs/cert.pem",
            "ServerCertSANs": [],
            "StorePath": "/Users/xxxx/.docker/machine/machines/default"
        }
    },
    "Name": "default"
}

**Comment by mohdaliiqbal** [comment]
I think behavior is same for all pdfs that i tried. but sample is here attached [3.pdf](https://github.com/kermitt2/grobid/files/413268/3.pdf)

**Comment by lfoppiano** [comment]
Hi, 
   I see that you have only 1024 Mb of memory in your machine. You should increase it. I have 2048 and it's working, however the best should be to have 4Gb. Could you try to change that and let me know whether it's at least working for single requests? 

In the meantime, I've also asked [here](https://github.com/appropriate/docker-jetty/issues/37#issuecomment-239110388) some information, but might take more time to fix them.

**Comment by mohdaliiqbal** [comment]
I just did that and it worked. Sorry for raising this stupid issue.

**Comment by lfoppiano** [comment]
No worries! In fact the issue wasn't stupid, since having GROBID running with only 2 Gb might not enough. ;-) 

I will leave this issue open until I've fixed the Docker image having GROBID running with 4Gb.
I'm going to update the documentation. 

Thanks! 👍

**Comment by mohdaliiqbal** [comment]
Thank you. By the way JAXB 2.0 works nicely with the generated bindings. I followed the instructions in TEI-encoding-of-results.md. With these bindings i was able to parse these papers and push interesting meta data in elasticsearch for analysis.

**Comment by kermitt2** [comment]
Thanks a lot Muhammad for this feedback about the bindings with JAXB 2.0! Very interesting, I will update the documentation ```TEI-encoding-of-results.md```. 

Regarding the memory requirement for GROBID, it is discussed a bit on the main readme.md page ->  extracting only metadata header from a PDF requires less than 2 GB memory in a multithreading usage, extracting citations uses around 3GB and extracting all the PDF structure around 4GB.

**Comment by lfoppiano** [comment]
Dockerfile and documentation have been updated. ;-)
