### ISSUE TITLE
FAILURE: gradle clean install or ./gradlew clean install

### ISSUE THREAD

**Issue by RLWOHIO** [kermitt2/grobid#1147]
Hi,

I am unable to install GroBid with my local gradle (8.3 or 8.9) or the gradlew wrapper included in the grobid download.  My system: HPC Linux cluster (4.18.0-553.8.1.el8_10.x86_64), JDK 20. Below are the errors. Please see details in the attached log files. I looked through the previous issues with regard to installation and did't get much help from the discussions therein. Thanks much for your help!

[log.gradleWrapperIncluded.errors.txt](https://github.com/user-attachments/files/16461717/log.gradleWrapperIncluded.errors.txt)
[log.gradle8.9.errors.txt](https://github.com/user-attachments/files/16461718/log.gradle8.9.errors.txt)

./gradlew clean install
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'grobid'.
> Could not open proj generic class cache for build file '/home/rwang/grobid-0.8.0/build.gradle' (/home/rwang/.gradle/caches/7.2/scripts/amvdgqqto9hown0vrmahictlx).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64
   
gradle clean install //locally installed gradle 8.3 or 8.9
FAILURE: Build failed with an exception.

* Where:
Build file '/home/rwang/grobid-0.8.0/build.gradle' line: 592

* What went wrong:
A problem occurred evaluating root project 'grobid'.
> Could not create task ':codeCoverageReport'.
   > No signature of method: org.gradle.api.reporting.internal.TaskGeneratedSingleFileReport.enabled() is applicable for argument types: (Boolean) values: [true]

Before creating a new issue, make sure you had a look at the [official documentation](https://grobid.readthedocs.com). For specific questions, you can try the [Mendable Q/A chat](https://www.mendable.ai/demo/723cfc12-fdd6-4631-9a9e-21b80241131b) (**NOTE**: This is rather experimental, if not sure, make sure you double-check using the official documentation.)

- What is your OS and architecture? Windows is not supported and Mac OS arm64 is experimentally supported. For non-supported OS, you can use Docker (https://grobid.readthedocs.io/en/latest/Grobid-docker/)

- What is your Java version (`java --version`)? 

- In case of build or run errors, please submit the error while running gradlew with ``--stacktrace`` and ``--info`` for better log traces (e.g. `./gradlew run --stacktrace --info`) or attach the log file `logs/grobid-service.log` or the console log.

**Comment by kermitt2** [comment]
Hello @RLWOHIO !

I think gradle 7.2 is not compatible with JDK 20 - thus the error "Unsupported class file major version 64".
To solve the issue, you can use JDK 17 for building the project.

(the Grobid gradle wrapper uses the version of gradle indicated under gradle/wrapper/gradle-wrapper.properties, the version of Jacoco currently used in `build.gradle` is also not compatible with gradle >=8, so we will need some updates in the future to support Gradle 8).
