### ISSUE TITLE
Fine Tuning GROBID

### ISSUE THREAD

**Issue by ap-mps** [kermitt2/grobid#1148]
1) When trying to Fine Tune GROBID is there a way to add new files in the corpus folder and load grobid from a pre saved state / checkpoint and then fine tune it. 

Right now it seems that one has to put all the data in the corpus folder and train the model with everything (old and new files)

**Comment by kermitt2** [comment]
Hello @ap-mps 

This is incremental training. You can check the documentation how to launch this type of training: 
https://grobid.readthedocs.io/en/latest/Training-the-models-of-Grobid/#train-and-evaluation-separately-and-using-more-parameters-full-mode
and go to the sub-section "Incremental training", It works both for CRF and  deep learning models. It uses the current model to continue the training/fine-tuning. 

In the corpus folder, you simply add the new files without removing the older ones, or remove the older files before adding the new ones. I didn't observe a clear difference between the two in term of accuracy, maybe removing the old ones lead to slightly better improvement, but not clear.

**Comment by ap-mps** [comment]
Thanks for the prompt reply.
