### ISSUE TITLE
createTRAINING batch command

### ISSUE THREAD

**Issue by ap-mps** [kermitt2/grobid#1149]
when running this command I noticed that corresponding to a certain PDF present in the 'directory of input files' files for the header model are not generated ? 

Why so and generally is there a criteria for generation of output files model wise corresponding to an input pdf?

**Comment by kermitt2** [comment]
Hello !

Normally it means that the PDF is image only (Grobid does not include an OCR, it has to be provided as pre-processing). Other possible explanations: encrypted PDF or corrupted PDF. Finally it's also possible that no header is detected by the segmentation model which is applied first. In the last case, it means the corrected segmentation training file has to be put first in the segmentation training and the segmentation model updated.
