### ISSUE TITLE
Format PDF to detect references

### ISSUE THREAD

**Issue by HuynhVuInnomize** [kermitt2/grobid#1152]
Can you explain how to edit the PDF file format and what the correct format should be to detect references?

In attached image. Grobib just detect ref at first case (word "and" the same line with "Vlissides (1995)") and can not detect the 2nd and third case.
Thank you.
!
![test_format](https://github.com/user-attachments/assets/598cda3d-da6c-4513-b267-7b9e43a2e0c0)

**Comment by lfoppiano** [comment]
@HuynhVuInnomize it depends on the paper, layout and other statistical factors. The model responsible for this extraction is the fulltext which has around 30 examples. Adding a few more training data with problematic cases, should help rapidly. If you can share the examples we are planning to work on the training data in future, we can include it, however, if you are in a hurry you can create and correct them on your own.
