### ISSUE TITLE
Issue with training and evaluating the header module

### ISSUE THREAD

**Issue by Ranch951** [kermitt2/grobid#1158]
Hello, 

I have been trying to train the header model of Grobid using 81 test files based on PHD job market papers. The goal is to be able to differentiate real authors and names listed in the acknowledgement section to have a usable dataset. I am running Grobid on WSL using Linux Ubuntu and Java 17.0.11. I am using the current development version of Grobid (0.8.1-SNAPSHOT). 

I am having a problem when I try to train and evaluate (segmentation ratio of 0.8), the training runs for approximately five-ten minutes then I get the error: 

Exception in thread "main" org.grobid.core.exceptions.GrobidException: [GENERAL] An exception occurred while evaluating Grobid.

To be honest I am unsure of what is causing the issue, I have tried various things, but I can not fix it. I have tried a clean install, and changing java versions. I have looked through my files to see if one of them is formatted wrong but I have found nothing wrong with them. Below I am attaching the output from Grobid. 

Thank you in advance! 

[Grobid_output_error (1).txt](https://github.com/user-attachments/files/16743243/Grobid_output_error.1.txt)

**Comment by lfoppiano** [comment]
Hi @Ranch951, I try to help you and I have a few questions: 
 - could you try to run it with parameter `-s 1`? Does return the same error?
 - The 81 additional files from PhD dissertations were added by you in `corpus/raw` and `corpus/tei` in addition to the current amount of training data, correct? 
 - if you run the example, [here](https://grobid.readthedocs.io/en/latest/Training-the-models-of-Grobid/), under "Automatically split data, train and evaluate", does it work fine?

**Comment by Ranch951** [comment]
Hi, 

Thank you so much for the fast response. To answer the three questions.

- When I run it with -s 1 it does not return the same error, I think that the error only occurs when some of the data is used for evaluation. 
- The 81 files are added under both corpus/raw and corpus/tei. Making the total training files 825. 
- The command I am using is the command from "Automatically split data, train and evaluate" just with a segmentation ratio of 0.8 not 0.75.

**Comment by lfoppiano** [comment]
Could you share the output of the error when using `-s 1`? 

I'm doing guess work here, I don't know what might be the problem. I can speculate one of the training data are not in sync (raw<->tei) but I'm not sure.

**Comment by Ranch951** [comment]
The output for -s 1 is attached below:

It is possible that the training data is not in sync, but I have tried on multiple clean installs being very careful with placing my training files into the specific folders to not cause an error.

[-s_1_Grobid_output.txt](https://github.com/user-attachments/files/16753717/-s_1_Grobid_output.txt)

**Comment by Ranch951** [comment]
The output for -s 1 is attached below:

It is possible that the training data is not in sync, but I have tried on multiple clean installs being very careful with placing my training files into the specific folders to not ca

[-s_1_Grobid_output.txt](https://github.com/user-attachments/files/16753747/-s_1_Grobid_output.txt)
use an error.

**Comment by lfoppiano** [comment]
This error is OKish 😄 because it's complaining that the data is empty, which is correct, since you selected `-s 1`

At this point, I need to see the data, if you could send me your training data I will have a look. You can send it at luca AT sciencialab.com

**Comment by lfoppiano** [comment]
The issue was due to some misalignment between the tei.xml files and the feature files (the text files).
