### ISSUE TITLE
GROBID does not parse author affiliations anymore.

### ISSUE THREAD

**Issue by mbosten** [kermitt2/grobid#1164]
I tried parsing PDFs today but GROBID seems to leave the author affiliation out for every document. 

I used Docker with the GROBID DL model (0.8.1-name-address) and did not specify a consolidation service. 
Later, I tried the web service demo and include the consolidation service, but to no avail. 
I believe it is not due to specific PDF formatting, since previously correctly converted PDF's currently did not include affiliation information using the webservice demo (see example below). 

Using the webservice with header and funder consolidation:
`
                        <author>
                            <persName>
                                <forename type="first">Peiyao</forename>
                                <surname>Li</surname>
                            </persName>
                            <email>**(removed for privacy reasons)**</email>
                        </author>
`

Running the same script in command line a few months earlier:
`
						<author>
							<persName><forename type="first">Peiyao</forename><surname>Li</surname></persName>
							<email>**(removed for privacy reasons)**</email>
							<affiliation key="aff0">
								<orgName type="laboratory">TKLNDST</orgName>
								<orgName type="institution">Nankai University</orgName>
								<address>
									<country key="CN">China</country>
								</address>
							</affiliation>
						</author>
`

Any clue where the issue might lie? The affiliation parsing for me is the most important aspect of the GROBID output, so any help would be much appreciated!

**Comment by lfoppiano** [comment]
@mbosten the docker image `0.8.1-name-address` is an experimental `work in progress` image. 

I would recommend you to use the stable version `0.8.0`.

**Comment by lfoppiano** [comment]
@mbosten I confirm there is a small issue with affiliation running grobid 0.8.1 full. The problem does not happens on the CRF-only image (`lfoppiano/grobid:0.8.1`), nor on the `master` version, using only the CRF models.

**Comment by lfoppiano** [comment]
@mbosten problem should be solved now for every docker image of 0.8.1
