### ISSUE TITLE
Training data non TEI-conformant

### ISSUE THREAD

**Issue by cboulanger** [kermitt2/grobid#1169]
Hi, this isn't really a big deal but might be easy to fix. If your create your custom training files with the "createTraining" batch job, you get a file like this one: 

10.1111_1467-6478.00057.training.references.authors.tei.xml
```xml
<?xml version="1.0" ?>
<TEI xml:space="preserve" xmlns="http://www.tei-c.org/ns/1.0" xmlns:xlink="http://www.w3.org/1999/xlink" 
 xmlns:mml="http://www.w3.org/1998/Math/MathML">
	<teiHeader>
		<fileDesc>
			<sourceDesc>
				<biblStruct>
					<analytic>
						<author><forename>A</forename>. <surname>Phillips</surname></author>

						<author><forename>T</forename>. <surname>Brennan</surname> and <forename>C</forename>. <surname>Pateman</surname></author>

						<author><forename>M</forename>. <surname>Sawer</surname> and <forename>M</forename>. <surname>Simms</surname></author>

<!-- snip -->
					</analytic>
				</biblStruct>
			</sourceDesc>
		</fileDesc>
	</teiHeader>
</TEI>

```

However, this is not valid `biblStruct`, which [must not have any non-marked-up content](https://tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COBITY). The right element would be `<bibl>` here.

**Comment by cboulanger** [comment]
Also as you probably know, `<middlename>` is not valid TEI either (middle names are just  additional `<forename>`s... but I assume you're interested less in TEI conformance than in extraction efficiency. It's just that my auto-validating editor is mad at me for all those schema violations 😄.

**Comment by lfoppiano** [comment]
AFAIK the training data files are not following strictly the TEI format, as they are "internal" files with the sole scope of being used for training, so in many case to avoid remapping all tags to the respective label there were introduced some additional tags 😄

**Comment by cboulanger** [comment]
Ok, I understand. Closing the issue.
