### ISSUE TITLE
Container 0.8.1 not working with Nvidia GPUs

### ISSUE THREAD

**Issue by dcfidalgo** [kermitt2/grobid#1170]
Hi there! Thanks for this super handy tool!!
Quick question: did someone manage to use GPUs with the new docker 0.8.1 image? I get the error 
```bash
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
```
Using version 0.8.0 everything works as expected.

- What is your OS and architecture? Windows is not supported and Mac OS arm64 is experimentally supported. For non-supported OS, you can use Docker (https://grobid.readthedocs.io/en/latest/Grobid-docker/)
Ubuntu 24.04

- What is your Java version (`java --version`)? 
docker

- In case of build or run errors, please submit the error while running gradlew with ``--stacktrace`` and ``--info`` for better log traces (e.g. `./gradlew run --stacktrace --info`) or attach the log file `logs/grobid-service.log` or the console log. 
`Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory`

**Comment by lfoppiano** [comment]
Hi @dcfidalgo thanks for reporting this issue. I've fixed and pushed a new image `lfoppiano/grobid:0.8.1-fixes`, please check it out. We'll roll out the new updated docker images ASAP.

**Comment by lfoppiano** [comment]
All docker image have been updated. Sorry for the inconvenience.

**Comment by dcfidalgo** [comment]
Thanks a lot for the quick fix!!
