### ISSUE TITLE
Null pointer exception on absent copyright model in 0.8.1. image

### ISSUE THREAD

**Issue by pasha-pplx** [kermitt2/grobid#1178]
### Log and information

```
ERROR [2024-10-05 16:15:24,662] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs. 
! java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.grobid.core.utilities.GrobidProperties.getGrobidEngineName(String)" is null
! at org.grobid.core.engines.HeaderParser.processingHeaderSection(HeaderParser.java:315)
```

Seems you need to inverse comparision there, something like "delft".equals(...getGrobidEngineName(...))

**Comment by lfoppiano** [comment]
Hi @pasha-ppx, could you please provide more information about your problem? 
Basically answer the questions that were asked above. Without more information, I'm afraid we won't be able to help.

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
