### ISSUE TITLE
some URLs are not extracted in DAS

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#1184]
Found a case where the URL is not extracted from the PDF: 

[10.1371_journal.pone.0215651.pdf](https://github.com/user-attachments/files/17450314/10.1371_journal.pone.0215651.pdf)

Without sentence segmentation:
```xml
<p>The wind and water level data is open access provided by the Swedish Meteorological and Hydrological Institute, SMHI, through www.smhi.se. The grain size data is available through an FTP server with address www. tvrl.se/caf/ftp/Sieved_grain_size_samples.xlsx. Model code, input and results files will not be provided open access but can be made available upon request. Contact Caroline Hallin at Lund University, Sweden, at caroline.hallin@tvrl.lth.se. Topographic and bathymetric data cannot be sha
```

With sentence segmentation" 
```xml
FTP server with address www.</s><s xml:id="_4pDBZYt" coords="1,36.00,626.65,138.17,6.80">tvrl.se/caf/ftp/Sieved_grain_size_samples.xlsx.</s>
```

**Comment by lfoppiano** [comment]
I flagged as a bug, but it's more the fact that the URL are not matched in the first place. They start with `www.` instead of `http|ftp`. 

Here there is a bit of a conundrum, should we try to extend these regexes, with the risk of messing them up? The regexes should be validated with the URL's PDF annotations when they are available.

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
