### ISSUE TITLE
Identification of Suffix in author name

### ISSUE THREAD

**Issue by ArchanaHole** [kermitt2/grobid#119]
Issue: 
Current tool is not identifying suffix given in author name separately.
I have attached file for your reference wherein suffix got captured as surname and first name in TEI output. Also, casing for suffix has been changed in final TEI output.
(e.g. 'Jr', 'Sr', 'I', 'II', 'III')

Requirement:
Tool should generate separate suffix tag in author name.
Tool should retain casing for suffix as given in input file.

[10708_2015_9672_Article.pdf](https://github.com/kermitt2/grobid/files/469341/10708_2015_9672_Article.pdf)

**Comment by kermitt2** [comment]
It should work quite well now, but more training data would help. 

```xml
                           <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">Anis</forename>
                                <surname>Elbarhoumi</surname>
                                <genName>II</genName>
                            </persName>
```

```xml
                           <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">Christelle</forename>
                                <surname>Clérandeau</surname>
                                <genName>Sr</genName>
                            </persName>
```
