### ISSUE TITLE
Offset of tags in output

### ISSUE THREAD

**Issue by nooralahzadeh** [kermitt2/grobid#120]
Is there any way to catch the start and end offset of the tags as an attribute in the output?

**Comment by lfoppiano** [comment]
Hi @nooralahzadeh, 
     I'm sorry but don't really understand what you mean. With output you mean the XML-TEI output? the start and stop offset... related to what? 

Could you please add some more details and, eventually, provide some examples? 

Thanks

**Comment by nooralahzadeh** [comment]
Hi @lfoppiano ;
Sorry it was my mistake, becuase I was parsing the grobid output in the wrong way. It is okay as far as you locate the inner element inside the outer element and it is easy to detect its offset.!
Thanks

**Comment by lfoppiano** [comment]
OK, feel free to close the issue. 

I'm still wondering one thing. Out of my curiosity, why would you need the offsets? 

Having the data in XML format, it's already kind of 'prepared'. So if you parse it you could extract the information you need based on the xml structure, e.g. you need the authors and so on. For visualisation, for example if you want to show the text and highlight some part of it, should be pretty straightforward.  
Or maybe you want to get the information as standoff annotations and/or store them separately? 

Thanks
