### ISSUE TITLE
Train Grobid on more diverse examples

### ISSUE THREAD

**Issue by liar666** [kermitt2/grobid#13]
Testing Grobid on papers from arXive.org, I've found at least two cases that Grobid does not manage correctly:
- If there are 2 symbols for 1 author with 2 affiliations, then the 2nd symbol becomes his last name;
- If there is a quote symbol in the author's lastname (e.g., O'Hare), then the lastname is only the first charaters before the quote.

**Comment by lfoppiano** [comment]
@liar666 I know it's a bit late, but could you please provide the documents affected by this mistake? 

Otherwise I would close this issue. It's kind of obsolete ;-)

**Comment by liar666** [comment]
Here are two examples :
http://arxiv.org/pdf/1604.03858
http://arxiv.org/pdf/1602.03781

I've just tested, now it works ! Thanks guys for the great job :)
