### ISSUE TITLE
Make TaggingLabel extendible

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#133]
The [TaggingLabel](https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/engines/TaggingLabel.java) class hold all enumeration of labels used to tag the tokens when applying CRF.
At the moment the `enum` class cannot be extended in java. 

Would be nice to have a way to make external modules being able to define their own labels without having to modify the TaggingLabel class.

**Comment by lfoppiano** [comment]
Add method called asEnum() that returns a TaggingLabels. This will avoid the annoyance of casting the TaggingLabel in TaggingLabels. 

```
switch ((TaggingLabels) clusterLabel) {
                    case CITATION_MARKER:
```

would became

```
switch ( clusterLabel.asEnum()) {
                    case CITATION_MARKER:
```

**Comment by MedKhem** [comment]
`Engine.getCntManager().i((TaggingLabels) clusterLabel);`

This line in Grobid doesn't present any problem, but in grobid-dictionaries it triggers: 

`java.lang.ClassCastException: org.grobid.core.engines.TaggingLabels$1 cannot be cast to org.grobid.core.engines.TaggingLabels
`

any explanation for that?

**Comment by lfoppiano** [comment]
Would be nice to see the whole code. 

In theory if it works in GROBID, should work everywhere else. 

Please commit and push so that I can reproduce the problem. ;-)

**Comment by MedKhem** [comment]
Done :)

**Comment by lfoppiano** [comment]
I need to revisit this implementation. I might need to remove the Enum :/ 

At the moment the solution at [previous comment ](https://github.com/kermitt2/grobid/issues/133#issuecomment-251981482) is not feasible.

**Comment by lfoppiano** [comment]
I've made the changes in the branch taggingLabel-issue133: 
 - I've removed the enums for TaggingLabel. It has been substituted by a class called TaggingLabels that contains the labels and the cache where the labels are registered. 
- The label itself is implemented by an interface `TaggingLabel` and a class `TaggingLabelImpl` for the implementation. 

The TaggingLabels class can be viewed [here](https://github.com/kermitt2/grobid/blob/taggingLabel-issue133/grobid-core/src/main/java/org/grobid/core/engines/TaggingLabels.java).

In any module it's possible to create our own labels, by extending TaggingLabels and registering the new labels in the static context, with the method register(...), [see here](https://github.com/kermitt2/grobid-quantities/blob/taggingLabel-issue133/src/main/java/org/grobid/core/engines/QuantitiesTaggingLabels.java)

I need someone that didn't touch the code, to test this :)

**Comment by lfoppiano** [comment]
This is the result coming out from the batch processing: 

```
************************************************************************************
COUNTER: org.grobid.core.engines.counters.TableRejectionCounters
************************************************************************************
------------------------------------------------------------------------------------
  CANNOT_PARSE_LABEL_TO_INT:         4
  EMPTY_LABEL_OR_HEADER_OR_CONTENT:  17
  HEADER_NOT_STARTS_WITH_TABLE_WORD: 6
  HEADER_NOT_CONSECUTIVE:            1
====================================================================================

************************************************************************************
COUNTER: org.grobid.core.engines.counters.ReferenceMarkerMatcherCounters
************************************************************************************
------------------------------------------------------------------------------------
  UNMATCHED_REF_MARKERS:                    4
  MATCHED_REF_MARKERS_AFTER_POST_FILTERING: 1
  STYLE_AUTHORS:                            8
  STYLE_NUMBERED:                           1
  MANY_CANDIDATES:                          4
  NO_CANDIDATES:                            7
  INPUT_REF_STRINGS_CNT:                    39
  MATCHED_REF_MARKERS:                      2
  NO_CANDIDATES_AFTER_POST_FILTERING:       3
  STYLE_OTHER:                              30
====================================================================================

************************************************************************************
COUNTER: org.grobid.core.engines.TaggingLabelImpl
************************************************************************************
------------------------------------------------------------------------------------
  FIGURE_LABEL:             50
  FULLTEXT_TABLE_MARKER:    12
  FULLTEXT_SECTION:         61
  TABLE_LABEL:              16
  TABLE_FIGDESC:            3
  FULLTEXT_FIGURE:          68
  FULLTEXT_TABLE:           29
  TABLE_FIGURE_HEAD:        30
  FIGURE_FIGDESC:           63
  TABLE_TRASH:              28
  FULLTEXT_FIGURE_MARKER:   86
  FULLTEXT_CITATION_MARKER: 39
  FULLTEXT_PARAGRAPH:       232
  FIGURE_FIGURE_HEAD:       63
====================================================================================
====================================================================================
```

**Comment by MedKhem** [comment]
I made the changes in grobid-dictionaries. No problems :) 
Just a small modification that should be made to TaggingLabelImpl class: the constructor should be public.

Otherwise, nice and clean job :+1:

**Comment by lfoppiano** [comment]
@MedKhem the constructor is made in a way that you have to have the class using the CustomTaggingLabels in the same package of TaggingLabelImpl, `org.grobid.core.engines`. The idea is that the TaggingLabelImpl should never be instantiate but in your CustomTaggingLabels class.

**Comment by MedKhem** [comment]
Well, in my case I didn't try to instantiate TaggingLabelImpl but I had all my CustomTaggingLabels classes in a sub-package "Labels" (It's not mandatory, but it's just a choice to structure my classes). In my case, I couldn't call the constructor. I don't know if such a constraint (having all CustomTaggingLabels under org.grobid.core.engines) is necessary.

**Comment by lfoppiano** [comment]
@MedKhem yes, the idea is to have the CustomTaggingLabels under org.grobid.core.engines ;-)
