### ISSUE TITLE
Update of the header model

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/grobid#136]
The header model requires a big refresh to be consistent with all the evolutions of GROBID during the three last years.
- [x] modify pdf2xml for having blocks in reading order at least for the header segment, see fork https://github.com/kermitt2/pdf2xml
- [x] use only the Segmentation model for getting the header segment for both training data and files to be processed
- [x] modify the training format to be consistent with the rest of GROBID's training
- [x] add some new features (line indent, centered, ...)
- [x] fix some issues with the training files: see #135, + 2 PDF files in training set has no content. 
  Use full file name as identifier and check for duplicates
- [x] review carefully modified training data format 
- [x] regression test and hopefully some improvements ;)

**Comment by kermitt2** [comment]
This is work in progress with branch ```modified-pdf2xml```...

**Comment by lfoppiano** [comment]
I'm adding a PDF example as test case for this extension.  While the text is correctly extracted from pdfalto, using `-readingOrder` option, the model is mixing up (I suppose) the various streams. 

I guess after updating the header model this pdf should be extracted normally.
