### ISSUE TITLE
Invalid Format Error in OSX

### ISSUE THREAD

**Issue by thomasopsomer** [kermitt2/grobid#142]
Problem running grobid on osx (actually macOS).

I used the installation process described in the doc :

```
wget https://github.com/kermitt2/grobid/archive/grobid-parent-0.4.1.zip
unzip grobid-grobid-parent-0.4.1.zip
mvn clean install
```

And then the tests don't pass, because _"invalid format error"_ when loading the wapiti models. If skip the test I get the same error when I try grobid on a PDF.

**Comment by lfoppiano** [comment]
Thanks @thomasopsomer for reporting this issue. 

I've tried to reproduce your problem without success. 

I'm running Mac OSX El Capitan. I've downloaded the zip and run the build without skipping the tests, everything was fine. Also running the service I didn't get your issues. 

Could you provide me a more detailed error log and some more information about your system? 

Thanks
Luca

**Comment by thomasopsomer** [comment]
Hello Luca,

So I'm running the new osx version: macOS Sierra v10.12. Like you it was working on El Capitan :)
I downloaded the zip and then when building with tests, here is a sample of logs:

```
Running org.grobid.core.test.TestFullTextParser
Loading external native CRF library
Loading Wapiti native library...
Library crfpp loaded
Loading model: /Users/thomasopsomer/grobid/grobid-home/models/fulltext/model.wapiti (size: 6685602)
[Wapiti] Loading model: "/Users/thomasopsomer/grobid/grobid-home/models/fulltext/model.wapiti"
error: invalid model format
Running org.grobid.core.test.TestHeaderParser
Loading external native CRF library
Loading Wapiti native library...
Library crfpp loaded
Loading model: /Users/thomasopsomer/grobid/grobid-home/models/header/model.wapiti (size: 36094028)
[Wapiti] Loading model: "/Users/thomasopsomer/grobid/grobid-home/models/header/model.wapiti"
error: invalid model format
Running org.grobid.core.test.TestNameParser
Loading external native CRF library
Loading Wapiti native library...
Library crfpp loaded
Loading model: /Users/thomasopsomer/grobid/grobid-home/models/name/header/model.wapiti (size: 2055704)
[Wapiti] Loading model: "/Users/thomasopsomer/grobid/grobid-home/models/name/header/model.wapiti"
error: invalid model format
Running org.grobid.core.test.TestReferencesParser
Loading external native CRF library
Loading Wapiti native library...
Library crfpp loaded
Loading model: /Users/thomasopsomer/grobid/grobid-home/models/citation/model.wapiti (size: 12972361)
[Wapiti] Loading model: "/Users/thomasopsomer/grobid/grobid-home/models/citation/model.wapiti"
error: invalid model format

....

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] grobid-parent ...................................... SUCCESS [  0.484 s]
[INFO] grobid-home ........................................ SUCCESS [ 16.847 s]
[INFO] grobid-core ........................................ FAILURE [ 55.110 s]
[INFO] grobid-trainer ..................................... SKIPPED
[INFO] grobid-service ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2016-10-13T12:31:04+02:00
[INFO] Final Memory: 26M/425M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project grobid-core: ExecutionException; nested exception is java.util.concurrent.ExecutionException: java.lang.RuntimeException: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
```

**Comment by lfoppiano** [comment]
Wow, what Apple didn't say about Sierra? :-o 

Can we check that the md5sum, checksum and dimension of the models has not been changed? I doubt so. 
 
There are mine: 

Md5: 
```
Johan:models lfoppiano$ md5 fulltext/model.wapiti 
MD5 (fulltext/model.wapiti) = e7a234087a43f18daaafe41f7a1e6426
Johan:models lfoppiano$ md5 header/model.wapiti 
MD5 (header/model.wapiti) = 1ae582a2abc0ad27dc8d08b9d1edbf1d
```

Checksum: 
```
Johan:models lfoppiano$ shasum header/model.wapiti 
b33401ac16516fff2aa7d25b9a163719032d9cbb  header/model.wapiti
Johan:models lfoppiano$ shasum fulltext/model.wapiti 
02d6627b690894da5b848b119e580ed7aa0de49f  fulltext/model.wapiti
```

dimension: 
```
Johan:models lfoppiano$ ls -l  fulltext/model.wapiti 
-rw-r--r--  1 lfoppiano  staff  6685602 Oct  2 00:10 fulltext/model.wapiti
Johan:models lfoppiano$ ls -l  header/model.wapiti 
-rw-r--r--  1 lfoppiano  staff  36094028 Oct  2 00:10 header/model.wapiti
```

**Comment by thomasopsomer** [comment]
mine :)

MD5:
```
md5 fulltext/model.wapiti 
MD5 (fulltext/model.wapiti) = e7a234087a43f18daaafe41f7a1e6426
md5 header/model.wapiti 
MD5 (header/model.wapiti) = 1ae582a2abc0ad27dc8d08b9d1edbf1d
```

Checksum
```
shasum header/model.wapiti 
b33401ac16516fff2aa7d25b9a163719032d9cbb  header/model.wapiti
shasum fulltext/model.wapiti 
02d6627b690894da5b848b119e580ed7aa0de49f  fulltext/model.wapiti
```

dimension
```
-rw-r--r--  1 thomasopsomer  staff  6685602  2 oct 00:10 fulltext/model.wapiti
-rw-r--r--  1 thomasopsomer  staff  36094028  2 oct 00:10 header/model.wapiti
```

Everything seems identical.

**Comment by lfoppiano** [comment]
I'm baffled!

Let's see the termination lines. If you run this command it should compare the file with LF termination line with the original: 
```
dos2unix < fulltext/model.wapiti | cmp -s - fulltext/model.wapiti 
```

If this is negative... I'm out of ideas for the moment :(

**Comment by thomasopsomer** [comment]
the cmd doesn't return anything, I guess it's positive ?

**Comment by lfoppiano** [comment]
it depends :) it means there is no difference... so the problem is somewhere else 🗡

...thinking...

**Comment by kermitt2** [comment]
Hello Thomas,

Well negative to find the problem ;)
Just another idea, what is your locale settings?

> locale

Normally, the issue related to locale have been solved since ~2 years with our Wapiti fork, but who knows...

**Comment by thomasopsomer** [comment]
Hello Patrice,

locale gives:
`
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
`

Anyway the good turn-around is to use Docker :)

**Comment by kermitt2** [comment]
Ah sure, Docker is the hammer solution !

What happens if you change your LOCALE in your terminal before launching GROBID? Simply try: 

>export LC_ALL=C

**Comment by thomasopsomer** [comment]
wow magic, the test passed and build completed with success :)

**Comment by kermitt2** [comment]
It means to check why the change of LOCALE integrated in our Wapiti fork (just before reading the CRF model, in order to be sure to have portable models) is not working anymore on Mac OS X 10.12 :( 

The other related problem is that the architecture info changed, because Apple renamed "OS X" into "macOS", this could impact the resolution of the path to the native stuff based on the architecture. 

Thanks a lot Thomas for helping us!

**Comment by iorala** [comment]
I've had similar problems on macOs sierra on which the workaround setting LC_ALL="C" worked.
I've managed to solve the issues by recompiling wapiti on macOS sierra. See pull request #240
