### ISSUE TITLE
Line status feature: "Line end" not captured for many instances in an OCRized dictionary sample

### ISSUE THREAD

**Issue by MedKhem** [kermitt2/grobid#146]
The file "[LettreP-117082016.pdf](https://github.com/kermitt2/grobid/files/557933/LettreP-117082016.pdf)" contains a OCRized scan from a dictionary page. The method **getBodyTextFeatured()** in **FullTextParser** captures just 6 "LINEEND" instances out of ~60. Here is the [LettreP_feature_matrix.txt](https://github.com/kermitt2/grobid/files/557963/LettreP_feature_matrix.txt)

**Comment by kermitt2** [comment]
Thanks @MedKhem !

I found the error. It should be fixed on the master branch thanks to the last commit 2916deeee34525640ddd9fde38afae2be4f7fa27

And it has a small but positive impact on body processing according to evaluation on PubMedCentral sample.

Thanks in advance if you could test again for confirmation.

**Comment by kermitt2** [comment]
@MedKhem could we close this one?

**Comment by MedKhem** [comment]
I have just tested again and the problem is fixed. I think you could close it :)
