### ISSUE TITLE
Pdf annotation doesn't notify in case of errors 

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#148]
When the PDF annotation fails, the page keep showing "Request server...". Seems a problem in the javascript. 

To reproduce the problem: 
1. select tab _PDF_ and then _Add layer to PDF_
2. select the following [PDF](https://www.nationalgallery.org.uk/upload/pdf/billinge_syson_spring2011.pdf)  
3. the "Request server..." remains independently from the fact that the request had failed with error 500 (see screenshot)

<img width="1224" alt="screen shot 2016-11-30 at 16 43 01" src="https://cloud.githubusercontent.com/assets/15426/20759239/a87af97c-b71c-11e6-911e-01c5e799d9f2.png">

**Comment by lfoppiano** [comment]
Seems there is a regression with commit 4a64a2e (see changes in grobid.js)

When the document is valid, there is still a 'request to server' information: 
<img width="896" alt="screen shot 2016-12-28 at 11 51 09" src="https://cloud.githubusercontent.com/assets/15426/21520422/7cc5f078-ccf4-11e6-8091-442a87cafcc1.png">

When the document is invalid, nothing happear: 
<img width="1343" alt="screen shot 2016-12-28 at 11 53 49" src="https://cloud.githubusercontent.com/assets/15426/21520387/5951cf9a-ccf4-11e6-8064-b07ab4d9b891.png">

**Comment by kermitt2** [comment]
ok it's only the add layer to pdf service right?

**Comment by lfoppiano** [comment]
The other service seems working fine. The 'request to server' is behaving correctly. I don't know in case of error, as I don't have a pdf that fails for that one.

**Comment by lfoppiano** [comment]
Seems correct now :-) 

<img width="951" alt="screen shot 2016-12-28 at 13 19 32" src="https://cloud.githubusercontent.com/assets/15426/21521792/533b297e-cd00-11e6-954f-a85a80fd2394.png">
