### ISSUE TITLE
Wrong order of teiHeader component in TEI output

### ISSUE THREAD

**Issue by laurentromary** [kermitt2/grobid#152]
The current TEI output (as provided by http://cloud.science-miner.com/grobid/; TEI/Process Fulltext Document) inserts encodingDesc as first element of the teiHeader. It should be placed after fileDesc, which is a mandatory first component of the TEI header.

**Comment by kermitt2** [comment]
Duplicate #509

**Comment by kermitt2** [comment]
Fix with PR #496
