### ISSUE TITLE
How to get GROBID version with RESTfull service

### ISSUE THREAD

**Issue by Katharsis** [kermitt2/grobid#155]
Hi guys,

Is there any way for getting GROBID version using REST API?

GET: http://<domain.com>/version/

On output I'd like to see text/plain or JSON with string "GROBID 0.4.1".
It will be very helpful for me.

**Comment by lfoppiano** [comment]
Dear @Katharsis thanks for your email, 
    indeed this feature is not present currently. We can add it. ;-) 

If you have already an idea on how to tokenize the version with maven, feel free to propose it ;-)

Cheers
Luca

**Comment by Katharsis** [comment]
@lfoppiano 

I'm not a Java developer but take a look at here:

https://web.archive.org/web/20120121133235/http://www.christophkiehl.com/easy-way-to-display-your-apps-version-using-maven-and-manifest

Is that what you asking for?

**Comment by lfoppiano** [comment]
@Katharsis Thanks. I'll have a look. ;-)

**Comment by lfoppiano** [comment]
Thanks to @czuraj for the PR. 
@Katharsis if you can test it would be great ;-)
