### ISSUE TITLE
Abstract has no space between words

### ISSUE THREAD

**Issue by liar666** [kermitt2/grobid#16]
When processHeader'ing some pdfs, I get an abstract with all words concatenated without spaces between them.

For instance:
http://guillaumemuller1.free.fr/Articles/iTrust2006_LNAI.pdf
But not with:
http://search.arxiv.org:8081/paper.jsp?r=1306.4727&qid=1375964777082mix_nCnN_-1091422823&qs=1306.4727

However, pdftoxml ran in commandline separates the words (TOKENs) correctly.

**Comment by kermitt2** [comment]
During the synchronisation between labeled tokens and the tokens coming from the PDF problems, special characters present in the PDF could result in this lack of space between tokens. Additional checks have been introduced to avoid that.
