### ISSUE TITLE
Titles end with question mark

### ISSUE THREAD

**Issue by paris0120** [kermitt2/grobid#169]
Grobid has difficulty in processing citation with titles ending with question mark. For example: 

Jensen, M.C., Meckling, W.H., 1978. Can the corporation survive? Financial Analysts Journal, 34: 31-37.

**Comment by kermitt2** [comment]
Thanks! I'll add more training examples for this case.

**Comment by kermitt2** [comment]
It should work fine now in general thanks to more training data. 
It is working on your example and a similar one.
