### ISSUE TITLE
PMC_sample_1943 dataset

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#172]
Hi,

The website references PMC_sample_1943 as the training data for GROBID. Unfortunately the referenced URL doesn't seem to be valid anymore. Is there any chance to get hold of that dataset?

Thank you

**Comment by kermitt2** [comment]
Hi Daniel,
Thanks for reporting this!
I've updated the url in the documentation to a version I've loaded on Amazon S3. 
Just as a precision, as explained in the doc, this dataset is only used for evaluation (benchmark for different releases are under `grobid/grobid-trainer/doc`), not for training.

**Comment by de-code** [comment]
That's great. Thank you
