### ISSUE TITLE
Umlaute: ü becomes Ã¼

### ISSUE THREAD

**Issue by nguanh** [kermitt2/grobid#173]
Hello!

I have this issue when processing references. Authors with last names such as "Müller" become
"MÃ¼ller"

**Comment by kermitt2** [comment]
Hello ! Thanks a lot for the error case. Can you give us some material like PDF or string to reproduce this error? 
We do our best to solve all the unicode issues that arise from PDF, and it's with examples like that that we can improve the tool. 
Thanks !

**Comment by nguanh** [comment]
Hello, thanks for the quick reply!
Okay here's one example: 
http://www.sciplore.org/wp-content/papercite-data/pdf/lipinski13.pdf
Reference [4] contains the name  Müller, C.

It is parsed as 
                            <author>
                                <persName
                                    xmlns="http://www.tei-c.org/ns/1.0" coords="">
                                    <forename type="first">C</forename>
                                    <surname>MÃ¼ller</surname>
                                </persName>
                            </author>

**Comment by kermitt2** [comment]
Hello,
I've just tried the paper with the current master, it worked fine:

```xml
                            <author>
                                <persName
                                    xmlns="http://www.tei-c.org/ns/1.0" coords="">
                                    <forename type="first">C</forename>
                                    <surname>Müller</surname>
                                </persName>
                            </author>
```

You can test it with the test demo http://grobid.science-miner.com

**Comment by kermitt2** [comment]
@nguanh could we close this issue?
Or do you still observe this problem and if this is the case, could you give us more information to reproduce it (your environment, grobid version, ...)?

**Comment by kermitt2** [comment]
As this is working fine with the provided example, I close the issue. Feel free to re-open it with more information if you still see the problem.
