### ISSUE TITLE
Spacing around references

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#177]
Hi,

It appears that generally there are no spaces around references (`ref`) in the generated XML.

For example (generated):
```
...presented in<ref type="table">Tables II, III</ref>the...
```

Which should be:
```
...presented in <ref type="table">Tables II, III</ref> the...
```

**Comment by kermitt2** [comment]
Hello - this is normally already fixed in the latest branch version.

**Comment by de-code** [comment]
Do you mean `master`?

**Comment by kermitt2** [comment]
oups yes sorry latest master !

**Comment by de-code** [comment]
Didn't mean to correct you, just to make sure. I made sure I updated `master` and did even clean before a rebuild. I removed the old XML file just to be sure but the issue appears to be still there. (e.g. first PubMed manuscript)

Anything I should be looking at?

**Comment by kermitt2** [comment]
No no I was wrong ;)

I tried the first PubMed central document of the PMC 1942 sample, I obtain this:

```xml
... <ref type="table" target="#tab_0">Tables II, III,</ref> the mice with adequate precision for all dose levels, as can be seen in the plots in <ref type="figure" target="#fig_1">Fig. 2</ref> which show both...
```

Apparently I've committed everything: 

```bash
lopez@smallbook:~/grobid$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**Comment by de-code** [comment]
Hmmm how very odd. On that example I am seeing now a space to the right but not to the left. i.e.:
```
presented in<ref type="table" target="#tab_0">Tables II, III,</ref> the mice
```

That is running it via the PubMed evaluation itself. i.e.:
`mvn compile exec:exec -PPubMedCentralEval -Dpmc=... -Drun=1`

When I run Grobid directly it seems to exhibit a different behaviour and continues with a different text (I guess it is picking up a different config) but still no space to the left.

`java -Xmx1024m -jar .../grobid-core/target/grobid-core-0.4.2-SNAPSHOT.one-jar.jar -gH .../grobid-home -gP .../grobid-home/config/grobid.properties -dIn ... -dOut ... -r -exe processFullText`

```
presented in<ref type="table" target="#tab_0">Tables II, III,</ref> </p></div>
```

(Doubting myself I did also look at it using different file editors / viewers)

What are of code / commit should have fixed that? I could make sure that it is run.

**Comment by kermitt2** [comment]
I also see the missing spaces on the left with the current master! I overlooked them because they are not apparent with the grobid console (there is a new line inserted before) and I did not check with a file editor. I try to fix that quickly, thanks.

**Comment by de-code** [comment]
Phew... I was starting to question what I was doing.

I also noticed missing spaces at page boundaries. For example (same PMC paper):
`only at the highest toxic doseof 200 mg qd`

instead of:
`only at the highest toxic dose of 200 mg qd`
(`dose` is on page 237 and `of` is on the following page 238, separated by a figure)

I am not sure if that is caused by the same issue.

**Comment by kermitt2** [comment]
Both issues are indeed related but with different models - segmentation in this particular case of page boundary and fulltext for the `<ref>` elements. Basically the way we create and iterate among labelled sequences (the nice `TaggingTokenClusteror` class), in some cases, does not preserve easily some starting and ending spacing. 

The missing spaces for the `<ref>` should be fixed with commit f5d5cd600ebf6f29b7dd7eff93692dc01911aeaa, I'll work on the other problem in the next days.

Thanks a lot for notifying all this problem, this is very useful !

**Comment by kermitt2** [comment]
Normally the spacing problems around references and in relation to your page boundary example are now all fixed.

**Comment by de-code** [comment]
Great, thank you.
