### ISSUE TITLE
build failed on linux 32 bit

### ISSUE THREAD

**Issue by stuartyeates** [kermitt2/grobid#18]
I'm following the instructions in the readme to get the code working, but getting the error:

Caused by: java.lang.RuntimeException: Unable to find a native CRF++ library: Folder /media/D020-1F62/github/grobid/grobid-home/lib/lin-32 does not exist

I'm on  "Linux rb-806-02-c 3.0.0-32-generic-pae #51-Ubuntu SMP Thu Mar 21 16:09:48 UTC 2013 i686 i686 i386 GNU/Linux"

**Comment by kermitt2** [comment]
linux-32 binaries for Wapiti are present since a couple of months and GROBID should work on this architecture, but I've not tested it myself because I don't have linux-32 environment around.

**Comment by lfoppiano** [comment]
@stuartyeates, @juanremi did you have the oportunity to test GROBID with linux 32? May I then close this issue?

**Comment by lfoppiano** [comment]
Tested with Ubuntu 32 bit. Works fine.
