### ISSUE TITLE
Problem with grobid build dependencies

### ISSUE THREAD

**Issue by LED-Jose** [kermitt2/grobid#182]
Hi!
I have compiled GROBID several times without problem. But now there are dependencies that I can not find in: https://repo.maven.apache.org
There are:
fr.limsi.wapiti:wapiti:jar and org.chasen:crfpp:jar

Can somebody help me.
Thanks in advance.

**Comment by lfoppiano** [comment]
Hi @LED-Jose, could you give us some details about your problem? version used, log, platform, etc. 
thanks

**Comment by kermitt2** [comment]
These two artefacts are not in repo.maven.apche.org, they are provided locally in the `grobid-core/lib/` directory. In the `pom` file, it is set like this: 

```xml
 <repositories>
        <repository>
            <id>3rd-party-local-repo</id>
            <name>This is a local repository included in the grobid project, to access 3rd party libs.</name>
            <url>file:///${basedir}/lib/</url>
            <layout>default</layout>
        </repository>
...
</repositories>
```

Be sure to have this included in your pom file (this is the case in the repo). Otherwise, I don't see what can cause this problem.

**Comment by lfoppiano** [comment]
@LED-Jose any more development on this? Can we close it?
