### ISSUE TITLE
What i need to run it?

### ISSUE THREAD

**Issue by juanremi** [kermitt2/grobid#19]
Hi i try to compile this project, but i get errors using this guide:
https://github.com/kermitt2/grobid/wiki/Grobid-service-quick-start

Tests run: 154, Failures: 0, Errors: 44, Skipped: 1

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] There are test failures.

actually i use:
Apache Maven 2.2.1 (rdebian-8)
Java version: 1.6.0_45
Java home: /usr/lib/jvm/jdk1.6.0_45/jre
Default locale: es_MX, platform encoding: UTF-8
OS name: "linux" version: "3.2.0-4-686-pae" arch: "i386" Family: "unix"

what i need.. SO, Architecture, Java version, Maven version?

thanks

**Comment by kermitt2** [comment]
Right now, GROBID is working fine with maven 3, JDK 1.7, under linux-64, mac os and normally linux-32. For Windows, this fork might be a solution: https://github.com/boumenot/Grobid.NET
