### ISSUE TITLE
Download of the resulting XML

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#201]
Add a button in the grobid console to download the resulting XML. 

To force the browser to download the xml instead of trying to parse it, see [here](https://stackoverflow.com/questions/3860750/how-to-download-an-xml-without-the-browser-opening-it-in-another-tab#3860782).

**Comment by kermitt2** [comment]
Hi @MedKhem  ! 

It's not working properly for me, here is the XML I download (attached).
[export.xml.txt](https://github.com/kermitt2/grobid/files/1155525/export.xml.txt)

* XML document is incomplete and cut suddently

* No line break anymore

**Comment by kermitt2** [comment]
(probably a matter of taste, but the button in the GUI looks very good for me!)

**Comment by MedKhem** [comment]
I re-tried the button with 3 different files on Safari and Chrome, and the output didn't cut for me. On which browser have you seen the anomaly?

For the line breaks, is it necessary to keep them? The generated xml file is anyway well formed and could be visualised in any browser correctly. Oxygen can as well display it correctly with a simple click on "Format and Indent".

For the button layout, I just followed the same layout for the other ones :) But is label ok or is it a bit long?

**Comment by kermitt2** [comment]
I tried it with Firefox 54.0

I think it's much better to keep the end of lines.  1) I don't see why we would want to modify the XML as compared to the original one returned by the API (it's confusing for a test console). 2) the advantage of TEI is that it should be readable and removing the EOL makes it unreadable. 3) not everybody view an XML file with a browser (I don't), and a lot of people are not using Oxygen (like me, too heavy and memory-hungry - and it costs $99). So having a pretty XML directly in an usual editor helps :) 

The label is nice I think, long but it makes the button well aligned with the other elements.

**Comment by kermitt2** [comment]
To keep track of progress - on the console make the button working for text input services: date, header authors, citation authors, affiliation and citation services

**Comment by lfoppiano** [comment]
After this last PR, may this issue be closed?
