### ISSUE TITLE
Use new Crossref API

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/grobid#213]
Classes are ready under package `org.grobid.core.utilities.crossref` thanks to @Vi-dot 
Consolidation of all the extracted bibliographical info will then be used by default.

**Comment by kermitt2** [comment]
So it's done. Multithreaded usage is well tested... 

What's good: 

* it's (normally) very fast as compared to the old OpenURL-style CrossRef API. All the citations of an article are checked against the API normally in a couple of seconds. The response time of the old API was rather 1 second per citation. 

* the returned metadata are complete as compared to the UNIXREF format. 

What's not good: 

* this is a search API, not a bibliographical item look-up like the old API. Look-up based on journal-title/volume/first-page or issn/volume/first-page are not possible. So the abbreviated citations common in medicine cannot anymore be checked/consolidated with the new API. 
We could use as fallback the old API for these cases maybe. 

* the web service is not reliable, sometime the response time is 20s in the middle of the day :/

**Comment by stzellerhoff** [comment]
Executing grobid by

`mvn exec:exec -Pprocess_citation_bibtex -Dpdf=/Users/zellerhs/Desktop/thefile.pdf -Dbib=/Users/zellerhs/Desktop/thefile.bib -Dconsolidation=true`

produces a bibtex file and the references are consilidated using crossref, but the process does not terminate, even if all references (or none) are found:

`>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> total (CrossRef JSON search API): 344 / 1060`

Invoking grobid with `... -Dconsolidation=false` works fine, after finishing the extraction the process terminates:

`[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.124 s
[INFO] Finished at: 2017-10-23T15:49:18+02:00
[INFO] Final Memory: 8M/245M
[INFO] ------------------------------------------------------------------------
bash-4.4$`

**Comment by kermitt2** [comment]
Thanks a lot for the report @stzellerhoff 
Could you try maybe the same file with the web service instead grobid-example? 
Maybe could you send me this pdf file so that I can reproduce the problem and investigate? (my email in the readme file)?
Thanks
