### ISSUE TITLE
Parameter for Cross-Origin Resource Sharing

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/grobid#226]
Currently CORS is allowed for any domains by default for all GROBID services. 

Add & support a config parameter for grobid-service to allow or not CORS, and to specify either any domains (*) or some selected domains.

**Comment by lfoppiano** [comment]
FYI here there is a more elegant way, although AFAIK still not configurable: https://github.com/baharclerode/dropwizard-cors

**Comment by lfoppiano** [comment]
Actually there is a simpler way: 

You can put these in the `
    public void run(MyConfiguration configuration, Environment environment) {
`
```
   // Configure CORS parameters
        cors.setInitParameter("allowedOrigins", "*");
        cors.setInitParameter("allowedHeaders", "X-Requested-With,Content-Type,Accept,Origin");
        cors.setInitParameter("allowedMethods", "OPTIONS,GET,PUT,POST,DELETE,HEAD");

        // Add URL mapping
        cors.addMappingForUrlPatterns(EnumSet.allOf(DispatcherType.class), true, "/*");

```

and you get the parameters from the configuration yaml file

**Comment by kermitt2** [comment]
@lfoppiano thanks, I guess in `GrobidServiceApplication.java` but what is this `cors` object?

**Comment by lfoppiano** [comment]
@kermitt2 sorry i forgot the first line. I can submit a initial PR with some of the code and we can take it from there

**Comment by lfoppiano** [comment]
I have pushed the implementation on https://github.com/kermitt2/grobid/tree/cors-configuration
