### ISSUE TITLE
git-commit-id-plugin Error

### ISSUE THREAD

**Issue by dominic-sps** [kermitt2/grobid#230]
`[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.2:revision (provide scm info) on project grobid-home: Could not complete Mojo execution... Unable to find commits until some tag: Walk failure. Missing commit c438d3a277529fe04e1a3fe2436ef92822688f52 -> [Help 1]`

this morning I noted the above error and on debugging found that this plugin in the maven central repository was changed on 28th August (`http://search.maven.org/#search%7Cga%7C1%7Cpl.project13`)

in groubid/pom.xml
```
<artifactId>git-commit-id-plugin</artifactId>
                <version>2.2.2</version>

```
to
```
<artifactId>git-commit-id-plugin</artifactId>
                <version>2.2.3</version>

```
It compiles now. Might be useful for someone.

**Comment by kermitt2** [comment]
Thanks! I've updated the plugin version with commit 06d69edf4914747a9934297ea58cdfc551f3bdf9
