### ISSUE TITLE
Correct annotations for DOI and arxiv ID's in the training data

### ISSUE THREAD

**Issue by iorala** [kermitt2/grobid#235]
Currently the output of `createTraining` of Grobid batch usuall correctly recognizes DOIs and arXiv ID's. It annotes them with the tag `<idno>`.  

E.g.: `<idno>doi :10.1088/1126-6708/2007/09/126</idno>,<idno>arXiv: 0707.3088</idno>`

The correct annotations for that would be to using the @type DOI or arxiv.
E.g: `<idno type="DOI">doi :10.1088/1126-6708/2007/09/126</idno>,<idno type="arxiv">arXiv: 0707.3088</idno>`

Manually correcting this is time intensive and it would be helpful if it was already done by the batch mode. An example of this working would be collaborations. Those are already annotated like `<orgName type="collaboration">ALICE Collaboration</orgName>`

**Comment by kermitt2** [comment]
It should be now present with commit fe582d50958fd991464955af34465fb1f5287a75
