### ISSUE TITLE
Fat jar as single dependency in example

### ISSUE THREAD

**Issue by rawsh** [kermitt2/grobid#242]
In grobid-example you have it calling the directory with grobid-home. How can I bundle grobid home in the core jar? Is there a way to reduce the file sizes (uploading to aws lambda)

**Comment by kermitt2** [comment]
Hello!
see #245, not possible because of the JNI libs...
You can always decrease the size of GROBID home by including in a deployment only the models that you need to use - the loading of models is lazy.
