### ISSUE TITLE
Build error duplicate entry

### ISSUE THREAD

**Issue by stzellerhoff** [kermitt2/grobid#249]
Installing version 0.4.4 fails reporting this error:

`Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project grobid-core: Error creating shaded jar: duplicate entry: META-INF/services/shadedgrobid.org.apache.lucene.codecs.PostingsFormat`

How can I avoid duplicate entries?

Stephan

**Comment by lfoppiano** [comment]
hi @stzellerhoff could you paste here the whole log? 

Thanks
Luca

**Comment by m9aertner** [comment]
I have no clue about your project, but I just happened to stumble across that PostingsFormat duplication issue, too:

lucene-core-7.2.1.jar contains "org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat" in "META-INF/services/org.apache.lucene.codecs.PostingsFormat" while
lucene-suggest-7.2.1.jar contains "org.apache.lucene.search.suggest.document.**Completion**50PostingsFormat"

The duplication is no problem usually (first one in classpath wins), but the "shade" plugin is smart about it and checks for such duplicates. HTH.
