### ISSUE TITLE
Question about -teiCoordinates

### ISSUE THREAD

**Issue by gonedjur** [kermitt2/grobid#252]
In batch mode passing

>-exe processFullText -teiCoordinates

doesn't give the coordinates of for examples paragraphs which have been identified. They just show up as \<p> \</p> in the resulting TEI XML. From the code, Paragraph.java, it looks like they should be available as \<p coords="5,75.30,709.69,15.27,8.91"> \</p> for example?

Am I missing something?

**Comment by kermitt2** [comment]
Hello @gonedjur 
The documentation is answering your question: http://grobid.readthedocs.io/en/latest/Coordinates-in-PDF/

**Comment by gonedjur** [comment]
Oh sorry I missed the very beggining....

**Comment by ai4ki** [comment]
Hi, sorry for bringing this up again, but I'm not sure if I fully understand this. The GROBID documentation says that coordinate areas can be obtained for the paragraph substructure; but I guess this is the crucial part: "Coordinates are currently available in full text processing (returning a TEI document) and the PDF annotation services (returning JSON for ref, figure and formula only)." 
So is there really no way to get the coordinates for p? Thanks for any pointers--and for the whole thing: GROBID is a tremendous piece of work!

**Comment by lfoppiano** [comment]
In the interface, you can select "Add coordinates"; if you select "Segment sentences", the coordinates will go in the sentences in the paragraphs. 

<img width="664" alt="image" src="https://github.com/kermitt2/grobid/assets/15426/8e33db98-1220-4b39-89f4-52c0d8616ca3">

**Comment by kermitt2** [comment]
@ai4ki the documentation need to be clarified, sorry.
Coordinates are present on `<p>` with the current version (and in the official demo that I have updated last week :) 

With curl (change to your own Grobid server):

> curl -v --form input=@/home/lopez/Downloads/socsci-10-00292-v2.pdf --form teiCoordinates=p https://kermitt2-grobid.hf.space/api/processFulltextDocument

```xml
<?xml version="1.0" encoding="UTF-8"?>
<TEI xml:space="preserve" xmlns="http://www.tei-c.org/ns/1.0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.tei-c.org/ns/1.0 https://raw.githubusercontent.com/kermitt2/grobid/master/gr
obid-home/schemas/xsd/Grobid.xsd"
 xmlns:xlink="http://www.w3.org/1999/xlink">
        <teiHeader xml:lang="en">
...
<abstract>
        <div xmlns="http://www.tei-c.org/ns/1.0">
                    <p coords="1,207.79,290.12,351.48,8.63;1,167.27,303.09,392.01,8.63;1,167.27,316.07,393.13,8.63;1,167.27,329.04,392.01,8.63;1,167.27,342.01,392.01,8.63;1,167.27,354.98,392.01,8.63;1,167.27,367.95,392.01,8.63;1,167.27,380.92,392.01,8.63;1,167.27,393.89,392.01,8.63;1,167.27,406.87,110.12,8.63">This article focuses on parental perceptions of signs of hunger and satiety in children under 4 years of age and their effects on feeding practices, in a sample of parents of children with typical development. Discourse analysis shows the close relationships between social food norms, nutritional norms, medicalized child care norms, and educational norms in adults' determination of children's appetites according to their perceived needs and psychomotor development. The results also indicate how these norms are expressed according to social position, parental experience and context. More broadly, this article addresses top-down education-from adults to children-in food socialization, and points to the varying attention paid to the signals given by the child. It thus highlights some of the processes by which biological, psychological and social factors interact in socializing children to food.</p>
       </div>
</abstract>
...
```
