### ISSUE TITLE
Batch mode: No Grobid home was found in classpath and no Grobid home location was not provided

### ISSUE THREAD

**Issue by philonor** [kermitt2/grobid#260]
**Version**: 0.5.0
**System**: Ubuntu 16.04 LTS

**Problem**: 
Running grobid in batch mode supplying a grobid home path fails with the following output:
```
Nov 15, 2017 12:10:38 PM org.grobid.core.main.GrobidHomeFinder getGrobidHomePathOrLoadFromClasspath
WARNING: No Grobid property was provided. Attempting to find Grobid home in the current directory...
Nov 15, 2017 12:10:38 PM org.grobid.core.main.GrobidHomeFinder getGrobidHomePathOrLoadFromClasspath
WARNING: Attempting to find and in the classpath...
Exception in thread "main" org.grobid.core.exceptions.GrobidPropertyException: [GENERAL] No Grobid home was found in classpath and no Grobid home location was not provided
```
The corresponding batch mode call:
```
$ java -Xmx1G -jar ./grobid-0.5.0/grobid-core/build/libs/grobid-core-0.5.0-onejar.jar -gH /home/ubuntu/uni.mp/project/backend/webservices/grobid-0.5.0/grobid-home/ -dIn ./pdfs/ -dOut ./pdfs/ -r -exe processHeader
```

If run from the grobid directory, it works, but specifying the `-gH` parameter isn't necessary:
```
$ java -Xmx1G -jar ./grobid-core/build/libs/grobid-core-0.5.0-onejar.jar -gH /home/ubuntu/uni.mp/project/backend/webservices/grobid-0.5.0/grobid-home/ -dIn ./../pdfs/ -dOut ./../pdfs/ -r -exe processHeader
```
```
$ java -Xmx1G -jar ./grobid-core/build/libs/grobid-core-0.5.0-onejar.jar -dIn ./../pdfs/ -dOut ./../pdfs/ -r -exe processHeader
```

**Possible reason**:
It seems that [`GrobidHomeFinder`](https://github.com/kermitt2/grobid/blob/5d56c06e8170df5a493c3620d9b2210c767124ae/grobid-core/src/main/java/org/grobid/core/main/GrobidHomeFinder.java#L67) only checks env variable but not commandline argument `-gH` ?

**Workaround**:
Create a symbolic link to grobid home in the directory grobid is called from:
```
ln -s ./grobid-0.5.0/grobid-home ./grobid-home
```

**Comment by lfoppiano** [comment]
Hi @philonor, thanks for the report. Indeed there is a problem because the grobid home provided is not used to configure the `GrobidHomeFinder`, which is looking on `../grobid-home` as default location.

**Comment by lfoppiano** [comment]
The issue should be fixed in my last commit, feel free to close the issue or comment back in case of problems

**Comment by lfoppiano** [comment]
Dear @philonor did you try the fix I've done? Does it works?

**Comment by philonor** [comment]
Sorry for my late reply, just checked your fix and it works now as expected. Thank you! 
I used master @ 593c3b8525f5ee013de527ff74142ab5eb7ceeb6, 3 commits after your specific commit.

**Comment by olgagolgan** [comment]
hello. same problem happens to me

**Comment by olgagolgan** [comment]
hello. same problem happens to me
