### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by dominic-sps** [kermitt2/grobid#262]
pom.xml files missing in the latest update. Any reason or documentation?

**Comment by kermitt2** [comment]
Hello @dominic-sps, we moved to gradle with grobid version `0.5.0`, the documentation is normally up-to-date for all the new build and usage instructions.
When built, jar are now under `build/libs` and, if needed by a another maven application, poms under `build/poms`

**Comment by dominic-sps** [comment]
Sorry. My mistake. 

Clearly mentioned in the docs.
