### ISSUE TITLE
Docker image for 0.5.0 version

### ISSUE THREAD

**Issue by mastak** [kermitt2/grobid#264]
What about docker image for the new version?

There is `Dockerfile` in the repository,  but it requires already built files. 
Docker multi-stage build (https://docs.docker.com/engine/userguide/eng-image/multistage-build/) can be used here for.

**Comment by lfoppiano** [comment]
Hi @mastak,  
    it's on my todo list :-) Many things has changed since the last release and it will require some re-thinking. If you have experience with Docker and you like to propose some solution, feel free. 

I'll try to get it done soon, however cannot guarantee when

Cheers
Luca

**Comment by mastak** [comment]
Hi @lfoppiano,

I'm not very familiar with Java, but I can help with docker. 
I see that there are should be 2 files, but how I can build them from source?:
```
ADD ./grobid-home/target/grobid-home-${GROBID_VERSION}.zip /opt
COPY ./grobid-service/target/grobid-service-${GROBID_VERSION}.war /var/lib/jetty/webapps/ROOT.war```

**Comment by lfoppiano** [comment]
@mastak you need to know a bit of building on java actually, we don't have a war build anymore, but I'm not sure it's perhaps good to add it back for the docker image. 
In the meantime if you use the docker image with tag 0.4.4 you will have roughly the same features, in version 0.5.x we have changed build method (gradle) and we added a framework. 

Cheers
Luca

**Comment by lfoppiano** [comment]
@mastak with long delay, the Dockerfile is now updated (thanks for your contribution!) and the image is uploaded on the docker hub (https://hub.docker.com/r/lfoppiano/grobid/tags/)
