### ISSUE TITLE
November month being detect as december by typo

### ISSUE THREAD

**Issue by rlucca** [kermitt2/grobid#269]
Hi there,

On the follow line about the november month, I saw that has a dicember lost inside. Is it maybe a typo?

https://github.com/kermitt2/grobid/blob/8e4ce03fc91a75d0185fd61f3a480444df21933e/grobid-core/src/main/java/org/grobid/core/engines/DateParser.java#L206

**Comment by kermitt2** [comment]
Hello!

Ah yes it's a typo sorry!
Lesson learnt: never write any manual rules, create a classifier for everything ;) 

thanks for reporting.

**Comment by kermitt2** [comment]
so fixed with commit 2d3e11eafcf7e5768ff48681b6af757dc4b4e84a
thanks again @rlucca !

**Comment by kermitt2** [comment]
I close this issue given the committed fix.
