### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Stargirlinsapporo** [kermitt2/grobid#276]
Hi
I have been trying to install 
Stuck with failed build

-----------------------------------------------
46 errors
:grobid-core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grobid-core:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

---------------------------------------------------------

What can I do?

**Comment by kermitt2** [comment]
Hello !

Could you give us some more information: what is your OS environment? which command are you using to build the tool, the whole error trace when possible as attachment - many thanks

**Comment by Stargirlinsapporo** [comment]
Thank you for reply!
I tried to run on Windows 7 32-bit. Later, in another thread read that it was not a good idea :smile: 
Will 32-version of Win ever be supported?
Anyway shall try again with different OS

**Comment by kermitt2** [comment]
We have no plan on supporting Win 32... Adding support to Windows 64 was already a time-consuming and painful task ;)
