### ISSUE TITLE
Change grobid into Chinese

### ISSUE THREAD

**Issue by JiangWenqi** [kermitt2/grobid#279]
Hello,kermitt.
First of all,thank you for providing such a convenient tool！
I'm a Chinese student.
And I want to refactor your tool to fit Chinese paper.
Where do I start?
(I'd  appreciate it if you can give me your email. :)

**Comment by yaojl2006** [comment]
Hi,
Actually Grobid supports for Chinese language analysis, although its accuracy is not so perfect as which for English.
So if you wanna a higher precision compared with that, you have to retrain almost all the CRF model `grobid/grobid-home/models/` in grobid with cn data because of different languages and paper struction.

------------------------------Translation are as follow-----------------------------
grobid是支持中文文献解析的，如果你不是有很高的精度需求可以凑合用一下。
如果你需要一个和解析英文差不多的精度，那只能重新标数据训练模型了，训练数据可以参考
 `grobid/grobid-home/models/`下面的文件。
然后你还要考虑中英文文献的格式差别，比如中文文献开头或者结尾的地方会有一段英文摘要，这东西会影响grobid判断……

**Comment by JiangWenqi** [comment]
我刚才看到你github上写的是北京，那我就不用蹩脚的英文了（苦笑
我看这个工具的开发手册上面有两个地方提到训练，我不知道我的理解是否正确：

1. User manual 目录下的GROBID batch mode 的 createTraining ，把我所提供的中文论文放进去（Input）然后得到一堆的xml文件（Output）,然后我手工进行标注纠错。

2.接着我把我标注好了的文件放到grobid/grobid-trainer/resources/dataset/*MODEL*/corpus/ （相应的目录下面）执行./gradlew <training goal. I.E: train_name-header> 命令，在grobid-home生成相应的规则文件。

------------------------------Translation are as follow-----------------------------
I see two places in the manual of this tool mentioned how to train data. But I don't know my understanding is correct:
First of all,I provide some Chinese papers create training data (output,like *.training.table.tei.xml) through GROBID batch mode.
Then, I corrected these files by manually and copy these files into grobid/grobid-trainer/resources/dataset/*MODEL*/corpus/  (such directory like this).
And then,I execute command like > ./gradlew <training goal. I.E: train_name-header>

Looking forward to your reply.
Thanks.

**Comment by yaojl2006** [comment]
Hi,
yeah, it's really troublesome.....And maybe you have to consider solving the problem about en-metadata，which largely influences grobid performance when handling cn-paper. Good luck :)

对的，这是个很麻烦的过程……因为grobid做的中文标注很大一部分都是错的。后面你可能还要考虑屏蔽中文文献里经常在开头或末尾出现的英文metadata的干扰，挺麻烦的，加油

**Comment by kermitt2** [comment]
Hello @JiangWenqi and thanks @yaojl2006 !

Indeed the solution is to add more training data with documents in Chinese language. 
The process is as you describe regarding correction and addition to the directories, but you need then to re-train the models, not just re-start GROBID. 
For retraining, see in the documentation: http://grobid.readthedocs.io/en/latest/Training-the-models-of-Grobid/#train-and-evaluation-in-one-command

The normal beginning is to add training data first for the segmentation model which is the first one to be use in the CRF cascade. Then after retraining the segmentation model, you can regenerate training data for full text, bibliographical references and header models (these zones will  be better recognized, and the generated training data will be more accurate).

**Comment by JiangWenqi** [comment]
Thanks @kermitt2 !
I already know the process, I'll try what you say.
but some details are not clear, I want to seek your help.
Can we contact by email?
 jiangwenqi1995@gmail.com

**Comment by JiangWenqi** [comment]
I have a question.

1. I have installed GROBID.
`> ./gradlew clean install`

2.I use batch mode:createTraining.
`java -Xmx4G -jar /Users/vinci/git/grobid/grobid-core/build/libs/grobid-core-0.6.0-SNAPSHOT-onejar.jar -gH /Users/vinci/git/grobid/grobid-home -dIn /Users/vinci/lib/Papers/Input -dOut /Users/vinci/lib/Papers/Output -exe createTraining`

3.I use `java -Xmx1024m -jar /Users/vinci/git/grobid/grobid-trainer/build/libs/grobid-trainer-0.6.0-SNAPSHOT-onejar.jar 0 header -gH /Users/vinci/git/grobid/grobid-home/`

```
14 tei files
	epsilon: 1.0E-5
	window: 20
	nb max iterations: 2000
	nb threads: 1
* Load patterns
* Load training data
error: no train data loaded
```

I do not why no train data loaded?

**Comment by kermitt2** [comment]
Hi @JiangWenqi !
Sorry for my slow answer - have you move the generated training data in the right subdirectory of grobid-trainer? e.g. `grobid-trainer/resources/dataset/header/corpus/headers` (for the feature matrix without label) and `grobid-trainer/resources/dataset/header/corpus/tei` for the labeled XML files? 
The files should be recognized there when launching the training.

**Comment by JiangWenqi** [comment]
Thanks @kermitt2  !
I am still haunted by this question.
First, I deleted all the files in this directory（`grobid-trainer/resources/dataset/header/corpus/headers`）.
Then I put the training data I generated （e.g. `CAR003.training.header`） in this directory.
At the same time, I also emptied out all the files in this directory（`grobid-trainer/resources/dataset/header/corpus/tei`） and added the files I marked (e.g. CAR003.training.header.tei.xml).
Finally, I execute the training statement（`Finally, I execute the training statement.`）.

It is still 
```

> 5 tei files
> 	epsilon: 1.0E-5
> 	window: 20
> 	nb max iterations: 2000
> 	nb threads: 1
> * Load patterns
> * Load training data
> error: no train data loaded
> 

```

I don't know where I made my mistake.

**Comment by JiangWenqi** [comment]
​I already know where I made my mistake.

Because grobid generated the file name by default (like. CAR002.training.header) when he created the training data.

But your source code requires this naming format.
                    if (localFileName.equals(parser2.getPDFName() + ".header")) {
                        headerFile = localFileName;
                        break;
                    }

                    if ((localFileName.startsWith(parser2.getPDFName() + "._")) & (localFileName.endsWith(".header"))) {
                        headerFile = localFileName;
                        break;
                    }

So,BufferedReader can not find pathHeader.

**Comment by sampanriver** [comment]
@JiangWenqi 
能把你的代码和训练的模型共享一下吗，grobid目前的中文模型基本没法用。

------------------------------Translation are as follow-----------------------------

It would be great if you can share your code and model. 

Thanks

**Comment by JiangWenqi** [comment]
> @JiangWenqi
> 能把你的代码和训练的模型共享一下吗，grobid目前的中文模型基本没法用。
> 
> ------------------------------Translation are as follow-----------------------------
> 
> It would be great if you can share your code and model.
> 
> Thanks

@sampanriver 这东西得根据你需要解析的中文文档进行训练建立对应的模型，我之前是用的保险文档。有不明白的话，可以直接给我发邮件。

**Comment by FengXuas** [comment]
> @JiangWenqi
> 能把你的代码和训练的模型共享一下吗，grobid目前的中文模型基本没法用。
> 
> ------------------------------Translation are as follow-----------------------------
> 
> It would be great if you can share your code and model.
> 
> Thanks

你好，请问你在中文模型上的训练有什么进展吗？

**Comment by wanghaisheng** [comment]
@JiangWenqi   我能协助提供一些标注素材吗  能给一下标注和输出的要求吗
