### ISSUE TITLE
Force loading of models etc. on startup

### ISSUE THREAD

**Issue by borkdude** [kermitt2/grobid#289]
Right now I'm using GROBID through Docker. I noticed the first call to `api/processFulltextDocument` takes about 50 seconds but the second call only 2 seconds (of course this varies over documents). This is due to lazy loading of the models (and possibly more stuff which I don't know about). It would be nice to have an option to load these on startup of the Docker container via some environment variable. I'm using Docker swarm with multiple instances of GROBID which are load balanced, so forcing the loading of the models by analyzing some dummy PDF doesn't always guarantee that all the containers are ready to go.

**Comment by kermitt2** [comment]
Thanks @borkdude, it absolutely makes sense to add such option.

**Comment by diversemix** [comment]
We've fallen foul of this - just before going into production with Sciencebeam. Can we help in anyway?

**Comment by lfoppiano** [comment]
This has been implemented long time ago: b62ff88a0f67858d4f96673252783829259b98b3
