### ISSUE TITLE
Fail to parse nicely documents containing row numbers at their margin

### ISSUE THREAD

**Issue by davidefiocco** [kermitt2/grobid#297]
The documents I am trying to parse have row numbers at their margin, as in 
https://i.stack.imgur.com/Yt4HD.png

My problem is that in abstracts and body texts, grobid extractions do have numbers in them.
Is there a way around this problem (without the need of retraining grobid)? 
Apache Tika seems to nicely extract content ignoring numbering, but still lacks the capability of correctly identifying parts of the document (title, abstract, refs, etc.) as grobid does, so that's why I'd love to stick to grobid (at least if I can get a clean, without-numbers extraction).

I can try to provide reproducible examples if need be.

**Comment by kermitt2** [comment]
Hello! Normally the next version which is using an improved pdf2xml (which better captures the reading order of the blocks) should be able to better handle that case. However I've never tested it with line numbers both on the left and the right - it's the first time I see that case actually, so I would be interested to get a reproducible example (my email is in the readme). I also have to say that some retraining will be required to work with the new pdf2xml so it will not be a rapid move.
