### ISSUE TITLE
Grobid server start halts at 88%

### ISSUE THREAD

**Issue by snw5208** [kermitt2/grobid#298]
I did a fresh install of Grobid and after successfully completing an install trying to run the server causes it to halt at 88% execution and hang here for upwards of ten minutes or more. The screen print is attached below

 ```
PUT     /api/processFulltextAssetDocument (org.grobid.service.GrobidRestService)
    POST    /api/processFulltextDocument (org.grobid.service.GrobidRestService)
    PUT     /api/processFulltextDocument (org.grobid.service.GrobidRestService)
    POST    /api/processHeaderDocument (org.grobid.service.GrobidRestService)
    PUT     /api/processHeaderDocument (org.grobid.service.GrobidRestService)
    POST    /api/processHeaderNames (org.grobid.service.GrobidRestService)
    PUT     /api/processHeaderNames (org.grobid.service.GrobidRestService)
    POST    /api/processReferences (org.grobid.service.GrobidRestService)
    PUT     /api/processReferences (org.grobid.service.GrobidRestService)
    POST    /api/referenceAnnotations (org.grobid.service.GrobidRestService)
    GET     /api/sha1 (org.grobid.service.GrobidRestService)
    POST    /api/sha1 (org.grobid.service.GrobidRestService)
    GET     /api/version (org.grobid.service.GrobidRestService)

INFO  [2018-03-22 14:41:27,488] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHand
ler@2513a118{/,null,AVAILABLE}
INFO  [2018-03-22 14:41:27,495] io.dropwizard.setup.AdminEnvironment: tasks =

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

INFO  [2018-03-22 14:41:27,501] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHand
ler@7be1ce6a{/,null,AVAILABLE}
INFO  [2018-03-22 14:41:27,513] org.eclipse.jetty.server.AbstractConnector: Started application@656d10a4{HTTP/1.1,[http/
1.1]}{0.0.0.0:8070}
INFO  [2018-03-22 14:41:27,514] org.eclipse.jetty.server.AbstractConnector: Started admin@63ec445c{HTTP/1.1,[http/1.1]}{
0.0.0.0:8071}
INFO  [2018-03-22 14:41:27,514] org.eclipse.jetty.server.Server: Started @7289ms
<===========--> 88% EXECUTING [5m 14s]
> :grobid-service:run
```

**Comment by lfoppiano** [comment]
hi @snw5208, 
    AFAIK this is a glitch in the gradle run task when you run the service, since it's shares the same JVM the gradle process stays appended. 

You should be able to run it as a service without gradle (from the grobid directory): 
```
./gradlew clean assemble 
./grobid-service/bin/grobid-service server grobid-service/config/config.yaml
```

Give it a try and let me know if it's working. If so I will add it to the documentation. 

Regards
Luca

**Comment by snw5208** [comment]
The first command resulted in a successful build:
```
BUILD SUCCESSFUL in 1m 10s
24 actionable tasks: 24 executed
```
However the second command results in:
`-bash: ./grobid-service/bin/grobid-service: No such file or directory`

**Comment by lfoppiano** [comment]
@snw5208 thanks, I will have a look. I remember fixing this problem already 😅 actually

**Comment by lfoppiano** [comment]
OK so there is no issue, I've just forgot some steps, after assembling it you need the grobid-service zip file and the grobid-home, they needs to be placed in a directory and afterwards they can be run successfully: 

```
./gradlew clean assemble 
cd ..
mkdir grobid-instal
cd grobid-instal
unzip ../grobid/grobid-service/build/distributions/grobid-service-0.6.0-SNAPSHOT.zip -d grobid-service
unzip ../grobid/grobid-home/build/distributions/grobid-home-0.6.0-SNAPSHOT.zip 
./grobid-service/bin/grobid-service server grobid-service/config/config.yaml
```

From grobid-installation there should be a tree of this type: 
```
.
├── grobid-home
└── grobid-service
```

It should work, let me know if works for you 
Luca

**Comment by lfoppiano** [comment]
@snw5208 is it working?

**Comment by alperozaydin** [comment]
I do have same problem and I followed your instruction but when I run the last command I get this error:

```
Exception in thread "main" java.io.FileNotFoundException: File grobid-service/config/config.yaml not found
	at io.dropwizard.configuration.FileConfigurationSourceProvider.open(FileConfigurationSourceProvider.java:18)
	at io.dropwizard.configuration.YamlConfigurationFactory.build(YamlConfigurationFactory.java:78)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:124)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:72)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at org.grobid.service.main.GrobidServiceApplication.main(GrobidServiceApplication.java:90)
```

**Comment by alperozaydin** [comment]
I have solved it. For me, I had to move all files under grobid-service (the one we unzipped) to main grobid-service. 

So these are the steps that I followed and it worked for me.
```
./gradlew clean assemble 
cd ..
mkdir grobid-instal
cd grobid-instal
unzip ../grobid/grobid-service/build/distributions/grobid-service-0.6.0-SNAPSHOT.zip -d grobid-service
unzip ../grobid/grobid-home/build/distributions/grobid-home-0.6.0-SNAPSHOT.zip 
cd grobid-service/grobid-service-0.5.1/
mv bin/ lib/ doc/ ../../../grobid-0.5.1/grobid-service/
cd ../../../grobid-0.5.1/
./grobid-service/bin/grobid-service server grobid-service/config/config.yaml

```

**Comment by atlasian** [comment]
Hello,
I confirm, following the steps indicated by @lfoppiano, this issue is solved, the grobid service is up.

**Comment by Aazhar** [comment]
Hello,
I confirm, following the steps indicated by @alperozaydin, this issue is solved, the grobid service is up.

**Comment by lfoppiano** [comment]
I've re-checked and updated the documentation with a slight change in the process. Thanks for the heads up.

**Comment by kandalavaishnavi** [comment]
Hey.. I have tried the above steps and still get the error as "No file or directory found". 

Can you please suggest?

**Comment by lfoppiano** [comment]
@kandalavaishnavi could you please share the log of the commands you've ran?

**Comment by kandalavaishnavi** [comment]
I am trying to install this in Windows environment:

step 1 - git clone https://github.com/kermitt2/grobid.git
step2 - ./gradlew clean install test
I also tried starting the server using gradle but it got stuck at 88% (as mentioned [here](https://grobid.readthedocs.io/en/latest/Grobid-service/))
step3 - /gradlew clean assemble 
step4 - 
> cd ..
> mkdir grobid-installation
> cd grobid-installation
post this, I manually unzipped "grobid-service-0.6.0-SNAPSHOT.zip" and moved to grobid-service (Folder)
step 5 - similarly unzipped grobid-home 
step6 - ./grobid-service/bin/grobid-service server grobid-service/config/config.yaml
when  I tried to run this command, it doesn't work and says the system cannot find the path specified.

**Comment by lfoppiano** [comment]
@kandalavaishnavi first of all, the fact that "get stuck" at 88% is not a bug, it's jus that the application is in service mode and since we run it from gradle it "doesn't finish" until you kill the service. For running on your local system, is the preferred way (cause leads to less problems) 

To be able to help you, I need to see the command as they were ran from the command line (including responses) or the structure of the grobid-installation directory

**Comment by ajinkya2903** [comment]
![image](https://user-images.githubusercontent.com/63385842/91968145-d753df80-ed31-11ea-9fbe-f5354126c2de.png)
Hey, even after following the steps you have shown in this issue it is not working. Is there any solution to this or I am doing any mistake here?
