### ISSUE TITLE
Recursive extraction

### ISSUE THREAD

**Issue by holoxy** [kermitt2/grobid#3]
Thanks a lot for the very promising meta data extraction tool.

Would it be possible to add a option for recursive extraction for folders and subfolder?

**Comment by kermitt2** [comment]
I still have not added that!

**Comment by kermitt2** [comment]
Add possible recursive processing for ```processHeader```, ```processFullText``` and ```processReferences``` with commit 8d1c038a342e5406d161a874993da5ffbd344c03.
