### ISSUE TITLE
Unable to disabe Crossref consolidation via consolidateHeader

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#300]
I am trying to disable the Crossref consolidation.

The UI has a tick box to disable it, but it doesn't seem to have an affect. I don't see the flag in the network request. (Both locally as well as on the demo site)

According to the docs, there is the _consolidateHeader_ flag. It looks like it is a form parameter.

```bash
curl -v --form input=@./thefile.pdf --form consolidateHeader=0 http://localhost:8070/api/processHeaderDocument
```
That doesn't seem to have the desired effect.

It could be that it's related to this if condition that seem to ignore the flag it found the DOI:
https://github.com/kermitt2/grobid/blob/2d3e11eafcf7e5768ff48681b6af757dc4b4e84a/grobid-core/src/main/java/org/grobid/core/engines/HeaderParser.java#L267

(The document has indeed a DOI and I can see the request being made for the DOI)

Test document:
https://www.biorxiv.org/content/biorxiv/early/2018/03/26/287888.full.pdf

In that PDF, author first names are abbreviated - with consolidateHeader=0 I am expecting the XML to contain the names as per PDF. Just to show that it's not hidden somewhere, disabling access to Crossref does produce the desired result.

**Comment by lfoppiano** [comment]
@kermitt2 I'm discussing with @de-code and I'm also wondering that if the consolidation is set to false, it should not be attempted, even if there is a DOI. What's the reason behind it? 

Thanks

**Comment by kermitt2** [comment]
I put the label bug to this issue ;)

**Comment by lfoppiano** [comment]
OK, it should be fixed now 😄

**Comment by de-code** [comment]
Working as expected. Thank you!
