### ISSUE TITLE
Grobid version in output TEI incorrect

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#322]
Very small issue, to not forget it :-) 

Grobid version in output TEI should be aligned with the version in gradle.properties: 

```
wifi-pro-83-011:grobid lfoppiano$ cat gradle.properties 
#Thu, 21 Apr 2016 18:39:55 +0200
version=0.6.0-SNAPSHOT
# Set workers to 1 that even for parallel builds it works. (I guess the shadow plugin makes some trouble)
org.gradle.workers.max=1
wifi-pro-83-011:grobid lfoppiano$ ```

```
<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.tei-c.org/ns/1.0 /Users/lfoppiano/development/inria/grobid/grobid-home/schemas/xsd/Grobid.xsd"
 xmlns:xlink="http://www.w3.org/1999/xlink">
	<teiHeader xml:lang="en">
		<encodingDesc>
			<appInfo>
				<application version="0.5.1-SNAPSHOT" ident="GROBID" when="2018-06-01T08:54+0000">
					<ref target="https://github.com/kermitt2/grobid">GROBID - A machine learning software for extracting information from scholarly documents</ref>
				</application>
			</appInfo>
		</encodingDesc>
		<fileDesc>
```

**Comment by kermitt2** [comment]
I never managed to do it with maven :( (where there is a mechanism dedicated to that, but impossible to make it working)
So version was hard coded :-1:

**Comment by lfoppiano** [comment]
Actually I know how to do it :-) but I have to find time to implement it and I just note it down not to forget ;-)
