### ISSUE TITLE
Is there any heuristic/workaround to filter tables/figures from the main body?

### ISSUE THREAD

**Issue by davidefiocco** [kermitt2/grobid#324]
I would like to extract the body of my corpus without including tables/figures as they might interfere with my post-processing. Can you provide any hints on how to do this?

Thanks in advance!

P.S.: Incidentally, are questions of this kind tolerated here? I was tempted to ask on StackOverflow, but as devs are reponsive here I thought to create an issue on GH...

**Comment by kermitt2** [comment]
Hello @davidefiocco 

You could simply filter out the figure and table sections in the output TEI file? Or maybe I don't understand your problem and your constraints.

**Comment by davidefiocco** [comment]
Hi! Now I see! Apologies for the dumb question, I had misunderstood the meaning of the sentence "Figures and tables belong to the main body structure: they are not to be encoded specifically." in https://grobid.readthedocs.io/en/latest/training/segmentation/#tables-and-figures (I was looking in the wrong part of the documentation, essentially). Thanks!
