### ISSUE TITLE
What XML tags can appear between <body> tags in the TEI XML?

### ISSUE THREAD

**Issue by davidefiocco** [kermitt2/grobid#329]
Hi devs,

As in #324, I would like to parse the body text of articles but disregarding elements like tables or figures.

What other elements can be encountered inside the <body> tags of a TEI-encoded document? 
I tried to have a look at https://github.com/kermitt2/grobid/blob/master/grobid-home/schemas/dtd/Grobid.dtd but to no avail. Thanks in advance for any hint on this!

**Comment by kermitt2** [comment]
Hello @davidefiocco !

If you open `grobid/grobid-home/schemas/doc/Grobid_doc.html` you will see all the possible tags of the TEI schema used by GROBID, in a more readable fashion than the dtd or rng schema. 

Is it helping you?

**Comment by davidefiocco** [comment]
Hi Patrice, thanks as usual for your prompt reply, this is the info I was looking for. Will reopen if I need more of your precious help on this if you don't mind!

**Comment by kermitt2** [comment]
Mmm my answer above is actually not very good.

A simple process for your goal would be to use a basic XSLT and only get the content text below the tag `<body>` (in 6 lines but not tested): 

```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
 version="1.0">
         <xsl:output method="text"/>
         <xsl:template match="/TEI/text/body">
             <xsl:apply-templates select="."/>
         </xsl:template>
     </xsl:stylesheet>
```

or you can use XPath (also not tested):

```
//body/descendant::text()
```

**Comment by davidefiocco** [comment]
Hi Patrice!
Thanks for your replies! 

What I need to do is to get body text but (also) _disregarding_ figures and tables and their captions (and potentially other elements I wasn't not aware of).

That's why I need the extensive list of all the tags that can appear in the body. I think that `Grobid_doc.html` does the job of providing a list of what elements can be encountered, so that I can try to include/exclude them.
