### ISSUE TITLE
Issue with command './gradlew clean install test'

### ISSUE THREAD

**Issue by luxuyan2018** [kermitt2/grobid#333]
Hi,
I met a problem when running this command: './gradlew clean install test'. The result is following:

luxuyan@DESKTOP-LD07LN5:~/grobid-0.5.1$ ./gradlew clean install test

> Task :grobid-core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :grobid-core:mainJar
The SimpleWorkResult type has been deprecated and is scheduled to be removed in Gradle 5.0. Please use WorkResults.didWork() instead.

> Task :grobid-service:compileJava
Note: /mnt/c/home/grobid-0.5.1/grobid-service/src/main/java/org/grobid/service/process/GrobidRestProcessFiles.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :grobid-trainer:compileJava
Note: /mnt/c/home/grobid-0.5.1/grobid-trainer/src/main/java/org/grobid/trainer/TrainerFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :grobid-core:compileTestJava
/mnt/c/home/grobid-0.5.1/grobid-core/src/test/java/org/grobid/core/annotations/DescriptionTest.java:423: error: no suitable method found for createStartElement(QName,Iterator<CAP#1>,Iterator<CAP#2>)
                return eventFactory.createStartElement(name, attributes, namespaces);
                                   ^
    method XMLEventFactory.createStartElement(QName,Iterator<? extends Attribute>,Iterator<? extends Namespace>) is not applicable
      (argument mismatch; Iterator<CAP#1> cannot be converted to Iterator<? extends Attribute>)
    method XMLEventFactory.createStartElement(String,String,String) is not applicable
      (argument mismatch; QName cannot be converted to String)
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
/mnt/c/home/grobid-0.5.1/grobid-core/src/test/java/org/grobid/core/annotations/ParagraphTest.java:138: error: no suitable method found for createStartElement(QName,Iterator<CAP#1>,Iterator<CAP#2>)
                return eventFactory.createStartElement(name, attributes, namespaces);
                                   ^
    method XMLEventFactory.createStartElement(QName,Iterator<? extends Attribute>,Iterator<? extends Namespace>) is not applicable
      (argument mismatch; Iterator<CAP#1> cannot be converted to Iterator<? extends Attribute>)
    method XMLEventFactory.createStartElement(String,String,String) is not applicable
      (argument mismatch; QName cannot be converted to String)
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
/mnt/c/home/grobid-0.5.1/grobid-core/src/test/java/org/grobid/core/annotations/TeiStAXParsedInfoTest.java:134: error: no suitable method found for createStartElement(QName,Iterator<CAP#1>,Iterator<CAP#2>)
                return eventFactory.createStartElement(name, attributes, namespaces);
                                   ^
    method XMLEventFactory.createStartElement(QName,Iterator<? extends Attribute>,Iterator<? extends Namespace>) is not applicable
      (argument mismatch; Iterator<CAP#1> cannot be converted to Iterator<? extends Attribute>)
    method XMLEventFactory.createStartElement(String,String,String) is not applicable
      (argument mismatch; QName cannot be converted to String)
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
/mnt/c/home/grobid-0.5.1/grobid-core/src/test/java/org/grobid/core/annotations/TeiStAXParserTest.java:234: error: no suitable method found for createStartElement(QName,Iterator<CAP#1>,Iterator<CAP#2>)
        return eventFactory.createStartElement(name, attributes, namespaces);
                           ^
    method XMLEventFactory.createStartElement(QName,Iterator<? extends Attribute>,Iterator<? extends Namespace>) is not applicable
      (argument mismatch; Iterator<CAP#1> cannot be converted to Iterator<? extends Attribute>)
    method XMLEventFactory.createStartElement(String,String,String) is not applicable
      (argument mismatch; QName cannot be converted to String)
  where CAP#1,CAP#2 are fresh type-variables:
    CAP#1 extends Object from capture of ?
    CAP#2 extends Object from capture of ?
/mnt/c/home/grobid-0.5.1/grobid-core/src/test/java/org/grobid/core/annotations/TeiStAXParserTest.java:257: error: incompatible types: Iterator<CAP#1> cannot be converted to Iterator<? extends Namespace>
        return eventFactory.createEndElement(name, namespaces);
                                                   ^
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object from capture of ?
Note: /mnt/c/home/grobid-0.5.1/grobid-core/src/test/java/org/grobid/core/utilities/TextUtilitiesTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grobid-core:compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
29 actionable tasks: 29 executed

I'm using the Windows subsystem for Linux. How can I solve this problem?

**Comment by Moosebaby** [comment]
I have the same issue as you. How did you solve the problem?

**Comment by luxuyan2018** [comment]
> I have the same issue as you. How did you solve the problem?
Sorry Moosebaby, I forgot how I solved that, I haven't using this software for a long time, hope you can solve it soon.
