### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by dbaehrens-averbis** [kermitt2/grobid#339]
Dear Grobid developers,

as an integrator, we use the Grobid annotator component in our text mining platform running at the European Patent Office (EPO) to process patent and literature references in over 100 million patent publications.

For some patent documents from the repository at EPO Grobid cannot finish the processing and throws a NumberFormatException. The numbers mentioned in the exceptions do not seem to be in the content of the documents, though.

Below, I  attach an example where the error occurs in UIMA XMI format (zipped).

[378875770.zip](https://github.com/kermitt2/grobid/files/2301786/378875770.zip)

Please tell me, if you can reproduce the issue with the example or in case you need more information to fix the exception in Grobid.

Thank you very much,
David

-- 
David Baehrens
Project Manager Averbis GmbH
Freiburg, Germany

> 0:15:21,486 SEVERE [org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl] ([UIMA AS 
> ThreadPool 9] 31553bbd-fb6f-4e51-ba27-cecb7d8d8bfd Process Thread - 828) Exception occurred: org.apache.uima.analysis_engine.AnalysisEngineProcessException
>     at de.averbis.textanalysis.components.grobidannotator.GrobidAnnotator.process(GrobidAnnotator.java:164) [grobid-annotator-1.2.0.jar:]
>     at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) [uimaj-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:396) [uimaj-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:314) [uimaj-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570) [uimaj-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412) [uimaj-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344) [uimaj-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265) [uimaj-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.aae.controller.PrimitiveAnalysisEngineController_impl.process(PrimitiveAnalysisEngineController_impl.java:813) [uimaj-as-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.aae.handler.HandlerBase.invokeProcess(HandlerBase.java:121) [uimaj-as-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.aae.handler.input.ProcessRequestHandler_impl.handleProcessRequestFromRemoteClient(ProcessRequestHandler_impl.java:572) [uimaj-as-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.aae.handler.input.ProcessRequestHandler_impl.handle(ProcessRequestHandler_impl.java:1090) [uimaj-as-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.aae.handler.input.MetadataRequestHandler_impl.handle(MetadataRequestHandler_impl.java:78) [uimaj-as-core-2.9.0.jar:2.9.0]
>     at org.apache.uima.adapter.jms.activemq.JmsInputChannel.onMessage(JmsInputChannel.java:731) [uimaj-as-activemq-2.9.0.jar:2.9.0]
>     at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721) [spring-jms-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681) [spring-jms-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651) [spring-jms-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:319) [spring-jms-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1166) [spring-jms-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1060) [spring-jms-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_72]
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_72]
>     at org.apache.uima.aae.UimaAsThreadFactory$1.run(UimaAsThreadFactory.java:132) [uimaj-as-core-2.9.0.jar:2.9.0]
>     at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_72] Caused by: org.grobid.core.exceptions.GrobidException: [GENERAL] An exception occured while running Grobid.
>     at org.grobid.core.engines.patent.ReferenceExtractor.extractAllReferencesString(ReferenceExtractor.java:730) [grobid-core-0.4.4.jar:]
>     at org.grobid.core.engines.Engine.processAllCitationsInPatent(Engine.java:1053) [grobid-core-0.4.4.jar:]
>     at de.averbis.textanalysis.components.grobidannotator.GrobidAnnotator.process(GrobidAnnotator.java:162) [grobid-annotator-1.2.0.jar:]
>     ... 24 more
> Caused by: java.lang.NumberFormatException: For input string: "6801412249" 
>     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) [rt.jar:1.7.0_72]
>     at java.lang.Integer.parseInt(Integer.java:495) [rt.jar:1.7.0_72]
>     at java.lang.Integer.parseInt(Integer.java:527) [rt.jar:1.7.0_72]
>     at org.grobid.core.engines.patent.PatentRefParser.processRawRefText(PatentRefParser.java:843) [grobid-core-0.4.4.jar:]
>     at org.grobid.core.engines.patent.ReferenceExtractor.extractAllReferencesString(ReferenceExtractor.java:649) [grobid-core-0.4.4.jar:]
>     ... 26 more

**Comment by dbaehrens-averbis** [comment]
It seems that the attachment was removed from my last comment via email.

> For your vaildation I also attach the example in original XML format
> from EPO patent repository.

[006271747_JPH0586974B2_Description_EN_378875770.zip](https://github.com/kermitt2/grobid/files/2306408/006271747_JPH0586974B2_Description_EN_378875770.zip)

**Comment by cgaege** [comment]
Dear Grobid developers,

do you already have a release plan for a new grobid release that contains the fix for this issue?

Thanks in advance,

Christian Gaege (Averbis GmbH)

**Comment by lfoppiano** [comment]
@cgaege can we close this issue?

**Comment by cgaege** [comment]
We are currently verifying the new grobid release on our side. This may take a couple of days. But feel free to close the issue. 

Thank you very much

**Comment by lfoppiano** [comment]
@cgaege feel free to reopen or comment
