### ISSUE TITLE
How to call the Gobid service from a Java application

### ISSUE THREAD

**Issue by juanluis17** [kermitt2/grobid#346]
Hello, I need to call the Gobid service from a Java application, can you help me build the URL and the Java code?

**Comment by kermitt2** [comment]
Hello! 
If you want to use the GROBID web service from a Java application, you can have a look at our following project code here (this is a multithreaded client):
https://github.com/anHALytics/anhalytics-core/tree/master/anhalytics-harvest/src/main/java/fr/inria/anhalytics/harvest/grobid
If you want to use the GROBID Java library from a Java application, a complete example is available here:
https://github.com/kermitt2/grobid-example

**Comment by lfoppiano** [comment]
I'm adding also the documentation section on the subject: https://grobid.readthedocs.io/en/latest/Grobid-java-library/

**Comment by lfoppiano** [comment]
@juanluis17 did you manage? If so please feel free to close this issue
