### ISSUE TITLE
Syntax of command is incorrect

### ISSUE THREAD

**Issue by chabdullahsiddique** [kermitt2/grobid#351]
grobid-service/bin/grobid-service server grobid-service/config/config.yaml
returns "The input line is too long.
The syntax of the command is incorrect."

**Comment by lfoppiano** [comment]
@chabdullahsiddique I've checked the documentation and the command works fine. Could you please give us more information? SO, Java version, etc... 

Thanks!

**Comment by lfoppiano** [comment]
I'm closing this issue. Feel free to reopen in needs?
