### ISSUE TITLE
Could GROBID extract headers, subtitles, paragraphs ?

### ISSUE THREAD

**Issue by Ninashka** [kermitt2/grobid#352]
Dear,
Is GROBID capable of extracting various text parts such as titles, subtitles, paragraphs, etc?
i don't mean only bibliographical information, but other subtitles that might exist in scientific paper

**Comment by kermitt2** [comment]
Hello!

Sure it does more than just bibliographical information, try the [demo](http://grobid.science-miner.com), select `TEI` / `process fulltext document` and load any scholar PDF. 

You'll find evaluations for the section titles, paragraph, figure, callout, etc. in the documentation.

**Comment by Ninashka** [comment]
Thanks for responding. And thanks for this library.
Is there any implementation in .NET ?

**Comment by kermitt2** [comment]
Even for Java, I recommend to use the [REST service](https://grobid.readthedocs.io/en/latest/Grobid-service/), or you can use the available docker - all these solutions are language independent.
