### ISSUE TITLE
building GROBID using GRADLE fails (Windows 10)

### ISSUE THREAD

**Issue by Ninashka** [kermitt2/grobid#353]
Dear, when i run command : gradlew clean install test, build fails with message:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'grobid'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve net.researchgate:gradle-release:2.6.0.
     Required by:
         project :
      > Could not resolve net.researchgate:gradle-release:2.6.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/net/researchgate/gradle-release/2.6.0/gradle-release-2.6.0.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/net/researchgate/gradle-release/2.6.0/gradle-release-2.6.0.pom'.
               > Received fatal alert: protocol_version
      > Could not resolve net.researchgate:gradle-release:2.6.0.
         > Could not get resource 'https://jcenter.bintray.com/net/researchgate/gradle-release/2.6.0/gradle-release-2.6.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/net/researchgate/gradle-release/2.6.0/gradle-release-2.6.0.pom'.
               > Connection reset
   > Could not resolve org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.4.0.
     Required by:
         project :
      > Could not resolve org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.4.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.4.0/coveralls-gradle-plugin-2.4.0.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.4.0/coveralls-gradle-plugin-2.4.0.pom'.
               > Received fatal alert: protocol_version
      > Could not resolve org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.4.0.
         > Could not get resource 'https://jcenter.bintray.com/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.4.0/coveralls-gradle-plugin-2.4.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.4.0/coveralls-gradle-plugin-2.4.0.pom'.
               > Connection reset
   > Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3.
     Required by:
         project :
      > Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.7.3/gradle-bintray-plugin-1.7.3.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.7.3/gradle-bintray-plugin-1.7.3.pom'.
               > Received fatal alert: protocol_version
      > Could not resolve com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3.
         > Could not get resource 'https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.7.3/gradle-bintray-plugin-1.7.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.7.3/gradle-bintray-plugin-1.7.3.pom'.
               > Connection reset
   > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
     Required by:
         project :
      > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom'.
               > Received fatal alert: protocol_version
      > Could not resolve com.github.jengelman.gradle.plugins:shadow:2.0.2.
         > Could not get resource 'https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/2.0.2/shadow-2.0.2.pom'.
               > Connection reset

what's wrong?

**Comment by lfoppiano** [comment]
Dear @Ninashka, could you please provide us more information about your system? 

Looks like you are not connected to the network. The first time, like in any java projects it's needed. Could you please check that?

**Comment by Ninashka** [comment]
I was connected to the network.
my system: Windows 10, 64 bit
i am trying to install grobid 0.5.2
i have gradle 4.10.2 installed

**Comment by lfoppiano** [comment]
From the log above, gradle is not able to connect and download dependencies. I believe this has to do with your system configuration. 

Unfortunately I don't have Windows 10, so I cannot be more helpful.

**Comment by kermitt2** [comment]
Are you using a proxy maybe ? The documentation describes some settings for that case.

**Comment by Ninashka** [comment]
i am not using proxy. Should I ?

**Comment by Ninashka** [comment]
@lfoppiano : thanks any way :)

**Comment by Ninashka** [comment]
@lfoppiano  , @kermitt2  : Dear, when i downloaded and installed JDK 8 everything went OK. thank you.
