### ISSUE TITLE
Grobid for German Reference structuring

### ISSUE THREAD

**Issue by sathiyabalu89** [kermitt2/grobid#359]
I would like to tag the references in German language using Grobid. Is it possible, if I just train using the 
German specific data?

**Comment by dineshbs7** [comment]
I would like to know that how to increase the limit of reference size to process with less? please help

**Comment by kermitt2** [comment]
Hello ! Sorry for the slow feedback. 

I've tested for different types of structures, either to build one model per language or a single language for all languages, and the second approach always give better results. I suppose structured information are not too dependent on the language, a lot is common (proper names, numbers) and having more training data with the multilingual model always improve the final result.

So the suggested approach for improving references in German (there are already some examples in the training data from the journal ZfN), would be to add examples to the current training data set and retrain, and not to train with German only examples.

**Comment by sathiyabalu89** [comment]
Thank you :) for your helpful reply
