### ISSUE TITLE
format of generareTrainingData

### ISSUE THREAD

**Issue by dineshbs7** [kermitt2/grobid#383]
generareTrainingData

**Comment by dineshbs7** [comment]
Please tell us  how to get training data for Citation model/

syntax for generareTrainingdata

**Comment by kermitt2** [comment]
See https://grobid.readthedocs.io/en/latest/Grobid-batch/#createtraining
and https://grobid.readthedocs.io/en/latest/training/General-principles/#generating-pre-annotated-training-data
