### ISSUE TITLE
createTraining

### ISSUE THREAD

**Issue by dineshbs7** [kermitt2/grobid#384]

**Comment by dineshbs7** [comment]
Dear sir,
Help needed
createTraining bacth command only createing training data for segmentation model. How to create others model

**Comment by kermitt2** [comment]
See https://grobid.readthedocs.io/en/latest/Grobid-batch/#createtraining
and https://grobid.readthedocs.io/en/latest/training/General-principles/#generating-pre-annotated-training-data
the table for the second url gives the file extensions for the created training data for each model.
