### ISSUE TITLE
Auto generating publishing date like 1998-03

### ISSUE THREAD

**Issue by dineshbs7** [kermitt2/grobid#394]

**Comment by dineshbs7** [comment]
Dear sir,
Input ref is:  Look at Mar. 1998.
A. Barak and O. La’adan. The MOSIX multicomputer
operating system for high performance cluster
computing. Future Generation Computer Systems,
13(4–5):361–372, Mar. 1998.

output ref is: lookn at  when="1998-03" 
<monogr>
		<title level="j">Future Generation Computer Systems</title>
		<imprint>
			<biblScope unit="volume">13</biblScope>
			<biblScope unit="issue">4-5</biblScope>
			<biblScope unit="page" from="361" to="372" />
			<date type="published" when="1998-03" />
		</imprint>
	</monogr>

**Comment by dineshbs7** [comment]
<monogr>
		<title level="j">Future Generation Computer Systems</title>
		<imprint>
			<biblScope unit="volume">13</biblScope>
			<biblScope unit="issue">4-5</biblScope>
			<biblScope unit="page" from="361" to="372" />
			<date type="published" when="1998-03" />
		</imprint>
	</monogr>

**Comment by kermitt2** [comment]
Hello @dineshbs7 
It is working exactly as expected, `Mar. 1998` is extracted, parsed and normalized in ISO 8601 format as `<date type="published" when="1998-03" />`.
