### ISSUE TITLE
Grobid Docker image for version 0.5.4

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#398]
I'm opening so I won't forget :-)

**Comment by davidefiocco** [comment]
(the documentation is already... ready for the future :)

At https://grobid.readthedocs.io/en/latest/Grobid-docker/ `docker pull lfoppiano/grobid:0.5.4` currently throws an error, I guess until this closes. Cheers!

**Comment by lfoppiano** [comment]
ok ok, I'll do it asap 😅

**Comment by lfoppiano** [comment]
Please test it 😄 

https://hub.docker.com/r/lfoppiano/grobid/tags

**Comment by davidefiocco** [comment]
Looks like.. the future is now! Looks perfectly functional to me with a single simple test.
