### ISSUE TITLE
createTrainingHeader

### ISSUE THREAD

**Issue by dineshbs7** [kermitt2/grobid#399]
Dear Sir, im getting following issues.How to solve this please help
C:\grobid-0.5.3>java -Xmx1024m -jar \grobid-0.5.3\grobid-core\build\libs\grobid-
core-0.5.3-onejar.jar -gH \grobid\grobid-home -gP \grobid\grobid-home\config\gro
bid.properties -dIn \grobid-0.5.3 -dOut \grobid-0.5.3\2 -exe createTrainingHeade
r
-exe value should be one value from this list: [close, processRawReference, proc
essAuthorsHeader, processAuthorsCitation, processAffiliation, processReferences,
 createTrainingMonograph, createTrainingBlank, createTrainingCitationPatent, pro
cessCitationPatentTEI, processCitationPatentST36, processCitationPatentTXT, proc
essCitationPatentPDF, processPDFAnnotation, processHeader, processFullText, proc
essDate, createTraining]

C:\grobid-0.5.3>

**Comment by kermitt2** [comment]
Hello @dineshbs7 
See my answer for #384 and the current documentation, there is only one method `createTraining` which will create training files for all the models, including header. 
https://grobid.readthedocs.io/en/latest/Grobid-batch/#createtraining
