### ISSUE TITLE
Differentiation between Headers and Subheaders

### ISSUE THREAD

**Issue by khoulih** [kermitt2/grobid#403]
First of all, we are really thankful to all the people involved in this project - it has been the only most reliable tool we could have found for our task: Extracting headers/subheaders and body from documents.

We are interested in differentiating between two levels of headers- top-level headers and subheaders. We have attempted to create a <list>, with each <item> holding the subheader and it's corresponding body of text. This, however, did not yield the results we were looking for, or results that were any different to running the fulltext model without the list and item tags.

Is there a possible way to tag/differentiate top-level headers and subheaders?

**Comment by kermitt2** [comment]
Thank you for the kind words! Issue #377 is already keeping track of this particular improvement, so I closed this one.
