### ISSUE TITLE
Some References are missing

### ISSUE THREAD

**Issue by dineshbs7** [kermitt2/grobid#404]

**Comment by dineshbs7** [comment]
Dear sir,
i used processReferences batch command.Input pdf file contains only references(around 634). When i execute,only 230 references are structured. How to solve to this i.e to structure all references
Thank u in Advance

**Comment by kermitt2** [comment]
Hello @dineshbs7 could you send me this PDF file? I suppose the segmentation model finds that part of the reference section is the body of an article. It is trained on usual scholar article, not reference-only document - but it might be possible to cover that too.

**Comment by kermitt2** [comment]
Closing this issue as it is not possible to reproduce the problem.
