### ISSUE TITLE
First body paragraph partially-duplicated in abstract

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#407]
Hi, 
  I've found a strange behavior on this paper: [1308.2125.pdf](https://github.com/kermitt2/grobid/files/2951048/1308.2125.pdf)

I've got the first paragraph of the body partially duplicated in the abstract: 
```
<profileDesc>
            <abstract>
                <div
                    xmlns="http://www.tei-c.org/ns/1.0">
                    <p>We studied double superconducting (SC) domes in LaFeAsO1−xHx by using 75  As and 1 H nuclearmagnetic-resonance techniques, and unexpectedly discovered that a new antiferromagnetic (AF) phase follows the double SC domes on further H doping, forming a symmetric alignment of AF and SC phases in the electronic phase diagram. We demonstrated that the new AF ordering originates from the nesting between electron pockets, unlike the nesting between electron and hole pockets as seen in the majority of undoped pnictides. The new AF ordering is derived from the features common to high-Tc pnictides; however, it has not been reported so far for other high-Tc pnictides because of their poor electron doping capability.</p>
                    <p>As a common feature in strongly correlated electron systems including high-transition-temperature (high-T c ) superconductors, the superconducting (SC) phase emerges adjacent to the antiferromagnetic (AF) phase on carrier doping. The AF order parameter vanishes by carrier doping, and the SC phase commonly manifests as a dome in the electronic phase diagram. On further carrier doping, the normal metallic state approaches a Fermi liquid state. This scenario is also seen in high-</p>
                </div>
            </abstract>
        </profileDesc>
    </teiHeader>
    <text xml:lang="en">
        <body>
            <div
                xmlns="http://www.tei-c.org/ns/1.0">
                <p>As a common feature in strongly correlated electron systems including high-transition-temperature (high-T c ) superconductors, the superconducting (SC) phase emerges adjacent to the antiferromagnetic (AF) phase on carrier doping. The AF order parameter vanishes by carrier doping, and the SC phase commonly manifests as a dome in the electronic phase diagram. On further carrier doping, the normal metallic state approaches a Fermi liquid state. This scenario is also seen in high-T c cuprates and several iron-based pnictides. In fact, a very close analogy between cuprates and pnictides such as Ba(Fe 1−x Co x ) 2 As 2 (Ba122 series) 
                    <ref type="bibr" target="#b0">[1]</ref>
                    <ref type="bibr" target="#b1">[2]</ref>
                    <ref type="bibr" target="#b2">[3]</ref> was suggested in the electronic phase diagram 
                    <ref type="bibr" target="#b3">[4]</ref>. The AF state appearing in an undoped or lightly doped regime is a stripe-type spin-density-wave (SDW) state 
```

For reference (and If I've not overlooked) I've seen the same behavior using both pdfalto and pdf2xml.

**Comment by kermitt2** [comment]
Yes it looks strange but it happens with the current approach for segmenting the header. We segment the header both with heuristics and with the segmentation model. As the heuristics still work better than the segmentation model for the header part, the latter is a fall back. The rest of the text body is then obtained with the segmentation model, so it is possible to have the beginning of the introduction also at the end of the abstract - or worse a piece of text which disappears at the beginning of the introduction.

It's not frequent, and a problem already spotted a couple of times, see #373 - this is the object of ongoing work on new header model and reading order improvement.

**Comment by danielrbrowne** [comment]
I can provide another example of a PDF which exhibits this behaviour of combining an abstract with following portions of a manuscript (when hitting the `/processHeaderDocument` endpoint). In this case, the extracted `<abstract>` also contains the first two full paragraphs of the Introduction section of the paper.
[JACS_Communication_HER_final.pdf](https://github.com/kermitt2/grobid/files/3338576/JACS_Communication_HER_final.pdf)

**Comment by danielrbrowne** [comment]
This is another example where the manuscript's keywords and the first paragraph of the Introduction are included in the extracted abstract:
[Vol 3 - Cont. J. Appl. Sci - 15-20.pdf](https://github.com/kermitt2/grobid/files/3338759/Vol.3.-.Cont.J.Appl.Sci.-.15-20.pdf)

**Comment by lfoppiano** [comment]
I've tested and: 
 - https://github.com/kermitt2/grobid/issues/407#issue-419326846 works with and without heuristics
 -  https://github.com/kermitt2/grobid/issues/407#issuecomment-506686240 works with both 

 - https://github.com/kermitt2/grobid/issues/407#issuecomment-506674405 works only without heuristics (the abstract is not correctly extracted, but no duplication)

**Comment by lfoppiano** [comment]
Since we disabled the heuristics, I guess this issue can be closed?

**Comment by kermitt2** [comment]
Yes !
