### ISSUE TITLE
Unit test for parser

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#410]
Today I might have found a solution for testing the parsers. I'm writing here hoping to get some feedback. 

We can create a 'special' model call `Models.NONE` (or `Models.DUMMY`), and when passed in the AbstractParser, the Grobid engine just the loading of any of the machinery under the hood (no wapiti/delft, etc)... 
The tests can be initialised by call a second constructor in the parsers (with package visibility)  and passing the dummy identifier for the model which will not require even the grobid-home to be available. 
```
new MyParser(Models.NONE).testMethod1()
```

More in detail `TaggerFactory.getTagger(model)` should return a NoneTagger or DummyTagger which will just return the same input when the method `label()` is called. 

I haven't tried to implement it, in theory seems working ... 

What do you think?

**Comment by kermitt2** [comment]
It looks like a very good simple solution indeed ! 
I don't see right now why it would not work (but there are often surprises D:).  

The only limit would be when we need stuff from the Lexicon (which uses `grobid-home` for init) to generate features, these aspects could then not be tested, which might be a bit limiting in some cases.

**Comment by lfoppiano** [comment]
I've managed to mock the FeatureFactory, for example, using PowerMock, see: 
 - https://github.com/kermitt2/grobid-quantities/blob/master/src/test/java/org/grobid/core/features/FeaturesVectorQuantitiesTest.java
 - https://github.com/kermitt2/grobid-quantities/blob/master/src/test/java/org/grobid/core/features/FeaturesVectorUnitTest.java

**Comment by lfoppiano** [comment]
I think this can be closed, perhaps after I've wrote a page on how to do it in the documentation ;-)

**Comment by kermitt2** [comment]
Oh yes, the developer notes section ! :D
