### ISSUE TITLE
NoSegmenter References

### ISSUE THREAD

**Issue by Crescentz** [kermitt2/grobid#412]
If I just want the whole part of 'References',   like 'Abstract' , NOT 'title ,name , author ...' what can i do

**Comment by Crescentz** [comment]
NOT:
<biblStruct >
	<analytic>
		<title/>
		<author>
			<persName xmlns="http://www.tei-c.org/ns/1.0"><forename type="first">C</forename><surname>Shen</surname></persName>
		</author>
		<idno>1409.8164</idno>
	</analytic>
	<monogr>
		<title level="j">Comput. Phys. Commun</title>
		<imprint>
			<biblScope unit="volume">199</biblScope>
			<biblScope unit="page">61</biblScope>
			<date type="published" when="2016" />
		</imprint>
	</monogr>
</biblStruct>

Like this:
Referens: [1]....[2]...

**Comment by kermitt2** [comment]
Hello! 
I don't understand the question. Do you mean getting the unparsed reference field of the header section?

**Comment by Crescentz** [comment]
thank you for your reply , i misunderstood something. This issue should be closed~
