### ISSUE TITLE
Error: "Could not determine java version from '10.0.1'"

### ISSUE THREAD

**Issue by rgieseke** [kermitt2/grobid#413]
I was trying to run grobid 0.5.4

I'm on Ubuntu 18.10 and running java

```
$ java --version
openjdk 11.0.1 2018-10-16
```

This led to the error mentioned above.

With updating the `distributionUrl` in `gradle/wrapper/gradle-wrapper.properties` i managed to get it to run following the instructions in the docs:

```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-all.zip
```

Maybe this helps someone.

**Comment by lfoppiano** [comment]
Dear @rgieseke thanks for your input. 

Did you update from gradle-4.6 to gradle 4.10? 

This could be indeed added to the Troubleshooting section of the documentation: https://grobid.readthedocs.io/en/latest/Troubleshooting/ 

Luca

**Comment by rgieseke** [comment]
Good point, I didn't check this section (just googled the error message and found lots of projects with the same problem).

Thanks for this cool tool!
