### ISSUE TITLE
Several Dates Parsing issue

### ISSUE THREAD

**Issue by ohld** [kermitt2/grobid#417]
I'm trying to parse thins PDF https://arxiv.org/pdf/1904.00007

The response:
![image](https://user-images.githubusercontent.com/5613295/55669936-10122f80-5886-11e9-847e-eaad88f0f103.png)

The pdf has several dates:
![image](https://user-images.githubusercontent.com/5613295/55669943-23bd9600-5886-11e9-9821-a710c0493e68.png)

As a result, the value in response XML is not a valid date.

**Comment by ohld** [comment]
By the way. I started to use your tool and already found some errors in recognition. Where should I send the pdf links and the problems? In the issues here?

**Comment by kermitt2** [comment]
Right now we have already a lot of examples/benchmarking with respect to header extraction and structuring issues, pretty clear for us what is necessary to do for improvement. I would be interested in horror cases for:

* author-affiliation attachment (to add to this issue #451 for instance)

* bibliographical reference callout and problems to match callout and bibliographic references

* bibliographic references in footnotes

* disaster case in relation to global zoning 

I  think there's no already opened issue for the last 3 cases. 

Thanks !

**Comment by kermitt2** [comment]
The date issue has been tackled in the update of the latest header model. Now in case we have several dates extracted in the header zone, we keep them separated and, in addition to different selection criteria (where they appear), we take the earliest one as publication date. 

In this example we have as expected: 

```xml
 <date type="published" when="2019-03-27">27 March 2019</date>
```

**Comment by ohld** [comment]
Awesome!
