### ISSUE TITLE
gradlew run fail

### ISSUE THREAD

**Issue by alimirzazadeh** [kermitt2/grobid#422]
ERROR [2019-04-15 03:21:18,867] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.net.BindException: Address already in use: bind
! at java.base/sun.nio.ch.Net.bind0(Native Method)

I sucessfully installed but when I tried to run this occured.
Also I received the following errors when I debugged the install:

23:26:30.330 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:26:30.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
23:26:30.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:26:30.331 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
23:26:30.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Task 'clean' not found in root project 'grobid-installation'.
23:26:30.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:26:30.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
23:26:30.332 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
23:26:30.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
23:26:30.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help athttps://help.gradle.org
23:26:30.333 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
23:26:30.333 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 40s

**Comment by kermitt2** [comment]
Hello @alimirzazadeh !

>  ! java.net.BindException: Address already in use: bind

It looks like you already have something running using the 8070 or 8071 port?

**Comment by alimirzazadeh** [comment]
Is there any way to change the port destination number? I have the following two programs running on 8070 that I am having trouble removing?
![image](https://user-images.githubusercontent.com/16345175/56109051-e0fe5c80-5f1c-11e9-910b-2857bc7933a0.png)

**Comment by kermitt2** [comment]
Sure, there is a server config file, it's documented here: 
https://grobid.readthedocs.io/en/latest/Grobid-service/#configure-the-server

**Comment by alimirzazadeh** [comment]
I see. I removed completely, reinstalled with new port numbers, but I still get this error in the installation process:
![image](https://user-images.githubusercontent.com/16345175/56110260-c1b5fe00-5f21-11e9-9efc-2314f21d71c2.png)

**Comment by kermitt2** [comment]
Which JVM version are you using? 

(to make things easier, it's better to join the error trace as text and not image, thanks!)

**Comment by alimirzazadeh** [comment]
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**Comment by kermitt2** [comment]
Ok! current GROBID is based on JVM 8 

For recent JVM, see these fixes:
https://grobid.readthedocs.io/en/latest/Troubleshooting/#wrong-java-version

**Comment by kermitt2** [comment]
I've just pushed da0a8f1d44b01f61b90ac4aa144bb4c520fecefb an update of the dependencies and gradle version to support JVM 10.
