### ISSUE TITLE
Upcoming Grobid Update

### ISSUE THREAD

**Issue by jonsaadfalcon** [kermitt2/grobid#426]
An application I'm developing will be using Grobid but since it can only run on Java10 and earlier, it'll be difficult for some of my clients with newer computers to run it since Macbook Pros now have JDK11. Is there any upcoming Grobid update that will make it compatible with Java 11?

**Comment by de-code** [comment]
Have you considered using it as a container instead? That way you don't need to worry about the Java version as it will be part of the container.

**Comment by lfoppiano** [comment]
@jonsaadfalcon please check https://grobid.readthedocs.io/en/latest/Grobid-docker/. The docker image is on https://hub.docker.com/r/lfoppiano/grobid

**Comment by lfoppiano** [comment]
I think grobid can be currently ran with java 10 or 11 #418
