### ISSUE TITLE
Changing Pointer for Grobid

### ISSUE THREAD

**Issue by jonsaadfalcon** [kermitt2/grobid#428]
How do you change the PATH variable in Grobid to point to Java8 instead of Java11? Or how to you merge the jre8 for Java 8 with grobid so it doesn't experience an error using Java11?

**Comment by jonsaadfalcon** [comment]
Or how to change the path that grobid points to to look for java8?

**Comment by kermitt2** [comment]
This is configured at system level. For macos, this stackoverflow [discussion](https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-os-x) might answer your question.

**Comment by jonsaadfalcon** [comment]
Thank you for the suggestion. I was curious if there was someway to change the java version only for grobid since I have other applications simultaneously running other versions of Java

**Comment by kermitt2** [comment]
Ah it seems doable at grobid level too: https://stackoverflow.com/a/21212790

**Comment by kermitt2** [comment]
Current GROBID should run now without issue on jvm 11 too, though this issue was not related to GROBID actually.
