### ISSUE TITLE
build.gradle dependency update

### ISSUE THREAD

**Issue by GrennanM** [kermitt2/grobid#432]
I had a problem with build.gradle. I am using:

- Gradle version: 5.0

- java-8-openjdk

The problem was in relation to the following on line 13:

`classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.2'`

I updated to:

`classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.3'`

The build was then successful.

**Comment by lfoppiano** [comment]
Yes I think we should upgrade to Gradle 5.0 👍 Probably after the next release cause there are too many moving parts that might break 😅

**Comment by lfoppiano** [comment]
I've create a branch gradle5 https://github.com/kermitt2/grobid/tree/gradle5 and the build works. If someone could test more deeply that everything works that would be helpful.

**Comment by lfoppiano** [comment]
I would close this issue, if there are problems, please reopen it
