### ISSUE TITLE
Is there a way to make `processFullText` only process the title, headers, and paragraphs? 

### ISSUE THREAD

**Issue by Santosh-Gupta** [kermitt2/grobid#434]
I looked over the documents and doesn't look like it, but just in case: Is there a way to make `processFullText` only process the title, headers, and paragraphs? 

I just need the paragraphs, and some of the tags such as `ref` split these paragraphs apart. It looks like filtering may be straight forward, just removing the tags, though I am a bit paranoid of edge cases. So, perhaps there is an established tool to extracting only the titles, headers, and paragraphs from the PDF?

**Comment by kermitt2** [comment]
Hello! It's XML, so any XML parser with xpath or any XSLT processors will do this.
