### ISSUE TITLE
https:// links for doi.org and arxiv.org

### ISSUE THREAD

**Issue by bnewbold** [kermitt2/grobid#444]
For general internet use the consensus is that HTTPS is better practice than HTTP.

GROBID generates links in TEI-XML in a couple places. I made the change from `http://` to `https://` in two places in this patch: https://github.com/bnewbold/grobid/commit/51edc9db01b1278932dd0d1ab547bb072e12e675

If you think this would be an improvement I can submit a PR after fixing any tests and hunting down any other instances (eg, in the PDF overlay code path?).

**Comment by kermitt2** [comment]
Yes that would be an improvement sure! There should not be other places I think, the links on top the PDF comes from the class you changed.
