### ISSUE TITLE
consistency in <idno type="DOI"> capitalization (vs. "doi")

### ISSUE THREAD

**Issue by bnewbold** [kermitt2/grobid#445]
A few GROBID code paths use "DOI", and a few use "doi".

I have a small patch I could cherry-pick and PR: https://github.com/bnewbold/grobid/commit/71d192d2d68cd42c5e9f9606aa081aa992a11d6b

Might be tricky if downstream users/parser have come to depend on this capitalization, though hopefully they haven't.

**Comment by kermitt2** [comment]
Thanks! The visible DOI (in final results) should be all in `BiblioItem.java` and `TEIFormatter.java` as far as I remember.
