### ISSUE TITLE
FullText Model: files are silently rejected from training starting from 0.5.4

### ISSUE THREAD

**Issue by Vitaliy-1** [kermitt2/grobid#455]
The problem appears to be starting from version 0.5.4 and persists on the current master branch.

To reproduce on the default set from the current master branch:
`./gradlew train_fulltext`
master branch vs 0.5.3
master branch:
```
* Summary
    nb train:    23
    nb labels:   22
    nb blocks:   481337
    nb features: 10589876
```
25 files for training overall. Accoding to logs, 0 files are rejected: https://github.com/Vitaliy-1/grobid_terminal_output/blob/master/output_default_grobid-master.txt but apparently only 23 from 25 were used for training.

0.5.3:
```
* Summary
    nb train:    25
    nb labels:   22
    nb blocks:   515588
    nb features: 11343398
```
According to logs, 0 files are rejected: https://github.com/Vitaliy-1/grobid_terminal_output/blob/master/output_default_grobid-0.5.3. All 25 documents are used for training

Terminal outputs are identical.

The problem is more substantial if comparing training of our test corpus from 800+ articles, none of which doesn't pass to the training in any version after 0.5.3 but according to logs 150+ annotated documents should pass sync check.

**Comment by Vitaliy-1** [comment]
The problem firstly appears in this commit: https://github.com/kermitt2/grobid/commit/f6cce2436323c9dff958b7ba6d6c49f801d783bb
@kermitt2, you probably know more about it.

**Comment by kermitt2** [comment]
Hello @Vitaliy-1 !

Thanks for reporting the issue.
Actually the problem is when Wapiti reads the training file, it's not silent, the Wapiti error message is:

> warning: missing tokens, cannot apply pattern 

So some features are missing apparently somewhere in the newly generated raw files. In the commit you indicate, I added a new feature to the model and re-generated the raw file accordingly. It would have been nice if Wapiti was indicating the line number of the problem :/

Interestingly I have only one example rejected by Wapiti on my side with the current master:

```
totalExamples: 25
        epsilon: 1.0E-4
        window: 20
        nb max iterations: 1500
        nb threads: 8
* Load patterns
* Load training data
warning: missing tokens, cannot apply pattern
* Initialize the model
* Summary
    nb train:    24
    nb labels:   22
    nb blocks:   506906
    nb features: 11152394
* Train the model with l-bfgs
...
```

I will have a look and try to regenerate the raw files without the issue.

**Comment by Vitaliy-1** [comment]
Ahh, yes, I see the message.

This problem is triggered by new data entered into CRF template by this commit: https://github.com/kermitt2/grobid/blob/f6cce2436323c9dff958b7ba6d6c49f801d783bb/grobid-trainer/resources/dataset/fulltext/crfpp-templates/fulltext.template#L137-L145

**Comment by kermitt2** [comment]
Yes, those new features are generated here:

https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java#L794

using this:

https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java#L375

One of those feature should be missing for one token I guess in the case of "generateTrainingData" is used (I didn't see this issue with large file process normally).

**Comment by Vitaliy-1** [comment]
After re-generating raw files with Grobid, the problem is more or less solved for our corpus. At least I don't see the message and articles are passing for the training, although the number of articles that pass sync check is slightly different than was before. 

So, probably the same would be true and for the default set. I don't have original PDFs to test.

**Comment by kermitt2** [comment]
I've re-generated the fulltext feature files and indeed it fixed the problem of number of features (there was certainly something done in-between to solve it, but I don't remember exactly what!). 

I have also updated the fulltext model (commit b01c2ad63fb41ba1a48b319468cf0cd5d8882ea5) and it improves slightly the header+fulltext and citation matching [accuracy](https://github.com/kermitt2/grobid/blob/master/grobid-trainer/doc/PMC_sample_1943.results.grobid-0.5.5-Glutton-09.07.2019).

**Comment by Vitaliy-1** [comment]
Thanks! Closing as is resolved.
