### ISSUE TITLE
Grobid hangs on a PDF

### ISSUE THREAD

**Issue by vha14** [kermitt2/grobid#46]
This is the PDF: http://www.aclweb.org/anthology/W12-4305

Grobid was able to process this file with `-exe processHeader`, but hanged when run with `-exe processReferences` and `-exe processFullText`.

**Comment by kermitt2** [comment]
Hi! I obtain a TEI with -exe `processFullText` for this PDF with the current Grobid version on my Mac. 
Are you using an older version of Grobid?

Probably not related to the hanging I think, the segmentation on this PDF looks bad, not clear why... I will have to look more carefully. I am still in the process of adding more training data for the initial segmentation model so it improves slowly.

**Comment by kermitt2** [comment]
This is the TEI I obtain: [link](https://grobid.s3.amazonaws.com/W12-4305.tei.xml)

(the fulltext body is not very good and incomplete in term of structures, because I am (re)working on it since a couple of days)

**Comment by vha14** [comment]
Hi Patrice, you are right. This happens with 0.3.1. After updating to 0.3.3 this problem went away. Many thanks!!
