### ISSUE TITLE
Exception with createTraining

### ISSUE THREAD

**Issue by Vitaliy-1** [kermitt2/grobid#464]
Current master branch.

When trying to create data for training, an exception occurs:
```
SEVERE: An error occured while processing the following pdf: ...: org.grobid.core.exceptions.GrobidException: [GENERAL] An exception occurred while running Grobid training data generation for full text.
Jul 25, 2019 2:10:42 PM org.grobid.core.engines.Engine batchCreateTraining
```

**Comment by Vitaliy-1** [comment]
Hmm, should the path to the directory contain trailing slash?

**Comment by Vitaliy-1** [comment]
Also worth to mention multiple:
```
SEVERE: Cannot parse file: /home/doc/Grobid/.../grobid-home/tmp/ytRZQdY6xC.lxml_outline.xml
```
(`tmp` folder is absent).
Multiple warning, like:
```
Warning, father not yet encountered! id is 2
```
And the fact that the output goes to Grobid's root folder rather than in a specified path.

**Comment by kermitt2** [comment]
Hello @Vitaliy-1 !

For reproducing your error, which PDF are you using?

The directory paths in the command line do not require trailing slash.

The outline files are currently not used, the parsing errors are outputted on purpose as a reminder that this part will need a bit more work. Outlines are generated by pdfalto and we need to put more robustness in the way there are structured (hierarchical identifiers). So there is nothing to worry about that normally. 

`tmp` folder is always under `grobid-home/tmp/` but the pdfalto files are cleaned after parsing. 

> And the fact that the output goes to Grobid's root folder rather than in a specified path.

Files are outputted in the provided output path (`-dOut `), default is current directory (see the batch command documentation, "if omitted the current directory").

**Comment by Vitaliy-1** [comment]
Hi @kermitt2, Thanks for the response!

It seems that the problem:
```
SEVERE: An error occurred while processing the following pdf: ...: org.grobid.core.exceptions.GrobidException: [GENERAL] An exception occurred while running Grobid training data generation for full text.
Jul 25, 2019 2:10:42 PM org.grobid.core.engines.Engine batchCreateTraining
```
and 
> And the fact that the output goes to Grobid's root folder rather than in a specified path.
Were associated with that I've used a command line from the IDE. It has a strange bug that resulted in incorrect `-dOut` path.

As you say that warning regarding outlines is not important, the only problem that is left here are warnings, like:
```
Warning, father not yet encountered! id is 2
```
But I suppose it's related to outline files, right? If not, I can provide an example of PDF.

**Comment by kermitt2** [comment]
Yes this is coming from the outline file that has often some weird hierarchy of section titles. It's very frequent.

**Comment by Vitaliy-1** [comment]
Thanks for the feedback!
