### ISSUE TITLE
Is it possible to submit batch of citations in string to extract TEI from them

### ISSUE THREAD

**Issue by darjusp** [kermitt2/grobid#478]
Hi guys,

thanks a lot for Grobid, it has been a big help for me. I am using it in another research project, but this time I need to extract citations info from raw text. 
this command does the job:
` java -Xmx1G -jar grobid-core/build/libs/grobid-core-0.5.5-onejar.jar -gH grobid-home -exe processRawReference -s "a reference string
`
but its very slow when you need to use it for many strings, as everytime it loads the model and search for home-directory.
Is it possible to supply in batch those strings, or somehow make the process faster?

Also is there a way to save the output in the TEI files  not just in the command line?

I am using python, but as i understood python client is not dealing with the raw text yet

**Comment by kermitt2** [comment]
Hello @darjusp !

Thanks for the interest for GROBID and very happy that it can be useful for you. 

Batch process is proposed for simplicity/convenience/test but should not be used for any intensive work. You need to use the service mode, as indicated in the documentation - then the models are always warm in memory and you can process hundred citations per second without issue (without consolidations... with consolidation you will be limited to the CrossRef API query rate, or you would need to use [biblio-glutton](https://github.com/kermitt2/biblio-glutton) for avoid this).  

Using the web service with Python should be very simple, just send the text as query to the service https://grobid.readthedocs.io/en/latest/Grobid-service/#apiprocesscitation

You could reuse the [grobid python client](https://github.com/kermitt2/grobid-client-python), and simply change the service endpoint and the parameters... Parallel requests should be pretty robust. If you add this service to the python client, that would be a great contribution I have to say :)

**Comment by darjusp** [comment]
Patrice, thanks a lot for the quick reply.
Surely would look into your written client.

But there is a bit interesting thing happening if I make a request to service through terminal:
`curl -X POST -d "citations=Peffers, K., & Ya, T. (2003). Identifying and evaluating the universe of outlets for information systems research: Ranking the journals. Journal of Information Technology Theory and Application (JITTA), 5(1), 6." localhost:8070/api/processCitation`
I get only:
```
<biblStruct >
	<monogr>
		<title/>
		<author>
			<persName xmlns="http://www.tei-c.org/ns/1.0"><forename type="first">K</forename><surname>Peffers</surname></persName>
		</author>
		<imprint/>
	</monogr>
</biblStruct>
```
but if use web interface for the same citation I get full extraction:
```
<biblStruct >
    <analytic>
        <title level="a" type="main">Examining differences across journal rankings</title>
        <author>
            <persName
                xmlns="http://www.tei-c.org/ns/1.0">
                <forename type="first">R</forename>
                <forename type="middle">K</forename>
                <surname>Rainer</surname>
                <genName>Jr</genName>
            </persName>
        </author>
        <author>
            <persName
                xmlns="http://www.tei-c.org/ns/1.0">
                <forename type="first">M</forename>
                <forename type="middle">D</forename>
                <surname>Miller</surname>
            </persName>
        </author>
    </analytic>
    <monogr>
        <title level="j">Communications of the ACM</title>
        <imprint>
            <biblScope unit="volume">48</biblScope>
            <biblScope unit="issue">2</biblScope>
            <biblScope unit="page" from="91" to="94" />
            <date type="published" when="2005" />
        </imprint>
    </monogr>
</biblStruct>
```

Is there something in string like escape characters that shouldn't be used?

**Comment by kermitt2** [comment]
I guess the `&` is interpreted as the background process control operator, it works if you replace `&` by `and`. 

mmm I  don't know how to escape this character... The best is certainly to use a programmatic approach like using `request` lib with python to avoid all this kind of problems.

**Comment by darjusp** [comment]
Aha , rookie mistake :) sorry for that.

**Comment by kermitt2** [comment]
I am closing the issue, if you have more questions or problems, feel free to re-open it or open a new one.
