### ISSUE TITLE
Pooling Question/Bug?

### ISSUE THREAD

**Issue by ulf2us** [kermitt2/grobid#49]
Hi,

I am using the latest Grobit Verison with j2sdk1.7-oracle on SMP Debian 3.2.60-1+deb7u1 x86_64 Linux
and it seems the Grobid is somehow unable to use it's pool, I have messages about an error in my log

ulf@ivanova:/data/delivermath/grobid/grobid-service$ tail -f grobid.log

17 Mar 2015 18:03.03 [INFO ] GrobidRestService         - Initiating Servlet GrobidRestService
17 Mar 2015 18:03.03 [INFO ] LibraryLoader             - Loading external native CRF library
17 Mar 2015 18:03.03 [INFO ] LibraryLoader             - Loading Wapiti native library...
17 Mar 2015 18:03.03 [INFO ] LibraryLoader             - Library crfpp loaded
17 Mar 2015 18:03.03 [INFO ] Lexicon                   - Initiating dictionary
17 Mar 2015 18:03.03 [INFO ] Lexicon                   - End of Initialization of dictionary
17 Mar 2015 18:03.03 [INFO ] Lexicon                   - Initiating names
17 Mar 2015 18:03.03 [INFO ] Lexicon                   - End of initialization of names
17 Mar 2015 18:03.04 [INFO ] Lexicon                   - Initiating country codes
17 Mar 2015 18:03.04 [INFO ] Lexicon                   - End of initialization of country codes
17 Mar 2015 18:03.04 [INFO ] GrobidRestService         - Initiating of Servlet GrobidRestService finished.
17 Mar 2015 18:03.29 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.29 [INFO ] WapitiModel               - Loading model: /data/delivermath/grobid/grobid-home/models/citation/model.wapiti (size: 12840798)
17 Mar 2015 18:03.32 [INFO ] WapitiModel               - Loading model: /data/delivermath/grobid/grobid-home/models/name/header/model.wapiti (size: 2215355)
17 Mar 2015 18:03.32 [INFO ] WapitiModel               - Loading model: /data/delivermath/grobid/grobid-home/models/name/citation/model.wapiti (size: 99017)
17 Mar 2015 18:03.32 [INFO ] WapitiModel               - Loading model: /data/delivermath/grobid/grobid-home/models/date/model.wapiti (size: 103543)
17 Mar 2015 18:03.32 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.32 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.32 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.33 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.33 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.33 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.33 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.33 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.33 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.34 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.34 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10
17 Mar 2015 18:03.34 [ERROR] GrobidPoolingFactory      - Number of Engines in pool active/max: 1/10

.
.
.

**Comment by kermitt2** [comment]
Hi Ulf,

This information should actually not be logged as an ERROR sorry, but as INFO. I will correct that.

If you have only one thread available for Grobid, it should be correct. If you have more available threads and only one thread is used in the pool, there could be an issue related to your environment because several tests were fine with the same JDK and Ubuntu or CentOS and with many threads.

**Comment by lfoppiano** [comment]
The log has been corrected. @ulf2us if you still have the problem feel free to reopen it.
