### ISSUE TITLE
ProcessCitation endpoint in Grobid REST API parses incorrect page ranges

### ISSUE THREAD

**Issue by lizdenhup** [kermitt2/grobid#492]
First, thank you for making such an awesome tool! Grobid performs impressively well and is a great project.

## Context

_Problem_: When I use the Grobid REST api to parse citations, I notice that the parsing returns a page range whose numbers don't always appear in the raw citation string I've passed to the service. 

For example, passing the following citation to the processCitation endpoint

![Screen Shot 2019-08-26 at 3 54 27 PM](https://user-images.githubusercontent.com/15963426/63723819-04ff7200-c81c-11e9-8d01-2e0746b0e111.png)

yields this parsing:

![Screen_Shot_2019-08-26_at_3_54_35_PM](https://user-images.githubusercontent.com/15963426/63723790-f87b1980-c81b-11e9-80c7-26e5b455a83d.jpg)

I don't understand CRF models very well, but I am puzzled as to how the parsing could contain digits which do not appear in the raw string?

## Steps to recreate

1) Go to http://cloud.science-miner.com/grobid/ --> TEI and click "processCitation" in the dropdown menu
2) Paste any of the following citations into the text field:

<hr>
Jensen JR, Cowen DC. Remote sensing of urban/suburban infrastructure and socio-economic attributes. Photogramm Eng Remote Sensing 1999;65(5):611–22.

Mokkink LB, Terwee CB, Patrick DL, et al. The COSMIN checklist for assessing the methodological quality of studies on measurement properties of health status measurement instruments: an international Delphi study. Qual Life Res. 2010;19(4):539-49.

Louvard Y, Medina A. Definitions and classifications of bifurcation lesions and treatment. EuroIntervention. 2015;11(V):V23-V6.

Généreux P, Kumsars I, Lesiak M, Kini A, Fontos G, Slagboom T, et al. A Randomized Trial of a Dedicated Bifurcation Stent Versus Provisional Stenting in the Treatment of Coronary Bifurcation Lesions. J Am Coll Cardiol. 2015;65(6):533-43
<hr>

This pattern may be spurious, but sometimes it seems that the Grobid service is performing arithmetic on the page range. For example, in the third citation listed above, the page range returned is 23-29. The trailing digits in the starting page and end page are 3 and 6, which sum to 9. I have seen this for other citations as well.

## Question
At any rate, do you have any ideas of why this may be happening? We use Grobid to process citations at scale. Should we retrain the model we have locally or is there some other clear step forward we should take? Can CRF models return parsings that have characters which don't appear in the input string?

Thanks!

**Comment by kermitt2** [comment]
Hello @lizdenhup ! 

Thank you for the detailed issue !

GROBID tries to normalize the final metadata, by cleaning the string, removing useless punctuations, etc. so that it is closer to usual bibliographical records. In the case it extracts as page range a first page that is much larger than the second, it applies a heuristic that supposes that the second number is the number of page of the article, so the final page is the sum of the two numbers. 

I wrote this heuristics long time ago (like 5-6 years ago!) because I had the impression that it was asomething valid, but your examples are clearly counter-examples, and this heuristics looks actually  bad in general.

The method that does this normalization is here: 

https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java#L3955

You could remove the heuristics and simply gives the actual extracted values or we could expand the second number with the prefix part of the first, which would work fine for your cases.

**Comment by georgediaz88** [comment]
@kermitt2, hi my name is George. I'm also wondering if this issue has been fixed? Thanks!

**Comment by kermitt2** [comment]
Hi George!

It's complicated because usually this post-processing normalization is making a good work in general, except for the American Medical Association citation style which are from where all these above counter-examples come from. 

If we process a complete article we could adapt the normalization according to the publisher (it would be quite well recognized I think when processing the header metadata in this case). For single citation in isolation, it looks harder to detect the citation style reliably.  So I don't really have a solution in mind, and I am open to any suggestions :D 

Now if you select the consolidation option, you might get the right pages from the publisher metadata, without the citation style hazard, for example: 

> Louvard Y, Medina A. Definitions and classifications of bifurcation lesions and treatment. EuroIntervention. 2015;11(V):V23-V6.

```xml
        <imprint>
            <biblScope unit="volume">11</biblScope>
            <biblScope unit="issue">V</biblScope>
            <biblScope unit="page" from="V23" to="V26" />
            <date type="published" when="2015-05" />
            <publisher>Europa Digital &amp; Publishing</publisher>
        </imprint>
```

**Comment by de-code** [comment]
Perhaps in the absence of a good solution, this could be a configuration option?

Maybe it would also be good to collect some of the main different styles that you have encountered.

**Comment by kermitt2** [comment]
I've iterated on this and with some heuristics we can distinguish between addition and substitution relatively well I think. All these cases are well formatted now:

```
Louvard Y, Medina A. Definitions and classifications of bifurcation lesions and treatment. EuroIntervention. 2015;11(V):V23-V6.
```

```xml
<biblStruct >
    <analytic>
        <title level="a" type="main">Definitions and classifications of bifurcation lesions and treatment</title>
        <author>
            <persName>
                <forename type="first">Y</forename>
                <surname>Louvard</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">A</forename>
                <surname>Medina</surname>
            </persName>
        </author>
    </analytic>
    <monogr>
        <title level="j">EuroIntervention</title>
        <imprint>
            <biblScope unit="volume">11</biblScope>
            <biblScope unit="page" from="V23" to="V26" />
            <date type="published" when="2015" />
        </imprint>
    </monogr>
</biblStruct>
```

```
Jensen JR, Cowen DC. Remote sensing of urban/suburban infrastructure and socio-economic attributes. Photogramm Eng Remote Sensing 1999;65(5):611–22. 
```

```xml
<biblStruct >
    <analytic>
        <title level="a" type="main">Remote sensing of urban/suburban infrastructure and socio-economic attributes</title>
        <author>
            <persName>
                <forename type="first">J</forename>
                <forename type="middle">R</forename>
                <surname>Jensen</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">D</forename>
                <forename type="middle">C</forename>
                <surname>Cowen</surname>
            </persName>
        </author>
    </analytic>
    <monogr>
        <title level="j">Photogramm Eng Remote Sensing</title>
        <imprint>
            <biblScope unit="volume">65</biblScope>
            <biblScope unit="issue">5</biblScope>
            <biblScope unit="page" from="611" to="622" />
            <date type="published" when="1999" />
        </imprint>
    </monogr>
</biblStruct>
```

```
Généreux P, Kumsars I, Lesiak M, Kini A, Fontos G, Slagboom T, et al. A Randomized Trial of a Dedicated Bifurcation Stent Versus Provisional Stenting in the Treatment of Coronary Bifurcation Lesions. J Am Coll Cardiol. 2015;65(6):533-43
```

```xml
<biblStruct >
    <analytic>
        <title level="a" type="main">A Randomized Trial of a Dedicated Bifurcation Stent Versus Provisional Stenting in the Treatment of Coronary Bifurcation Lesions</title>
        <author>
            <persName>
                <forename type="first">P</forename>
                <surname>Généreux</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">I</forename>
                <surname>Kumsars</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">M</forename>
                <surname>Lesiak</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">A</forename>
                <surname>Kini</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">G</forename>
                <surname>Fontos</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">T</forename>
                <surname>Slagboom</surname>
            </persName>
        </author>
    </analytic>
    <monogr>
        <title level="j">J Am Coll Cardiol</title>
        <imprint>
            <biblScope unit="volume">65</biblScope>
            <biblScope unit="issue">6</biblScope>
            <biblScope unit="page" from="533" to="543" />
            <date type="published" when="2015" />
        </imprint>
    </monogr>
</biblStruct>
```

```
Stuart SN, Chanson JS, Cox NA, Young BE, Rodrigues ASL, Fischman DL, et al. Status and trends of amphibian declines and extinctions worldwide. Science (80-). 2004;306(5702):1783-6.
```

```xml
<biblStruct >
    <monogr>
        <title level="m" type="main">Status and trends of amphibian declines and extinctions worldwide. Science (80-)</title>
        <author>
            <persName>
                <forename type="first">S</forename>
                <forename type="middle">N</forename>
                <surname>Stuart</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">J</forename>
                <forename type="middle">S</forename>
                <surname>Chanson</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">N</forename>
                <forename type="middle">A</forename>
                <surname>Cox</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">B</forename>
                <forename type="middle">E</forename>
                <surname>Young</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">Asl</forename>
                <surname>Rodrigues</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">D</forename>
                <forename type="middle">L</forename>
                <surname>Fischman</surname>
            </persName>
        </author>
        <imprint>
            <date type="published" when="2004" />
            <biblScope unit="volume">306</biblScope>
            <biblScope unit="page" from="1783" to="1786" />
        </imprint>
    </monogr>
</biblStruct>
```

And an example of addition:

```
Morris-Thurgood J, Turner M, Nightingale A, Mumford C, Masani N, Frenneaux M:   "Normal QRS duration should not be a contraindication to pacing for heart failure". Europace 2000; 1  (suppl D): 156-1.
```

```xml
<biblStruct >
    <analytic>
        <title level="a" type="main">Normal QRS duration should not be a contraindication to pacing for heart failure</title>
        <author>
            <persName>
                <forename type="first">J</forename>
                <surname>Morris-Thurgood</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">M</forename>
                <surname>Turner</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">A</forename>
                <surname>Nightingale</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">C</forename>
                <surname>Mumford</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">N</forename>
                <surname>Masani</surname>
            </persName>
        </author>
        <author>
            <persName>
                <forename type="first">M</forename>
                <surname>Frenneaux</surname>
            </persName>
        </author>
    </analytic>
    <monogr>
        <title level="j">Europace</title>
        <imprint>
            <biblScope unit="volume">1</biblScope>
            <biblScope unit="page" from="156" to="157" />
            <date type="published" when="2000" />
        </imprint>
    </monogr>
    <note>suppl D</note>
</biblStruct>
```
