### ISSUE TITLE
superscript/subscript, bold/italics not always parsed correctly

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#495]
I've noticed that bold/italics were taken only from FONTSTYLE, however (as explained here: https://github.com/kermitt2/pdfalto/issues/57#issuecomment-527337488) sometimes the information is present in the font name (ending with `-bold` or `_bd` etc...) 

I've added a unit test and try to fix the issue (https://github.com/kermitt2/grobid/tree/pdfalto_parser_fixes)  in the xml parser, however I'm not sure what's expected to be outputed from pdfalto...

**Comment by kermitt2** [comment]
Font style like bold and italic are already derived from the font name by pdfalto via xpdf (this is common to know about these font attributes), so any style information in FONTSTYLE are already covering the font name and looking again FONTFAMILY in GROBID is redundant. 

In xpdf, I think the main piece performing this check is `GlobalParams.cc, line 237 (version 4.00), this method:

```
SysFontInfo *SysFontList::find(GString *name)
```

So we should never see these attributes missing in FONTSTYLE when present in the font name. If it is the case, this should be fixed normally in xpdf.

**Comment by lfoppiano** [comment]
In this example I have this: 

```
<TextStyle ID="font0" FONTFAMILY="kmhhoc+advtimes_bd" FONTSIZE="11.955" FONTTYPE="serif"
                   FONTWIDTH="proportional" FONTCOLOR="#000000" FONTSTYLE=""/>
        <TextStyle ID="font1" FONTFAMILY="kmhhod+advmtmrb" FONTSIZE="8.368" FONTTYPE="sans-serif" FONTWIDTH="fixed"
                   FONTCOLOR="#000000" FONTSTYLE="subscript"/>
        <TextStyle ID="font2" FONTFAMILY="kmhhof+advmtmib" FONTSIZE="8.368" FONTTYPE="sans-serif" FONTWIDTH="fixed"
                   FONTCOLOR="#000000" FONTSTYLE="subscript"/>
        <TextStyle ID="font3" FONTFAMILY="kmhhog+advtimes_rg" FONTSIZE="9.963" FONTTYPE="serif" FONTWIDTH="proportional"
                   FONTCOLOR="#000000" FONTSTYLE=""/>
        <TextStyle ID="font4" FONTFAMILY="kmhhoh+advmtmr" FONTSIZE="6.974" FONTTYPE="sans-serif"
                   FONTWIDTH="proportional" FONTCOLOR="#000000" FONTSTYLE="superscript"/>
        <TextStyle ID="font5" FONTFAMILY="kmhhoj+advtimes_rg_it" FONTSIZE="7.970" FONTTYPE="serif"
                   FONTWIDTH="proportional" FONTCOLOR="#000000" FONTSTYLE=""/>
```
[JPS081033701-CC.xml.zip](https://github.com/kermitt2/grobid/files/3588148/JPS081033701-CC.xml.zip)

[JPS081033701-CC.pdf](https://github.com/kermitt2/grobid/files/3588149/JPS081033701-CC.pdf)

**Comment by lfoppiano** [comment]
Looking at the code, it seems that it's not looking for `_bd` or `it` or other variations like `-bold`: 

```
// look for "Italic"
    if (n > 6 && !strcmp(name2->getCString() + n - 6, "Italic")) {
      name2->del(n - 6, 6);
      italic = gTrue;
      n -= 6;
    }

    // look for "Bold"
    if (n > 4 && !strcmp(name2->getCString() + n - 4, "Bold")) {
      name2->del(n - 4, 4);
      bold = gTrue;
      n -= 4;
    }
```

**Comment by kermitt2** [comment]
Thanks for the test case!

Yes in xpdf, it's also not constraining the match to `-` tag markers and only check end of font name. It looks a bit superficial. 
However I am not 100% sure it's the only place in xpdf that this font name analysis is done, I just did a quick check. 

Just looking a bit more, it is further done in the pdfalto part, `XmlAltoOutputDev.cc`, line 603-606 ("bold", "italic", "oblique") and lines 914-917.  The method `normalizeFontName()` is also relevant. I think it's the right places to modify to address this issue.

**Comment by lfoppiano** [comment]
OK, so I've made a quick fix (https://github.com/kermitt2/pdfalto/pull/71). It's doing the same as in Java. Feel free to rewrite it, I have no clue how C++ works... 💃

**Comment by kermitt2** [comment]
Fix with PR #496, thank you Luca !

**Comment by savithavelumani7** [comment]
Hello,

I am giving reference as plain text to GROBID instead of extracting from pdf. If the reference contain style tags like italic or bold, its tagging incorrectly. Whereas if i remove the style tags and post the reference its tagging correctly. Is there any way I can pass the references with style tags still get the correct tagged reference.

**Comment by lfoppiano** [comment]
@savithavelumani7 sorry, I"m not following. Could you please open a new issue and provide more information? When you create a new issue you should enter them in the different places, otherwise we will not be able to help you.
