### ISSUE TITLE
Not well-formed xml output

### ISSUE THREAD

**Issue by JKillian** [kermitt2/grobid#50]
I've been running GROBID on a variety of pdfs as of late and came across one where the xml is not well-formed. I'm using GROBID as a service via its `processFulltextDocument` method.

[Offending PDF](https://www.dropbox.com/s/pbxlap3t1bxjf0c/paper.pdf?dl=0)
[Resulting XML file](https://www.dropbox.com/s/pcx1kg3ksoeit6o/result.xml?dl=0)

The problem with the XML file is in Line 172 (below, line-breaks added by me for readability) where there's a `quot;` entity that seems to have gotten messed up and leaves us with an unescaped ampersand.

```xml
<p>To find out on which level of granularity 
visual pattern are classified as single &quot;objects&quot; (see Figure 6), 
a questionnaire with eight different screen-dumps 
of a commercial multimedia information system 
(called &quot;mock-ups&quot;, see[Rauterberg 1995c]) was answered
by a heterogeneous group of potential users. 
A total of 33 women (between 14 and 66 year of life) 
and 33 men (between 21 and 55 year of life) participated 
(no significant difference in age between both groups). 
The computer experience of each subject was measured on a rating scale 
(&quot;no experience&quot ; = 0 … &quot;expert&quot; = 90). 
We found a significant difference in computer experience between both groups: 
40 ±27 for women and 63 ±24 for men (p≤ .001); 
the men were more experienced than the women.</p>
```

Using a version of GROBID cloned from github about a month or so ago. Let me know if any other info is needed.

**Comment by JKillian** [comment]
Seeing the same thing with a PDF that is mostly images:
[PDF](https://www.dropbox.com/s/tmbxs5oa1hbsqs4/imagepdf.pdf?dl=0)
[Result XML](https://www.dropbox.com/s/7nqr5v3861ppqer/imagepdf.xml?dl=0)

In this case there's a stray `</back>` tag near the end:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:xlink="http://www.w3.org/1999/xlink" 
 xmlns:mml="http://www.w3.org/1998/Math/MathML">
	<teiHeader xml:lang="en">
		<fileDesc>
			<titleStmt>
				<title level="a" type="main"></title>
			</titleStmt>
			<sourceDesc>
				<biblStruct>
					<analytic>
					</analytic>
				</biblStruct>
			</sourceDesc>
		</fileDesc>
	</teiHeader>
	<text xml:lang="en">
		<body/>
			<div type="references">

		<listBibl>

		</listBibl>
			</div>
		</back>
	</text>
</TEI>
```

**Comment by kermitt2** [comment]
Thanks ! The two cases have been fixed in the meantime, a couple of weeks ago :)

**Comment by JKillian** [comment]
Thanks for the update! I'll grab the newest version of GROBID and close this issue as long as the issues don't persist.

**Comment by JKillian** [comment]
Updated and then retested on the documents above, seems like everything is working correctly. Thanks for the great work!
