### ISSUE TITLE
processCitationPatentTXT  broken ? 

### ISSUE THREAD

**Issue by cverluise** [kermitt2/grobid#505]
Hello, 

Thanks for the great work !

## Issue

It seems that the processCitationPatentTXT service is no longer supported by the latest release of Grobid. 

## Reproducing the issue

```shell
git clone https://github.com/kermitt2/grobid.git
cd grobid
./gradlew run
curl -X POST -d "input=In EP0123456B1 nothing interesting." localhost:8070/api/processCitationPatentTXT #example from the doc
```

**output**
```shell
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 415 Unsupported Media Type</title>
</head>
<body><h2>HTTP ERROR 415</h2>
<p>Problem accessing /api/processCitationPatentTXT. Reason:
<pre>    Unsupported Media Type</pre></p>
</body>
</html>
```

Actually, the online demo seems to be affected by the same issue

- navigate to http://cloud.science-miner.com/grobid/
- select "Extract citation patent Text"
- fill the blank field with "In EP0123456B1 nothing interesting."
- Submit

**output**
>Error encountered while requesting the server.
>HTTP ERROR 415
>Problem accessing /api/processCitationPatentTXT. Reason:
>
>    Unsupported Media Type

## Some ideas

If I roll back to commit  4f3a906fb7fc9e4eec060ce644 (30 July), the service is still working (I did not check which precise commit actually caused processCitationPatentTXT to fail).

**Comment by kermitt2** [comment]
Hi @cverluise ! Many thanks for the very detailed issue as always. 
It was a bad cut and paste when I added the new `includeRawCitations` parameter in the citation service, it is fixed with commit ce45a96c3e3318e6a54c234041f2e0a435734498.

**Comment by cverluise** [comment]
Thanks @kermitt2 !

**Comment by kermitt2** [comment]
I am closing the issue, but if you still have any troubles with the `processCitationPatentTXT` please reopen it! Thanks again for the issue.
