### ISSUE TITLE
Put <fileDesc> before <encodingDesc>

### ISSUE THREAD

**Issue by laurentromary** [kermitt2/grobid#509]
The TEI generic model for the `<teiHeader>` element imposes that `<fileDesc>` be set as its first (mandatory) child. See [ref-teiHeader](https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-teiHeader.html)

**Comment by kermitt2** [comment]
It will be changed in release 0.5.6 as last minute fix ;)

**Comment by kermitt2** [comment]
Fix with PR #496
