### ISSUE TITLE
Page dimensions missing in fulltext process TEI

### ISSUE THREAD

**Issue by jknabe** [kermitt2/grobid#523]
I appreciate the feature teiCoordinates to include element bounding boxes in the XML.

The coordinates are always relative to scaled page size I guess.
For JSON results I understand the page dimensions are included in the response.
If I did not miss something this is currently not an option for TEI XML output
https://grobid.readthedocs.io/en/latest/Coordinates-in-PDF/#coordinates-in-teixml-results

Please include the page dimensions in the XML if any teiCoordinates are requested.

**Comment by kermitt2** [comment]
Hello @jknabe, thanks for the issue. This is correct and indeed the page sizes need to be added in the TEI XML to be able to scale the bounding boxes similarly as in the json response.

**Comment by kermitt2** [comment]
This implemented by commit 672fa613e0a446b228fe7ade62510b81f4e6b671

Using the TEI stuff, it gives an additional `<facsimle>` element with the page coordinates - in case the coordinates for at least one element is requested. See the documentation https://grobid.readthedocs.io/en/latest/Coordinates-in-PDF/#coordinates-in-teixml-results
