### ISSUE TITLE
Error on submitting PDF for processing

### ISSUE THREAD

**Issue by ParikhKadam** [kermitt2/grobid#524]
The command line shows this error and then the server exits.

```
INFO  [2019-12-12 06:32:08,345] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@53125718{/,null,AVAILABLE}
INFO  [2019-12-12 06:32:08,351] org.eclipse.jetty.server.AbstractConnector: Started application@77c3c037{HTTP/1.1,[http/1.1]}{0.0.0.0:8070}
INFO  [2019-12-12 06:32:08,351] org.eclipse.jetty.server.AbstractConnector: Started admin@252744a1{HTTP/1.1,[http/1.1]}{0.0.0.0:8071}
INFO  [2019-12-12 06:32:08,352] org.eclipse.jetty.server.Server: Started @2378ms
INFO  [2019-12-12 06:32:16,890] org.grobid.core.jni.WapitiModel: Loading model: /media/kadam/data drive/Research Paper Builder/backend/grobid/grobid-home/models/affiliation-address/model.wapiti (size: 2699936)
error: too much input files on command line

```

I think the model loaded above is getting passed through command line arguments. In systems, there's a limit in number of bytes up to which we can pass command line arguments. And that value is low compared to model size. Maybe that is causing this error. Though I ain't aware of what actually is causing this error, can you please help?

**Comment by lfoppiano** [comment]
@ParikhKadam just as a random though, might well be the spaces in the path which is not well digested... could you try to remove them and see if ti works?

**Comment by ParikhKadam** [comment]
@lfoppiano Yeah.. that worked. Thank you for your quick reply :)
