### ISSUE TITLE
Feature request: Extract affiliation text

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#547]
(I hope I did not raise that before)

We internally came to the conclusion, that we rather extract the affiliation string as text (as it appeared in the document), instead of (or in addition to) being split into separate fields. That is in part due to inconsistencies and information either not being reliable or incomplete.

Maybe having an additional field would be best. Then one can choose whether to use that or the individual fields.

Any thoughts on that?

**Comment by de-code** [comment]
Is there any work being planned on the affiliation extraction?

I looked at `AffiliationAddressParser` and I guess it could benefit from a bit of refactory. `resultBuilder` is more than `500` lines, with many nested levels that make it hard to see where in the "decision tree" one is. Perhaps also not helped by the variable naming (`s1` etc). I believe there are `10` places with `new Affiliation`.

/cc @kermitt2 @lfoppiano

**Comment by kermitt2** [comment]
Hi Daniel, `AffiliationAddressParser` is one of the models where the "`resultBuilder`" has not been updated to use the nice TaggingTokenClusteror, which is much more readable, concise and less error-prone (I've updated the `HeaderParser` result builder for instance in one fork which I will merge soon... hopefully at some point the remaining vintage parsers will be all updated). Apart from that there is a lot to improve in the `AffiliationAddressParser` to be honest, but there is no short term work on it planned on my side. 

We could add an option to have the raw affiliation string, as we did with the `includeRawCitations` service parameter (raw reference string is useful for reference disambiguation)? I would prefer not to overload the default XML output.

**Comment by de-code** [comment]
Thank you, Patrice. An additional flag would also work.

I am trying to write some tests before I make changes. I have a question regarding some of the logic. There are a few cases where it would start a new affiliation if there is the `LINESTART` feature, e.g.: https://github.com/kermitt2/grobid/blob/64ab5c18cddf8a24347df6e5df90d3698b2e3733/grobid-core/src/main/java/org/grobid/core/engines/AffiliationAddressParser.java#L324-L325

Which I believe comes from `@newline` via https://github.com/kermitt2/grobid/blob/64ab5c18cddf8a24347df6e5df90d3698b2e3733/grobid-core/src/main/java/org/grobid/core/features/FeaturesVectorAffiliationAddress.java#L181-L182

But then it seems to replace a line feed with a space: https://github.com/kermitt2/grobid/blob/64ab5c18cddf8a24347df6e5df90d3698b2e3733/grobid-core/src/main/java/org/grobid/core/engines/AffiliationAddressParser.java#L49-L58

Should it still consider a new line as such or was the intention of replacing the line feed with a space to no longer make that distinction?

**Comment by de-code** [comment]
Another question, do you think the raw affiliation text should include the marker? For our purpose it probably wouldn't be useful. But maybe you have an opinion on that?

**Comment by kermitt2** [comment]
The processing of affiliation as string is not used when processing a PDF, we use `processReflow()` (which propagate some labels from the header model). In the case of a PDF, affiliations can be segmented by their positions as separate distant blocks. 

The processing of affiliation as a string supposes more or less that we have a unique affiliation/address sequence on one line, it's a kind of by-product for people wanting to parse affiliation strings in isolation - a different task than parsing affiliations in PDF.

**Comment by de-code** [comment]
Okay, thank you. I have a WIP PR against our repo for now: https://github.com/elifesciences/grobid/pull/13

(I can submit the equivalent to the main repo once that is done)

**Comment by de-code** [comment]
Is there a preferred TEI element for that?

**Comment by de-code** [comment]
Interestingly, [the examples here](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-affiliation.html) seem to suggest that the whole reference text becomes the text of the `affiliation` element and the text within it is annotated using the appropriate tags.

```xml
<affiliation>Junior project officer for the US <name type="org">National Endowment for
   the Humanities</name>
</affiliation>
```

```xml
<affiliation notAfter="1960-01-01"
 notBefore="1957-02-28">Paid up member of the
<orgName>Australian Journalists Association</orgName>
</affiliation>
```

```xml
<affiliation from="1902-01-01"
 to="1906-01-01">Was an assistant professor at Mount Holyoke College.</affiliation>
```

Although information not directly encoded in the text would probably have to become attributes.

**Comment by kermitt2** [comment]
You can put the "raw" affiliation text directly under `<affiliation>`, but I might update it after receiving the feedback from a TEI master ;)

**Comment by kermitt2** [comment]
There are different level of encoding in TEI. We can annotate text as it appears in non-formal way, this is done in the training data (where we must follow exactly the original text flow) and it corresponds to these examples from the TEI guidelines. Or we can encode more as a "metadata record" with normalized fields not mixing text flow, which is what is done in the Grobid result TEI (because we are trying to capture the logical structure).

**Comment by de-code** [comment]
It will be easier to stick with the `note`. But it would be kind of nice to annotate the actual text. That could be fed back to the user. But it would require quite a few more changes.

Making it optional actually was quite a bit of work because the parameter needs to be fed through so many places. In any case, there is a PR now.

**Comment by de-code** [comment]
I have a related question, why is the `address` in the header model separate from the `affiliation`. Is it not the purpose of the `affiliation-address` model to extract the address from an affiliation?

**Comment by de-code** [comment]
I noticed that biorxiv's JATS XML looks more like the annotated text example, e.g.:

```xml
<aff xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="a1"><label>1</label><institution>Department of MCD Biology</institution>, 1156 High Street, <institution>University of California</institution>, Santa Cruz, CA 95064 <country>USA</country></aff>
```

And maybe the marker / label should actually be included. Need to check whether TEI has the equivalent for the label or whether it could be embedded in the note.

(Whether the `institution` tagging in that example is actually correct, is another question)

**Comment by de-code** [comment]
I've now included the marker in the raw affiliation as well. e.g.:

```xml
<note type="raw_affiliation"><label>a</label> Department of Biology, Hopkins Marine Station, Stanford University, Pacific 5 Grove, California 93950 USA;</note>
```

If was no marker, it would just output:

```xml
<note type="raw_affiliation">Department of Biology, Hopkins Marine Station, Stanford University, Pacific 5 Grove, California 93950 USA;</note>
```

**Comment by kermitt2** [comment]
> I have a related question, why is the address in the header model separate from the affiliation. Is it not the purpose of the affiliation-address model to extract the address from an affiliation?

This is for historical reason, the CORA corpus annotates header was tagging affiliation and address separately. Then when working on the parsing of affiliations, it was clear that the whole block affiliation+address should be considered and that the model should indeed extract the address from an affiliation.

However, the CORA corpus plus the other header examples annotated in-between provided a very large amount of labelled data, more than the affiliation-address training data, and the separation of affiliation and address was apparently more reliable in the header than in the affiliation-address parser, so I combined both to avoid loosing annotations.

**Comment by kermitt2** [comment]
`<label>` is good! 

JATS is a mixture of inline and normalized "metadata record", a bit everything is possible. This is very loose and it's why it's a painful format. Writing a good parser or a stylesheet for JATS must cover plenty of variants chosen by the different publishers. It took years to have something covering a satisfactory amount of JATS variants in [Pub2TEI](https://github.com/kermitt2/Pub2TEI). With GROBID and Pub2TEI, the principle is to have strict constraints and normalization for the TEI, so that there is only one way to encode one information, and to avoid the JATS mess.
