### ISSUE TITLE
Abstract regression on bioRxiv current master

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#555]
This is somewhat related to #424 (but not the same)

I thought I raise it more for awareness. The abstract extraction on the bioRxiv because it is now using the segmentation model for the abstract even when heuristics is meant to be used. On the PMC dataset that appears to be more accurate but not bioRxiv. It doesn't affect us so much, because we are training the segmentation model anyway but it became apparent when I looked at a merge issue.

`4fb374f` is when #424 was fixed.
`bc0d325` is when the segmentation model is being used for the abstract regardless of the config.

The solution might well be to just use more bioRxiv data.

Results on bioRxiv (subset with 100 documents):

![image](https://user-images.githubusercontent.com/1016473/76197280-bf1c6100-61e3-11ea-927d-e53898e051ac.png)

Results on PMC (subset with 390 documents):

![image](https://user-images.githubusercontent.com/1016473/76197219-a613b000-61e3-11ea-8f53-001de03ec5bb.png)

(I used a smaller dataset for quicker feedback, it's probably enough for indicative results)

**Comment by kermitt2** [comment]
I've added 3 biorXiv training documents in the segmentation model in master (there was 0 before). Not sure it helps for the abstract, but it fixes the head notes added on the PDF by bioRxiv on all PDF, which was not recognized.

**Comment by de-code** [comment]
I merged your change. It appears the line numbers are really throwing it off. The updated models seems to be getting worse with the line numbers still in there. But using my "hack" to remove the line numbers, the results appear to be getting slightly better. (Of course, the validation set is a bit small)

(I can't test how GROBID 0.5.3 would have behaved with line numbers removed as it doesn't have that feature)

![image](https://user-images.githubusercontent.com/1016473/78037369-5b5d0200-7363-11ea-8284-38ef19710b95.png)

**Comment by lfoppiano** [comment]
@de-code I reopen this for further validation

**Comment by kermitt2** [comment]
@lfoppiano there is now a process dedicated to bioRxiv for each release based on the dataset https://zenodo.org/record/3873702 prepared by @de-code, for keeping track of regression and progress, see [here](https://github.com/kermitt2/grobid/blob/master/grobid-trainer/doc/bioRxiv_test_2000.results.grobid-0.6.1-SNAPSHOT-Glutton-20.06.2020) for instance.

**Comment by lfoppiano** [comment]
I see, so we can close this I guess?

**Comment by kermitt2** [comment]
I would say yes !

**Comment by lfoppiano** [comment]
Et hop! 😄
