### ISSUE TITLE
Missing information from the extracted content

### ISSUE THREAD

**Issue by ajinkya2903** [kermitt2/grobid#566]
Hi, I have re-trained a grobid using 50 pdfs. These pdfs are technical pdfs. I want to extract the total text content from the pdfs. But grobid missed some content from pdfs though we have retrained it. I am not understanding even after retraining it is missing the contents of the pdfs. Can you tell me the solution for this?

**Comment by lfoppiano** [comment]
Dear @ajinkya2903 you need to give some more information in order for us to help you. Which content do you want to extract? 

Also before doing that, please read the documentation. 
There is a whole section explaining how to create training data and use them:
https://grobid.readthedocs.io/en/latest/training/General-principles/

In addition, I also suggest you to do a search in the previous opened issues from other people, there are few on this same subject, I'm pulling out some of them: 
 - https://github.com/kermitt2/grobid/issues/535 
 - https://github.com/kermitt2/grobid/issues/372
 - https://github.com/kermitt2/grobid/issues/198
 - https://github.com/kermitt2/grobid/issues/196

**Comment by ajinkya2903** [comment]
Hi,
