### ISSUE TITLE
{"&" + "amp"} different than {xml entity "&amp;"}

### ISSUE THREAD

**Issue by rloth** [kermitt2/grobid#57]
Hello Patrice,

I have noticed a small bug in grobid.core.utilities.HTMLEncode() with the ```skip``` boolean being too laxist !

An input sequence (str from BiblioItem result) that contains '&' and characters like 'amp' or 'quot' will be mistakenly recognized as an XML entity (althought it has no ';')

For instance imagine this input document:
![image](https://cloud.githubusercontent.com/assets/1257512/8455714/f56e9c1a-2006-11e5-864e-d251926d054a.png)

It will generate the following result:
![image](https://cloud.githubusercontent.com/assets/1257512/8455805/885dea76-2007-11e5-90fd-3ae26ed04cf0.png)

But the expected valid result would be:
![image](https://cloud.githubusercontent.com/assets/1257512/8455810/953b6ec6-2007-11e5-8569-53f444f4347b.png)

Suggested fix is around line 650 of grobid.core.utilities.HTMLEncode() by adding a check like ```c5 == ;```

Nevertheless perhaps not checking for ';' was motivated by another reason ? Hope you have time to look into this at some point...

See you around !

**Comment by kermitt2** [comment]
Hi Romain,

Thank you for the detailed error report! 

This is fixed in commit da8843f2757f1f52e1b0c8d8eba82c130558aa28 and I've added in the test the case you provided.

**Comment by rloth** [comment]
Thank you Patrice !

**Comment by kermitt2** [comment]
Sorry romain, I should have let you close yourself the issue you opened, much better practice ;)

**Comment by rloth** [comment]
np :)
