### ISSUE TITLE
[TIMEOUT] PDF to XML conversion timed out

### ISSUE THREAD

**Issue by anupam20sep** [kermitt2/grobid#570]
For few PDFs I am getting following error while pro cessing full text.
Any idea what could be the problem
Version- 0.5.5

**Comment by kermitt2** [comment]
Hello! The problem is in the PDF and the timeout is to protect the grobid VM. You could test the PDF with [pdfalto](https://github.com/kermitt2/pdfalto) and report an issue on this repo with a link to PDF is possible.

**Comment by anupam20sep** [comment]
Sure the problem was with the PDF. Got it resolved by re creating the PDF. Thanks for help
