### ISSUE TITLE
Changes in output from updates of segmentation/fulltext models

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#578]
Just noticed that grobid extracts different infromation from this pdf: 
[JPS0710709-CC.pdf](https://github.com/kermitt2/grobid/files/4562304/JPS0710709-CC.pdf)

after these changes: 
 - 93526704f855f57fd39140bf3681e84c65e744b2 for fulltext model and 
 - d16317564dfae4e94f1d2b54abc85a255d576908 for segmentation model

**Comment by kermitt2** [comment]
Well, as you can imagine, it's not that bad to have some changes after the update of the models ;)  

Could you point to the new problem? The figures I guess? As there's really too few training data for this two particular models (especially the full text model), they are sensitive to regression issues, the best is to add more training data to get stability.

**Comment by lfoppiano** [comment]
Sure! 

My idea was to share the file to be added as training data. In fact there are several differences. The biggest one is: 
 - the first row of page 2 is missing
 - page 6:  `[18] Such a temperature dependence [...]` is not there... 

Let me know if you need more details.

**Comment by lfoppiano** [comment]
To be more precise, it's the new segmentation model the source of the changes. Just for information.

**Comment by lfoppiano** [comment]
This is corrected as of grobid 0.7.0
