### ISSUE TITLE
Build fails with JDK 14

### ISSUE THREAD

**Issue by hoangthaiduong** [kermitt2/grobid#579]
Grobid fails to build with JDK 14 on Windows 10 for me.
Per https://github.com/gradle/gradle/issues/10248#issuecomment-606786229 this is likely an issue with old versions of Gradle (< 6.3) being incompatible with JDK 14. Updating to Gradle 6.3 fixes the problem (although I have to now disable everything that has to do with jacocoRootReport in the build.gradle file).

**Comment by EvgeniyMish** [comment]
same issue here

**Comment by lfoppiano** [comment]
@hoangthaiduong, @EvgeniyMish  could you try using the branch 'feature/update_jdk_and_gradle`? 

you can move to the branch using: 

`git checkout feature/update_jdk_and_gradle`

and let me know if it works. 

I tested on Mac and it works with JDK 13 and 14. I did not test it on windows.

**Comment by stephantul** [comment]
Hey @lfoppiano , this solved the issue for me. Thanks!

**Comment by hoangthaiduong** [comment]
> @hoangthaiduong, @EvgeniyMish could you try using the branch 'feature/update_jdk_and_gradle`?
> 
> you can move to the branch using:
> 
> `git checkout feature/update_jdk_and_gradle`
> 
> and let me know if it works.
> 
> I tested on Mac and it works with JDK 13 and 14. I did not test it on windows.

It's working for me. Thank you!
