### ISSUE TITLE
After segmentation pdf file executes empty xml

### ISSUE THREAD

**Issue by MVytautas** [kermitt2/grobid#583]
On a virtual machine, after "createTraining" and receiving xml segmentation file into "output" directory I changed (fixed) and added correct xml tags as should be. Then edited segmentation xml files were uploaded into /grobid-training/resources/segmentation/corpus/tei/ directory .
After those steps: segmentation training was executed. 

Unfortunately, after segmentation training pdf file process empty XML .

Same procedure was executed on local machine and pdf file was submitted. As a result XML file was with content.

Could you please advise me on how to reset grobid on a virtual machine and at the same time do not lose training modules, because there was spent quite a lot of time on it.

Also, I am missing information about how to edit XML files after segmentation, what is the right way to do it.

**Comment by lfoppiano** [comment]
Dear @MVytautas, have you tried the pdf before training the segmentation model? Did it return anything? 

I guess adding just one corrected file, might not make any difference. To get us understanding, could you share the input PDF and the corrected segmentation xml? 

Just one thing, together with the segmentation.xml file there is also a file `.segmentation` which contains the feature tabular information. This should be copied into `segmentation/corpus/raw`.

**Comment by MVytautas** [comment]
@lfoppiano yes, I tried pdf before training and after training as well. There were significant differences and I am good with that, but as I said after manual tag changes of `pdf.training.segmentation.tei.xml` file after submit XML is empty. 
----
sure
input pdf file:
[Panevezio_balsas.pdf](https://github.com/kermitt2/grobid/files/4644968/Panevezio_balsas.pdf)

correct XML segmentation
[tei xml.zip](https://github.com/kermitt2/grobid/files/4644991/tei.xml.zip)

added tie XML file to zip folder, because it is not allowed to add XML here.

**Comment by lfoppiano** [comment]
> @lfoppiano yes, I tried pdf before training and after training as well. There were significant differences and I am good with that,

I'm not following, there were significant difference between? 

 but as I said after manual tag changes of `pdf.training.segmentation.tei.xml` file after submit XML is empty.

Walk me through the process because I'm lost here... 

You did 
a. process the pdf with the current version 
b. create the training data for the segmentation
c. correct the training data
d. copied the XML with the segmentation corrected files (what about the file `.segmentation`?)
e. train
f. process the pdf again and obtained an empty body? 

Is this correct? What about the file `.segmentation`? Did you add it as well as I've previously asked?

**Comment by MVytautas** [comment]
@lfoppiano described process is correct. And yes I copied pdf.training.segmentation file. 

.segmentation file:
[segmentation.zip](https://github.com/kermitt2/grobid/files/4648575/segmentation.zip)

**Comment by lfoppiano** [comment]
OK, I went back to your first comment and now I understand... I'm quoting and commenting your previous comments. 

> Unfortunately, after segmentation training pdf file process empty XML .

Just an empty XML, did you get any error? 

Could you log in to the virtual machine and check the log file, it should be into the directory `logs/grobid-service.log` 
 
> Could you please advise me on how to reset grobid on a virtual machine and at the same time do not lose training modules, because there was spent quite a lot of time on it.

the models are in `grobid-home/models/segmentation`, but we first need to understand what was not working in the virtual machine. 

> Also, I am missing information about how to edit XML files after segmentation, what is the right way to do it.

What do you mean with `edit XML files after segmentation`?

**Comment by MVytautas** [comment]
@lfoppiano yes just empty xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<TEI xml:space="preserve"
    xmlns="http://www.tei-c.org/ns/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.tei-c.org/ns/1.0 /opt/grobid/grobid-home/schemas/xsd/Grobid.xsd"
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <teiHeader xml:lang="lt">
        <fileDesc>
            <titleStmt>
                <title level="a" type="main"></title>
            </titleStmt>
            <publicationStmt>
                <publisher/>
                <availability status="unknown">
                    <licence/>
                </availability>
            </publicationStmt>
            <sourceDesc>
                <biblStruct>
                    <analytic></analytic>
                    <monogr>
                        <imprint>
                            <date/>
                        </imprint>
                    </monogr>
                </biblStruct>
            </sourceDesc>
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application version="0.6.0-SNAPSHOT" ident="GROBID-SDO" when="2020-05-15T15:17+0000">
                    <desc>GROBID - A machine learning software for extracting information from scholarly documents</desc>
                    <ref target="https://github.com/kermitt2/grobid-sdo"/>
                </application>
            </appInfo>
        </encodingDesc>
        <profileDesc>
            <abstract>
                <div
                    xmlns="http://www.tei-c.org/ns/1.0">
                    <p>Kaina 0,60 Eur www.panbalsas.lt Nr. 8 (15 843) 97-ieji leidimo metai PANEVĖŽIO KRAŠTO SAVAITRAŠTIS IŠEINA PIRMADIENIAIS 2020 m. vasario 24kovo 1 d.</p>
                </div>
            </abstract>
        </profileDesc>
    </teiHeader>
    <text xml:lang="lt">
        <body/>
        <back>
            <div type="annex">
                <div
                    xmlns="http://www.tei-c.org/ns/1.0" />
                </div>
                <div type="references">
                    <listBibl/>
                </div>
            </back>
        </text>
    </TEI>
```

> Could you log in to the virtual machine and check the log file, it should be into the directory logs/grobid-service.log

Sure:
[grobid-service.log](https://github.com/kermitt2/grobid/files/4651382/grobid-service.log)

> What do you mean with edit XML files after segmentation?

I mean to train pdf file to let grobid understand correctly where is start and where is end of article, as I understand it could be achieved by editing tags. 
I found this documentation, but it is not very clear or I don't understand
https://grobid.readthedocs.io/en/latest/training/General-principles/#correcting-pre-annotated-files

**Comment by lfoppiano** [comment]
> @lfoppiano yes just empty xml:

mmm, it seems the same result I obtain when I process only the header. Are you sure you are processing the full-text? If you are using the interface, could you try to use the "Process Fulltext" in the dropdown box?  (disable the consolidation that won't be necessary for this kind of pdf)

<img width="880" alt="image" src="https://user-images.githubusercontent.com/15426/82405741-498b0780-9a54-11ea-9087-fe786d229e7c.png">
 
> I mean to train pdf file to let grobid understand correctly where is start and where is end of article, as I understand it could be achieved by editing tags.
> I found this documentation, but it is not very clear or I don't understand
> https://grobid.readthedocs.io/en/latest/training/General-principles/#correcting-pre-annotated-files

The theory is simple: first you need to annotate training data for the segmentation model, then you train this model, then you need to re-generate the training data and check the fulltext, correct and train again. 

May I ask you, what is your final goal? Just extract text from newspaper pdfs or you want to structure them more? 

I'm asking because the current segmentation model and, generally most of the models that are used after in cascade, are trained on scientific articles. So depending on your goal, you might want to extend what's currently available or start from scratch using only documents that are the target for you.

**Comment by MVytautas** [comment]
@lfoppiano yes you were right

> Are you sure you are processing the full-text? If you are using the interface, could you try to use the "Process Fulltext" in the dropdown box?
I got "undefined"
![Screen Shot 2020-05-20 at 8 35 28 AM](https://user-images.githubusercontent.com/9050351/82408775-00977b00-9a75-11ea-9755-442afb8028d8.png)

> May I ask you, what is your final goal? Just extract text from newspaper pdfs or you want to structure them more?

Yes, basically extract text from articles. Read newspaper article header and body. Also if article consists of 2 or more pages - map them. 

> I'm asking because the current segmentation model and, generally most of the models that are used after in cascade, are trained on scientific articles. So depending on your goal, you might want to extend what's currently available or start from scratch using only documents that are the target for you.

That's what I am trying to achieve on my local machine, train only newspapers. Thats why I deleted grobid tei and raw files (default) from all modules and started from scratch. But as I said, seems I got same results as it was with existed files.

**Comment by lfoppiano** [comment]
> @lfoppiano yes you were right
> 
> > Are you sure you are processing the full-text? If you are using the interface, could you try to use the "Process Fulltext" in the dropdown box?
> > I got "undefined"
> > ![Screen Shot 2020-05-20 at 8 35 28 AM](https://user-images.githubusercontent.com/9050351/82408775-00977b00-9a75-11ea-9755-442afb8028d8.png)

OK let me first understand. You have this in the virtual machine or in the local one? 
Does it happens only when you select "process Fulltxt"? 

Can you send me the logs again, where this happens?

**Comment by MVytautas** [comment]
> OK let me first understand. You have this in the virtual machine or in the local one?

@lfoppiano this happens on a virtual machine (server), locally everything runs perfectly. 

> Does it happens only when you select "process Fulltxt"?
Strangely, but seems it happens from time to time, now when I selected "process Fulltext" I got empty XML: 

```
<?xml version="1.0" encoding="UTF-8"?>
<TEI xml:space="preserve"
    xmlns="http://www.tei-c.org/ns/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.tei-c.org/ns/1.0 /opt/grobid/grobid-home/schemas/xsd/Grobid.xsd"
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <teiHeader xml:lang="lt">
        <fileDesc>
            <titleStmt>
                <title level="a" type="main"></title>
            </titleStmt>
            <publicationStmt>
                <publisher/>
                <availability status="unknown">
                    <licence/>
                </availability>
            </publicationStmt>
            <sourceDesc>
                <biblStruct>
                    <analytic></analytic>
                    <monogr>
                        <imprint>
                            <date/>
                        </imprint>
                    </monogr>
                </biblStruct>
            </sourceDesc>
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application version="0.6.0-SNAPSHOT" ident="GROBID-SDO" when="2020-05-21T06:22+0000">
                    <desc>GROBID - A machine learning software for extracting information from scholarly documents</desc>
                    <ref target="https://github.com/kermitt2/grobid-sdo"/>
                </application>
            </appInfo>
        </encodingDesc>
        <profileDesc>
            <abstract>
                <div
                    xmlns="http://www.tei-c.org/ns/1.0">
                    <p>Kaina 0,60 Eur www.panbalsas.lt Nr. 8 (15 843) 97-ieji leidimo metai PANEVĖŽIO KRAŠTO SAVAITRAŠTIS IŠEINA PIRMADIENIAIS 2020 m. vasario 24kovo 1 d.</p>
                </div>
            </abstract>
        </profileDesc>
    </teiHeader>
    <text xml:lang="lt">
        <body/>
        <back>
            <div type="annex">
                <div
                    xmlns="http://www.tei-c.org/ns/1.0" />
                </div>
                <div type="references">
                    <listBibl/>
                </div>
            </back>
        </text>
    </TEI>
```

> Can you send me the logs again, where this happens?

[grobid-service.log](https://github.com/kermitt2/grobid/files/4660906/grobid-service.log)

**Comment by lfoppiano** [comment]
OK. So you obtain an empty output when you process the fulltext (in fact it's not an empty output, but the result of just the header) using the newly trained model. 

The main reason here (intuitively, because I don't' have access to your machine) is that you need to add more training data, at least 10-15 documents as a start. 

Meanwhile, could you send me the `model.wapiti` file from your `grobid-home/models/segmentation` on the machine where you ran the training? 

This page describes the approach to correct the segmentation files `https://grobid.readthedocs.io/en/latest/training/segmentation/` but, in your case you need to decide (and perhaps document) what each tag should identify as your news articles are structured differently from the scientific publications we are using as training data.

**Comment by MVytautas** [comment]
> The main reason here (intuitively, because I don't' have access to your machine) is that you need to add more training data, at least 10-15 documents as a start.

@lfoppiano you mean add more any documents? (default grobid docs)

> Meanwhile, could you send me the model.wapiti file from your grobid-home/models/segmentation on the machine where you ran the training?

[wapiti.zip](https://github.com/kermitt2/grobid/files/4671592/wapiti.zip)

> but, in your case you need to decide (and perhaps document) what each tag should identify as your news articles are structured differently from the scientific publications we are using as training data.

yes, that's what I am trying to achieve. What would you do in this case. What do you suggest how should be identified header and body of the paragraph? Maybe you can suggest the way to do it?

------
P.S empty content XML only appears for that particular news file, other pdf files extract with content.

**Comment by lfoppiano** [comment]
Dear @MVytautas sorry for the delay in responding. 

I've tested grobid using your model 
<img width="570" alt="Screenshot 2020-06-01 at 06 33 31" src="https://user-images.githubusercontent.com/15426/83363107-67c30280-a386-11ea-9601-2c96e8ddab71.png">


and your pdf and I've got the fulltext back. 
[Uploading Panevezio_balsas.pdf.tei(1).xml.zip…]()

Could you change the log level to DEBUG in `resources/config/config.yml`, try again and send it back? The current log doesn't show any information.
