### ISSUE TITLE
schema: Grobid.xsd

### ISSUE THREAD

**Issue by FengXuas** [kermitt2/grobid#586]
Is Grobid.xsd obsolete? I see that there is no <encodingDesc> in the Grobid.xsd file, but there is <encodingDesc> in the latest TEI file.

**Comment by kermitt2** [comment]
Hi @FengXuas 

Thank you for the issue, indeed I have forgotten to update the XML schema files for the latest release and the `<encodingDesc>` sub-hierarchy which have been recently added is missing in the schema.

**Comment by FengXuas** [comment]
Thank you for your reply. Is it possible to provide the latest Grobid.xsd

**Comment by kermitt2** [comment]
Sure, the XML schema zoo has been updated on master with commit d9767dab040132c37614405f60252494d7472196

Don't hesitate to tell me if you see any issues!
