### ISSUE TITLE
Doc: Additional warning needed for error: Unsupported class file major version 57

### ISSUE THREAD

**Issue by lucbouge** [kermitt2/grobid#593]
Dear Patrice,

I followed the documentation at URL [https://grobid.readthedocs.io/en/latest/Install-Grobid/#build-grobid-with-gradle](https://grobid.readthedocs.io/en/latest/Install-Grobid/#build-grobid-with-gradle) to build Brobid on may Mac (MacOs Mojave, 10.14.6).

The `./gradlew clean install` was rejected with a strange error message: `General error during semantic analysis: Unsupported class file major version 57`.

I took me some time to understand that it is originated in the Java version I am using.  The Grobid version you distribute at [](https://github.com/kermitt2/grobid/archive/0.6.0.zip) uses Gradle 5.4.1, which uses Java 11, whereas my Mac is running Java 13, installed through HomeBrew.
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Mac OS X 10.14.6 x86_64
```
The only solution I could find is to uninstall my HomeBrew version of Java. Hopefully, the native version of Java on MacOS 14 is still java 11. 
```
$ /usr/bin/java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
After that, it worked perfectly.
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.6 x86_64
```
An additional warning in the doc would probably help other colleagues.

Regards,

Luc.

**Comment by lucbouge** [comment]
PS: A minor error in the doc at  [](https://grobid.readthedocs.io/en/latest/Grobid-batch/).
```
The following command display some help for the batch commands:

> java -jar grobid-core/build/libs/grobid-core-<current version>.onejar.jar -h
```
The name of the file is `-onejar.jar`, not `.onejar.jar`

**Comment by lfoppiano** [comment]
@lucbouge could you try using the branch 'feature/update_jdk_and_gradle`? 

you can move to the branch using: 

`git checkout feature/update_jdk_and_gradle`

and let me know if it works. I tested on Mac and it works with JDK 13 and 14. (AdoptJDK)

BTW: I also noticed that your `gradle --version` return `oracle JDK`, which is weird.

**Comment by lucbouge** [comment]
Thanks Luca. I will try it tomorrow. 

I use Homebraw java, which is Open JDK. I do not know where the "Oracle" comes from. See the experiments below.

Regards, Luc.brew

```
$ brew info java
openjdk: stable 13.0.2+8 (bottled) [keg-only]
Development kit for the Java programming language
https://openjdk.java.net/
/usr/local/Cellar/openjdk/13.0.2+8_2 (631 files, 314.6MB)
  Poured from bottle on 2020-06-30 at 19:30:16
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openjdk.rb

$ which java
/usr/local/opt/openjdk/bin/java

$ java --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

However, gradlew --version return `Java 13.0.2 (Oracle Corporation 13.0.2+8)`.

I tried to look at the internals of gradlew. Here are the results. It seems that the "Oracle" comes from the execution of `org.gradle.wrapper.GradleWrapperMain`.

```
$ pwd -P
/Users/bouge/.../grobid

$ ./gradlew --version 
...
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)

$ java  -classpath /Users/bouge/Repositories/no_save/GIT/ANR/Knowledge_base/Segmentation/grobid/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain --version
...
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)

$ java  -classpath /Users/bouge/Repositories/no_save/GIT/ANR/Knowledge_base/Segmentation/grobid/gradle/wrapper/gradle-wrapper.jar  --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

```
