### ISSUE TITLE
SSL - https

### ISSUE THREAD

**Issue by dominic01** [kermitt2/grobid#594]
Just wondering how to install the SSL certificates to run Grobid service in https

**Comment by kermitt2** [comment]
Hi @dominic01, it's not really related to Grobid as you can imagine, but to dropwizard - the framework used by Grobid for the web service. There are quite a lot of resources on this online, you can have a look here ->
https://stackoverflow.com/questions/14988478/dropwizard-and-ssl
and/or search more stuff on "dropwizard" + "ssl".

**Comment by dominic01** [comment]
Thank you. This is nothing do with Grobid. Now every service requires https access. So, I was searching for a web server (https://grobid.readthedocs.io/en/latest/Grobid-service/) inside Grobid and I dont know where the config files are. I have not used dropwizard (or jetty) and let me dig further.

**Comment by lfoppiano** [comment]
I would recommend you to set up a reverse proxy (apache or nginx) in front and configure ssl / https over there: 

Just quick google I found these: 
- nginx: https://linuxtechlab.com/simple-guide-to-configure-nginx-reverse-proxy-with-ssl/ 
- apache: https://www.centosblog.com/configure-apache-https-reverse-proxy-centos-linux/

**Comment by kermitt2** [comment]
I would suggest to close this issue, because deploying the service in https is outside the scope of a specific service like Grobid. 

But I agree with Luca that the best would be certainly to use a reverse proxy with https configuration, this is more general and easy than configuring directly dropwizard.

**Comment by dominic01** [comment]
I dont want to start one more thread.
Now  wanted to do reverse proxy but my issues is little different. The grobid server has few other services running already and just wondering instead of running http://123.456.789.123:8070 something like `http://123.456.789.123:8070/grobid`
and the api like `http://123.456.789.123:8070/grobid/api`.

**Comment by kermitt2** [comment]
In a reverse proxy scenario with different services on a downstream server, you can just run the service on another port, see https://github.com/kermitt2/grobid/blob/master/grobid-service/config/config.yaml#L16

**Comment by dominic01** [comment]
Running Grobid in a different port is not an issue. But I am facing difficulties in separating Grobid request from other requests. Just checking if it is possible to run Grobid in a different route like http://123.456.789.123:8070/grobid
and the api like http://123.456.789.123:8070/grobid/api.

This way I can check the url location /grobid and pass the request to http://123.456.789.123:8070/grobid

**Comment by kermitt2** [comment]
Well, you can separate the grobid request based on the port number because there's only grobid running on that port, e.g.  http://123.456.789.123:8070/ is mapped to http://123.456.789.123/grobid
Then there is nothing to touch on Grobid itself. 
Are you using Apache server as reverse proxy ? 

Now if you want really to do like this, in the same config file:

```
server:
        applicationContextPath: "/grobid/*"
```

**Comment by dominic01** [comment]
This is working fine. If someone interested, this is my Nginx config. 

```
    server {
        listen       443 ssl http2 default_server;
        listen       [::]:443 ssl http2 default_server;
        server_name  myserver.com;
        root         /usr/share/nginx/html;

        ssl_certificate "/etc/ssl/bundle.crt";
        ssl_certificate_key "/etc/ssl/privatekeyrsa.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;

        ssl_protocols               TLSv1.2 TLSv1.3;
        ssl_ciphers                 SOMETHING SOMETHING
        ssl_prefer_server_ciphers   on;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location /grobid {
            proxy_read_timeout  90s;
            proxy_connect_timeout 300;
            proxy_send_timeout 300;
            send_timeout 300;
            client_max_body_size 100M;

            proxy_set_header   X-Forwarded-For $remote_addr;
            proxy_set_header   Host $http_host;
            proxy_pass http://111.222.333.444:8070/grobid;
        }

        error_page 404 /404.html;
			location = /404.html {
        }

        error_page 500 502 503 504 /50x.html;
			location = /50x.html {
        }
    }
}

```
