### ISSUE TITLE
Build failed: Java exit with non zero value

### ISSUE THREAD

**Issue by dominic01** [kermitt2/grobid#595]
I tried to build Grobid in a new AWS server (Linux 2/RedHat)

Downloaded `wget https://github.com/kermitt2/grobid/archive/0.6.0.zip`

```
[root@xx.xx.xx.xx grobid-0.5.6]# ./gradlew clean install

> Task :grobid-core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :grobid-trainer:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3m 3s
29 actionable tasks: 24 executed, 5 up-to-date
```
Now I run the service `./gradlew grobid-service:run` and I am able to see the web page. now I selected TEI/Process Affiliatio and "Biobest Belgium NV, Department of Research & Development, Westerlo, Belgium", Submit I got the following error

```
> Task :grobid-service:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':grobid-service:run'.
> Process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.amzn2.0.1.x86_64/bin/java'' finished with non-zero exit value 137

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 41s
6 actionable tasks: 1 executed, 5 up-to-date
```

I got the same error for 0.6.0 as well. Any pointers?
Attached --stacktrace output

[trace.txt](https://github.com/kermitt2/grobid/files/4809652/trace.txt)

**Comment by kermitt2** [comment]
Hello! could you give the error trace from the server log files (`grobid/logs/grobid-service.log`)? Thanks

**Comment by dominic01** [comment]
PFA 
[grobid-service-2020-06-21.log](https://github.com/kermitt2/grobid/files/4811272/grobid-service-2020-06-21.log)

Later I donwloaded the files using `git -clone --branch 0.6.0` and tried the same installation. It worked for sometime but crashde with the same error this morning. Attached the available one and some of the old logs were deleted.

**Comment by lfoppiano** [comment]
@dominic01 The current log doesn't show any information. 
Could you change the log level to DEBUG in resources/config/config.yml, try again and send it back?

**Comment by dominic01** [comment]
PFA Two logs files
1. grobid-service.log
[grobid-service.log](https://github.com/kermitt2/grobid/files/4818697/grobid-service.log)

2. grobid-service.log
[grobid_run.log](https://github.com/kermitt2/grobid/files/4818698/grobid_run.log)

Surprisingly it crashed during idle time in our test server.

Appreciae any help in this regard.

**Comment by lfoppiano** [comment]
sorry another question, could you give some details about the machine on amazon, youre running grobid on? 

Thanks

**Comment by dominic01** [comment]
```
[root@grobid]# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:            1
CPU MHz:             2299.933
BogoMIPS:            4600.13
Hypervisor vendor:   Xen
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            46080K
NUMA node0 CPU(s):   0,1
```

```
[root@grobid]# free
              total        used        free      shared  buff/cache   available
Mem:        4037592     1154204     2624932         836      258456     2669220
Swap:             0           0           0

```

**Comment by lfoppiano** [comment]
Is the ram 4Gb? `free -h` for humans would be easier for me ;-)

**Comment by dominic01** [comment]
It was 4GB and now I raised it to 8GB. Let me check.

**Comment by lfoppiano** [comment]
From the log, it seems that you just processed the citations, so 4Gb should be enough. 
At a first glance, it seems more a problem of the timeout, due to a somehow longer than expected response from the system. It's great to troubleshoot this on the AWS server so that we can somehow test it and hopefully solve this issue ;-)
