### ISSUE TITLE
The information of the <table> tag may be wrong in Grobid_doc.html

### ISSUE THREAD

**Issue by FengXuas** [kermitt2/grobid#598]
Hello, in the recently updated Grobid_doc.html and some schema information, it seems that there are still some problems in interpreting the information of \<table\>. For example, the field contained in the \<table\> tag is only ‘Character data only’, I guess it may be the old version of the \<table\> tag.

**Comment by kermitt2** [comment]
Thank you very much @FengXuas I've forgotten to update the `<table>` element of the ODD schema, so it was still expecting only text. I've pushed a fix with commit 162e83da4c845be314aa3b0fd2ac98fd93c135b5 and it should be correct now.
