### ISSUE TITLE
output without teiheader

### ISSUE THREAD

**Issue by Viswanath660** [kermitt2/grobid#604]
I am using grobid to process PDFs other than publications. Is it possible to get the output without teiheader and its contents? I just want grobid to find the headings, text, figures and tables in the PDF.

**Comment by kermitt2** [comment]
Hello @Viswanath660 
You need to apply the `fulltext` model directly to the input. 

You can do it with something like that:

```java
        Document doc = new Document(documentSource);
        doc.addTokenizedDocument(GrobidAnalysisConfig.defaultInstance());
        Pair<String, List<LayoutToken>> result = fullTextParser.processShortNew(doc.getTokenizations(),  doc);
```

The first component of the `result` object gives the labeling result, which can be serialized into TEI XML with the methods of class `TEIFormatter`.

**Comment by Viswanath660** [comment]
> Hello @Viswanath660
> You need to apply the `fulltext` model directly to the input.
> 
> You can do it with something like that:
> 
> ```java
>         Document doc = new Document(documentSource);
>         doc.addTokenizedDocument(GrobidAnalysisConfig.defaultInstance());
>         Pair<String, List<LayoutToken>> result = fullTextParser.processShortNew(doc.getTokenizations(),  doc);
> ```
> 
> The first component of the `result` object gives the labeling result, which can be serialized into TEI XML with the methods of class `TEIFormatter`.

Thanks @kermitt2 , I will try this.
