### ISSUE TITLE
Missing patent models in master?

### ISSUE THREAD

**Issue by zezke** [kermitt2/grobid#61]
Hi,

I am trying to set up some experiments using patents, but I get an error that the Model file grobidhome/models/patent/npl/model.wapiti does not exist. Could it be that some models were removed from the patent directory in the grobid-home directory?

Adding the model files from a different branch doesn't seem to work, I get complaints that grobidhome/models/patent/all/model.wapiti is in an invalid format.

**Comment by kermitt2** [comment]
Hi ! 

This model for NPL-only is not used anymore, there is only one model that extract both patent and NPL references (grobidhome/models/patent/all/model.wapiti). In the current master, this NPL model is normally not loaded at all, so if you have this error somewhere I have most likely forgotten to remove a reference in an obscure place.

Can you give me your error trace and some information on how you use the library (web service, batch, java lib)? The problem should be straightforward to fix. 

Thank you!

**Comment by zezke** [comment]
I am using the library as a Java lib. I recompiled the grobid-core and updated my local repository and that seemed to fix things. Seems like I got an outdated jar somewhere, might have been that I took the one from the example project.

Anyway: in short, it works. Thanks for the response!
