### ISSUE TITLE
Reference parsing, last page number incorrect for short version

### ISSUE THREAD

**Issue by de-code** [kermitt2/grobid#615]
Hi,

(I am not sure whether this has been raised before. I somehow thought I have seen something but couldn't find anything)

The calculated to page number appears to be incorrect for documents where the last or to page number of a page range is using a short version.

For example [10.1101/482968](https://doi.org/10.1101/482968):

> Stuart SN, Chanson JS, Cox NA, Young BE, Rodrigues ASL, Fischman DL, et al. Status and trends of amphibian declines and extinctions worldwide. Science (80-). 2004;306(5702):1783-6.

GROBID extracts `1789` as the to page number:

```xml
<biblScope unit="page" from="1783" to="1789"/>
```

That seems to be adding the `6` to the from page number. But what I think the page range is meaning is that the last or to page number is `1786` (i.e. last digit is `6`). Or generally the rule should probably be that it should replace the last digits of the first page, with the last page digits.

(of course that may become more complicated when character prefixes or suffixes are involved, #222)

**Comment by kermitt2** [comment]
Thanks @de-code, I think it's the same as #492 

Not easy because for some citation styles, the second number means the number of pages, which is why I've introduced this normalization. This style with digit replacement and not addition is American Medical Association if I am not wrong.

**Comment by de-code** [comment]
Okay, thank you for the quick response. Yes, that sounds very much like the issue I am describing.
