### ISSUE TITLE
Change http to https

### ISSUE THREAD

**Issue by sdf1444** [kermitt2/grobid#618]
Hi

I was wondering if you can change the address of demo server from a http one to a https one because my react nodejs app deployed on heroku does not accept the http server of grobid so this means I cannot make api calls in production mode on heroku. Also I have absolute no way of running my own instance of Grobid as it is beyond my capability to do this.

Thanks
Spencer

**Comment by kermitt2** [comment]
Hello, sorry please do not use the demo grobid server for your production work. As it is indicated in the readme, it is not intended and scaled for that, thanks.

**Comment by sdf1444** [comment]
Ok but I have no idea how to use it in production.

**Comment by sdf1444** [comment]
Ok But I have no idea how to use this in production.

Regards

________________________________
