### ISSUE TITLE
[PDFTOXML_CONVERSION_FAILURE] PDF to XML conversion failed on pdf

### ISSUE THREAD

**Issue by lpanichi** [kermitt2/grobid#619]
I wanted to test grobid out of the box in a java project and tried it on a couple of pdf. So far I only got `[PDFTOXML_CONVERSION_FAILURE] PDF to XML conversion failed on pdf `.

My two pdfs are [here](https://www.researchgate.net/publication/265487498_Machine_Learning_for_Document_Structure_Recognition) and [here](https://www.cscjournals.org/manuscript/Journals/IJIP/Volume11/Issue2/IJIP-1114.pdf).

What I did :
1) git clone of the projet to copy quickly the grobid-home
2) add to my pom.xml :
```
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>bintray-rookies-maven</id>
      <name>bintray</name>
      <url>https://dl.bintray.com/rookies/maven</url>
    </repository>

    <dependency>
      <groupId>org.grobid</groupId>
      <artifactId>grobid-core</artifactId>
      <version>0.6.0</version>
    </dependency>
```
3) Some java code
```
    public void analyseDocument(String id){
        try {
            String grobidHome = "/home/Codes/grobid/grobid-home";
            Path docToAnalyze = filesystemStorage.getDocumentsTemp().resolve(id);
            GrobidHomeFinder grobidHomeFinder = new GrobidHomeFinder(Arrays.asList(grobidHome));
            GrobidProperties.getInstance(grobidHomeFinder);
            System.out.println(">>>>>>>> GROBID_HOME=" + GrobidProperties.get_GROBID_HOME_PATH());
            Engine engine = GrobidFactory.getInstance().createEngine();

            // Header
            BiblioItem resHeader = new BiblioItem();
            String tei = engine.processHeader(docToAnalyze.toString(), 0, resHeader);
            String bt = resHeader.toBibTeX();
            System.out.print("tei  : ");
            System.out.println(tei);
            System.out.print("bt  : ");
            System.out.println(bt);
            // References
            List<BibDataSet> citations = engine.processReferences(docToAnalyze.toFile(), 0);
            for (BibDataSet bib : citations) {
                if (bib.getResBib() != null){
                    String ref = bib.getResBib().toBibTeX();
                    System.out.print("ref  : ");
                    System.out.println(ref);
                }
            }

        } 
        catch (Exception e) {
            e.printStackTrace();
        } 
    }
```

Error in console :
```
  >>>>>>>> GROBID_HOME=/home/Codes/grobid/grobid-home
org.grobid.core.exceptions.GrobidException: [PDFTOXML_CONVERSION_FAILURE] PDF to XML conversion failed on pdf file /home/Filesystems/temp/d76604ea-29e3-4f57-bb39-f2ac5fd37b92
        at org.grobid.core.document.DocumentSource.processPdfToXmlThreadMode(DocumentSource.java:208)
        at org.grobid.core.document.DocumentSource.pdf2xml(DocumentSource.java:154)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:63)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:49)
        at org.grobid.core.engines.HeaderParser.processing(HeaderParser.java:78)
        at org.grobid.core.engines.Engine.processHeader(Engine.java:390)
        at org.grobid.core.engines.Engine.processHeader(Engine.java:374)
     ...
```

Did I miss something ? I'm a little confused by the configuration options (I juste started my journey), maybe I should somehow configure it to use pdfalto instead of pdftoxml ?

**Comment by kermitt2** [comment]
Hello, sorry for that, we are in the process of creating a new release (I try to do it this night) and the current grobid-home is not compatible anymore with grobid 0.6.0 (change of `pdfalto` arguments, which is doing the PDF to XML conversion). 

You can either use the current master grobid 0.6.1-SNAPSHOT (`./gradlew clean install` will install the jar in your .m2/repo) or checkout the repo version 0.6.0 with the following command:

> git clone -b 0.6.0 https://github.com/kermitt2/grobid 

to get an older grobid-home
or even simpler if you have already clone the stuff:

> git checkout 0.6.0

and you will make available the old grobid-home

**Comment by lpanichi** [comment]
Hi, a big thank you for your quick reply.
A checkout on 0.6.0 did the trick and the error is gone, it's good enough for my purpose right now.
And thanks for this tool, it seems pretty amazing !

**Comment by kermitt2** [comment]
Thank you ! In 1 or 2 days, version 0.6.1 will be ready :)
it introduces quite a lot of improvement.
