### ISSUE TITLE
Docx support

### ISSUE THREAD

**Issue by navraj28** [kermitt2/grobid#631]
Dear Sir,
    I see that you already have a branch (docx-support), for handling Word documents. Can you please merge this onto Master branch, as a lot of our documents are in the Word format?
Thanks & Regards,
Naveen

**Comment by kermitt2** [comment]
Hello! Thanks for the interest in that feature.
The branch is not ready, the error rate of the docx parsing with apache POI is too high I think. I need to experiment with alternative or explore some patch.

**Comment by kermitt2** [comment]
As it is redundant with #313 and PR #515 , I am closing the issue thanks.

**Comment by ayhama16** [comment]
Hi, any news about "Docx support"? Thanks!
