### ISSUE TITLE
Error case for the segmentation model 

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#632]
I have this PDF (https://www.nature.com/articles/s41598-020-58065-9.pdf) and I notice some issue in processing it. 

It seems that everything goes in the body section from the segmentation parser: 
[segmentation.txt](https://github.com/kermitt2/grobid/files/5154961/segmentation.txt)

This is the output from pdfalto: 
[3SHt4RC7GX.xml.txt](https://github.com/kermitt2/grobid/files/5154978/3SHt4RC7GX.xml.txt)

I also noticed that this pdf contains a lot of characters that are not encoded correctly, maybe can be used as a test case for pdfalto?

**Comment by kermitt2** [comment]
It looks like it only concerns the header zone recognition, the rest of the segmentation labels are more or less good. But as it's the header, it is very visible of course. Normally Nature open access publication are CC-BY so we could add some training data and fix the error case like that. At some point, the segmentation will need again some work with better features, it works very badly when special characters/equations are around, but we need more training data available to make a meaningful job on this.

**Comment by lfoppiano** [comment]
This was implemented in #951
