### ISSUE TITLE
Does the addition of an email address for CrossRef consolidation require to rebuild the Docker container?

### ISSUE THREAD

**Issue by davidefiocco** [kermitt2/grobid#634]
I am using GROBID on Docker https://grobid.readthedocs.io/en/latest/Grobid-docker/ and thought to use CrossRef consolidation, doing that in the "polite" way, thus specifying a value for the `mailto` value in `grobid-home/config/grobid.properties` (which is a very trivial change).

To do so, do I need to rebuild a custom Docker image, or do I have the option to pass the email address to be used in the CrossRef calls to the container pulled from the public image on Docker Hub e.g. with an option in

    docker run -t --rm --init -p 8080:8070 -p 8081:8071 lfoppiano/grobid:${latest_grobid_version}

?

**Comment by lfoppiano** [comment]
Hi @davidefiocco, 
 in theory you can use the environment variables as explained here: https://github.com/kermitt2/grobid/pull/482 

to overwrite the property you want in the `grobid.properties`. 

```
export ORG__GROBID__CROSSREF__MAILTO=youremail
```

should do the trick.

**Comment by davidefiocco** [comment]
OK @lfoppiano , I will try! By that reasoning, would 

    docker run -t --rm --init -p 8080:8070 -p 8081:8071 --env ORG__GROBID__CROSSREF__MAILTO='myemail' lfoppiano/grobid:${latest_grobid_version}

also do? That would be super handy also considering https://github.com/kermitt2/grobid/issues/628

**Comment by lfoppiano** [comment]
Yes. As mentioned in the documentation https://grobid.readthedocs.io/en/latest/Grobid-docker/#configuration-using-environment-variables
