### ISSUE TITLE
No improvement in extraction of Grobid

### ISSUE THREAD

**Issue by ajinkya2903** [kermitt2/grobid#639]
Hey, We were facing a issue of missing contents in the extraction of the contents. So for this we corrected xml files of the pdfs in which there were issues of missing part and retrained segmentation model. But unfortunately even after retraining there isn't any improvement in the extraction, it is still missing some part of pdfs in extraction. I don't know what is the cause, so please can you suggest me any solution for this. Thank You

**Comment by kermitt2** [comment]
Hi @ajinkya2903 ! Could you give more details and sample data so that we can understand and reproduce the problem, thanks !
