### ISSUE TITLE
Troubleshooting DeLFT with GROBID (logs provided)

### ISSUE THREAD

**Issue by andrei-volkau** [kermitt2/grobid#643]
I would like to use DeLFT with GROBID.[ I followed instructions regarding Integration with DeLFT, but something is wrong. ](https://grobid.readthedocs.io/en/latest/Deep-Learning-models/)

<img width="1440" alt="dsd" src="https://user-images.githubusercontent.com/12778567/94348177-bdf93700-0042-11eb-91af-c266fe31cc1c.png">

**Let me provide logs.**
[grobid-service.log](https://github.com/kermitt2/grobid/files/5287181/grobid-service.log)

**Let me provide some info about my environment.**

I am using Python3.6. All of the dependencies from requremnts.txt are successfully installed as a part of the virtual environment. The virtual environment was activated before running `./gradlew run` I am using 0.6.1 version of GROBID. 

The value of JAVA_HOME variable is `/usr/lib/jvm/java-8-openjdk-amd64/ `

I am using Ubuntu 16.04 (AWS EC2 instance). 

**Let me provide a screenshot of**  `grobid.properties`
I provided the correct path for DeLFT 

<img width="1440" alt="Screen Shot 2020-09-26 at 21 36 30" src="https://user-images.githubusercontent.com/12778567/94348217-26e0af00-0043-11eb-91de-1a2f89fb7cb3.png">

I believe that the issue might be related to JEP. I am struggling to understand whether it is possible to fix something or not.

**Comment by kermitt2** [comment]
Hello @andrei-volkau 

You could try to indicate in the property file the path to your virtual environment associated to DeLFT, for example:

```
grobid.delft.python.virtualEnv=/home/lopez/delft/env/
```

If it's still not working, I think the solution is to re-build JEP on your system. I had to do this when deploying GROBID+DeLFT on a cloud service (but not AWS). 

```shell
git clone https://github.com/ninia/jep

python3 setup.py build

cp build/lib.linux-x86-64-3.6/jep/jep.cpython-35m-x86_64-linux-gnu.so ~/grobid/grobid-home/lib/lin-64/libjep.so
```

(the exact path to the .so build might change with the version of python and your linux env.)

and I think that's it if I remember well. At some point in the future, when I will find the time, I will try to improve the support/integration of DeLFT+Jep to have something working more out-of-the-box and an improved Docker for DeLFT support.

**Comment by kermitt2** [comment]
Ah I've just seen this:

https://github.com/ninia/jep/issues/208#issuecomment-545986352

So one thing to try before rebuidling is to update the file `grobid/build.gradle`, line 248

```
        implementation 'black.ninia:jep:3.8.2'
```

by

```
        implementation 'black.ninia:jep:3.9.0'
```

**Comment by andrei-volkau** [comment]
Hi @kermitt2! Thank you very much for your reply!

> You could try to indicate in the property file the path to your virtual environment associated to DeLFT, for example:
> 
> ```ini
> grobid.delft.python.virtualEnv=/home/lopez/delft/env/
> ```

I was able to try that previously. No luck. I will work on the rest of your ideas tomorrow. Let's see what will happen. Thank you!

**Comment by lfoppiano** [comment]
As an addition, before rebuilding jep, can you try the following: first activate the environment, and then run grobid? 
As far as I remember this was working.

**Comment by andrei-volkau** [comment]
Hi @kermitt2! 

I did everything from scratch to check everything in the most reliable way.

**Step 1.** Download grobid
`wget https://github.com/kermitt2/grobid/archive/0.6.1.zip`
`unzip 0.6.1.zip`

**Step 2** Install delft  
`git clone https://github.com/kermitt2/delft`
`cd delft`
`virtualenv --system-site-packages -p python3 env`
`source env/bin/activate`
`pip3 install -r requirements.txt`

**Step 3**  Edit `grobid-properties` as shown below
<img width="1440" alt="Screen Shot 2020-09-27 at 10 52 17" src="https://user-images.githubusercontent.com/12778567/94359378-93919300-00af-11eb-94df-96c23b328646.png">

**Step 4** update the file `grobid/build.gradle`, line 248

<img width="1440" alt="Screen Shot 2020-09-27 at 10 29 39" src="https://user-images.githubusercontent.com/12778567/94358836-68597480-00ac-11eb-953a-4dc8ffe3e347.png">

**Step 5** 

`cp build/lib.linux-x86_64-3.6/jep/jep.cpython-36m-x86_64-linux-gnu.so ~/grobid-0.6.1/grobid-home/lib/lin-64/libjep.so`

<img width="1440" alt="Screen Shot 2020-09-27 at 10 55 01" src="https://user-images.githubusercontent.com/12778567/94359446-f420d000-00af-11eb-85de-08a8833cace7.png">

**Step 6** Run `./gradlew clean install`

<img width="1440" alt="Screen Shot 2020-09-27 at 10 57 52" src="https://user-images.githubusercontent.com/12778567/94359514-58439400-00b0-11eb-8629-a9857eeb589b.png">

**Step 7** Run `./gradlew run` and check using a file

<img width="1440" alt="Screen Shot 2020-09-27 at 11 10 33" src="https://user-images.githubusercontent.com/12778567/94359855-1d426000-00b2-11eb-82da-b2e908a4be8e.png">

Unfortunately, the problem is not resolved. I am sending the logs.
[grobid-service.log](https://github.com/kermitt2/grobid/files/5287909/grobid-service.log)


**One note**
Please take a look at the following screenshot. I am using `env` with installed dependencies for delft. I am able to see the following error while trying to import jep using python. Does jep need to be imported without such an error?

<img width="1440" alt="Screen Shot 2020-09-27 at 11 12 46" src="https://user-images.githubusercontent.com/12778567/94359890-65fa1900-00b2-11eb-82e7-2b80aaaee14a.png">

**Comment by kermitt2** [comment]
Awww can you try then simply under your virtual env.:

> pip3 install jep

and test again ?

I think it is missing from DeLFT `requirement.txt`

**Comment by andrei-volkau** [comment]
@kermitt2 thank you for spotting the missing jep requrement. I successfully installed jep. 
<img width="1440" alt="Screen Shot 2020-09-27 at 19 21 56" src="https://user-images.githubusercontent.com/12778567/94370637-d37d6800-00f9-11eb-9408-7d531d91c4b9.png">

I have another kind of issue now.  

<img width="1440" alt="Screen Shot 2020-09-27 at 19 43 02" src="https://user-images.githubusercontent.com/12778567/94370706-32db7800-00fa-11eb-93f0-2359f4acedb8.png">
<img width="1440" alt="Screen Shot 2020-09-27 at 19 43 19" src="https://user-images.githubusercontent.com/12778567/94370737-51da0a00-00fa-11eb-965c-0a32dbde98d7.png">
[grobid-service.log](https://github.com/kermitt2/grobid/files/5288687/grobid-service.log)

Maybe something is wrong with my Java?

I was exporting JAVA_HOME using the following statement. It was necessary while installing jep.
`export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/`

I have the following items inside of `/usr/lib/jvm` directory.
<img width="1440" alt="Screen Shot 2020-09-27 at 19 54 40" src="https://user-images.githubusercontent.com/12778567/94370892-505d1180-00fb-11eb-978c-1b260c3e2840.png">

**Comment by kermitt2** [comment]
@andrei-volkau Since I had similar problems/errors to make JEP working after updating it to its new version, I added some step-by-step instructions:

https://grobid.readthedocs.io/en/latest/Deep-Learning-models/#classic-python-and-virtualenv

I've updated and re-installed GROBID with DL models on 3 different servers in-between and that worked well following these steps.

**Comment by andrei-volkau** [comment]
@kermitt2 I confirm that I was able to successfully run GROBID with DeLFT while following the step-by-step instructions. I am closing the issue because of that. Thank you!
