### ISSUE TITLE
DeLFT: packages are not available from conda channels

### ISSUE THREAD

**Issue by andrei-volkau** [kermitt2/grobid#644]
I have a question regarding creating a conda env in case DeLFT. [The documentation ](https://grobid.readthedocs.io/en/latest/Deep-Learning-models/) provides the following command. 

`conda create --name grobidDelft --file requirements.conda.delft.cpu.txt`
So we have the following error. 
<img width="1440" alt="Screen Shot 2020-09-29 at 22 32 42" src="https://user-images.githubusercontent.com/12778567/94607500-a9b47480-02a4-11eb-842a-0cfd3c26e051.png">

It looks like those packages are not really available through any conda channels. It looks like such packages need to be installed using pip while having env activated. Am I right?

@lfoppiano I would appreciate your thought regarding the problem if possible. Thank you in advance for the info!

**Comment by lfoppiano** [comment]
Dear @andrei-volkau my bad, this requirement files is old and I've stopped using it some time ago, but I forgot to update the documentation. 

The best solution so far I found is the following: 
1. create a conda environment
   `conda create --name delft_grobid pip` should install pip within the environment... 

2. make sure you are using the pip inside the environment (sometimes conda uses the root pip and mess up with your system): 
`which pip` should return a path within your environment

3. import the delft packages using pip

**Comment by andrei-volkau** [comment]
Hi @lfoppiano ! Thank you for the comments!



> * create a conda environment
>   `conda create --name delft_grobid pip` should install pip within the environment...

Yeah, I created the conda env. 



> * make sure you are using the pip inside the environment (sometimes conda uses the root pip and mess up with your system):
>   `which pip` should return a path within your environment

Yeah, I checked that. Thank you. I am using pip inside the conda environment.


> 3\. import the delft packages using pip

I installed packages from [requirements.txt](https://github.com/kermitt2/delft/blob/master/requirements.txt) I installed jep also since jep is missing there. 

I have a kind of failure you was facing[ in this thread](https://github.com/kermitt2/grobid/pull/454).

<img width="1440" alt="Screen Shot 2020-09-30 at 21 33 40" src="https://user-images.githubusercontent.com/12778567/94734213-96bba600-0371-11eb-806e-9d6b35136046.png">

It looks like such a kind of failure should be solved while doing the following stuff 

`conda install libgcc`
`export LD_PRELOAD=/home/ubuntu/anaconda3/lib/libstdc++.so.6.0.25`

I did that. No luck.

I am using Ubuntu 16.04 (AWS EC2 instance). I am using Python3.6. All of the dependencies from requremnts.txt are successfully installed as a part of the conda virtual environment. The virtual environment was activated before running ./gradlew run I am using 0.6.1 version of GROBID.

[grobid-service.log](https://github.com/kermitt2/grobid/files/5308034/grobid-service.log)


I was using a regular python virtual environment as well[ in this issue](https://github.com/kermitt2/grobid/issues/643). I faced the same error as shown on the screenshot. 


I am sure that you was able to run GROBID+DELFT on Linux somehow. Could try to formulate some ideas regarding approaching the issue?

**Comment by lfoppiano** [comment]
Dear @andrei-volkau the sigterm there is frigthening but just a consequence of some previous error. 

In the grobid-service.log I see: 

```
ERROR [2020-09-30 19:17:20,041] org.grobid.core.jni.JEPThreadPool: JEP initialization failed
! jep.JepException: <class 'ImportError'>: Traceback (most recent call last):
!   File "/home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
!     from tensorflow.python.pywrap_tensorflow_internal import *
!   File "/home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
!     _pywrap_tensorflow_internal = swig_import_helper()
!   File "/home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
!     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
!   File "/home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/imp.py", line 243, in load_module
!     return load_dynamic(name, filename, file)
!   File "/home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/imp.py", line 343, in load_dynamic
!     return _load(spec)
! ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
! 
! 
! Failed to load the native TensorFlow runtime.
! 
! See https://www.tensorflow.org/install/errors
! 
! for some common reasons and solutions.  Include the entire stack trace
! above this error message when asking for help.
! at /home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.<module>(pywrap_tensorflow.py:74)
! at /home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/tensorflow/python/__init__.<module>(__init__.py:49)
! at /home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/tensorflow/__init__.<module>(__init__.py:24)
! at /home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/keras/backend/tensorflow_backend.<module>(tensorflow_backend.py:5)
! at /home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/keras/backend/__init__.<module>(__init__.py:89)
! at /home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/keras/utils/conv_utils.<module>(conv_utils.py:9)
! at /home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/keras/utils/__init__.<module>(__init__.py:6)
! at /home/ubuntu/anaconda3/envs/delft_grobid361/lib/python3.6/site-packages/keras/__init__.<module>(__init__.py:3)
! at <string>.<module>(<string>:1)
! at jep.Jep.eval(Native Method)
! at jep.Jep.eval(Jep.java:451)
! at org.grobid.core.jni.JEPThreadPool.initializeJepInstance(JEPThreadPool.java:87)
! at org.grobid.core.jni.JEPThreadPool.createJEPInstance(JEPThreadPool.java:107)
! at org.grobid.core.jni.JEPThreadPool.getJEPInstance(JEPThreadPool.java:137)
! at org.grobid.core.jni.DeLFTModel$InitModel.run(DeLFTModel.java:53)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
```

AFAIK the problem is coming from tensorlfow: 

```
from tensorflow.python.pywrap_tensorflow_internal import *
```
and in particular 

```
! ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```
Something is wrong with your tensorflow initialisation. Can you run delft wihtout problems, using the same environment? 

For example could you run `python3 grobidTagger.py date tag` or `python3 grobidTagger.py date train_eval`? The first will ran faster.

**Comment by andrei-volkau** [comment]
Hi @lfoppiano!

> Something is wrong with your tensorflow initialisation.


Yes, I was using `requirements.txt` in the case of EC2 t2.medium instance. Such an instance is obviously don't have GPU. So [`requirements.txt`](https://github.com/kermitt2/delft/blob/master/requirements.txt) was not the right choice because of `tensorflow_gpu `. Really sorry, that was my silly mistake. I am using 
[`requirements.test.txt`](https://github.com/kermitt2/delft/blob/master/requirements.test.txt) now. 

I am sending a screenshot containing the output of `python3 grobidTagger.py date tag`. So that works since I installed [`requirements.test.txt`](https://github.com/kermitt2/delft/blob/master/requirements.test.txt).


<img width="1440" alt="Screen Shot 2020-10-02 at 20 01 30" src="https://user-images.githubusercontent.com/12778567/94952046-f6d75700-04ed-11eb-85c3-adf63baf0265.png">

Unfortunately, I still experience an error.

<img width="1440" alt="Screen Shot 2020-10-02 at 20 28 35" src="https://user-images.githubusercontent.com/12778567/94952602-e673ac00-04ee-11eb-8163-9a91765c61ce.png">

[grobid-service.log](https://github.com/kermitt2/grobid/files/5319480/grobid-service.log)

Could you try to look into logs, please?

**Comment by andrei-volkau** [comment]
@lfoppiano Let me provide information regarding the steps I used to set up everything.

**Step 1.** Download grobid
`wget https://github.com/kermitt2/grobid/archive/0.6.1.zip`
`unzip 0.6.1.zip`

**Step 2.** Create conda env
`conda create -n py36 python=3.6 --name delft_grobid363`
`pip3 install -r requirements.test.txt`
`pip3 install jep`

**Step 3** Change config file as shown below

<img width="1440" alt="Screen Shot 2020-10-02 at 20 44 23" src="https://user-images.githubusercontent.com/12778567/94953352-140d2500-04f0-11eb-8002-d3a0b3296a74.png">

@kermitt2 was able to suggest [the following points](https://github.com/kermitt2/grobid/issues/643). I was able to try them also. No luck.

<img width="906" alt="Screen Shot 2020-10-02 at 21 54 16 1" src="https://user-images.githubusercontent.com/12778567/94959446-df05d000-04f9-11eb-870f-4a814411b796.png">

I am using Python3.6.  The virtual environment was activated before running `./gradlew run`. I am using 0.6.1 version of GROBID.

The value of JAVA_HOME variable is `/usr/lib/jvm/java-8-openjdk-amd64/`

I am using Ubuntu 16.04 (AWS EC2 instance). t2 medium instance (4GB RAM, 2 vCPUs)

**Comment by lfoppiano** [comment]
Dear @andrei-volkau,
    somehow we are progressing forward. Although this seems your initial error 😅 

I think now it's just a matter of using jep 3.9.0 as the error you see seems related to that. 

could you send the result of `conda list | grep jep` and the line of  the jep dependencies in the build.gradle? 

Regards
Luca

**Comment by lfoppiano** [comment]
I'm sending you the parameters of my environment. I configured tensorflow to work with CPU: 

See my pip environment: 

```
(tensorflowC) [Luca@falcon grobidl]$ pip list
Package                          Version   
-------------------------------- ----------
absl-py                          0.7.1     
asn1crypto                       1.3.0     
astor                            0.7.1     
boto                             2.49.0    
boto3                            1.11.0    
botocore                         1.14.0    
bz2file                          0.98      
certifi                          2019.11.28
cffi                             1.13.2    
chardet                          3.0.4     
cryptography                     2.8       
docutils                         0.15.2    
gast                             0.2.2     
gensim                           3.8.0     
google-pasta                     0.1.7     
grpcio                           1.16.1    
h5py                             2.9.0     
idna                             2.8       
jep                              3.8.2     
jmespath                         0.9.4     
joblib                           0.13.2    
Keras                            2.2.4     
Keras-Applications               1.0.8     
keras-bert                       0.70.1    
keras-embed-sim                  0.7.0     
keras-layer-normalization        0.12.0    
keras-multi-head                 0.20.0    
keras-pos-embd                   0.11.0    
keras-position-wise-feed-forward 0.6.0     
Keras-Preprocessing              1.1.0     
keras-self-attention             0.41.0    
keras-transformer                0.29.0    
langdetect                       1.0.7     
lmdb                             0.94      
Markdown                         3.1.1     
mkl-fft                          1.0.12    
mkl-random                       1.0.2     
mock                             3.0.5     
nltk                             3.4.4     
numpy                            1.16.4    
pandas                           0.25.3    
pip                              19.1.1    
protobuf                         3.8.0     
pycparser                        2.19      
pyOpenSSL                        19.1.0    
PySocks                          1.7.1     
python-dateutil                  2.8.1     
pytz                             2019.3    
PyYAML                           5.1.1     
regex                            2019.6.5  
requests                         2.22.0    
s3transfer                       0.3.0     
scikit-learn                     0.21.2    
scipy                            1.2.1     
setuptools                       41.0.1    
six                              1.12.0    
sklearn                          0.0       
smart-open                       1.9.0     
tensorboard                      1.12.2    
tensorflow                       1.12.0    
tensorflow-estimator             1.13.0    
termcolor                        1.1.0     
textblob                         0.15.3    
tqdm                             4.32.1    
urllib3                          1.25.7    
Werkzeug                         0.15.4    
wheel                            0.33.4    
wrapt                            1.11.2
```

here the conda list (In this environment I've installed most of the packages with conda): 

```
(tensorflowC) [Luca@falcon grobidl]$ conda list
# packages in environment at /home/Luca/.conda/envs/tensorflowC:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.3.0                       mkl  
absl-py                   0.7.1                    py36_0  
asn1crypto                1.3.0                    py36_0  
astor                     0.7.1                    py36_0  
blas                      1.0                         mkl  
boto                      2.49.0                   py36_0  
boto3                     1.11.0                     py_0  
botocore                  1.14.0                     py_0  
bz2file                   0.98                     py36_1  
c-ares                    1.15.0               h7b6447c_1  
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.13.2           py36h2e261b9_0  
chardet                   3.0.4                 py36_1003  
cryptography              2.8              py36h1ba5d50_0  
docutils                  0.15.2                   py36_0  
gast                      0.2.2                    py36_0  
gensim                    3.8.0            py36h962f231_0  
google-pasta              0.1.7                      py_0  
grpcio                    1.16.1           py36hf8bcb03_1  
h5py                      2.9.0            py36h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
idna                      2.8                      py36_0  
intel-openmp              2019.4                      243  
jep                       3.8.2                    pypi_0    pypi
jmespath                  0.9.4                      py_0  
joblib                    0.13.2                   pypi_0    pypi
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-bert                0.70.1                   pypi_0    pypi
keras-embed-sim           0.7.0                    pypi_0    pypi
keras-layer-normalization 0.12.0                   pypi_0    pypi
keras-multi-head          0.20.0                   pypi_0    pypi
keras-pos-embd            0.11.0                   pypi_0    pypi
keras-position-wise-feed-forward 0.6.0                    pypi_0    pypi
keras-preprocessing       1.1.0                      py_1  
keras-self-attention      0.41.0                   pypi_0    pypi
keras-transformer         0.29.0                   pypi_0    pypi
langdetect                1.0.7                      py_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libprotobuf               3.8.0                hd408876_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markdown                  3.1.1                    py36_0  
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
mock                      3.0.5                    py36_0  
ncurses                   6.1                  he6710b0_1  
nltk                      3.4.4                      py_0    conda-forge
numpy                     1.16.4           py36h7e9f1db_0  
numpy-base                1.16.4           py36hde5b4d6_0  
openssl                   1.1.1d               h516909a_0    conda-forge
pandas                    0.25.3           py36he6710b0_0  
pip                       19.1.1                   py36_0  
protobuf                  3.8.0            py36he6710b0_0  
pycparser                 2.19                       py_0  
pyopenssl                 19.1.0                   py36_0  
pysocks                   1.7.1                    py36_0  
python                    3.6.8                h0371630_0  
python-dateutil           2.8.1                      py_0  
python-lmdb               0.94             py36h14c3975_0  
pytz                      2019.3                     py_0  
pyyaml                    5.1.1            py36h7b6447c_0  
readline                  7.0                  h7b6447c_5  
regex                     2019.06.05       py36h7b6447c_0  
requests                  2.22.0                   py36_1  
s3transfer                0.3.0                    py36_0  
scikit-learn              0.21.2                   pypi_0    pypi
scipy                     1.2.1            py36h7c811a0_0  
setuptools                41.0.1                   py36_0  
six                       1.12.0                   py36_0  
sklearn                   0.0                      pypi_0    pypi
smart_open                1.9.0                      py_0  
sqlite                    3.29.0               h7b6447c_0  
tensorboard               1.12.2           py36he6710b0_0  
tensorflow                1.12.0          mkl_py36h69b6ba0_0  
tensorflow-base           1.12.0          mkl_py36h3c3e929_0  
tensorflow-estimator      1.13.0                     py_0  
termcolor                 1.1.0                    py36_1  
textblob                  0.15.3                     py_0    conda-forge
tk                        8.6.8                hbc83047_0  
tqdm                      4.32.1                     py_0  
urllib3                   1.25.7                   py36_0  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py36_0  
wrapt                     1.11.2           py36h7b6447c_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  
```


My jep version is the old one: 
```
(tensorflowC) [Luca@falcon grobidl]$ cat build.gradle | grep jep
        implementation 'black.ninia:jep:3.8.2'
```
```
(tensorflowC) [Luca@falcon grobidl]$ pip list | grep jep
jep                              3.8.2  
```

Let me know if you need more information, but in your case you should maybe try downgrade the jep version on your python environment.

**Comment by lfoppiano** [comment]
With the latest delft version (which I haven't updated) you should install 'truecase' as well, if I'm not mistaken.

**Comment by andrei-volkau** [comment]
Hi @lfoppiano!

Thank you very much for the lists of packages! Let me please take my time to carefully install the packages needed. I hope to come back on weekends. 

I will try to use jep 3.8.2. Thank you.

**Comment by andrei-volkau** [comment]
Hi @lfoppiano!

> With the latest delft version (which I haven't updated) you should install 'truecase' as well, if I'm not mistaken.

Yes, that is mentioned in [requirements.test.txt](https://github.com/kermitt2/delft/blob/master/requirements.test.txt). I am using the requirements.test.txt. So  'truecase'  was installed.
_________

I did all of the stuff from the very beginning. I mean that installed DeLFT/GROBID using a new EC2 instance as per instructions.

Thank you for sending your` pip list`. This is my pip environment:
```
Package                          Version
-------------------------------- ----------------------
absl-py                          0.10.0
astor                            0.8.1
bleach                           3.2.1
blinker                          1.3
chardet                          2.3.0
click                            7.1.2
cloud-init                       20.3
command-not-found                0.3
configobj                        5.0.6
cryptography                     1.2.3
gast                             0.4.0
gensim                           3.4.0
grpcio                           1.32.0
h5py                             2.7.1
hibagent                         1.0.1
idna                             2.0
importlib-metadata               2.0.0
jep                              3.8.2
Jinja2                           2.8
joblib                           0.17.0
jsonpatch                        1.10
jsonpointer                      1.9
Keras                            2.2.4
Keras-Applications               1.0.8
keras-bert                       0.39.0
keras-embed-sim                  0.3.0
keras-layer-normalization        0.11.0
keras-multi-head                 0.18.0
keras-pos-embd                   0.9.0
keras-position-wise-feed-forward 0.4.0
Keras-Preprocessing              1.1.2
keras-self-attention             0.39.0
keras-transformer                0.21.0
langdetect                       1.0.7
language-selector                0.1
lmdb                             0.94
Markdown                         3.3
MarkupSafe                       0.23
nltk                             3.5
numpy                            1.16.1
oauthlib                         1.0.3
packaging                        20.4
pandas                           0.22.0
pip                              20.2.3
pkg-resources                    0.0.0
prettytable                      0.7.2
protobuf                         3.13.0
pyasn1                           0.1.9
pycurl                           7.43.0
pydot                            1.2.4
pygobject                        3.20.0
PyJWT                            1.3.0
pyparsing                        2.4.7
pyserial                         3.0.1
python-apt                       1.1.0b1+ubuntu0.16.4.9
python-dateutil                  2.8.1
python-debian                    0.1.27
python-systemd                   231
pytz                             2020.1
PyYAML                           3.11
regex                            2018.2.21
requests                         2.9.1
scikit-learn                     0.19.1
scipy                            1.5.2
setuptools                       50.3.0
six                              1.10.0
smart-open                       3.0.0
ssh-import-id                    5.5
tensorboard                      1.12.2
tensorflow                       1.12.0
termcolor                        1.1.0
textblob                         0.15.1
tqdm                             4.21.0
truecase                         0.0.11
ufw                              0.35
unattended-upgrades              0.1
Unidecode                        1.0.22
urllib3                          1.13.1
virtualenv                       15.0.1
webencodings                     0.5.1
Werkzeug                         1.0.1
wheel                            0.35.1
zipp                             3.3.0
```
My environment looks pretty similar if I am not mistaken.

> Let me know if you need more information, but in your case you should maybe try downgrade the jep version on your python environment.

I am using `jep 3.8.2`. Thank you.

I still experience an issue.

<img width="1440" alt="Screen Shot 2020-10-11 at 22 40 05" src="https://user-images.githubusercontent.com/12778567/95688433-c345ac80-0c12-11eb-9eff-e72b66e23170.png">

Could you please take a look at the logs? Thank you very much in advance for any hints!
[grobid-service.log](https://github.com/kermitt2/grobid/files/5361830/grobid-service.log)

**Comment by lfoppiano** [comment]
OK, I've been in this situation and I remember I needed to find a way to understand which model is actually causing the issue. 

Could you please 
1. switch to the branch `bugfix/delft-integration-experiments`
   -  `git checkout bugfix/delft-integration-experiments`
2. stash and pull: 
  -   `git stash `
   -  `git pull`
   -  `git stash pop `


And try again, and send the log? 

we are close to the solution ;-)

**Comment by andrei-volkau** [comment]
Hi @lfoppiano, thank you!

I am sending you the logs. I am using `bugfix/delft-integration-experiments` branch.

[grobid-service.log](https://github.com/kermitt2/grobid/files/5365771/grobid-service.log)

**Comment by lfoppiano** [comment]
@andrei-volkau thanks. As of now I'm trying to figure out what is not working. I pushed some more logging information.  

could you update(git pull) and try again?

**Comment by andrei-volkau** [comment]
Hi @lfoppiano, thank you! Sorry for my late reply. 

I am sending you the logs. I am using the latest `bugfix/delft-integration-experiments`
[grobid-service.log](https://github.com/kermitt2/grobid/files/5392854/grobid-service.log)

**Comment by lfoppiano** [comment]
> Hi @lfoppiano, thank you! Sorry for my late reply.
> 
> I am sending you the logs. I am using the latest `bugfix/delft-integration-experiments`
> [grobid-service.log](https://github.com/kermitt2/grobid/files/5392854/grobid-service.log)

@andrei-volkau are you sure you activate the conda environment? here the log says it cannot find jep

Could you check and re-try?

**Comment by andrei-volkau** [comment]
@lfoppiano Sorry, I forgot to do that. I am sending you the correct logs.

[grobid-service.log](https://github.com/kermitt2/grobid/files/5393948/grobid-service.log)


I am sending relevant screenshots also. Thank you.
<img width="1440" alt="Screen Shot 2020-10-16 at 22 40 28" src="https://user-images.githubusercontent.com/12778567/96302177-ffa54e00-1000-11eb-87fb-621d6241069b.png">
<img width="1440" alt="Screen Shot 2020-10-16 at 22 40 55" src="https://user-images.githubusercontent.com/12778567/96302182-0207a800-1001-11eb-8ebf-9c81fa51ff67.png">
<img width="1440" alt="Screen Shot 2020-10-16 at 22 41 10" src="https://user-images.githubusercontent.com/12778567/96302193-06cc5c00-1001-11eb-87ec-748569b783ae.png">

**Comment by lfoppiano** [comment]
@andrei-volkau thanks. No need to send the screenshots. The important part of the log is before. However from your log I can see only 

```
ERROR [2020-10-16 19:39:15,405] org.grobid.core.jni.JEPThreadPool: JEP initialization failed
! jep.JepException: <class 'ModuleNotFoundError'>: No module named 'delft'
! at <string>.<module>(<string>:1)
! at jep.Jep.eval(Native Method)
! at jep.Jep.eval(Jep.java:507)
! at org.grobid.core.jni.JEPThreadPool.initializeJepInstance(JEPThreadPool.java:89)
! at org.grobid.core.jni.JEPThreadPool.createJEPInstance(JEPThreadPool.java:107)
! at org.grobid.core.jni.JEPThreadPool.getJEPInstance(JEPThreadPool.java:137)
! at org.grobid.core.jni.DeLFTModel$InitModel.run(DeLFTModel.java:53)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
INFO  [2020-10-16 19:39:15,533] org.grobid.core.jni.DeLFTModel: Loading DeLFT model for name-header...
INFO  [2020-10-16 19:39:15,534] org.grobid.core.jni.JEPThreadPool: Creating JEP instance for thread 29
```

Are you sure the setup is correct?

**Comment by andrei-volkau** [comment]
@lfoppiano I forgot to specify one of two paths in the GROBID setting file. I mean either DELFT path or DELFT env path. I do not remember which one. Anyway, thank you for your patience! The following logs are for 100% correct setup. 

[grobid-service.log](https://github.com/kermitt2/grobid/files/5394168/grobid-service.log)

**Comment by lfoppiano** [comment]
@andrei-volkau sorry, there is still something not clear.. are you sure you pull the latest version? 
could you send me the result of `git log --oneline --decorate --graph`? I don't see the additional logs I added.

**Comment by andrei-volkau** [comment]
> could you send me the result of `git log --oneline --decorate --graph`?

@lfoppiano Sure! I am sending that. Thank you.

```
* 294c2b5 (HEAD -> bugfix/delft-integration-experiments, origin/bugfix/delft-integration-experiments) adding some more logging
* 50b784b output the model name for debugging
* b0560b5 (master) improve documentation on delft configuration
* bda9314 more self-explaining property file regarding DL models
* 2fd52bd add jni class for DeLFT classifier via JEP
* ad5276c review benchmarking doc and licenses
* 570c8c0 update citation deep learning model and add corresponding benchmarks
* 41d5e6a update doc
* 01ab5c9 fix error case sentence segmentation without sentence
* f43e301 support for page number ranges with postfix letter
*   ebdbb89 Merge branch 'master' of https://github.com/kermitt2/grobid
|\
| * a62daf3 fix on page range string manipulation
* | 32b3123 upate citation model
|/
* 39fa6a9 better normalisation of page ranges
* 295e468 review serialization of series and editors in bib. ref.
*   4be789e Merge branch 'master' of https://github.com/kermitt2/grobid
|\
| * 0a22345 typo in formatting doc
* | d18f5e4 add specific series field in the citation model
|/
* a69290a fix issue with space characters in generated training data for citation model, add specific <series> label
* ac47e1f updated citation model for better identifier coverage
* 295be65 review handling of identifiers in ref bib, add training data
*   4d1938c Merge pull request #640 from OrionNebula/OrionNebula--gradle_sentence_segmentation
|\
| * 6d3d927 Add "sentence-segmentation/**" to Gradle package
|/
* 51ec543 update url with https://
* 6d82c9e customize pmc eval
* e262107 add doi, pmid and pmcid fields in the end-to-end eval
*   f56c7af Merge pull request #636 from elifesciences/enable-dist-zip-for-docker-build
|\
| * d43df05 enabled service dist zip for docker build
```

**Comment by lfoppiano** [comment]
@andrei-volkau I'm sorry I could not find time to look in your issue. I'm going to work on the #662 so that we can solve the issue in a clean way

**Comment by andrei-volkau** [comment]
@lfoppiano  I was able to successfully run GROBID with DeLFT while following [step-by-step instructions](https://grobid.readthedocs.io/en/latest/Deep-Learning-models/#classic-python-and-virtualenv). I am closing the issue because of that. Thank you for the great support along the way!
