### ISSUE TITLE
Is includeRawAffiliations available in batch mode? 

### ISSUE THREAD

**Issue by manuelguzmandao** [kermitt2/grobid#646]
Hello,
We are currently using version 0.6.1 in batch mode to take advantage of the multi-threading. We can't find how to use the option includeRawAffiliations in batch mode. Is it possible to do so or is it only available through the REST service?

**Comment by kermitt2** [comment]
Hello @manuelguzmandao !

Batch mode does **not** use multi-threading, see the [documentation](https://grobid.readthedocs.io/en/latest/Grobid-batch/). Batch mode is typically for testing or for small jobs with a low number of PDF that do not require something really fast. 

I encourage you to use the service and [one of the client](https://grobid.readthedocs.io/en/latest/Grobid-service/#clients-for-grobid-web-services) to take advantage of multi-threading, a larger range of parameters and for efficient scaling. 

It's possible that at some point in the future, the batch mode will disappear, to have something easier to maintain on our side, given all the advantages of the service.

**Comment by manuelguzmandao** [comment]
Thanks @kermitt2 !

I'll take a look at updating the python service to add the parameter as it does not seem to have it today
