### ISSUE TITLE
Skip if tei.xml file exists

### ISSUE THREAD

**Issue by keto33** [kermitt2/grobid#647]
I extract fulltext from PDF files in folders as

`java -Xmx4G -jar grobid-core/build/libs/grobid-core-0.6.1-onejar.jar -gH grobid-home -ignoreAssets -segmentSentences -dIn PDF -dOut XML -exe processFullText `

on Ubuntu. I regularly add files to the PDF folders. Is it possible to run the above command again and skip the extraction process if the target tei.xml files exist?

**Comment by kermitt2** [comment]
Hello @keto33 
This is implemented in the [python client](https://github.com/kermitt2/grobid-client-python) for instance (this is the default usage, use `--force` to re-generate the tei.xml files), which I suggest you strongly to use... with server and client, you will get much better runtime performance (multi-threading) and more parameters are available with the service.

**Comment by keto33** [comment]
I will definitely use the python client. 

One related question: Is it possible (by the command line or the python client) to provide a list of PDF files instead of a folder? The output can be the standard folder. Just loading the models once for parsing a list of PDF files residing in different directories.

**Comment by kermitt2** [comment]
>  Is it possible (by the command line or the python client) to provide a list of PDF files instead of a folder? The output can be the standard folder. Just loading the models once for parsing a list of PDF files residing in different directories.

Right now it is not possible, but I guess with the python client, it could be implemented in a matter of minutes :) 
Please be welcome to open an issue in the python client ! 

I don't plan to really go forward with the batch mode/command line, my feeling is that it would be better to just keep the client/server (very easy via Docker) - something less to maintain would help to save time to improve more core functions.

**Comment by keto33** [comment]
My bad! Your design is perfect.

This is intended as a java server rather than the command line. With the server running, we can process many documents simultaneously via cURL with least overload.

This is what the python client does, and we can do in any other programming language.
