### ISSUE TITLE
Co-relating extracted figure assets and XML figure tag

### ISSUE THREAD

**Issue by vishnudas-raveendran** [kermitt2/grobid#649]
Hi,

I tried searching, but didn't come across a way explaining how the extracted images from documents can be related back to the figure tags. 

Am I missing something right under my nose?

**Comment by kermitt2** [comment]
Hello @vishnudas-raveendran 

See https://grobid.readthedocs.io/en/latest/Coordinates-in-PDF/ 
With the parameter `teiCoordinates`, the service will return bounding boxes coordinates for figures/tables.

If you wish to crop the corresponding image from the PDF bitmap, you can then use these bounding boxes with tools/library like pdfplumber, Ghostscript, pdfcrop, ... but other people might have more experience with these tools than me. 

In the included demo, you have some example of cropping areas with PDF.js (for biblio objects and formulas), see below...

---

![Screenshot from 2020-10-12 21-12-19](https://user-images.githubusercontent.com/2340795/95782204-a6bb7a00-0ccf-11eb-96f3-037dc27e0adc.png)

**Comment by vishnudas-raveendran** [comment]
Hello @kermitt2 ,

Yes, I would be using that too.

However, the one I was searching for was <figure>...<graphic url="image_03.png"></figure>. I did not find the graphic tag in one of my data-set, because extraction was done with "--ignoreAssets". I later found out my folly.

Thank you very much for your quick reply and assistance though. :)
