### ISSUE TITLE
Training segmentation model error - "too many synchronization issues, file not used in training data and to be fixed!"

### ISSUE THREAD

**Issue by karatekaneen** [kermitt2/grobid#659]
We are trying to add some more training data and for some (but not all) files that we add as well as some of the files included from the start we get the following error when running `./gradlew train_segmentation`

```
VARNING: 100.v84-264.training.segmentation.tei.xml / too many synchronization issues, file not used in training data and to be fixed!
```

I've looked through some of the files looking for the fixes to make but I can't find anything that stands out. Is there any way to see more information about the error? 
Currently my hypothesis is that we've misunderstood the structure required by the model. We don't have any nested fields but everything is not covered by the other tags, such as body etc.
Example:
```xml
<tei>
	<teiHeader>
		...
	</teiHeader>
	<text>
		<note place="headnote">some note</note>
		<page>1</page> out of 200 <-- this text is outside of any other tag. Could this be the error?
		<body>
		    some body <lb/>
		     some more body
		</body>
	</text>
</tei>
```

**Comment by lfoppiano** [comment]
Dear @karatekaneen,
     for each document, there are two files associated to it (see the section "general principle"): https://grobid.readthedocs.io/en/update_header/training/General-principles/, one XML file and one feature file. 
The error you are seeing is due to a missing synchronisation between those two files. 

It is normal to have part of the data outside tags, but the format you are showing in the example is "strange". Usually, you don't have "teiHeader", as the structure is much flatter. 

Could you share the whole training examples?

**Comment by karatekaneen** [comment]
Hmm, so the error could be that we happened to modify the text by mistake maybe?

Here are the files: 
- [Raw file](https://drive.google.com/file/d/1ygqlBsU9I65feYe17tdYlxVj6aCpQ6SW/view?usp=sharing)
- [XML](https://drive.google.com/file/d/1oIzOdL7kKg28fZN2xUrGGByL8Uh8tEO-/view?usp=sharing)

For future readers; if the links are dead this is the xml and the raw file for `100.v84-264.training.segmentation.tei.xml` that are included in this repo.

**Comment by lfoppiano** [comment]
@karatekaneen I have a few questions. 

The file that you sent me is already in the training repository, I wonder why did you try to modify it?  
I also see that all the line break (`<lb/>`) and spaces have been modified. 

![image](https://user-images.githubusercontent.com/15426/96840118-9034c180-1439-11eb-8822-383f9bc5f8fb.png)
(green = original, grey = yours)


Did you generate your XML and RAW file from the PDF or you just modify the original from the grobid-trainer repository?

**Comment by karatekaneen** [comment]
I could have sworn that I did not modify the file but it's clear that it's not quite true. 
I'm going to do a hard reset and rebuild of the project and this problem (at least for this file) will probably go away. 

Is it correct to assume that the errors from the other files stemmed from that the file contents was modified?

Anyways, thanks for the help and thanks for the awesome project!

**Comment by lfoppiano** [comment]
@karatekaneen I think you have an old version. I can see this file has been modified in april/may 2020 when we updated the various models. I think if you do a git pull you should be able to get the current version.
