### ISSUE TITLE
Question: Is it possible to analyze font properties using GROBID?

### ISSUE THREAD

**Issue by andrei-volkau** [kermitt2/grobid#661]
Is it possible to determine using GROBID whether a span(token) is presented in a nonregular font (bold/italics)? 

It is well known that font properties might be analyzed using low-level PDF parsers. For example, [PyMuPDF](https://github.com/pymupdf/PyMuPDF) is able to do that. I am wondering whether it's possible to do the same using GROBID.  Thank you in advance for any hints!

**Comment by kermitt2** [comment]
Yes these are attributes of the LayoutToken objects, as well as superscript, underscript - they are used as features for the sequence labeling. They come from the low level PDF parsing tool that we are also developing/using, [pdfalto](https://github.com/kermitt2/pdfalto/), based on xpdf (chosen in particular for the license, which is more liberal than mupdf).

**Comment by andrei-volkau** [comment]
Thank you for the great info! I am closing the question.

**Comment by zoranmedic** [comment]
I'm also interested in this. Is there any way to get the font properties in the output of GROBID? Thanks!

**Comment by kermitt2** [comment]
The goal of GROBID is to extract the logical structure of a document, abstracting mere presentation elements like fonts, style, positions, etc. so to produce something like a JATS file for instance.... the goal is actually not to output any font information :)

We normally don't want to have presentation information when doing higher level content analysis and text mining of scientific documents.  

You can get the font properties with [pdfalto](https://github.com/kermitt2/pdfalto).

If you're courageous and dive a bit in the GROBID library, you can get all the font information for any tokens in GROBID using the `LayoutToken.java` object. The LayoutToken objects are propagated from the PDF parsing to the final serialization to XML.

**Comment by zoranmedic** [comment]
Thanks for a quick response! I'll try to get the font information that way then.
