### ISSUE TITLE
isalive REST endpoint doesn't work

### ISSUE THREAD

**Issue by chrismattmann** [kermitt2/grobid#67]
Tried to use it in tika - didn't work not sure why but will investigate.

**Comment by Aazhar** [comment]
Hi,
the path declaration is missing from https://github.com/kermitt2/grobid/blob/master/grobid-service/src/main/webapp/WEB-INF/web.xml

**Comment by kermitt2** [comment]
Well I was not convinced about its usefulness and started to remove it :)
So I removed it from the web.xml file and the documentation.

Ok it is back with commit e1e205cec26628dfd07c6a9253bd821e807de746

**Comment by chrismattmann** [comment]
Thanks @kermitt2 - yeah what confused me is that it was still in the documentation. Anyways thanks for adding it back @Aazhar
