### ISSUE TITLE
[Question] Is it possible to configure GROBID to ignore invisible/hidden text somehow?

### ISSUE THREAD

**Issue by andrei-volkau** [kermitt2/grobid#675]
Is it possible to configure GROBID to ignore invisible/hidden text somehow? Those things are obviously invisible to humans, but they are visible for GROBID. I am also wondering about the case where two bits of text have overlapping coordinates, etc.

**Comment by kermitt2** [comment]
Hi @andrei-volkau 

Invisible text is currently processed as "normal" text indeed. 

Knowing that a text is invisible is not explicit in a PDF. We would need first to introduce some recognition of this "layout feature" for instance in pdfalto - so recognize that we have white font on white background, or that the font is microscopic, or that there is a mask on top of the text, ... I've never tried to do that, but it's certainly doable. 

Then we could think about how to manage it in Grobid, likely just ignoring it? It's usually some sort of hidden watermark put by the publisher with the idea to help enforcing their copyrights. I already find the config and parameters too heavy in Grobid, I don't really like the idea to add more... it's time consuming to maintain and slow down other development efforts. 

Overlapping text is different I think. It's a super frequent and normal stuff in PDF (character composition for diacritics, formula, figures). The case of overlapping unreadable text is very rare and it could be complicated to distinguish it from the the usual "technical" overlapping.

**Comment by andrei-volkau** [comment]
Hi @kermitt2 !

Many thanks for addressing the question in a comprehensive way. I am closing it. Thank you.
