### ISSUE TITLE
suggestion: consider onnx for model persistence and inference  

### ISSUE THREAD

**Issue by joelkuiper** [kermitt2/grobid#699]
Just a suggestion, but it seemed like a nice fit here. The ONNX https://onnx.ai/ framework supports an inference API in on the JVM side. If the produced deep learning models could be serialized to that format it would potentially speed up inference, but more importantly it could deprecate the inference/run-time dependency on the python bits while keeping the training pipelines probably identical.

**Comment by kermitt2** [comment]
Thank you @joelkuiper ! Train with python and infer on Java, this is definitively worth investigating for this project.

**Comment by lfoppiano** [comment]
@kermitt2 this subject came up on a discussion and I was wondering if you tried already?  This could be a way to simplify the architecture and maybe speed it up (we won't have the limitation of a single thread?).

**Comment by kermitt2** [comment]
I looked at this but this is complicated to get it working with a custom layer as we are using for CRF, not sure if it is even possible in this case. Second, it seems there is no onnx support for Keras 3/TF 2.16 yet. 
onnx is not doing tokenization afaik indeed, it's just model weight and standard architecture - so a lot of work obviously if we want to run this via the JVM.

**Comment by lfoppiano** [comment]
Thanks. I think we can then park this. If someone ever come up with a working solution we may reconsider :-)
