### ISSUE TITLE
Missing Introduction section

### ISSUE THREAD

**Issue by AaronNGray** [kermitt2/grobid#700]
Getting a missing Introdiction section first paragraphs for some strange reason ?

http://lampwww.epfl.ch/~amin/dot/fool.pdf

Text picks up on second column text "well as its mixture of nominal ..."

**Comment by qhreul** [comment]
@AaronNGray I have observed the same issue on medical articles. 

As part of [EHF2-6-1105.pdf](https://github.com/kermitt2/grobid/files/6985111/EHF2-6-1105.pdf), I have observed that the whole "Epidemiology" section in page one (defined across 2 columns) is missing in the TEI XML after conversion. This behaviour was observed with docker version (i.e. `lfoppiano/grobid:0.7.0`).

**Comment by lfoppiano** [comment]
@AaronNGray @qhreul I've been revising the open issues with error cases, and both your problems seems to be solved in version 0.8.1.
