### ISSUE TITLE
Disparity between demo and local version regarding coordinates in headers

### ISSUE THREAD

**Issue by Dauriel** [kermitt2/grobid#709]
Hello,

I have the following issue:

I upload a PDF to the demo site under TEI, select "Process Fulltext Document" and mark the "Add coordinates" option. The resulting XML contains coordinates in each of the headers.

`<div xmlns="http://www.tei-c.org/ns/1.0"><head n="1" coords="1,90.00,566.29,80.00,11.10">Introduction</head><p><s`

I try to obtain the exact same result through my local grobid service by calling the python file (grobid_client.py) in processFulltextDocument mode with the --teiCoordinates keyword, but headers now come without coords.

`<div xmlns="http://www.tei-c.org/ns/1.0"><head n="1">Introduction</head><p>`

What am I missing? How can I replicate what the demo is extracting?
(I checked the documentation and cannot really find an answer to this)

Thank you in advance.

**Comment by kermitt2** [comment]
Hello @Dauriel !

This is a question for the client https://github.com/kermitt2/grobid_client_python
The configuration file of the client `config.json` defines the elements where the coordinates will be added. So normally simply change in this file:

```json
"coordinates": [ "persName", "figure", "ref", "biblStruct", "formula" ]
```
to 

```json
"coordinates": [ "persName", "figure", "ref", "biblStruct", "formula", "head" ]
```

**Comment by Dauriel** [comment]
Solved! Thank you very much for your fast response.
