### ISSUE TITLE
Minor: citation type

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#720]
I bumped into this minor thing by chance (see [here](https://github.com/kermitt2/grobid/blob/bfc10f77998a141e14e1a88483ef42954e0d30b2/grobid-core/src/main/java/org/grobid/core/engines/FullTextParser.java#L502), shouldn't be `nbAuthorType` instead of `nbNumbType`?

**Comment by kermitt2** [comment]
Yes ! good catch... and bad cut and paste ;)

**Comment by lfoppiano** [comment]
I pushed the fix with 610426f3d3dec9de16ad82098f00cca84991a452

**Comment by kermitt2** [comment]
It would require to retrain the fulltext model together with the change of the input feature for this model.

**Comment by lfoppiano** [comment]
Ah I missed that… I’ll move that on a separate branch then… I should have done it before but I though the change was minimal, did not think of other impacts…

**Comment by lfoppiano** [comment]
OK I reverted master and moved my change to a separate branch.

**Comment by kermitt2** [comment]
I retrained the fulltext model with the corrected features (committed in the branch) and run the benchmarks before/after. There is no real difference (minor second digit change on citation context/reference marker recognition), so the feature value itself does not seem to be very impactful... (the feature is effective, but the distinction that the token is a "digit" or "textual" reference marker does not seem to improve results - given the current training data at least).

**Comment by kermitt2** [comment]
I think this is ready for merging!

**Comment by lfoppiano** [comment]
👍
