### ISSUE TITLE
Updating docker Image? 

### ISSUE THREAD

**Issue by yassinetb** [kermitt2/grobid#730]
Hi, 

Just wondering if there are any plans of updating the docker image? I'm running GROBID through Docker and I am trying to get the coordinates of the headers, which is a functionality added in November (so after the most recent Docker Image) - see: 
https://github.com/kermitt2/grobid/issues/456#issuecomment-720022414 

Thank you!

**Comment by kermitt2** [comment]
Hi @yassinetb !
We normally update the docker image for each Grobid release. I am on the 0.6.2 release right now... so the updated docker image should be available a few days after that (at least for CRF docker image, for the Deep Learning models the image is too large for my poor internet connexion).
