### ISSUE TITLE
0.6.2 Tag branch

### ISSUE THREAD

**Issue by HulioVRD** [kermitt2/grobid#734]
Is this tag branch up to date? 
<https://github.com/kermitt2/grobid/tree/0.6.2>

I see that some of the files are old like
<https://github.com/kermitt2/grobid/blob/0.6.2/CHANGELOG.md>

**Comment by kermitt2** [comment]
Hi @HulioVRD !

I am updating the changelog, readme and the doc files after tagging and release, assuming that users look only at the current master version for those files - an error it seems :D

**Comment by HulioVRD** [comment]
I see. If everything else is up to date, I think we could close it. Changelog and docs were the first thing that I looked at, but the code is most important for me.

Thank you for the fast response and have a nice day!
