### ISSUE TITLE
Completeness of coordinates in TEI-XML vs. JSON for document annotation

### ISSUE THREAD

**Issue by bnewbold** [kermitt2/grobid#739]
I hadn't previously realized how powerful the PDF annotation layer in browser (using pdf.js) is: the pop-up bibliography references, clicking through to consolidated links, etc.

Curious if the coordinates when encoded in the TEI-XML output (eg, `/api/processFulltextDocument` with `teiCoordinates=1`) contains all of the annotation metadata that would be would be included in JSON results (`/api/referenceAnnotations`).

As an example application, we have GROBID TEI-XML output pre-computed for many millions of PDFs, and can fetch individual XML documents rapidly (milliseconds). If we wrote our own XML-to-JSON transform, we could potentially display PDFs in-browser with the pdf.js annotation layer without needing to wait for processing to occur. If the TEI-XML coordinate metadata is not "complete", then this kind of transform would not be possible, and we would need to re-process all documents with both `processFulltextDocument` and `referenceAnnotations` separately, and store (and fetch) the results separately, which would be less efficient (presumably up to twice the processing compute time, and twice the number of citation consolidation requests).

Relevant section of documentation: <https://grobid.readthedocs.io/en/latest/Coordinates-in-PDF/#coordinates-in-teixml-results>

**Comment by kermitt2** [comment]
Hi @bnewbold !

Yes the TEI with coordinates contains normally all the information present in the json response of `/api/referenceAnnotations` (note that in the service `/api/processFulltextDocument`, the `teiCoordinates` parameter is the list of elements where you want to see the coordinates, not a boolean - so for instance `<ref>` and `<biblStruct>`). The TEI with coordinates includes in particular the size of the pages of the PDF (the `<facsimile>` elements), an information that is necessary to "rescale" correctly the coordinates following the PDF displayed on screen. 

So your analysis is correct, if you want both the TEI and the coordinates, better to use simply one time the  `/api/processFulltextDocument` service with coordinates. I added the JSON response service `/api/processFulltextDocument` as something fast and easy to use with javascript - in case we just want to display on the fly on a PDF (as in the demo). You could produce the JSON offline from the TEI or use directly the TEI with some javascript XML parsing, and displaying the annotations on the PDF should be super fast for the user. 

PS: not related, but I really love Internet Archive Scholar :) congratulation!
