### ISSUE TITLE
Add MD5 digest in file processing response

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/grobid#740]
When processing a PDF with the web service, we should include in the TEI result the MD5 digest of the original file, so that we can bind the TEI to the right version of the PDF. 

This is done for instance [here](https://github.com/ourresearch/software-mentions/blob/master/src/main/java/org/grobid/service/controller/SoftwareProcessFile.java#L79). Just one problem, I don't know how to encode it in the TEI header (under `<sourceDesc>`? but how?).

**Comment by kermitt2** [comment]
@laurentromary would you known maybe how to encode a MD5 digest corresponding to the source file in the TEI header ? :)

**Comment by laurentromary** [comment]
In the HAL export the encoding used is: `<email type="md5">43c6e47d10a9ab0dce7aa7e96ce47786</email>` for email encoding, but this is indeed quite specific. For your use case, this is really related to the identification of the source. Something like?:
``XML
<TEI xmlns="http://www.tei-c.org/ns/1.0">
   <teiHeader>
      <fileDesc>
         <sourceDesc>
            <biblStruct>
               <analytic>
                  <idno type="md5"/>
               </analytic>
            </biblStruct>
         </sourceDesc>
      </fileDesc>
   </teiHeader>
</TEI>
``

**Comment by kermitt2** [comment]
Thanks a lot Laurent! I think the `<idno>` for `<sourceDesc>` is working fine and quite clear. Maybe we could use a `@subtype="pdf"` to indicate that the digest relates to a PDF original format?

**Comment by laurentromary** [comment]
Is this part of the logic of MD5? Or just a convenient hack? Not that I would have something against that but want to assess  the generosity of the trick.

**Comment by kermitt2** [comment]
We can calculate a MD5 digest from any data, it's a way to get a signature. The `@subtype="pdf"` would indicate that the MD5 was calculated from the PDF used to create the TEI, so not a docx or another xml format of the document for instance. One motivation behind this is to be sure that we can use the coordinate information present in the TEI with a given PDF (that might be downloaded online, so without guarantee that it was the PDF originally used with Grobid).

**Comment by laurentromary** [comment]
That makes perfect sense (i.e. the coordinates). But in a way, you not even have to know this subtype to check. Let's go ahead with this in any case.

**Comment by kermitt2** [comment]
Yes, you're right about the subtype, thinking twice this looks really unnecessary, so let's drop it! thanks !!
