### ISSUE TITLE
Accessing demo server- service not available 

### ISSUE THREAD

**Issue by YasithAri** [kermitt2/grobid#754]
I am testing some PDF files on following demo server. and seems to be some serveries are not available.
https://cloud.science-miner.com/grobid/ 

![image](https://user-images.githubusercontent.com/72807632/116993298-f602df80-acdf-11eb-9aaa-f3d9d93b8a31.png)

**Comment by kermitt2** [comment]
Too much traffic, saturated job queue... in this case the service respond with 503. 
One solution is to wait :)

It's available again after a while normally (it's why the 503 are firing). 

I should maybe try to better adjust quotas and avoid heavy queries from same IP, but most of the time everything works fine.
