### ISSUE TITLE
Why do I get "You have sent too many requests in a given amount of time." upon CrossRef consolidation?

### ISSUE THREAD

**Issue by davidefiocco** [kermitt2/grobid#755]
I am running GROBID on docker via 

    docker run -t --rm --init -p 8080:8070 -p 8081:8071 --env ORG__GROBID__CROSSREF_mailto=my@address.com lfoppiano/grobid:0.6.0
    
(passing my actual email address as docker env var) on a local collection of PDF docs in a `PDFs` folder. 
To extract reference DOIs I use:

```python
from bs4 import BeautifulSoup
from pathlib import Path
import requests

def grobid_extract_pdf(pdf_file, url, consolidate = 0):
    multipart_form_data = {
        'input': open(pdf_file, 'rb'),
        'consolidateCitations' : consolidate
    }
    response = requests.post(url + '/api/processFulltextDocument', files=multipart_form_data)
    if response.status_code == 200:
        return response.text

def get_dois(filename, consolidate):
    raw = grobid_extract_pdf(filename, url='http://localhost:8080', consolidate = consolidate)
    soup = BeautifulSoup(raw, 'lxml')
    dois = soup.find("div", {"type":"references"}).findAll("idno", {"type":"DOI"})
    return [doi.text for doi in dois]

# get list of files in my working dir
files = list(Path("./PDFs").glob("*"))

# attempt to extract DOIs contained within each PDF, using consolidation
for f in files:
    print(get_dois(f, consolidate = 2))
```

When running the script, I see in the INFO logs strings like

```
Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html><body><h1>429 Too Many Requests</h1>
You have sent too many requests in a given amount of time.
```

Am I doing anything wrong? 
I understood from https://grobid.readthedocs.io/en/latest/Consolidation/ that GROBID self-limits the query rate to use CrossRef properly.

The problem reproduces also when building the docker 0.6.0 tag container by setting my email in `grobid-home/config/grobid.properties`

Thanks!

**Comment by kermitt2** [comment]
Hello David !

I can't really say if it's related to CrossRef or not, but I advise you to use/look at the python client https://github.com/kermitt2/grobid_client_python to see how to send requests to the grobid server according to its availability. The server manage a pool of threads to deal with requests and return 503 to ask the client too wait before sending more requests. 
However you should get 503 and not 429. But it's better to send requests according to the service availability and not a whole directory of PDF in one time - it might be a safety mechanism of Docker itself. 

About CrossRef, you're right, grobid uses the x-rate-limit-interval parameter in the CrossRef response header to adjust the query rate, but the interpretation of this parameter has changed in the last months and we pushed a fix for this. You need to use the latest version of Grobid and docker image to use it. 

Working with CrossRef in production is a really challenge, response rate changes a lot over time and the max query rate makes that most of the time in Grobid processing is spent waiting for CrossRef response. [biblio-glutton](https://github.com/kermitt2/biblio-glutton) has been developed to solve these limitations.

**Comment by davidefiocco** [comment]
I now see that with release 0.7.0 `X-Rate-Limit-Limit` is updated for compliance with CrossRef.
Does that mean that any behavior of versions < 0.7.0 will be sanctioned by CrossRef? Thanks!

**Comment by kermitt2** [comment]
For casual usage, low stress on CrossRef, it should still work okay, but it's better to use the latest version for safety and for more serious usage.
