### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by liar666** [kermitt2/grobid#76]
Hello Kermitt2,

Thanks for the great job with Wapiti, etc.

Unfortunately, the online API documentation does not seem to be up-to-date :{

Indeed, at the end of page:
http://grobid.readthedocs.org/en/latest/Grobid-java-library/?q=keyword&check_keywords=yes&area=default#javadoc
for the javadoc of the API, we are redirected to:
http://grobid.github.io/grobid-core/index.html

And there are some oddities: for instance, the getKeywords  method in http://grobid.github.io/grobid-core/index.html is described as:
public List<String> getKeywords()
whereas trying to compile a code using it raises a compilation error saying that the actual prototype is:
public List<Keyword> getKeywords()

Bye!

**Comment by kermitt2** [comment]
The javadoc pages are updated! http://grobid.github.io
```getKeywords()``` looks better now.

**Comment by kermitt2** [comment]
OK for closing the issue Guillaume?
