### ISSUE TITLE
expired certificate on https://grobid.science-miner.com  ?

### ISSUE THREAD

**Issue by Vitexus** [kermitt2/grobid#764]
Hallo maybe is the certbot sleeping ?

**Comment by kermitt2** [comment]
Hi @Vitexus, yes I saw this... https://cloud.science-miner.com/grobid is working and the certbot is not sleeping, I need to check the other subdomains, but I didn't find the time to look more at it sorry.

**Comment by kermitt2** [comment]
The updated wildcard certificate is not used for https://grobid.science-miner.com which is a redirect, I am checking with my hosting provider why the old wildcard certificate is used for redirect, while the new one is correctly used for direct access (probably there's something I misunderstood in the process).

**Comment by kermitt2** [comment]
Finally it was an issue from my hosting service and they fixed it :)
