### ISSUE TITLE
Lucene jar imported twice?

### ISSUE THREAD

**Issue by liar666** [kermitt2/grobid#77]
I'm not sure if it is only on my installation, but when I use Grobid in batch mode, I get:
JarClassLoader: Warning: org/apache/lucene/analysis/cn/smart/hhmm/SegTokenFilter.class in lib/lucene-analyzers-smartcn-4.5.1.jar is hidden by lib/wipo-analysers-0.0.1.jar (with different bytecode)

$ locate lib/lucene-analyzers-smartcn-4.5.1.jar
/home/guillaume/Softs/grobid/grobid-service/target/grobid-service-0.3.9-SNAPSHOT/WEB-INF/lib/lucene-analyzers-smartcn-4.5.1.jar
$ locate lib/wipo-analysers-
/home/guillaume/Softs/grobid/grobid-service/target/grobid-service-0.3.9-SNAPSHOT/WEB-INF/lib/wipo-analysers-0.0.1.jar

It occurs even after a git pull + mvn clean package and I don't have any idea on how to better test this problem, so I'm submitting it to your appreciation.

**Comment by aoboturov** [comment]
The WIPO library should be changes in the following way:
https://gist.github.com/aoboturov/b27bb814e6c6fea8a80c667bc54cf4f0

One this is done, Lucene should be added as a direct dependency to Grobid Core.

@kermitt2 could you publish the sources for the WIPO library on Github?

**Comment by aoboturov** [comment]
Actually, the prefix for the shadow should be more project specific, e.g. something like `wipo-analysers`

**Comment by aoboturov** [comment]
I actually forgot to shade services from SPI:

https://gist.github.com/aoboturov/00028fbc0a15c2dc0f3e990ceb5a9eac

The new pom.xml contains these changes.

**Comment by kermitt2** [comment]
I've integrated your changes thanks @aoboturov ! It should work fine now with commit a35706a2db27cc7d1b24167bbcee1494d9c26246.
