### ISSUE TITLE
"grobid-core-0.7.0-SNAPSHOT-onejar.jar" is missing

### ISSUE THREAD

**Issue by coloyellow** [kermitt2/grobid#775]
Hi 
I want to create some training data.
I follow this page below :
https://grobid.readthedocs.io/en/latest/Grobid-batch/#createtraining

I can't find "grobid-core-0.7.0-SNAPSHOT-onejar.jar" in grobid folder.
May you tell me how to create training data in latest version grobid?

**Comment by kermitt2** [comment]
Hi @coloyellow 

You need to [build the tool](https://grobid.readthedocs.io/en/latest/Install-Grobid/#build-grobid-with-gradle) which is one command line normally, then 

```shell
lopez@work:~/grobid$ ll grobid-core/build/libs/grobid-core-0.7.0-SNAPSHOT-onejar.jar 
-rw-rw-r-- 1 lopez lopez 76M Jun 11 10:23 grobid-core/build/libs/grobid-core-0.7.0-SNAPSHOT-onejar.jar
```

**Comment by coloyellow** [comment]
Oops

I forgot this step.

I solved this problem, thank you so much.

**Comment by kermitt2** [comment]
Closing the issue as you noted it is solved, feel free to reopen it if necessary !
