### ISSUE TITLE
Invalid dockerfiles for the latest master branch.

### ISSUE THREAD

**Issue by elonzh** [kermitt2/grobid#782]
I am trying to build grobid docker image with the latest master branch.

The problem of dockerfile is the new config is located in `grobid-home/config/grobid.yaml`, not `grobid-service/config/config.yaml`.

```dockerfile
CMD ["./grobid-service/bin/grobid-service", "server", "grobid-service/config/config.yaml"]
```

```
02:17:13.968 [main] INFO org.grobid.service.main.GrobidServiceApplication - Configuration file: /opt/grobid/grobid-service/config/config.yaml
java.io.FileNotFoundException: File grobid-service/config/config.yaml not found
        at io.dropwizard.configuration.FileConfigurationSourceProvider.open(FileConfigurationSourceProvider.java:18)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:80)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at org.grobid.service.main.GrobidServiceApplication.main(GrobidServiceApplication.java:126)
```

PS: I think we shouldn't use hardcode arguments.

**Comment by kermitt2** [comment]
Oh yes sorry I've completely forgotten that in the last update. I never liked that command line at all, and yes we should not use hardcoded arguments, so I removed both the `config.yaml` and the `./grobid-service/bin/grobid-service`. 

In the docker image, it should be now simply:

```shell
./gradlew grobid-service:run
```

instead of the bad looking:

```shell
CMD ["./grobid-service/bin/grobid-service", "server", "grobid-service/config/config.yaml"]
```

**Comment by elonzh** [comment]
> Oh yes sorry I've completely forgotten that in the last update. I never liked that command line at all, and yes we should not use hardcoded arguments, so I removed both the `config.yaml` and the `./grobid-service/bin/grobid-service`.
> 
> In the docker image, it should be now simply:
> 
> ```shell
> CMD [./gradlew grobid-service:run]
> ```
> 
> instead of the bad looking:
> 
> ```shell
> CMD ["./grobid-service/bin/grobid-service", "server", "grobid-service/config/config.yaml"]
> ```

Ready? Why we need gradle for a released layer?

**Comment by elonzh** [comment]
I also found that libfontconfig is required for pdfalto

```
ERROR [2021-06-29 07:11:43,574] org.grobid.core.process.ProcessPdfToXml: pdfalto process finished with error code: 127. [/opt/grobid/grobid-home/pdfalto/lin-64/pdfalto_server, -fullFontName, -noLineNumbers, -noImage, -annot
ation, -filesLimit, 2000, /opt/grobid/grobid-home/tmp/origin9823192860162901769.pdf, /opt/grobid/grobid-home/tmp/gfmWEw2Bxc.lxml]
ERROR [2021-06-29 07:11:43,574] org.grobid.core.process.ProcessPdfToXml: pdfalto return message:
/opt/grobid/grobid-home/pdfalto/lin-64/pdfalto: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

ERROR [2021-06-29 07:11:43,577] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs.
! org.grobid.core.exceptions.GrobidException: [PDFALTO_CONVERSION_FAILURE] PDF to XML conversion failed. pdfalto cannot be executed correctly. Has libxml2 been installed in the system? More information can be found in the l
ogs.

```

**Comment by kermitt2** [comment]
> Ready? Why we need gradle for a released layer?

To get rid of the `GrobidServiceApplication.java` ? So simplify a bit... But maybe a bad idea, do we have an overhead with gradle?

**Comment by elonzh** [comment]
The dockerfile uses multi-stage builds to minimized image size, so the runtime stage does not have Gradle and source code.

**Comment by lfoppiano** [comment]
I honestly don't think having the "hardcoded" path inside the docker image is a bad thing, because we build the image and the internal docker structure is actually settle by us. 
This small bug was due to the fact that a) we don't have a docker CI build and b) the latest modification were a substantial re-design of the configuration files

**Comment by elonzh** [comment]
> I honestly don't think having the "hardcoded" path inside the docker image is a bad thing, because we build the image and the internal docker structure is actually settle by us.
> This small bug was due to the fact that a) we don't have a docker CI build and b) the latest modification were a substantial re-design of the configuration files

Yes! we need docker CI build!

**Comment by kermitt2** [comment]
Yes you're right gradle is not in the runtime image! 

We need to update `GrobidServiceApplication.java` to simplify it.

**Comment by kermitt2** [comment]
> We need to update `GrobidServiceApplication.java` to simplify it.

mmm no too fast, `GrobidServiceApplication.java`  was updated and it is fine.
