### ISSUE TITLE
Parsing measurement types

### ISSUE THREAD

**Issue by khundman** [kermitt2/grobid#79]
Was wondering if any thought or effort has been put towards parsing out references to specific measurements by measurement type within a doc?

For example, given a publication about satellite imagery, references to cameras' spatial resolutions could be extracted (and maybe even tied to specific satellites). Or given a publication about a disease, biomarker measurements could be extracted by type of measurement.

**Comment by chrismattmann** [comment]
I'm very interested in this too thanks for filing this issue @khundman

**Comment by kermitt2** [comment]
Very good point indeed and this is one of my goal!

I have started working on a new subproject in GROBID for identifying and parsing physical measurements. There is a CRF model which identifies in text quantities and units, which are then grouped into measurements (which could be atomic, intervals, lists, ...), and then normalized into international units using JScience. Does it cover the requirements you are raising? 

I am aware of two implementations of such a tool - [Quantalyze](https://www.quantalyze.com/) and [one developed at FIZ Karlsruhe](https://www.researchgate.net/profile/Hidir_Aras/publication/268346690_Applications_and_Challenges_of_Text_Mining_with_Patents/links/5469a66c0cf2397f782d79b9.pdf) - targeting patent documents. They both use rules and are not open source. I think machine learning and CRF can do a very good job on this and reusing all the work done in GROBID helps for creating rapidly new text annotators based on CRF and training data.

**Comment by khundman** [comment]
@kermitt2 thanks for the info! This is exactly what I am searching for. Looking forward to following your progress.

**Comment by chrismattmann** [comment]
thanks @kermitt2 awesome. So is there some code we could test out @NASAJPL right now? We would love to test it.

**Comment by kermitt2** [comment]
@chrismattmann it is still early and incomplete but I will try to focus more on it and put a first version on GitHub in the next 2-3 weeks. However given the small current amount of training data, I think only a limited set of measurement types will have decent results.

**Comment by chrismattmann** [comment]
Thank you really appreciate it @kermitt2

**Comment by chrismattmann** [comment]
Hey @kermitt2 @khundman one thing I just mentioned to Kyle. [Apache cTAKES](http://ctakes.apache.org/) which is a Clinical Text and Knowledge Extraction System (cTAKES) is built on top of UIMA and extracts biomedical data from text. Well some of its annotators also do measurements and dates/times. We use it in [Tika](http://wiki.apache.org/tika/cTAKESParser) and it's already integrated. I wonder if it would make sense to use this in Grobid too? Right now Tika can use Grobid *and* cTAKES and thus we can extract measurements too and merge the extractions.

**Comment by khundman** [comment]
Hey @kermitt2! Just wanted to check-in and see if you have made any progress toward this?  @chrismattmann and I are still very interested and would love to test.

**Comment by kermitt2** [comment]
Hi @khundman and @chrismattmann

Yes, we are making progress - actually mainly since the beginning of February when this work was seriously resumed... But I still think it's too early for a real world testing. The project is right now in a private GitHub repository  - which will go public when we are minimally happy with the results... Do you want maybe to be added to the repository to follow the progress? 

For improving our training data, more representative articles with many measurements of interest for you would be very interesting!

**Comment by chrismattmann** [comment]
@kermitt2 we would be happy to share some training data. Also yes please add us to the private repo and we can start sharing there. cc @khundman

**Comment by kermitt2** [comment]
Now public repo ;) 
https://github.com/kermitt2/grobid-quantities

**Comment by chrismattmann** [comment]
👍

**Comment by kermitt2** [comment]
So, as there is now a dedicated project and repo on this since more than one year, I close the issue ;)
