### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by pradobelen** [kermitt2/grobid#81]
I cannot compile. What should I do?
Could you please help me

artemis@ubuntu:~/grobid/grobid-service$ mvn -Dmaven.test.skip=true jetty:run-war
Warning: JAVA_HOME environment variable is not set.
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/org/eluder/coveralls/coveralls-maven-plugin/3.1.0/coveralls-maven-plugin-3.1.0.pom
Downloaded: http://repo.maven.apache.org/maven2/org/eluder/coveralls/coveralls-maven-plugin/3.1.0/coveralls-maven-plugin-3.1.0.pom (10 KB at 46.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/eluder/eluder-parent/6/eluder-parent-6.pom
Downloaded: http://repo.maven.apache.org/maven2/org/eluder/eluder-parent/6/eluder-parent-6.pom (15 KB at 293.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Downloaded: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom (7 KB at 164.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/eluder/coveralls/coveralls-maven-plugin/3.1.0/coveralls-maven-plugin-3.1.0.jar
Downloaded: http://repo.maven.apache.org/maven2/org/eluder/coveralls/coveralls-maven-plugin/3.1.0/coveralls-maven-plugin-3.1.0.jar (77 KB at 738.6 KB/sec)
...
Downloaded: http://repo.maven.apache.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar (479 KB at 1523.6 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.264s
[INFO] Finished at: Tue Oct 06 00:42:13 PDT 2015
[INFO] Final Memory: 8M/22M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project grobid-service: Could not resolve dependencies for project org.grobid:grobid-service:war:0.3.9-SNAPSHOT: Could not find artifact org.grobid:grobid-core:jar:0.3.9-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by kermitt2** [comment]
Hello!

You need to build first Grobid from the root project ```grobid/``` before starting the service from ```grobid/grobid-service```. 

See http://grobid.readthedocs.org/en/latest/Install-Grobid/

**Comment by pradobelen** [comment]
Thank you! 
That helped me
