### ISSUE TITLE
HTTP ERROR 503

### ISSUE THREAD

**Issue by pradobelen** [kermitt2/grobid#82]
Hello,
I have compiled grobid service
but when I try to test service via url:
I receive following error:

HTTP ERROR 503
SERVICE_UNAVAILABLE
Thanks in advance for your assistance

**Comment by kermitt2** [comment]
Can you give the error message in the logs? Normally the logs are written in the console. 
Note that Windows is currently not supported by Grobid (the native CRF Wapiti library is missing). 
If you simply want to test the library, I can give you access to a demo service.

**Comment by lfoppiano** [comment]
This seems to be quite obsolete, and no more information were provided. I'm closing it. 

@pradobelen should you still have the problem, don't hesitate to reopen it and add some more log information ;-)
