### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by wang0618** [kermitt2/grobid#822]
I try to build the docker image with the latest code, but I encounter some error both in CRF-only image and deep learning image. It seems like the gradle error:
![image](https://user-images.githubusercontent.com/8682073/130459769-4a5b3ad3-4703-4b82-b137-19e67a3dce35.png)

**Comment by kermitt2** [comment]
I made a quick fix with 605da3d90bf01baffa558d9fbebdbd431ce7b099. 
The docker build for the CRF-only image is working now for me.

**Comment by wang0618** [comment]
Awesome. I try the CRF image, it works good.
