### ISSUE TITLE
Grobid not working on AWS SageMaker (out of the box)

### ISSUE THREAD

**Issue by xegulon** [kermitt2/grobid#823]
Hi @kermitt2, I have installed Grobid on an AWS SageMaker EC2 instance.

As the instance seems to be CENTOS-like, I had to build `pdfalto` myself.

But when I run Grobid in batch mode, I get this error:

![image](https://user-images.githubusercontent.com/74178038/130473020-16545ce2-07cc-46bd-b9c2-e89e14ab685e.png)

I built Grobid with gradle, and the Java version installed on the EC2 instance is:

![image](https://user-images.githubusercontent.com/74178038/130473486-c925b58e-8dd9-4f85-addb-55d666d580ee.png)

What's wrong?

**Comment by kermitt2** [comment]
Normally this error means that the version of the JDK used to build Grobid is higher than the version of the JRE used to run Grobid. The JRE must always be equal or higher version ("backward compatibility").

**Comment by kermitt2** [comment]
Could you check maybe on this instance: 

> javac -version

**Comment by xegulon** [comment]
Here is what I have on SageMaker:
![image](https://user-images.githubusercontent.com/74178038/130584255-beacbfb4-f926-4a2d-8378-0f9373e4c3f6.png)

To detail how I installed pdfalto, here is what I did:
- cd `~/SageMaker/`
- `git clone https://github.com/kermitt2/pdfalto.git` && `cd pdfalto`
- `git clone https://github.com/kermitt2/xpdf-4.03.git` (the command `git submodule update --init --recursive` did not work on SageMaker)
- in `CMakeLists.txt`, I had to set `set(CMAKE_C_STANDARD 99)` else I had an error when compiling
- `cmake .` then `make`
- `cp ~/SageMaker/pdfalto/pdfalto ~/SageMaker/grobid-0.7.0/grobid-home/pdf2xml/lin-64/`
- rebuild Grobid using command: `./gradlew clean install test`
Some of the tests failed, but when I build without the tests, it goes "well". But at the end, I still get the versions error.

**Comment by xegulon** [comment]
I made an install script for that: https://github.com/xegulon/sagemaker-grobid-install

**Comment by kermitt2** [comment]
Could you do the following on your instance: 

> sudo update-alternatives --config java

This will list the installed JRE. If there's a JRE installed with version lower than the JDK, it might be used for whatever reasons and shortcut your environment settings maybe.

**Comment by xegulon** [comment]
I get that:

![image](https://user-images.githubusercontent.com/74178038/130611200-2235932d-54ab-4011-a31b-889cc0180f75.png)

**Comment by kermitt2** [comment]
So apparently the currently selected system JRE version is 1.7, and it might be the one used by gradle (so not using the one of your user environment - but at the same time, this is normal for gradle to use the selected one). So it is too low (must be >= 1.8). 

Probably the simplest is to add the following to `grobid/gradle.properties`:

```
org.gradle.java.home=/path_to_jdk_11
```

where path_to_jdk_11 is the location of the JDK 11 directory on your system (`> whereis java`)
I think it can work, but not sure, otherwise you'll need to install a recent JRE and select it with `sudo update-alternatives --config java`

**Comment by xegulon** [comment]
Now, I get this error:

![image](https://user-images.githubusercontent.com/74178038/130616885-591a757d-21d3-4efb-ae9f-e455f3ca5647.png)

**Comment by kermitt2** [comment]
Is it just for one or a few PDF out of many, or for all PDF ?

**Comment by xegulon** [comment]
I ran it in a folder of 15 PDFs, same error for each one.

**Comment by xegulon** [comment]
I did:
![image](https://user-images.githubusercontent.com/74178038/130617891-92f3a2a9-923f-47df-8a6a-e2dd5a3e57e0.png)
Then:
![image](https://user-images.githubusercontent.com/74178038/130617930-0d53672d-ceca-4576-ab6c-b7765386dfcc.png)
Then I get this error:
![image](https://user-images.githubusercontent.com/74178038/130617984-7f76bfb4-f2d6-4228-89b5-cbc077a97a34.png)

**Comment by xegulon** [comment]
How do I set the property well?

![image](https://user-images.githubusercontent.com/74178038/130618225-0a7f1d12-d600-44ed-8706-1b9315165c8c.png)

**Comment by kermitt2** [comment]
OK Sagemaker is modifying your java environment for jupyter notebook and this kind of things, this is not a normal setup  (are you sure you don't want to use the docker image ? :D or a normal non-sagemaker instance?). 

For the gradle property, you need to specify the location of the JDK 11 **directory** on your system, not an executable, so probably:

```
org.gradle.java.home=/usr/lib/jvm/jre-1.8.0-openjdk.x86_64
```

**Comment by xegulon** [comment]
Compiling worked when I set `org.gradle.java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-1.64.amzn1.x86_64`.

But still the same error: `[PDFALTO_CONVERSION_FAILURE] PDF to XML conversion failed`. Maybe I should inspect this `pdfalto` stuff?

It's way more practical for me to have Grobid installed on my SageMaker instance, but I'll adapt myself if I can't fix this soon enough.

**Comment by kermitt2** [comment]
About the pdfalto error, there's likely a problem with the `pdfalto` build... Could you try the following command with one of your pdf `example.pdf`: 

> ~/SageMaker/pdfalto/pdfalto -fullFontName -noLineNumbers -noImage -annotation -filesLimit 2000 example.pdf result.xml
 
or this one should be the same:

> ~/SageMaker/grobid-0.7.0/grobid-home/pdf2xml/lin-64/pdfalto_server -fullFontName -noLineNumbers -noImage -annotation -filesLimit 2000 example.pdf result.xml

**Comment by xegulon** [comment]
It works, I get the correct XML file.

**Comment by kermitt2** [comment]
Mmm weird... have you tried the service? (`./gradlew run`)
then something like:
> curl -v --form input=@/home/ec2-user/SageMaker/example.pdf localhost:8070/api/processFulltextDocument
same error?

you have read+write rights under `grobid/grobid-home/tmp` ?

**Comment by xegulon** [comment]
In fact the docker version works very well with the python client. Thanks a lot @kermitt2! Less pain with docker!
