### ISSUE TITLE
Field labels that appear in the header training data do not get reported in evaluation

### ISSUE THREAD

**Issue by k8si** [kermitt2/grobid#83]
The fields

copyright, dedication, degree, entitle 

all appear as labels in the header training data, but the evaluation reports no result for them. Is this a mistake or is there a reason for this?

**Comment by kermitt2** [comment]
Hello,

Normally these fields appear in the evaluation report, but they don't frequently appear in the training data. What set of data are you using for the evaluation?

Using the "split train evaluate", I can see them in my older evaluation report:

```
===== Field-level results =====

label		accuracy	precision	recall		f1

<date>		98.66		82.21		79.91		81.04
<copyright>		99.53		87.21		81.52		84.27
<note>		94.88		72.61		75.13		73.85
<title>		97.17		89.36		88.3		88.83
<abstract>		98.26		85.71		91.89		88.7
<author>		97.99		91.08		91.08		91.08
<affiliation>	97.41		92.29		87.74		89.95
<address>		98.36		93.53		91.88		92.7
<email>		99.36		94.31		92.33		93.31
<pubnum>		99.23		83.17		74.34		78.5
<keyword>		99.73		96.88		91.18		93.94
<submission>	99.56		91.89		85.71		88.7
<web>		99.58		75		90.48		82.01
<grant>		99.82		75		84		79.25
<intro>		98.81		73.08		53.27		61.62
<reference>		98.59		78.35		78.35		78.35
<date-submission>	99.95		100		57.14		72.73
<degree>		99.82		100		35.29		52.17
<dedication>	99.95		100		40		57.14
<entitle>		99.9		0		0		0
<phone>		99.87		77.78		53.85		63.64

all fields		98.88		87.43		85.88		86.65	(micro average)
			98.88		82.83		72.54		75.8	(macro average)
```

**Comment by k8si** [comment]
I am using the test data produced by

> mvn generate-resources -Ptrain_header -e

(the one that gets stored in grobid-home/tmp). 

However, I just realized that this file contains no instances of the labels I mentioned. So that must be why these fields are never evaluated. Thanks!
