### ISSUE TITLE
Issue with consolidateCitations and BibTeX (author: "and null")

### ISSUE THREAD

**Issue by geritwagner** [kermitt2/grobid#837]
I encountered an issue when parsing citations with consolidateCitations enabled (v 0.7.0). The author field contains several "and null" parts. This is BibTeX specific, it is not the case when retrieving TEI instead. The issue occurs in processReferences and processCitation (I did not test it for other services). It can be reproduced with the following code:

```
curl -X POST -H "Accept: application/x-bibtex" -d "consolidateCitations=1&citations=Abbasi, A., Zhou, Y., Deng, S., and Zhang, P. 2018. “Text Analytics to Support Sense-Making in Social Media: A Language-Action Perspective,” MIS Quarterly (42:2), pp. 427-464." localhost:8070/api/processCitation
```
Output:
```
@article{-1,
  author = {Abbas, Ahmed and null and Zhou, Yilu and Deng, Shasha and Zhang, Pengzhu and null and null and null},
  title = {Text Analytics to Support Sense-Making in Social Media: A Language-Action Perspective},
  journal = {MIS Quarterly},
  publisher = {MIS Quarterly},
  year = {2018},
  pages = {427-464},
  volume = {42},
  number = {2},
  doi = {10.25300/misq/2018/13239}
}
```

**Comment by kermitt2** [comment]
Hello @geritwagner !

Thank you for the issue.

I am testing with current master version,  as the `null` are not visible: 

```
lopez@smallbook:~/tmp$ curl -X POST -H "Accept: application/x-bibtex" -d "consolidateCitations=1&citations=Abbasi, A., Zhou, Y., Deng, S., and Zhang, P. 2018. “Text Analytics to Support Sense-Making in Social Media: A Language-Action Perspective,” MIS Quarterly (42:2), pp. 427-464." localhost:8070/api/processCitation
@article{-1,
  author = {Abbas, Ahmed and Zhou, Yilu and Deng, Shasha and Zhang, Pengzhu},
  title = {Text Analytics to Support Sense-Making in Social Media: A Language-Action Perspective},
  journal = {MIS Quarterly},
  publisher = {MIS Quarterly},
  date = {2018-02-02},
  year = {2018},
  month = {2},
  day = {2},
  pages = {427-464},
  volume = {42},
  number = {2},
  doi = {10.25300/misq/2018/13239}
}
```

**Comment by geritwagner** [comment]
Hello @kermitt2,

thank you for looking into this, and sorry for not testing the latest master version. I am using Docker and would wait for the next version then. The issue can be closed.

**Comment by lfoppiano** [comment]
@geritwagner actually, FYI there is a temporary docker version [0.7.1-SNAPSHOT](https://hub.docker.com/layers/grobid/grobid/0.7.1-SNAPSHOT/images/sha256-4c3ab9d8ec734b9d82a2cf49c82dc3a9b7dd23d6eb309e9252893ec706983c5b?context=explore) which is 2 weeks old.
