### ISSUE TITLE
nb_thread => nbThread: Typo in doc

### ISSUE THREAD

**Issue by lucbouge** [kermitt2/grobid#841]
In the doc at https://grobid.readthedocs.io/en/latest/Training-the-models-of-Grobid/

> The `nb_thread` parameter in the configuration file grobid-home/config/grobid.yaml can be increased...

After the `config/grobid.yaml ` file, it looks like it is  `nbThreads` (plural).

**Comment by kermitt2** [comment]
Typo corrected, I close the issue :) 
Thank you @lucbouge  !
