### ISSUE TITLE
Don't let grobid occupy 8070 port when using docker image

### ISSUE THREAD

**Issue by JaniceXiong** [kermitt2/grobid#855]
Hi, I saw the document that we can map 8070 to 8080 if we want to use grobid on 8080. 
But in this way, 8070 is still used for grobid. Here I have another need that 8070 is not available and I don't want grobid occuping on this port. How can I do it if I use docker image?

**Comment by kermitt2** [comment]
Hello @JaniceXiong !

When using the docker image with port mapping, 8070 is **not** used on the host machine by Grobid, only "inside" the container. 

For instance, I start Grobid image with mapping to 8080:

```
docker run -t --rm --init -p 8080:8070 lfoppiano/grobid:0.7.0
```

Port 8070 on the host machine is free (checked with `sudo lsof -i -P -n | grep LISTEN` on linux). 

If you want Grobid to use another port inside the container, you can always indicate another port in the config file, see the documentation -> https://grobid.readthedocs.io/en/latest/Configuration/#service-configuration (last paragraph)
but it does not impact the host machine where the container is running.
