### ISSUE TITLE
Questions/clarification on training

### ISSUE THREAD

**Issue by mneis1** [kermitt2/grobid#856]
I'm trying to understand when an xml file should be deleted vs corrected when training grobid. In my instance, I'm trying to train grobid on some unique pdf's for fulltext extraction. 

I generated the training xml's from the pdf's, and annotated the segmentation structure. When I went to annotate the fulltext training xml's, I found that they contain headnote lines that don't relate to the document text (its just a disclaimer on all pages). I don't see anything in the fulltext annotation documentation about how I should handle that kind of text which makes me think that the fulltext xml's should be deleted as it states in the training section of the documentation. If that's the case, I don't see how I could train fulltext at all in my instance since those headnotes are in every one of my fulltext training xml's. 

Is there a specific annotation I should use for a headnote in the fulltext training xml? If I do need to delete the fulltext training xml's, should I train with the segmentation training xml's and regenerate the training data?

**Comment by kermitt2** [comment]
Hello @mneis1 !

> should I train with the segmentation training xml's and regenerate the training data?

Yes this is the expected process. First fix segmentation issues in the segmentation training xml and model, then retrain the segmentation model and regenerate the training files for the fulltext model. It should produce fulltext training data following the segmentation-level example, so without headnotes and so one. 
This is cumbersome to have to retrain the segmentation model, but this modularity avoids annotating too much stuff for each model. 

I need to describe the process in the documentation, sorry for not being clear in the current state. 

Normally, no text content should be deleted in the training fulltext files. It should be fixed at the level of the segmentation model. If some text still not relevant appears in the fulltext training data, we just ignore it and leave it without any fulltext markup - it will be considered/learnt as "noise" by the fulltext model.

**Comment by mneis1** [comment]
Ahhh that makes sense! Thank you so much!
