### ISSUE TITLE
How to handle table of contents that span multiple pages?

### ISSUE THREAD

**Issue by mneis1** [kermitt2/grobid#860]
Im trying to figure out how to work with a table of contents that spans more than one page. I tried setting each section of the table of contents with the table of contents div label but after training the segmentation model it only recognizes the first page of that the table of contents is on as the table of contents and table of content text on the following pages get labeled as body. I'm thinking maybe I should wrap the table of contents within the front tag but I don't know if that would be the right thing to do. Any thoughts?

**Comment by mneis1** [comment]
I found some examples in the included training files that shows using two different toc divs for a table of contents that spans two pages is the way to go. I may just need more training data.

**Comment by kermitt2** [comment]
Yes you can segment the pieces on different pages. 

There are very few tables of content in the training data, so I considered that, for the moment, it's not usable yet. 

Table of contents are annotated in the training data, there are introduced as a label in the  segmentation model (so if I remember well, they could be predicted as "area"), but there are not outputted in the final TEI file. What is missing is more tables of content in the training data and, second, a way to structure the table of content it self. We could output in the TEI the table of content as blob of text, but it's not very satisfactory.
