### ISSUE TITLE
Should I put a space in between a heading that was split?

### ISSUE THREAD

**Issue by mneis1** [kermitt2/grobid#861]
I'm annotating some fulltext training data and came across an instance that makes me question what will alter the stream of text or not. 

I have the following block of data after generating training data:
`<head>3.2.1 (U) Staffing</head>`
`<figure type="table">Criteria<lb/>`
Each are on separate lines in the file.

"Criteria" should be in the head section after "Staffing" but there is no space between `</head>` and `<figure type="table">`. There is a space in the header of the actual PDF but im not sure if the fixed annotation should be `<head>3.2.1 (U) StaffingCriteria</head>` or `<head>3.2.1 (U) Staffing Criteria</head>`. 

Any thoughts?

**Comment by kermitt2** [comment]
Hi @mneis1  !

In the generated training data, an end of line is equivalent to a space. And the two tokens should be separated to introduce a new label. So `<head>3.2.1 (U) Staffing Criteria</head>` should be the right one.

**Comment by mneis1** [comment]
Thanks so much @kermitt2 ! I really appreciate your help.

Just to clarify, does adding more breaks between labels affect the amount of spaces? For instance, does:
`<p>test</p>`
`<p>string</p>`

and 

`<p>test</p>`
` ` (ignore the space just imagine this is a new line)
`<p>string</p>`

and 

`<p>test</p>`
` `  (ignore the space just imagine this is a new line)
` `  (ignore the space just imagine this is a new line)
`<p>string</p>`

all equal the string "test string" with one space or will 2 and 3 have extra spaces?

Also is there anything wrong with ending the label on a new line? Like: 
`<p>test`
`</p>`

Once again, thanks for all your help!

**Comment by kermitt2** [comment]
You're very welcome @mneis1 !

Adding more space or end of line in the training XML files has no impact. They are all seen as one delimiter. So you can introduce EOL/spaces to improve readability. 

The training file is simply used to align tokens with the feature file and get a label (with the XML mark-up).

The actual layout information, delimiters, space, etc. are all captured in the feature files that come with the TEI for training.

The idea is that the TEI file captures the labellng information that is stable over time. The feature files capture all the rest and can be updated each time we add/change features or improve pdfalto to better extract tokens and layout information (for instance usually there is no space character in a PDF, they are introduced by the PDF parser that tries to detect token delimiters based on font size and positions).

**Comment by mneis1** [comment]
Thanks! Thats a huge help!
