### ISSUE TITLE
Difference between Caption and Section extraction in GROBID 0.7.0

### ISSUE THREAD

**Issue by Apurv3377** [kermitt2/grobid#863]
Hello, 

I have been evaluation GROBID for multiple semantic structures. And when it comes to Caption and Section Header extraction, I could not see unique tags for both in TEI XML. Instead, they are both appearing under the tag "Head."
Is there any other way I can extract Section Headers and Captions separately?

For example 

`<div xmlns="http://www.tei-c.org/ns/1.0"><head n="1">Introduction</head><p>Despite the proliferation of clustering algorithms (Kmeans-based, spectral, density-based, statistical), hierarchical clustering (HC) algorithms still are one of the most commonly used variants. This is attributed to their parameterless nature and their simplicity of implementation. No cluster parameter is required because HC builds a nested hierarchy of the clusters formed, often visualized using dendrograms. Dendrograms can be 'cut' at any level to form the desired number of clusters.</p><p>Many HC algorithms run in Ω(N 2 ) time because all pairwise distances are computed. This limits their applicability to rather small datasets. Solutions exist that attempt to mitigate the large runtime by means of approximations, heuristic search, projections, etc. As we will discuss in depth in the Related Work Section, many of these algorithms come with several assumptions or traits that impose certain limitations: complex parameter choices, applicability for specific linkage functions</p><p>• Introduction of a single data property B for adaptive analysis to capture the computational difficulty of hierarchical clustering.</p><p>1.1 Overview Our clustering algorithms consist of two phases. The first phase is the same for all algorithms and partitions the data into sets of close points. The algorithm PerturbMultiPartition, described in Section 4, constructs sets of neighboring points by first perturbing the points given to deal with unfavorable point arrangements and then partitioning them using random projections onto randomly chosen lines. The distances between points on a projected line are scaled by the same factor for all points in expectation. So, close points in the high-dimensional space remain close on the random line and distant points remain distant.</p><p>The second phase uses the sets resulting from the partitioning to create clusters efficiently by computing distances only for pairs of points contained in the same set. Thus, instead of computing the entire distance matrix of size Ω(N 2 ) for N points, our algorithm generally requires much fewer distance computations. Specifically, the number of required distance computations depends on the density of data points as discussed and formalized in Section 5.</p></div>`
 
and 

`<figure xmlns="http://www.tei-c.org/ns/1.0" type="table" xml:id="tab_3"><head>Table 2 :</head><label>2</label><figDesc>The HCs (i.e. dendrograms) computed by the RP-SLC/ALC algorithms and traditional HC algorithms are almost identical. 100%</figDesc><table><row><cell>2000</cell><cell></cell><cell></cell><cell></cell><cell></cell><cell>8000</cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell></row><row><cell></cell><cell cols="2">Single¡Linkage</cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell></row><row><cell>Time (sec)</cell><cell cols="2">Clustering</cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell cols="2">Average¢Linkage Clustering</cell><cell></cell></row><row><cell>1000</cell><cell></cell><cell></cell><cell>22x</cell><cell></cell><cell cols="2">4000</cell><cell></cell><cell></cell><cell></cell><cell></cell></row><row><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell></cell><cell>10x</cell><cell></cell></row><row><cell></cell><cell></cell><cell></cell><cell></cell><cell>RP SLC</cell><cell></cell><cell></cell><cell></cell><cell cols="2">RP£ALC</cell><cell></cell></row><row><cell>0</cell><cell>10K</cell><cell>20K</cell><cell>30K</cell><cell>40K</cell><cell>50K</cell><cell>0</cell><cell>1K</cell><cell>2K</cell><cell>3K</cell><cell>4K</cell></row><row><cell></cell><cell></cell><cell cols="3">Number of Objects</cell><cell></cell><cell></cell><cell></cell><cell>Number of Objects</cell><cell></cell><cell></cell></row></table></figure>`

**Comment by kermitt2** [comment]
Hello @Apurv3377 !

This is actually an XML question :)

We usually use XPath to get structured content: 
- `"//dev/head"` for section header
- `"//figure/head"` for figure header

In python, you can use lxml, which is very good (you will need to specificy the namespace `http://www.tei-c.org/ns/1.0` as argument). There are good xml libraries in every languages. 

With command line xmllint it's something like this: 

```
xmllint --xpath "//*[local-name()='div']/*[local-name()='head']" file.xml
```

```
xmllint --xpath "//*[local-name()='figure']/*[local-name()='head']" file.xml
```
because xmllint does not support namespaces setting. 

Hope this helps !
