### ISSUE TITLE
Where do you set max.connections in GROBID 0.7?

### ISSUE THREAD

**Issue by keto33** [kermitt2/grobid#876]
In the previous versions, I could change the number of connections in `grobid-home/config/grobid.properties`

`org.grobid.max.connections=10`

but apparently, this file is deprecated and no longer used. However, there is no instruction (at least, I didn't find) on where the settings can be adjusted.

**Comment by lfoppiano** [comment]
Dear @keto33, it should be under `grobid` and is called `concurrency`. 

See https://grobid.readthedocs.io/en/latest/Grobid-service/#parallel-mode
