### ISSUE TITLE
Error reading from remote server

### ISSUE THREAD

**Issue by angelosalatino** [kermitt2/grobid#877]
Hello all,

I have installed a GROBID client on my server. It was working perfectly until 2 days ago.

Since I am in development phase, I am testing always the same bunch of papers. Up to two days ago, GROBID would classify them, without problem. Now, I get always the same error to the very same papers.

From the web interface, I get:

```
Error encountered while requesting the server.
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /grobid-test/api/processHeaderDocument.

Reason: Error reading from remote server
```

To see whether the GROBID instance I am using is corrupted, I installed a second instance of GROBID on a second server (much powerful of the first one) and still I cannot get away with it. Actually, here the process seems stuck and does not return any error message.

For the sake of test, I tried also this client: https://cloud.science-miner.com/grobid/, but I get: 
```
Error encountered while requesting the server.
{ "message":"The upstream server is timing out" }
```

Ho can I fix this?

I just want to add further details, so you can reproduce the error.

I go to the web page of GROBID http://localhost:8070
Then, I go to TEI,
Then, Process Header Document
Then, I check Consolidate header (only)
Load the pdf
And hit Submit.

**Comment by angelosalatino** [comment]
UPDATE:

if I CURL the API, it works!

It is not working via the web interface (see screenshot), but if I launch ```curl -v --form input=@./2003.12611.pdf localhost:8070/api/processHeaderDocument```, it works perfectly.

![Screenshot 2021-12-17 at 15 32 11](https://user-images.githubusercontent.com/6604456/146559932-a099f0ba-b1db-4073-b677-733177ed0b04.png)

Any help is really appreciated.

Thank you
Angelo

**Comment by angelosalatino** [comment]
Further update.

We are connecting to the very same instance of GROBID with the python client. In the past, was working perfectly. Now, instead I get:

```
Processing of ./file.pdf failed with error 408
```

**Comment by kermitt2** [comment]
Hello @angelosalatino !

Thanks for using Grobid. 

This kind of proxy errors are not related to Grobid, but to your environment. In that case your web client is connecting to a proxy even for localhost. On linux for instance, you can set some exception for localhost for you tests: 

```
$ gsettings set org.gnome.system.proxy ignore-hosts "['localhost']"
```

On other OS, it's done differently. 

You can also check the proxy settings of your web browser.

Error 408 means timeout. Timeout comes usually from too large documents, or too high concurrency on your server given the number of available cores/threads (default is 10). You can change the timeout and the concurrency parameters of the server as documented [here](https://grobid.readthedocs.io/en/latest/Configuration/). The python client adjusts the query rate itselt based on the server response, but it also takes a parameter `n` for parallel requests that you might want to decrease (see [here](https://grobid.readthedocs.io/en/latest/Frequently-asked-questions/#could-we-have-some-guidance-for-server-configuration-in-production)).

**Comment by angelosalatino** [comment]
Thanks a lot @kermitt2 

I will adjust the server parameters then and see how it goes.

Thank you again.
