### ISSUE TITLE
Training fulltext on newly created training data fails with "error: no train data loaded"

### ISSUE THREAD

**Issue by mneis1** [kermitt2/grobid#879]
I've generated and corrected some training data for the full text model but when I try to run the training using command `java -Xmx1024m -jar grobid-trainer/build/libs/grobid-trainer-0.7.0-onejar.jar 0 fulltext -gH grobid-home` , I get the following output:

```
path2GbdHome=grobid-home   path2GbdProperties=grobid-home/config/grobid.properties
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
sourceTEIPathLabel: /grobid-0.7.0/grobid-home/../grobid-trainer/resources/dataset/fulltext/corpus/tei
sourceRawPathLabel: /grobid-0.7.0/grobid-home/../grobid-trainer/resources/dataset/fulltext/corpus/raw
trainingOutputPath: /grobid-0.7.0/grobid-home/tmp/fulltext1256019064274288690.train
evalOutputPath: null
40 tei files
        epsilon: 1.0E-4
        window: 20
        nb max iterations: 1500
        nb threads: 12
* Load patterns
* Load training data
warning: missing tokens, cannot apply pattern
error: no train data loaded
```

It works without my training data. Just to double check myself, I regenerated the training data and tried using it completely unedited but it still fails. Any idea what I'm doing wrong?

**Comment by kermitt2** [comment]
Hi @mneis1 !

I am sorry there is a problem with the logs for the training command that I did not manage to correct in this version and the current master. 

First, despite the error message "warning: missing tokens, cannot apply pattern", the error is normally a non well-formed training XML file. Usually missing or wrong closing tag. Normally the logs are written on the console (and in a file) and you can see which XMLfile is failing for correction. 

If I remember well (I can't test it right now), to force the logs to be available in the console what is possible to do is to comment the lines 412-414 in `build.gradle`, those ones under `configurations`:

```gradle
configurations {
        //all*.exclude group: 'org.slf4j', module: "slf4j-jdk14"
        //all*.exclude group: 'org.slf4j', module: "slf4j-log4j12"
        //all*.exclude group: 'log4j', module: "log4j"
    }
```

**Comment by mneis1** [comment]
This solved it! Thanks so much @kermitt2 !
