### ISSUE TITLE
deploy over streamlit or azure function

### ISSUE THREAD

**Issue by wanghaisheng** [kermitt2/grobid#883]
anyone here try to deploy service to streamlit or other platform

**Comment by lfoppiano** [comment]
You can definitely deploy grobid on azure by using the "App service" and deploy through containers using the docker image. 
I'm not sure about streamlit.

**Comment by wanghaisheng** [comment]
azure function got 1 million free call .so I want to take advantage of this instead of my local dev computer to provide consistent transform i can use in my local project~  @lfoppiano

**Comment by lfoppiano** [comment]
With docker you can deploy grobid on azure, aws, gcloud or even nativaly
