### ISSUE TITLE
Conversion between output formats

### ISSUE THREAD

**Issue by Phyks** [kermitt2/grobid#90]
Hi,

Just wondering, by chance, do you know any tool to handle and convert Grobid output to some other formats? For instance http://jats.nlm.nih.gov/archiving/tag-library/1.1/.

Thanks!

**Comment by kermitt2** [comment]
Hello!

Well, there is a BibTex output for citations :)

I don't have style sheets for converting GROBID's TEI to other formats, but maybe other users have something. 

Personally in different projects, I am using the TEI output as a document ingestion format, so as a working format to merge various heterogeneous documents. So I have rather the opposite, tools to convert various publishers native XML formats into the same TEI as GROBID produce, see this project: https://github.com/kermitt2/Pub2TEI
The motivation here, it that TEI supersedes all these formats and can accommodate well various other document types (patent, books, etc.), noisy text and automatic annotations. Something like JATS for instance is rather an exchange format than a working format.

**Comment by Phyks** [comment]
Concerning BibTeX output, you mean using https://github.com/kermitt2/grobid-example?

Ok for the formats. These are formats I am not at all familiar with, so I may miss important points to determine which one is the best one.

If by chance someone has a style sheet for converting TEI to JATS (or reciprocally), I would be really interested in it.

In the meantime, as it is more a question than a real Grobid issue, I guess this issue can be safely closed.
