### ISSUE TITLE
Incorrect sentences coordinates

### ISSUE THREAD

**Issue by NicolasKieffer** [kermitt2/grobid#908]
Sentences sometimes have wrong coordinates.

Sample files used (PDF, TEI & training files) : [60806_R1.zip](https://github.com/kermitt2/grobid/files/8496318/60806_R1.zip)

Notes:
- borders are rendered by our application, based on the TEI elements `s[coords]` values (**which are usually correct**)
- GROBID segmentation model have been trained on these PDF (and the fulltext model "recognises the refs correctly")

# Case sentence with element `<ref>` containing char `;`

#### PDF (coordinates rendering)

First bugged sentence
![image](https://user-images.githubusercontent.com/16922410/163573294-b27200b7-3e52-4768-92c7-e32dcf05df04.png)

Group of bugged sentence
![image](https://user-images.githubusercontent.com/16922410/163577300-47836cfb-5b12-421e-97f0-345cfaaef14a.png)

All sentences of this page
![image](https://user-images.githubusercontent.com/16922410/163576572-8a2b0517-1eca-4c2a-9ab6-046e3d168546.png)

#### TEI (processing)
![image](https://user-images.githubusercontent.com/16922410/163579306-e8809477-b25b-404a-8402-444c20bc9715.png)

Note : the right part of the ref is no longer in this file (after the `;` char)

#### TEI (training)
![image](https://user-images.githubusercontent.com/16922410/163579408-e9d7c8bc-82ef-4f48-95b3-b6c6cb53b518.png)
Note : the entire ref is in this file

#### PDF (coordinates rendering)
![image](https://user-images.githubusercontent.com/16922410/163574989-8c5da530-d610-4457-86f8-20c323f29940.png)
![image](https://user-images.githubusercontent.com/16922410/163575605-1c809982-a422-47b0-a299-7c20c75e6695.png)

#### TEI (processing)
![image](https://user-images.githubusercontent.com/16922410/163575763-25725da6-0b18-43f8-978c-0ef2781f86dc.png)

#### TEI (training)
![image](https://user-images.githubusercontent.com/16922410/163580803-f85bb8a2-b8bc-4808-92c6-a5c7ab927eae.png)

#### PDF (coordinates rendering)
![image](https://user-images.githubusercontent.com/16922410/163576111-28fbb27b-dbb2-4425-8756-c44ac22c107d.png)
![image](https://user-images.githubusercontent.com/16922410/163575880-7906bc04-040e-4d26-8428-043fc9a7a45e.png)

#### TEI (processing)
![image](https://user-images.githubusercontent.com/16922410/163576260-de17701a-6d09-42b5-b946-9c450b6d9105.png)

#### TEI (training)
![image](https://user-images.githubusercontent.com/16922410/163587843-b0984ea8-bef2-47a3-b8f7-39ec621f481f.png)

**Comment by kermitt2** [comment]
Hi @NicolasKieffer !

Many thanks for the very clear and documented issue. 

It is fixed in Grobid master, it was just one missing line in the "if" statement :/
The coordinates of the full sentence are correct too now.

```xml
<head n="2.1.1" coords="7,90.02,257.53,24.00,10.80;7,144.02,257.53,245.59,10.80">Static Model: 
a single season occupancy analysis</head>
<p>
     <s coords="7,90.02,285.13,391.18,10.80;7,72.02,312.73,464.39,10.80;7,72.02,340.33,467.45,10.80;
                        7,72.02,367.93,465.80,10.80;7,72.02,395.53,272.00,10.80">The MSDOM is a form of the 
     multi-state occupancy model with state uncertainty 
     <ref type="bibr" coords="7,72.02,312.73,118.87,10.80" target="#b59">(MacKenzie et al., 2009;</ref> 
     <ref type="bibr" coords="7,193.90,312.73,97.62,10.80">Nichols et al., 2007)</ref> and is defined below 
     with four states equivalent to the original co-occurrence model 
```

The fix will be part of next release `0.7.1`, which should come in the next days.
