### ISSUE TITLE
pdfalto process error

### ISSUE THREAD

**Issue by Yuxiang1995** [kermitt2/grobid#911]
Hello, when I process this PDF(https://arxiv.org/pdf/2204.12536.pdf), grobid throw the error
`org.grobid.core.process.ProcessPdfToXml: pdfalto process finished with error code: 143. [/opt/grobid/grobid-home/pdfalto/lin-64/pdfalto_server, -fullFontName, -noLineNumbers, -noImage, -annotation, -filesLimit, 2000, /opt/grobid/grobid-home/tmp/origin6001765469370931985.pdf, /opt/grobid/grobid-home/tmp/GwEkZWZaPN.lxml]
org.grobid.core.process.ProcessPdfToXml: pdfalto return message:
`
I was running at 0.7.1

**Comment by Yuxiang1995** [comment]
It is a especial case, for others grobid works well

**Comment by kermitt2** [comment]
Hi @Yuxiang1995 !

Thanks for the issue.

It works on my local Grobid with current master, which at this stage matches version `0.7.1`, I attached the resulting XML.

It doesn't work with the online demo https://grobid.science-miner.com due to timeout. pdfalto timeout is 20s on the demo. 

Could you give more details about environment? OS, are you running with container?
Which service are you calling? 
The SIGTERM kill error (143) is an indication of a system issue when running pdfalto on your machine. It is used to protect the JVM and keep the service alive despite problematic and corrupted PDF. How much memory is available for the service on your test? 

It might be due to the amount of available memory, because this PDF has huge vector graphics embedded figure 4, figure 7 etc.). pdfalto actually creates around 250MB of SVG files for these figures. 

[2204.12536.pdf.tei.xml.gz](https://github.com/kermitt2/grobid/files/8582611/2204.12536.pdf.tei.xml.gz)

**Comment by Yuxiang1995** [comment]
@kermitt2  Thanks for your reply！
I am running with the latest container 0.7.1, and calling service /api/processFulltextDocument. The memory is over 1TB on the server.

**Comment by lfoppiano** [comment]
@foobarbecue Grobid does not run natively on Windows 10. However, you can use it through docker without issues.  See https://grobid.readthedocs.io/en/latest/Troubleshooting/#windows-related-issues

**Comment by Changchun-lin** [comment]
I run git master code. And met the same issue.
my OS is  Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-47-generic x86_64)
log:

INFO  [2022-09-22 01:09:19,076] org.grobid.core.factory.GrobidPoolingFactory: Number of Engines in pool active/max: 1/10
ERROR [2022-09-22 01:09:19,096] org.grobid.core.process.ProcessPdfToXml: IOException while launching the command [/home/dsj/IdeaProjects/grobid/grobid-home/pdfalto/lin-64/pdfalto_server, -fullFontName, -noLineNumbers, -noImage, -annotation, -filesLimit, 2000, /home/dsj/IdeaProjects/grobid/grobid-home/tmp/origin2835843649374831213.pdf, /home/dsj/IdeaProjects/grobid/grobid-home/tmp/r2RZyDfBgs.lxml, --timeout, 6000] : Cannot run program "/home/dsj/IdeaProjects/grobid/grobid-home/pdfalto/lin-64/pdfalto_server": error=2, No such file or directory
ERROR [2022-09-22 01:09:19,097] org.grobid.service.process.GrobidRestProcessFiles: An unexpected exception occurs. 
! org.grobid.core.exceptions.GrobidException: [BAD_INPUT_DATA] An error occurred while converting pdf /home/dsj/IdeaProjects/grobid/grobid-home/tmp/origin2835843649374831213.pdf
! at org.grobid.core.document.DocumentSource.processPdfaltoServerMode(DocumentSource.java:238)
! at org.grobid.core.document.DocumentSource.pdfalto(DocumentSource.java:149)
! at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:64)
! at org.grobid.core.engines.FullTextParser.processing(FullTextParser.java:107)
! at org.grobid.core.engines.Engine.fullTextToTEIDoc(Engine.java:506)
! at org.grobid.core.engines.Engine.fullTextToTEI(Engine.java:496)
! at org.grobid.service.process.GrobidRestProcessFiles.processFulltextDocument(GrobidRestProcessFiles.java:208)
! at org.grobid.service.GrobidRestService.processFulltext(GrobidRestService.java:268)
! at org.grobid.service.GrobidRestService.processFulltextDocument_post(GrobidRestService.java:220)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:566)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
! at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89)
! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:505)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
! at java.base/java.lang.Thread.run(Thread.java:829)
192.168.113.2 - - [22/Sep/2022:01:09:19 +0000] "POST /api/processFulltextDocument HTTP/1.1" 500 131 "http://192.168.40.64:8070/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 9226

**Comment by lfoppiano** [comment]
Dear @Changchun-lin could you please share the PDF document?

**Comment by Changchun-lin** [comment]
sure

**Comment by lfoppiano** [comment]
@foobarbecue about your issue, please run grobid using docker or on Linux.

**Comment by lfoppiano** [comment]
@Changchun-lin Please send it again via the web interface, not by email

**Comment by Changchun-lin** [comment]
https://github.com/uni2022/filex/blob/main/S1369-7021%252813%252970015-4.pdf

**Comment by lfoppiano** [comment]
The pdf works fine, however you have an error saying: 

```
Cannot run program "/home/dsj/IdeaProjects/grobid/grobid-home/pdfalto/lin-64/pdfalto_server": error=2, No such file or directory
```

Are you sure the pdflato_server is in the correct directory and you've updated to the latest master?

**Comment by Changchun-lin** [comment]
yes,download from git at this month,09-05.









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Luca ***@***.***&gt;; 
发送时间: 2022年9月22日(星期四) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kermitt2/grobid] pdfalto process error (Issue #911)





 
The pdf works fine, however you have an error saying:
 Cannot run program "/home/dsj/IdeaProjects/grobid/grobid-home/pdfalto/lin-64/pdfalto_server": error=2, No such file or directory  
Are you sure the pdflato_server is in the correct directory and you've updated to the latest master?

**Comment by lfoppiano** [comment]
The issue seems in your set up rather than on grobid. I've tested both on linux and mac and both worked.

**Comment by Changchun-lin** [comment]
which is your linux version and jdk version?

**Comment by lfoppiano** [comment]
I ran it on docker. Your problem seems to be accessing `/home/dsj/IdeaProjects/grobid/grobid-home/pdfalto/lin-64/pdfalto_server` as I mentioned before. Please check that such file exists and it's executable.

**Comment by Changchun-lin** [comment]
dsj@dsj:~/IdeaProjects/grobid/grobid-home/pdfalto/lin-64$ sh pdfalto_server 
: not foundver: 2: 
: not foundver: 9: 
pdfalto_server: 10: Bad substitution
dsj@dsj:~/IdeaProjects/grobid/grobid-home/pdfalto/lin-64$ ll -lrt
total 36272
-rwxrwxrwx 1 dsj dsj     3589  9月  6 11:29 xpdfrc*
-rwxrwxrwx 1 dsj dsj     1066  9月  6 11:29 pdfalto_server*
-rwxrwxrwx 1 dsj dsj 37126056  9月  6 11:29 pdfalto*
drwxrwxrwx 8 dsj dsj     4096  9月  6 11:29 ../
drwxrwxrwx 2 dsj dsj     4096  9月  6 11:29 ./

**Comment by Changchun-lin** [comment]
Do have the cmd to execute the pdfalto_server ? I'd like to have a try

**Comment by lfoppiano** [comment]
Could you try `./pdfalto_server` instead?

**Comment by Changchun-lin** [comment]
dsj@dsj:~/IdeaProjects/grobid/grobid-home/pdfalto/lin-64$ ./pdfalto_server 
-bash: ./pdfalto_server: /bin/bash^M: bad interpreter: No such file or directory

**Comment by lfoppiano** [comment]
Did you download it with Windows and then copy it on Linux? 

It seems that this is your issue: https://stackoverflow.com/questions/14219092/bash-script-and-bin-bashm-bad-interpreter-no-such-file-or-directory 

I recommend you to delete it and clone it again: `git clone https://github.com/kermitt2/grobid`

**Comment by Changchun-lin** [comment]
Yes,i copy from windows. I have know that. Thank you

**Comment by lfoppiano** [comment]
@Changchun-lin I close this issue. If you still have the problem, please reopen and let me know whether there are additional information.
