### ISSUE TITLE
Wrong grobid version at dockerhub

### ISSUE THREAD

**Issue by Levalife** [kermitt2/grobid#917]
I'm trying to update grobid 0.7.0 version to grobid 0.7.1. But by running docker lfoppiano/grobid:0.7.1 or grobid/grobid:0.7.1 getting 0.7.2-SNAPSHOT
<img width="1381" alt="Снимок экрана 2022-05-27 в 11 49 41" src="https://user-images.githubusercontent.com/4678023/170665813-abc5eb29-4fa3-4da7-8936-d6a708eaad43.png">

<img width="861" alt="Снимок экрана 2022-05-27 в 11 45 09" src="https://user-images.githubusercontent.com/4678023/170664844-eceaab9f-ae5c-41b9-9184-bff3e7c070d5.png">

<img width="961" alt="Снимок экрана 2022-05-27 в 11 46 46" src="https://user-images.githubusercontent.com/4678023/170665040-b6f2e5e4-0dc2-419a-9aba-cd1aff5aa5a9.png">

**Comment by lfoppiano** [comment]
@Levalife I built the crf version lfoppiano/grobid:0.7.1 and I remember building it from the tag 0.7.1 (the jar inside should have the right version) so it should be just a problem of having the wrong version in `/api/version`. Nevertheless, I will have a look next week.

**Comment by lfoppiano** [comment]
Dear @Levalife, you're right indeed there is a problem with the version. I've updated the image `lfoppiano/grobid:0.7.1` on docker hub. Could you please double check?

**Comment by lfoppiano** [comment]
This is also fixed on the `grobid/grobid:0.7.1`
