### ISSUE TITLE
Hello, does this framework support the extraction of author details in PDF

### ISSUE THREAD

**Issue by xurent** [kermitt2/grobid#918]
If yes, how can I use to save the author's details in PDF. thanks

**Comment by elonzh** [comment]
Grobid can extract author name, email, affiliation from PDF. Try it in https://cloud.science-miner.com/grobid/

**Comment by lfoppiano** [comment]
Here the overview: https://grobid.readthedocs.io/en/latest/Principles/

@xurent You can take the output XML and parse it, by extracting the information you need.
