### ISSUE TITLE
two authors with same ORCID

### ISSUE THREAD

**Issue by Aazhar** [kermitt2/grobid#919]
Hello

we end up with two authors associated to the same ORCID when processing this document : https://mdpi-res.com/d_attachment/foods/foods-11-00274/article_deploy/foods-11-00274-v2.pdf

in this case, the DOI was extracted so I think we should fully rely on the consolidated metadata, the annotations are not always reliable..

Cheers
Achraf

**Comment by kermitt2** [comment]
Hi Achraf !

Indeed, without consolidation we have the author "Elena Bozzetta" associated to the ORCID of the previous author, while she does not have an ORCID on this paper. We should prevent having one ORCID attributed to more than one person.

With consolidation everything is correct now, following your fix in #838
