### ISSUE TITLE
build fail on windows 64-bit

### ISSUE THREAD

**Issue by raviraju** [kermitt2/grobid#92]
Hi,

I initially had JDK 64-bit version installed on my Windows 10.Compiling Grobid landed me into issue http://stackoverflow.com/questions/10533290/running-grobid-on-windows-64-bit 
Hence I uninstalled existing JDK 64-bit and tried 32bit, but still I am unable to compile grobid on JVM 32-bit
Please find the attached log for reference
[issue.txt](https://github.com/kermitt2/grobid/files/167650/issue.txt)

**Comment by kermitt2** [comment]
Hello! 

Thanks for the interest in GROBID.

As mentionned in the documentation, Windows is currently not supported by Grobid. There is no Wapiti library with JNI for Windows included in Grobid - only for Linux and Mac OS.

If Wapiti could be compiled for Windows and the dll provided, I would add it to Grobid and it would be a great addition ;)

**Comment by SomnathKadam** [comment]
Thanks for time saving comment.

**Comment by lfoppiano** [comment]
Hi @SomnathKadam, we've integrated the ported version of Wapity for Windows 64bit, thanks to the great job of @boumenot.

I'm going to close this issue. For any problem related to Wapiti on Windows, please refer to #74 . 

Cheers
Luca
