### ISSUE TITLE
Unable to proceed with ./gradlew clean install on macOS

### ISSUE THREAD

**Issue by afreenshakeel24** [kermitt2/grobid#925]
I tried with the command: ./gradlew clean install and I am getting the following error
<img width="568" alt="gr1" src="https://user-images.githubusercontent.com/71022185/174833349-cf86e88e-9640-44ff-a524-0784c780c21c.png">
I have both JDK and JRE installed and java version is 10
<img width="503" alt="gr2" src="https://user-images.githubusercontent.com/71022185/174833473-9d7c9f53-df05-4b2a-8bc0-eb88bee6d823.png">
<img width="465" alt="gr4" src="https://user-images.githubusercontent.com/71022185/174839736-b8fb7dfc-1d75-420f-b5b9-d96b32cc70c2.png">

The task that failed is
<img width="1111" alt="gr3" src="https://user-images.githubusercontent.com/71022185/174834181-afcf20f9-1757-423b-af19-958216926166.png">

**Comment by lfoppiano** [comment]
Hi @afreenshakeel24, could you please send the result (as text please) of `./gradlew --stacktrace --info`

**Comment by lfoppiano** [comment]
@afreenshakeel24 I'm closing this. If you still have the same problem please feel free to reopen it.
