### ISSUE TITLE
Help: Permanently run Grobid service

### ISSUE THREAD

**Issue by Xennis** [kermitt2/grobid#93]
In the [documentation](http://grobid.readthedocs.org/en/latest/Grobid-service/) it's described, that I can run the Grobid service by using the maven: `mvn jetty:run-war` The service stops, when I close the terminal. But how do I permanently run the service? I installed Jetty and created a `/opt/jetty/webapps/grobid.xml` file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/grobid</Set>
  <Set name="war">/webapps/grobid/grobid-service/target/grobid-service-0.4.1-SNAPSHOT.war</Set>
</Configure>
```
In this configuration file I set the `war` to the built `.war`-file in the `grobid-service/target/` directory. Now I can successfully access `http://localhost:8080/grobid/`. But when I want to access for instance `localhost:8080/grobid/processFulltextDocument`, I receive a 405 with the Jetty message _Method Not Allowed_.

1) Am I on the right track? 2) If yes, what is the correct configuration?

**Comment by kermitt2** [comment]
Hello!

The service can run like any web applications, by deploying the war with a web application server, e.g. Tomcat, JBoss, Glassfish, etc. and you would have then something permanent, that can be  administrated, secure, etc.

If you want to use jetty and have no production constraints (so quick and dirty is ok ;), you can always simply use maven and detached the process from your terminal, e.g.:

> nohup mvn -Dmaven.test.skip=true jetty:run-war &

For deploying the war on an separate jetty application server, your config file looks fine but I have very few experience with jetty, so I am not reliable at all :) 

Something to remember: as explained in the GROBID service manual, you need to set variables for the paths to the properties files and to GROBID_HOME before starting the service (for Jetty, I guess in this descriptor XML file). More simply, it can also be done manually in the file web.xml before creating the deployable war.
