### ISSUE TITLE
Support for Mac ARM-64

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#937]
In this thread we should collect all issues related to MacOS ARM. 

In general ARM is not yet supported. Please consider using Docker for the time being (https://grobid.readthedocs.io/en/latest/Grobid-docker/). Performances won't be the same due to the Rosetta interpreter. 

Since nobody has a Mac ARM help is more than welcomed.

**Comment by LukasWallrich** [comment]
Thanks for flagging that this will not work. However, I also can't get the docker to work ...

After downloading the image (`docker pull grobid/grobid:0.7.2-SNAPSHOT`) I need to remove the GPUs from the command given in the docs for the server to start (`docker run --rm --platform=linux/amd64 -p 8070:8070 grobid/grobid:0.7.2-SNAPSHOT`). However, in that case, the Docker crashes as soon as TensorFlow is called: 

```The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped```

That seems to be a [common issue](https://github.com/tensorflow/tensorflow/issues/52845) ... but are you aware of how to get grobid to work on an M2 mac?

**Comment by lfoppiano** [comment]
@LukasWallrich the OS of the host machine you tried to run them, was it a macOs or Linux ARM?

**Comment by LukasWallrich** [comment]
Mac OS wit M2

**Comment by kermitt2** [comment]
Thank you @LukasWallrich 

I am surprised that the current grobid image works on ARM, it should not :) 
So I suppose the amd64 image is emulated? which would impact runtime. 

My idea was to create multi-arch build images, but I've never tried to do it. 
It's also hard to test for me I must say (I only have access to a M1 mac, the one of my wife but she's using it a lot ;).

**Comment by LukasWallrich** [comment]
It is emulated - and therefore really rather slow ... but much better than
nothing.

Unfortunately I can't be of much use re the transition - don't really know
any of the technology this is based on ...

**Comment by jacksongoode** [comment]
Just to give an update from an M1 Pro user, the only thing that prevented me from running Grobid was lilibwapiti.dylib, which, once built on my machine, worked

**Comment by lfoppiano** [comment]
@jacksongoode in which directory did you copied it? Did you override the version under `mac-64`, under `grobid-home/pdfalto`?

**Comment by jacksongoode** [comment]
`grobid-0.7.2/grobid-home/lib/mac-64/libwapiti.dylib`

**Comment by lfoppiano** [comment]
@jacksongoode could you test the PR #975 ?

**Comment by jacksongoode** [comment]
@lfoppiano Sure! I'll get to it tomorrow!
