### ISSUE TITLE
Custom tag in header model

### ISSUE THREAD

**Issue by Tanmay98** [kermitt2/grobid#943]
So I created my own tags in the header model by doing all the necessary changes in:

- HeaderParser.java
- Biblioitem.java
- TEIFormatter.java
- TEIHeaderSaxParser.java

This gave me my own new tags in the output xml produced for only a single instance. 
My problem is that whenever the new tags are used for more than once in the header, I dont get that data in output prediction. 

Here is the code for my new tags looks like in TEIFormatter.java
<img width="822" alt="Screenshot 2022-08-23 at 10 33 55 AM" src="https://user-images.githubusercontent.com/31308303/186074112-d5d34553-3606-472d-b7cd-8109ac0a1a7c.png">

I tried checking the code for tags like docAuthor that grobid gives and I think you tend to save all instances in a list and then parse that list. Can you help me @kermitt2 ?

**Comment by Tanmay98** [comment]
Hi @kermitt2 , 
I think I got it, so you have used the list inherited from person class to store the authors,  editors. After duplicating for my own tag (eg. in this case petitioner), I made changes in the biblioitem.java file to the toTEIAuthor function.

This way I am getting my tag in the training results but I cant see the tag predicted after using procesFulltextDocument.
Can you help me why>? (Should I change the <author> tag in name-header model too??)

**Comment by Tanmay98** [comment]
Changing the author tag in the name_header model to my own custom tag worked for me !

**Comment by kermitt2** [comment]
Hi @Tanmay98 ! 

Indeed the tag need to be propagated to apply lower-level models. 

The data model for the tag depends on the "semantic" of the tag, which is selected when "decoding" the labeled data. If we have something that can occur several times in the results (like authors), we store every labeled sequence in a List. Other possibility is to concatenate what is labeled into a string that is extended as we find more labeled fields with this tag, or we can ignore additional labeled string after a first field is found.

**Comment by Tanmay98** [comment]
Thanks @kermitt2 for your reply!

**Comment by Tanmay98** [comment]
Hi @kermitt2 ,

So, I am a bit confused as to now i am getting the tags predicted several times but there is no text predicted in it. Can you tell me as to why it could be happening?

Look at the petitioner_lawer, respondent_lawer, etc. tags. They are getting shown several times now but there is not text in it.

<img width="742" alt="Screenshot 2022-08-29 at 12 03 34 PM" src="https://user-images.githubusercontent.com/31308303/187138380-aaa28c27-a25b-4457-80a1-1e3b4a001045.png">

**Comment by dlculver** [comment]
@Tanmay98 What exactly were the changes you made to those files you mention in your first post?
