### ISSUE TITLE
Can´t use ELMO in DeepLearning Train

### ISSUE THREAD

**Issue by rodyoukai** [kermitt2/grobid#946]
- What is your OS and architecture? Ubuntu 22.04

- What is your Java version (`java --version`)? openjdk version "1.8.0_342"

Hi @kermitt2, I have success to Train a citation model using DELFT but when I try to use ELMO y get this error message... 

`Loading data...
Error: either provide a path to a directory with the ELMo model individual options and weight file or to the model in a ZIP archive.
10000 total sequences
9000 train sequences
1000 validation sequences
ELMo weights used: /media/lopez/T51/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5`

Where can I found this file and how can I change the path ?

**Comment by lfoppiano** [comment]
Dear @rodyoukai, 
      You have to configure the ELMO embeddings under `delft/delft/resource-registry.json`, See the file: https://github.com/kermitt2/delft/blob/master/delft/resources-registry.json

change the path near this section: 
```
"embeddings-contextualized": [
        {
            "name": "elmo-en",
            "path-config": "/media/lopez/T51/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json",
            "path_weights": "/media/lopez/T51/embeddings/elmo_2x4096_512_2048cnn_2xhighway_5.5B/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5",
            "path-vocab": "data/models/ELMo/en/vocab.txt",
            "path-cache": "data/models/ELMo/en/",
            "cache-training": true,
            "lang": "en",
            "url_config": "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway_5.5B/elmo_2x4096_512_2048cnn_2xhighway_5.5B_options.json",
            "url_weights": "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway_5.5B/elmo_2x4096_512_2048cnn_2xhighway_5.5B_weights.hdf5"
        },
```

Are you using docker?

**Comment by rodyoukai** [comment]
Hi, @lfoppiano, im not using docker I am clone the project to my local, thanks for your answer I will try it

**Comment by kermitt2** [comment]
Hi @rodyoukai 

Yes you need to download manually the config and weights file for ELMo. Contrary to transformers and static embeddings, the automatic download is not written yet ! (my fault, I forgot to add it :) 

The two url are still working, so you just need to download and move these files in the path you indicated. 

ELMo is working very well for sequence labeling ! (and almost as fast as transformers in the last version of DeLFT)

**Comment by rodyoukai** [comment]
Thanks @kermitt2 I will follow your instructions.

**Comment by kermitt2** [comment]
Hi @rodyoukai !

>  tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor of shape [2048] and type float

It seems that you're out of memory with ELMo, it's a good sign that it was loaded :)

What's your GPU memory capacity? Normally I think I got ELMo running well with 4GB GPU memory, but for training it's rather something like 8GB.

**Comment by rodyoukai** [comment]
Hi @kermitt2, Thanks for the quick answer, I have 3GB for GPU, is there a  kind of workaround for this?

**Comment by kermitt2** [comment]
Unfortunately training with ELMo embeddings is not manageable with this amount of GPU memory (I don't think you can run it neither below 4GB, but not sure).

**Comment by rodyoukai** [comment]
Thanks for the answer @kermitt2, I have another question,bud you know if exist ELMo embeddings in Spanish and where can I download?

**Comment by rodyoukai** [comment]
Hi again @lfoppiano or @kermitt2 I need some advice, how can I create a ELMo embeddigns model in spanish? I supouse you create the english and french hdf5 files, can you share the process maybe I can generate my own embeddings in spanish....

**Comment by lfoppiano** [comment]
> Hi again @lfoppiano or @kermitt2 I need some advice, how can I create a ELMo embeddigns model in spanish? I supouse you create the english and french hdf5 files, can you share the process maybe I can generate my own embeddings in spanish....

@rodyoukai we used the already available ELMo embeddings provided by the authors of ELMo. I personally don't know exactly how to create a new ELMo embedding from scratch. You might check this issue https://github.com/kermitt2/delft/issues/155 but tests from Patrice did not show improvement so this implementation was not kept.

**Comment by kermitt2** [comment]
Hi @rodyoukai 

I give you more details: 

- English ELMo is from AI2, the authors of ELMo, at the time training a model (1B tokens) was done with 3 GPU during 2 weeks if I remember well
- Fench ELMo has been created by @pjox (who build OSCAR, which includes training resources for Spanish), he's likely the right person to contact if you want to push this forward

About [elmoformanylangs](https://github.com/HIT-SCIR/ELMoForManyLangs), it includes an ELMo pretrained model for Spanish. However after integrating and benchmarking these models into DeLFT (and I think I did it correctly), you can see that they were marginally better than static embeddings, and not at all at the level of the "standard" ELMo models:

https://github.com/kermitt2/delft/issues/155#issuecomment-1400735270

**Comment by rodyoukai** [comment]
Thanks for the answers @kermitt2 & @lfoppiano
