### ISSUE TITLE
reference model for markers and callouts

### ISSUE THREAD

**Issue by Tanmay98** [kermitt2/grobid#948]
Hi @kermitt2 ,

Do I have to explicitly train a model for callouts and markers for tables?
I mark the tables in the fulltext xmls using `<ref type="table">` but I was not able to find any data for this marker tag apart from in the shorttext model but it only contains `<ref type="biblio">` tags and not any type="table"?

**Comment by lfoppiano** [comment]
Hi @Tanmay98, 
  these markers are marked in the fulltext training data. 

<img width="742" alt="image" src="https://user-images.githubusercontent.com/15426/191577985-bf06ed5c-3725-4efc-8125-936ef5efbd08.png">

**Comment by Tanmay98** [comment]
Thanks for your help! I got it. @lfoppiano
