### ISSUE TITLE
Unsupported protocol in web app

### ISSUE THREAD

**Issue by malee1382** [kermitt2/grobid#949]
Hi,

As a newbie to developing web applications, I am developing an app (java 8, maven, tomcat, windows 10) using grobid. 

To be able to use grobid resources, I need to reach grobid-home folder as mentioned here [https://grobid.readthedocs.io/en/latest/Configuration/]

The code to find home folder is:

`String pGrobidHome = "src/main/resources/grobid-home";
GrobidHomeFinder grobidHomeFinder = new GrobidHomeFinder(Arrays.asList(pGrobidHome));
GrobidProperties.getInstance(grobidHomeFinder);`

and this works fine when I run my code locally (w/o tomcat). **PS. I run my code using WSL so it uses linux system.**

However, when I use the same code part in my app changing the path with, 

`ServletContext ctx=getServletContext();
String path = ctx.getRealPath("/WEB-INF/classess");`

I got the following error:

`Unsupported protocol for Grobid home at location: file:/C:/Users/u0156666/TOMCAT/apache-tomcat-9.0.65/webapps/webapp_war/WEB-INF/classes/grobid-home/lexicon/names/firstname.5k

org.grobid.core.main.GrobidHomeFinder.fail(GrobidHomeFinder.java:92)
	org.grobid.core.main.GrobidHomeFinder.getGrobidHomePathOrLoadFromClasspath(GrobidHomeFinder.java:141)
	org.grobid.core.main.GrobidHomeFinder.findGrobidHomeOrFail(GrobidHomeFinder.java:53)
	org.grobid.core.utilities.GrobidProperties.getInstance(GrobidProperties.java:97)
	main.java.mainProcess.<init>(mainProcess.java:48)
	main.java.FileUploadServlet.doPost(FileUploadServlet.java:55)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)`

Does it have something to with windows as it is not supported and I cannot use WSL with tomcat as it is not supported yet, or does
it simply tell the path to the home-folder is not correct or is it something else?

Thanks in advance!

**Comment by lfoppiano** [comment]
Hi @malee1382, 
   At a glance, I think the error `Unsupported protocol, seems a problem with the prefix, which should be `file://`. 

Generally, just a reminder that you might have further issues due to the lack of windows support. https://grobid.readthedocs.io/en/latest/Troubleshooting/#windows-related-issues

Regards
Luca

**Comment by malee1382** [comment]
Many thanks Luca!

Regarding windows, indeed I am using WSL(windows subsystem for linux) with intellij. So it works perfectly when I run my code locally. However, at this point when trying to reach grobid-home, being on a windows or linux does not matter I guess? 

As for the prefix, do you mean I should use it like:

`String path = ctx.getRealPath("//WEB-INF//classess//grobid-home");`

Apparently home finder reaches further than grobid-home as ...lexicon/names/firstname.5k. 
Maybe this has nothing to do with grobid but the way I am trying to reach the grobid-home in my webapp?

Kind regards,
Mehmet

**Comment by lfoppiano** [comment]
Dear @malee1382, 
   I though it was a problem with the prefix of the path that should be `file://` but now I'm not so sure anymore. 

Could you try instead to use: 

```java
GrobidProperties.getInstance(new GrobidHomeFinder().findGrobidConfigOrFail("src/main/resources/grobid-home"))
```

let me know if that works better

**Comment by malee1382** [comment]
Dear Luca,

It was my bad. Apparently the way I used servlet context is not correct or something missing there due to lack of my knowledge.

Now I have tried classloader as below:

`ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
 String ghPath = classLoader.getResource("/grobid-home").getPath();`

(root path is **WEB-INF\classes**) and it worked.

Many thanks again!

**Comment by lfoppiano** [comment]
Great! I close the issue. If you have any issue related to it, feel free to reopen.
