### ISSUE TITLE
Different (incomplete) extracted texts for each run

### ISSUE THREAD

**Issue by victoryhb** [kermitt2/grobid#953]
Hi, thanks for developing the awesome software!
When running Grobid (through grobid_client_python) with the processFulltextDocument command, I found that each run for the same PDF extracts slightly different texts, none of which is 100% correct. For example, the following image shows the extracted texts for the same paragraph in the same PDF, produced by running the same command (`grobid_client --input="test.pdf" processFulltextDocument`) twice.
![Screen Shot 2022-10-09 at 10 51 05 AM](https://user-images.githubusercontent.com/3033215/194735425-a9bb103f-aa7d-4b33-b09c-31c0da88b21e.png)
Both texts are missing some words, which make the sentences incomplete.
Is this the expected behavior? Is there a way to ensure that all words are included in the same output?

**Comment by kermitt2** [comment]
Hi @victoryhb 

Thank you for the issue !

This is not expected, nor easy to understand... normally everything in Grobid is deterministic (except training of deep learning models, but here the models stay the same), so there should not be any difference from one run to another one, although there might be differences between linux and macos (mainly due to system fonts). 

Would it possible to share the PDF and to give more information about your environment so that we can try to reproduce this behavior and fix it?

**Comment by victoryhb** [comment]
Hi @kermitt2, thank you for your reply.
Please see the PDF file below for an example.
[10.1145@2790296.pdf](https://github.com/kermitt2/grobid/files/9741605/10.1145%402790296.pdf)
Also I have attached the different outputs produced from the same command (`grobid_client --input="test.pdf" processFulltextDocument`) below:
[different_outputs.zip](https://github.com/kermitt2/grobid/files/9741612/different_outputs.zip)

My Environment:
MacOS 10.13.6
Grobid 0.7.1
grobid_client_python 0.0.4
pdfalto (manually compiled on MacOS) 0.5

I am glad to hear this is not the normal behavior. If this bug proves too hard too track down, at least I can switch to another environment. :) 
Thanks a lot.

Victor

**Comment by kermitt2** [comment]
Hi Victor,

I ran the PDF around 10 times on my linux install and I have a stable output:

```xml
<div
                xmlns="http://www.tei-c.org/ns/1.0">
                <head n="7.1">Three Stylistic Local Effects</head>
                <p>We manually downloaded 115 images from Flickr and resized them such that their larger 
dimension has 512 pixels. Seventy images were chosen for training and the remaining 45 images for 
testing. A professional photographer used Photoshop to retouch these 115 images and produce the 
datasets for three different stylistic local effects. She could perform a wide range of operations to adjust 
the images, including selecting local objects/areas with the region selection tool, creating layers with 
layer masks, and blending different layers using various modes, just to name a few. To reduce 
subjective variation during retouching, she used the "actions" tool, which records a sequence of 
operations and can be repeatedly applied to selected image regions.</p>
```

I think it's the same MacOS specific error as https://github.com/kermitt2/pdfalto/issues/123

... although having `pdfalto` eating random word on MacOS only does not make much sense to me. 

I can't test easily and I don't work on MacOS, so I would suggest to use the docker image to get stable/well tested/production results - or run directly the application on a Linux env.

**Comment by victoryhb** [comment]
Yes, I also think the bug is macOS-specific and I will switch to Docker for future extractions. Thanks a lot for your kind help! @kermitt2
