### ISSUE TITLE
Context is read only error

### ISSUE THREAD

**Issue by jjbenitez26** [kermitt2/grobid#96]
I'm trying to use GRID in an application in Grails. My code looks like this:
```
public String TeiHeader() throws Exception {

        String root = "/media/jose/Datos/DOCUMENTS/Datos/Gobid/GROBID_COMPILED";

        String pdfPath = root + File.separator + "doc" + File.separator + "GROBID.pdf";
        String pathGHome = root + File.separator + "grobid-home";
        String pathGProp = root + File.separator + "grobid-home" + File.separator + "config" + File.separator + "grobid.properties";
        String resp = "";

        MockContext.setInitialContext(pathGHome, pathGProp);
        GrobidProperties.getInstance();

        Engine engine = GrobidFactory.getInstance().createEngine();
        BiblioItem bi = new BiblioItem();

        resp = engine.processHeader(pdfPath, false, bi);

        MockContext.destroyInitialContext();

        return resp;

    }
```

This throw this error:
```
Class
javax.naming.OperationNotSupportedException
Message
Context is read only

Line | Method
->>  961 | checkWritable     in org.apache.naming.NamingContext
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    548 | createSubcontext  in     ''
|    574 | createSubcontext  in     ''
|    487 | createSubcontext  in org.apache.naming.SelectorContext
|    483 | createSubcontext  in javax.naming.InitialContext
|     37 | setInitialContext in org.grobid.core.mock.MockContext
|     76 | setInitialContext in     ''
|     42 | TeiHeader         in GrobidUtil.java
|      8 | index . . . . . . in UserManagerController.groovy
|    198 | doFilter          in PageFragmentCachingFilter.java
|     63 | doFilter . . . .  in AbstractFilter.java
|   1145 | runWorker         in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run               in java.lang.Thread
```

Someone told me it may be an attempt to use JDNI unconfigured.
Someone can help me find a solution?
For months I stuck in this.
Thanks in advance !!!

**Comment by lfoppiano** [comment]
Dear @jjbenitez26, the code looks correct. 

Googling around I have the impression your error is due to JNDI connection configuration issues (see http://stackoverflow.com/questions/14580286/context-is-read-only#14580519).  

Sometimes GRAILS requires quite some work on the dependencies, it could also well be that you have the JNDI dependency in your project and is clashing with the SelectorContext. If you don't need the database  you should remove it.  
What you can try to do is to run the same code using https://github.com/kermitt2/grobid-example, it it's working, then is a problem of GRAILS. 

Cheers
Luca

**Comment by jjbenitez26** [comment]
Thanks for the quick reply !
I'm not using JNDI directly,  I am using JDBC to a Postgresql database. The only thing I see related is a GROBID dependency : "directory-naming:naming-java:0.8". 
When i compile the project in a WAR and run it, the error disappears and yours examples work perfect in java applications, but in Grails not work.
I have no idea that I set to work, it really is a headache.
Thanks for your help !

**Comment by lfoppiano** [comment]
> When i compile the project in a WAR and run it, the error disappears and yours examples work perfect in java applications, but in Grails not work.

Which project are you talking about? The grails project running as a war or the grobid example project?

**Comment by jjbenitez26** [comment]
Sorry my english !
The grails project only work when i create a WAR and deploy it.
Your example in a non-web java application works good.

**Comment by lfoppiano** [comment]
@jjbenitez26 no problem. If this is the case then is the usual problem of running projects with Grails. 
For what concern GROBID there are no problem in my view. My suggestion is to check whether while running grails (using grails) something is misconfigured (maybe debugging it would help).

**Comment by lfoppiano** [comment]
@jjbenitez26 I'm closing it, since seems to be not a problem of GROBID. If you have further information or development to share, feel free to reopen it.

**Comment by digitalw** [comment]
Seems like I have the same/or related issue in tomcat8 
the following code produces the `javax.naming.OperationNotSupportedException: Context is read only` error when the web application is deployed:    

    javax.naming.OperationNotSupportedException: Context is read only
	at org.apache.naming.NamingContext.checkWritable(NamingContext.java:967) ~[tomcat8-catalina-8.0.38.jar:8.0.38]
	at org.apache.naming.NamingContext.createSubcontext(NamingContext.java:553) ~[tomcat8-catalina-8.0.38.jar:8.0.38]
	at org.apache.naming.NamingContext.createSubcontext(NamingContext.java:579) ~[tomcat8-catalina-8.0.38.jar:8.0.38]
	at org.apache.naming.SelectorContext.createSubcontext(SelectorContext.java:488) ~[tomcat8-catalina-8.0.38.jar:8.0.38]
	at javax.naming.InitialContext.createSubcontext(InitialContext.java:489) ~[na:1.8.0_131]
	at org.grobid.core.mock.MockContext.setInitialContext(MockContext.java:39) ~[grobid-core-0.4.2-SNAPSHOT.jar:na]
	at org.grobid.core.mock.MockContext.setInitialContext(MockContext.java:81) ~[grobid-core-0.4.2-SNAPSHOT.jar:na]
	at OntoRais.MetaData.Grobid.init(Grobid.java:43) ~[classes/:na]


The source at Grobid.java:43:    

     @PostConstruct
    public void init() {
        try {
            String path = getClass().getClassLoader().getResource("grobid-home").getPath();
            pGrobidHome = path;
            pGrobidProperties = path + "/config/grobid.properties";
            System.out.println(pGrobidHome+" "+pGrobidProperties);
            MockContext.setInitialContext(pGrobidHome, pGrobidProperties);

            engine = GrobidFactory.getInstance().createEngine();
        } catch (Exception e) {
            logger.error(e.getMessage(),e);
        }
    }


Any help would be greatly appreciated
Benedict Wright
