### ISSUE TITLE
TextUtilities.cleanField returns null

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#968]
I've got some cases where the process fails because the method cleanField get an empty string and returns null. 

```
public final static String cleanField(String input0, boolean applyStopwordsFilter) {
 [...]
        if (input0.length() == 0) {
            return null;
        }
 [...]
```

The case is quite special but could happens: 

<img width="849" alt="image" src="https://user-images.githubusercontent.com/15426/202997995-56ec40a0-e50e-49c7-a384-f8845c1d5ed6.png">

I'm not sure what would be the best approach to fix it... either null check (which needs changes in many places) or perhaps at least avoid to replace "" with Null. 

Not sure honestly. 😄

**Comment by kermitt2** [comment]
Hi Luca, 

This was change at some point relatively recently:

https://github.com/kermitt2/grobid/blob/master/grobid-core/src/main/java/org/grobid/core/data/BiblioItem.java#L2148

The latest version includes these updates, but not version 0.7.0.

**Comment by lfoppiano** [comment]
Oh... sorry I missed it. 
I'm still at 0.7.1 and I should update to 0.7.2 👍

**Comment by kermitt2** [comment]
Ah yes it's in 0.7.2 but not in 0.7.1
