### ISSUE TITLE
Load Library Failed: libnvidia-ml.so.1

### ISSUE THREAD

**Issue by LukasTr** [kermitt2/grobid#969]
I'm trying to run full Grobid on Ubuntu 22.04.1 LTS on an Amazon EC2 g4ad.xlarge instance with Docker.

I have run the following steps to install (from a fresh instance), and I'm getting the error "load library failed: libnvidia-ml.so.1" (seen at the bottom of the listing below). I am not sure if this is has even anything to do with Grobid. 

How could I start investigating this issue?

> sudo apt-get update
> 
> sudo apt-get install docker.io
> 
> sudo docker pull grobid/grobid:0.7.2
> 
> sudo docker run --rm --gpus all -p 8070:8070 grobid/grobid:0.7.2
> >> docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
> 
> 
> 
> distribution=$(. /etc/os-release;echo $ID$VERSION_ID)       && curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | sudo apt-key add -       && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
> 
> sudo apt-get install -y nvidia-docker2
> 
> sudo apt-get install -y nvidia-container-toolkit
> 
> sudo docker run --rm --gpus all -p 8070:8070 grobid/grobid:0.7.2
> >> docker: Error response from daemon: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
> >> nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
>

**Comment by kermitt2** [comment]
Hi @LukasTr !

I think this is likely the missing nvidia-container-toolkit

Did you try to restart docker before launching the docker run after install of nvidia-container-toolkit ?

**Comment by LukasTr** [comment]
Thanks for your quick response. I rebooted the entire system and tried again, same result.

**Comment by kermitt2** [comment]
I am not sure to be very helpful, in principle Ubuntu 22.04.1 LTS is well supported:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

It seems that removing entirely docker and nvidia-container-toolkit and reinstalling can help because of some symbolic link issues:

https://github.com/NVIDIA/nvidia-docker/issues/1682#issuecomment-1250952249
https://github.com/NVIDIA/nvidia-docker/issues/1637

**Comment by LukasTr** [comment]
Thank you! Unfortunately, that doesn't make a difference. I did:

```
sudo apt-get remove nvidia-container-toolkit
sudo apt-get remove docker.io
sudo reboot
sodo install nvidia-container-toolkit
sudo install docker.io
sudo docker run --rm --gpus all -p 8070:8070 grobid/grobid:0.7.2
```

**Comment by kermitt2** [comment]
Just to be 100% sure that it's not Grobid related (almost sure!), do you have the same error with the basic CUDA container: 

> sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi

You need the nvidia driver installed on your machine, it might be the issue.  

I found this related to your problem: https://github.com/NVIDIA/nvidia-docker/issues/539

**Comment by LukasTr** [comment]
Thanks for your help. Indeed it is not a Grobid error, as the same problem appears when running the CUDA base image.

I was mistaken in the driver selection -- the instance "g4ad" I have chosen is actually one with an AMD GPU. The "g4dn" is one with an NVidia GPU. After running all these steps on a g4dn instance, Grobid starts and runs correctly.
