### ISSUE TITLE
grobid 0.7.2 not recognizing greek alphabets

### ISSUE THREAD

**Issue by prashanthdumpuriNeurance** [kermitt2/grobid#973]
I'm running grobid-0.7.2 on Windows 11 using docker. I followed instructions from [your documentation](https://grobid.readthedocs.io/en/latest/Grobid-docker/#configure-using-the-normal-yaml-config-file) to mount the docker image **_lfoppiano/grobid:0.7.2_**. 

While PDF extraction and sentence extraction works like a charm, grobid is **not recognizing greek alphabets** in my PDFs. I have a lot of text in the PDF that includes greek alphabets as a suffix to english words. For example, here's a sentence from my PDF - `"It has also been reported that the production of interferon-g (IFN-g) may be lowered."` `g` here is actually written as gamma in the PDF (I just didn't know how to write greek alphabets here). 

grobid is converting the greek alphabet `gamma` (g) to the [unicode delete character U+2425](https://www.compart.com/en/unicode/U+2425). 

I also changed the sentence segmenter to pragmatic sentence detector in my local yaml file and mounted it using the following command
`docker run --rm -p 8070:8070 -p 8070:8070 -v "D:/grobid/grobid-0.7.2/grobid-0.7.2/grobid-home/config/grobid.yaml":/opt/grobid/grobid-home/config/grobid.yaml:ro lfoppiano/grobid:0.7.2`

grobid is still not parsing greek alphabets correctly. I'm pretty sure i'm missing something. Can someone please help me?

Thanks in advance
PD

**Comment by kermitt2** [comment]
Hi @prashanthdumpuriNeurance 

Thanks for the issue.

There can be several reasons why the unicode resolution of some characters fail when parsing a PDF. If you share your PDF, I can have a better look, but the main reason is that these characters are embedded fonts. The image glyph of the character will be used in display, but the unicode of the character is lost, because it corresponds to free/reserve range of unicode or control code as here.

The other usual source of errors with Greek symbol, is the usage of non-Greek unicode with a Greek font, so the character unicode would be solved as `g` (or `c`) instead of `γ`, but display as Greek letter. 

It's not related to Grobid, but to the information available in the PDF, and its parsing done by [pdfalto](https://github.com/kermitt2/pdfalto) in our case (see [here](https://github.com/kermitt2/pdfalto#future-work) about these unicode issues). PDF is a presentation format, and many "logical" information is lost as here. 

However, in most of the modern PDF, the Greek symbols are well encoded and will be available correctly in the structured text.

**Comment by prashanthdumpuriNeurance** [comment]
Thanks @kermitt2. I figured as much that it's a PDF encoding issue. And thanks for your offer to check it out in detail. Here's the link to the PDF

https://sci-hub.se/10.1038/sj.mp.4000650

Let me know if it does not work and I can upload the PDF to dropbox/google drive. Also, can you please let me know how you debug it?

Thanks again
PD

**Comment by kermitt2** [comment]
Hi @prashanthdumpuriNeurance 

(I edited your post to put a more "public" link to your pdf. )

The problem with this PDF apparently is the usage of a secondary font (a Greek font) to display the unicode for `g` into `γ`... so we would have to change the unicode based on the secondary font. This is something much easier to do that recovering unicode for embedded font, and it is planned for next version of pdfalto. The current behavior of pdfalto is to put placeholders for all these problematic unicode (thus I think the weird `␥`, although it should be something else normally, but not sure anymore).  

In principle, you should not see anymore this  kind of problem for more modern PDF from mainstream publishers.

**Comment by prashanthdumpuriNeurance** [comment]
Thank you for the edit and the quick response. How did you figure out that the PDF used a secondary font? Asking so I can learn.

Thanks again

**Comment by kermitt2** [comment]
@prashanthdumpuriNeurance I am using pdfalto which gives PDF font families, stream tokens and associated fonts. 

In this PDF, the code for the `γ` character is 0067, which is `g` in unicode (U+0067). However it is associated to the `symbol` font family, where character code 0067 is mapped to the `γ` glyph. We would expect that the code would be U+03B3 (Greek small letter gamma) and be associated to the "primary" normal font ("primary font" in this PDF is melior serif). So the fix I plan to make in pdfalto would be to map Greek letters and certain special characters from Greek and symbol fonts into their "standard" unicode of the primary font. 

You can use `pdftotext` for instance (on Linux) and the converted text uses `g` for `γ`, which shows the font mapping problem:

```
Molecular Psychiatry (2000) 5, 150–158
 2000 Stockton Press All rights reserved 1359–4184/00 $15.00
www.nature.com/mp

ORIGINAL RESEARCH ARTICLE

Decreased in vitro production of interferon-gamma and
interleukin-2 in whole blood of patients with
schizophrenia during treatment
V Arolt1, M Rothermundt1, K-P Wandinger2 and H Kirchner2
1

Department of Psychiatry, University of Muenster, Germany; 2Department of Immunology, University of Luebeck School
of Medicine, Germany
A pattern of aberrations in the T-cell cytokine system that is typical for autoimmune disorders
has also been reported in patients with schizophrenia, namely a decreased interleukin-2 (IL2) production and increased levels of the soluble IL-2 receptor (sIL-2R). It has also been
reported that the production of interferon-g (IFN-g) may be lowered. 
...
```

**Comment by prashanthdumpuriNeurance** [comment]
Thanks @kermitt2. I'm closing this issue. 

P.S. Not only is grobid a great tool, but support is also great. I'm glad I stumbled upon it.
