### ISSUE TITLE
Add additional pattern to match the mathematical dashes (hypens

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid#980]
I've been facing a small issue with the character `\u2212` which is a `MINUS SIGN` and belongs under the mathematical symbols (https://stackoverflow.com/questions/57358321/why-unicode-character-minus-sign-u2212-is-not-in-regex-unicode-group-ppd#57363745), therefore is not replaced by the Dash regex in UnicodeUtil.normalizeText(). 

Issue with this character is that the FormatNumber class fails to parse a negative number with such symbol. 

e.g.: 
```
 java.text.ParseException: Unparseable number: "−0.5341"
```

I was wondering if we could add an additional regex to replace such symbol with the classic `-`.

**Comment by kermitt2** [comment]
Hi Luca !

You could extend the normalization class DASH_PATTERN in UnicodeUtil.java, something like this: 
DASH_PATTERN = Pattern.compile("[\\p{Pd}\\u2212]");
