### ISSUE TITLE
Citation not working

### ISSUE THREAD

**Issue by andreagemelli** [kermitt2/grobid#981]
When I cite your project in my paper using your bibtex from the GitHub page, the second link (arxiv) is not working.

**Comment by kermitt2** [comment]
Hi @andreagemelli 

You need to use a BibTeX csl file that can interpret correctly the `archivePrefix` attribute in the BibTeX entry. 

For example if the  unsrt (unsorted) BibTeX style, which is one of the four standard bibliography styles in BibTeX, it will generate this citation:

![Screenshot from 2022-12-15 12-34-17](https://user-images.githubusercontent.com/2340795/207849446-9f80e1b7-ebed-4c85-8c2d-68503cf1fc0d.png)

If you can't update/change your citation style, you will need to remove the `archivePrefix` attribute and find what's more appropriate in this style.
