### ISSUE TITLE
Removing footnote stripping/tagging footnote origin points

### ISSUE THREAD

**Issue by TheDeponent** [kermitt2/grobid#996]
- What is your OS and architecture? Windows is not supported and Mac OS arm64 is not yet supported. For non-supported OS, you can use Docker (https://grobid.readthedocs.io/en/latest/Grobid-docker/)
Ubuntu 22.04.2

- What is your Java version (`java --version`)? Expected versions are currently Java 8, 9 and 10. 
JDK 11.0.18

Hey! 

First off, I'd like to thank you for creating this tool. After testing a number of tools to markup and extract text from pdfs, I can quite confidently say that yours is the best for both usability and accuracy - it's helped me with my current project immensely, so thanks again.

For context, my current project relates to Australian legal cases and academic texts in the legal field - I have been working on code which extracts the text of these documents and converts them to an audio file using ESPNet. GROBID has been doing the heavy lifting for my text extraction, and on the whole works beautifully, but it is somewhat overzealous on footnote classification for legal documents. Occasionally, it will strip paragraphs of the body of the case out as footnotes, moving them to the footer.

I was wondering if there is a way to stop GROBID from stripping footnotes altogether - I have other ways to process them if necessary. I have tried implementing custom TEI schemas, but can only succeed in moving the location of the footnotes, not keeping them in the body/their original position. 

Alternatively, if there is a way to tag the original position of the footnotes, I could reinsert them by post-processing the .xml.

Thank you in advance for any help you may be able to provide, and thanks again for creating this tool.

**Comment by kermitt2** [comment]
Hi @TheDeponent !

Thank you very much for the kind words on grobid and happy that it can be useful for your project.

The legal field is still challenging for Grobid, not really represented in the training data for the moment. But even in general, there's this issue of paragraph incorrectly labeled as footnote, which is an error very visible and not really possible to recover with the final XML only. 

Unfortunately at this time, the addition of coordinates does not include the element `note`, I need to add it - I note it for the next release.

If you're courageous, one "hacking" solution is to retrain a `segmentation` model without the "foot note" structure, I think it should work:

- modify the segmentation training data XML parser to consider `<note place="footnote">` tag as `<body>`:

Change this: 

https://github.com/kermitt2/grobid/blob/master/grobid-trainer/src/main/java/org/grobid/trainer/sax/TEISegmentationSaxParser.java#L157

the line 157 into these 3 lines:

```java
currentTag = "<body>";
upperTag = currentTag;
upperQname = "body";
```

- retrain the segmentation model (this command will also recompile for the above change):

```console
> ./gradlew train_segmentation
```

After some hours (it depends on the number of CPU of your machine - usually half day), you get a new segmentation model and  there should not be any foot note section anymore, they will be included as paragraph in the normal body text.

**Comment by TheDeponent** [comment]
@kermitt2 Thanks so much for your response. Even with the lack of legal documents in the training data, the error rate is still quite low, on average in my testing it misidentifies 5 paragraphs in a legal document containing 200 numbered paragraphs.

I will attempt retraining the segmentation model over the next few days, and will
